### ISSUE TITLE
Action Bar title is not changing when back button is pressed and app redirects to some other Fragment.

### ISSUE THREAD

**Issue by danzzen** [openfoodfacts/openfoodfacts-androidapp#1003]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting a issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
Title at Action bar is not changing according to the fragments, when we are at a fragment and pressing back button directs us to the previous fragment(which we have visited previously) , So this time the title at action bar is not changed according to current fragment.

**Steps to reproduce:** 
1. Open the app and it is at HOME and action bar title is **Home**
2. Click on `Search by barcode`  option in navigation Drawer.
3. Press back button of your phone.
4. Now it is at home but title is **Search by barcode** only

**Expected behavior:** 
When the back button is pressed the title, should change accordingly. (For this case **Home** should be title of action bar when returning back to Home Fragment)

**Observed behavior:** 

The title is unchanged when transaction happen between any to Fragments by pressing the back button.

**Device :** 
one+ X 
**android version:** 
6.0.1 marshmallow 

**Screenshots:** 

<p align="center">

<img src="https://user-images.githubusercontent.com/22103919/36835752-40546286-1d5d-11e8-9526-48a480cba4d1.jpeg" width="300" height="480"/>

</p>

<h2 align="center">First we are at home</h2>
<br/>
<br/>

<p align="center">

<img src="https://user-images.githubusercontent.com/22103919/36835821-708d4030-1d5d-11e8-85aa-6e6ed0e23075.jpeg" align="center" width="300" height="480"/>
</p>
<h2 align="center">After Pressing Search by Barcode</h2>
<br/>
<br/>

<p align="center">

<img src="https://user-images.githubusercontent.com/22103919/36835849-87c13d9c-1d5d-11e8-989a-d60040410ac2.jpeg" align="center" width="300" height="480"/>

</p>

<h2 align="center">On pressing back button</h2>

**Comment by danzzen** [comment]
I would like to work on this issue.

**Comment by PrajwalM2212** [comment]
@danzzen I have already created this issue earlier . Please refer before creating issues and do not create a duplicate issue .
I have already sent a pull request for the same and has been approved.

**Comment by danzzen** [comment]
@PrajwalM2212 sir i downloaded current version of code and running it on my phone is creating this issue.

**Comment by PrajwalM2212** [comment]
@danzzen  My pull request is merged now , so  update your fork now . You will not find the problem now .
