### ISSUE TITLE
Common name is always displayed in French, although we have translations for it

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1005]
Common name is always displayed in French, although we have translations for it

https://world.openfoodfacts.org/product/4021912006023/hemp-beer-cannabia

![image](https://user-images.githubusercontent.com/1689815/36845399-da44c95a-1d56-11e8-9438-3e5128418c33.png)

Order of the fallbacks: 
1. Display UX language if available
2. Otherwise display English if available
3. Else display the Main language of the product

**Comment by sachincool** [comment]
Working on it!

**Comment by sachincool** [comment]
@teolemon 
My research  resulted in some cool facts :- 
* The Search api endpoint it this 
`https://world.openfoodfacts.org/cgi/search.pl?search_simple=1&json=1&action=process&fields=image_small_url,product_name,brands,quantity,code&search_terms=cannabia&page=1`

This results in only 1 product with same Barcode as you mentioned in

 `https://world.openfoodfacts.org/product/4021912006023/hemp-beer-cannabia`  then why is it that in the main page it is showing it in English whereas in the endpoint json it is in fr. am I missing something?

**Comment by Karljoones** [comment]
@sachincool are you still working on this?

**Comment by sachincool** [comment]
no, @Karljoones you can take it. :smile:

**Comment by teolemon** [comment]
This is still an issue on latest trunk. Becoming more problematic as we welcomed many Canadian and Belgian users.

![image](https://user-images.githubusercontent.com/1689815/46006439-d4690280-c0b7-11e8-9a7f-b35c12513d4c.png)

**Comment by teolemon** [comment]
It would probably about asking product_name +"_languageoftheUX"

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2034
There's a pull request open by @shiv07tiwari but it's not functional

**Comment by teolemon** [comment]
you can go ahead, please look at my comments here, and bonbonking's in the PR. Feel free to outline your approach as well.

**Comment by balaji-ramavathu** [comment]
I'm getting the same problem as in the PR i.e, the problem occurs when there's no product_name to get from the api. ( eg: {"status_verbose":"product found","product":{},"status":1,"code":"5400141297171"} ) In such case the textView is becoming invisible. So I think when this happens, we can
1.give an option to the user to add the product_name or
2.if generic name is there, we can show it as the main name and remove the empty space above.
Am I right? @teolemon any other suggestions?

**Comment by teolemon** [comment]
In this exact case, it seems to have a name in French and Dutch:
https://world.openfoodfacts.org/api/v0/product/5400141297171.json?fields=product_name_fr,product_name_nl

So getting the current language from the API should be as simple as sending a query asking the product name in the current app language ?
product_name_ + APP_LANGUAGE ?

If no product_name_XX in the current language is available, fallback on just product_name

if no product_name is available, we don't currently do anything, but we could have a field to type it (that's another bug in my opinion).

**Comment by balaji-ramavathu** [comment]
Yeah I got it! I did the exact thing that you just said but forgot to change my app language to french and thought my code is not working. Will submit the PR now :-)
