### ISSUE TITLE
Ingredients always displayed in French, although we have translations for it

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1006]
Ingredients always displayed in French, although we have translations for it

https://world.openfoodfacts.org/product/4021912006023/hemp-beer-cannabia

![image](https://user-images.githubusercontent.com/1689815/36845539-7352e50a-1d57-11e8-8fee-32b3a7329787.png)

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
Probably, this issue is just a small part of this one #945, which I'm working on.
If everyone starts to translate some small part of product, we will get the mess...
