### ISSUE TITLE
"Take more photos" doesn't seem to work anymore

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1007]
"Take more photos" doesn't seem to work anymore. No feedback as to whether cropped photos are actually uploaded, and they are not arriving online.

**Comment by jaztriumph** [comment]
I think I got this. I am working on this.

**Comment by Karljoones** [comment]
I'm going to leave this open, the PR is merged but I think this should be tested once more to confirm closure.
