### ISSUE TITLE
Fix Serbian locale bug

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1008]
Investigate the right locale for Serbian latin and Serbian cyrillic and fix the language folder, and language switcher accordingly.

**Comment by roychowdhuryrohit-dev** [comment]
I would like to solve this issue.

**Comment by teolemon** [comment]
Please go ahead. Also, please notify me here the locale folder names we need to export to

**Comment by roychowdhuryrohit-dev** [comment]
There will be no need to any change in locale folder names. I have fixed a bug where BCP 47 language tags were used which is only supported from Android Lollipop.
