### ISSUE TITLE
Don't delete brand and product name if we upload an Offline product that already exists

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1010]
![image](https://user-images.githubusercontent.com/1689815/36846687-eb12ac70-1d5b-11e8-8123-b6583e1f8790.png)
https://world.openfoodfacts.org/product/3263859858117
Don't delete brand and product name if we upload an Offline product that already exists, but without giving any brand or name.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/36848374-5d2e8c16-1d61-11e8-92ea-601197c107e6.png)

**Comment by Shubham2320** [comment]
It is similar to #375 could you please elaborate it on what has to be done :).

**Comment by teolemon** [comment]
It is the same issue as #375 
On upload, a check needs to be done:

If brand, weight, name is empty, don't send an empty parameter (like brand=&weight=&name=) (otherwise the server will assume you want to delete it)

**Comment by Shubham2320** [comment]
Okay :) I would like to work on it.
