### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/OpenFoodFacts-androidApp#102]
I found two issues in the login process:
* When identifying in the app, if I try with any login (even a random one) and no password, I get a green notification to let me know I'm connected, which makes no sense. Logically, if I give a login, I should give a password as well. 
* After logging in, when I look in the left menu, the login isn't updated (this is the case with a real login / pwd as well). I have to exit with the return button and launch the app again to see the new login in the left drawer.

**Comment by itchix** [comment]
I fix the first point, I'm working on the second

**Comment by herau** [comment]
@itchix any news about this topic ? i can try to solve them with an Pull request if you want ?

**Comment by itchix** [comment]
Sorry I don't have time this past few months...
Yes you can =)
