### ISSUE TITLE
Update mechanism for the in-app taxonomies

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1020]
As mentioned in #1019 , we want to now include multilingual taxonomies within the app for better reliability.

However, we update them regularly, and thus we must provide an update mechanism.

The zipped version of the files are located at: 

https://static.openfoodfacts.org/data/taxonomies/categories.json
https://static.openfoodfacts.org/data/taxonomies/labels.json
https://static.openfoodfacts.org/data/taxonomies/additives.json
https://static.openfoodfacts.org/data/taxonomies/countries.json
https://static.openfoodfacts.org/data/taxonomies/allergens.json

The app should download https://static.openfoodfacts.org/data/taxonomies/version.json and check if it has changed compared to the local version.

**Comment by Shubham2320** [comment]
Okay, so what I understood from this is that we'll store all these files in the greendao database a single time and then perform regular checks regarding the version of files. If I'm correct please let me know that can we perform network requests on SplashActivity to get these files on the first run of the app, At present, we're performing a single request to get allergens there.
Please correct me if I'm wrong :).

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
1) https://static.openfoodfacts.org/data/taxonomies/version.json - 404 Not Found
2) To start working on this we firstly need to merge this one #1115

**Comment by teolemon** [comment]
We're not introducing a version.json, rather we should directly check the version of the file and see if it has changed.
last modified or the http etag  (if the server returns 304, no new version)

I haven't checked on #1115 yet again, been busy all day

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
Did the server side enable "Cache-Control: private, must-revalidate"? Because I always get 200.

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
Ping-ping)

**Comment by teolemon** [comment]
@stephanegigandet Server side issue for taxonomies: "Did the server side enable "Cache-Control: private, must-revalidate"? Because I always get 200."

**Comment by teolemon** [comment]
We fixed this.
