### ISSUE TITLE
Grouping header groups in preference screen

### ISSUE THREAD

**Issue by ManognaMutyala** [openfoodfacts/openfoodfacts-androidapp#1033]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search for the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

How about grouping preferences in preference screen?Like grouping -Scan on startup, power mode scan, upload on mobile data under **Scan and Settings**, grouping the rest under **help and support**
I would like to work on this if approved by maintainers.

**Screenshots:** 
![screenshot_20180302-131444](https://user-images.githubusercontent.com/22299553/36889264-44efb594-1e1f-11e8-845b-1aeb8344b86e.png)

**Comment by PrajwalM2212** [comment]
Chrome Custom Tabs are for opening webpages . Refer https://developer.chrome.com/multidevice/android/customtabs

**Comment by ManognaMutyala** [comment]
I was not clear in explaining my issue @PrajwalM2212, I think now things are clear.
