### ISSUE TITLE
Crash when scanning EAN 4039228005371

### ISSUE THREAD

**Issue by davidak** [openfoodfacts/OpenFoodFacts-androidApp#104]
http://de.openfoodfacts.org/produkt/4039228005371/pizza-alla-california-veganz

i had added the product with the android app with just Quantity and one picture (i took 3 pictures but they overwrite the earlier :()

![screenshot_2016-06-03-22-35-18](https://cloud.githubusercontent.com/assets/91113/15792984/4688735c-29e1-11e6-9c3b-4758482beb68.png)

after i added more information on the website, scanning works again.

---

Version 0.2.3 installed from F-Droid

**Comment by itchix** [comment]
I can't reproduce the bug :/

**Comment by teolemon** [comment]
Try the OBF version. Somebody reported the same bug. Just take pictures. Click send. rescan the product.

**Comment by davidak** [comment]
1. scan product
2. take picture
3. upload

here a barcode to reproduce:
![barcode](https://cloud.githubusercontent.com/assets/91113/16203555/1a4bc806-371b-11e6-9cb4-4635beabe997.jpg)
