### ISSUE TITLE
Multi-format barcode does not supports 

### ISSUE THREAD

**Issue by iml-v** [openfoodfacts/openfoodfacts-androidapp#1040]
**Summary:** 

App does not supports multi-barcode formats like UPC_EAN_EXTENSION ,MAXICODE ,DATA_MATRIX, RSS_EXPANDED ,CODABAR etc.

**Expected behavior:** 

App should be multi-formats barcode supported 

**Observed behavior:** 

It does not supports above mentioned formtats

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

I am working on this .

**Comment by teolemon** [comment]
@iml-v Do all of them have a numeric translation ?

**Comment by iml-v** [comment]
@teolemon  yes ,also all are used in Retail  industry

**Comment by Karljoones** [comment]
@iml-v are you still working on this?
