### ISSUE TITLE
display progress bar until history is loaded

### ISSUE THREAD

**Issue by jaztriumph** [openfoodfacts/openfoodfacts-androidapp#1043]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting a issue.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

use progress bars to notify user of loading history.

**Expected behavior:** 

![progress](https://user-images.githubusercontent.com/22943390/36897699-a0b22b1e-1e3d-11e8-82ca-216d959c2103.gif)

**Comment by jaztriumph** [comment]
I am working on this.

**Comment by Shubham2320** [comment]
Yeah, it would be good :).
