### ISSUE TITLE
Remove fastscroller_track & fastscroller_handle strings

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1047]
Remove  
```
<string name="fastscroller_track">फास्टस्क्रोलर ट्रैक</string>
<string name="fastscroller_handle">फास्टस्क्रोलर हैंडल</string>
```

**Comment by iml-v** [comment]
I will correct it

**Comment by iml-v** [comment]
@teolemon  will you clarify about this , should I remove these strings from all String files or only from specified language (Hindi ) because these strings have been used in fastscroller

**Comment by teolemon** [comment]
Those strings just mention FastScroller, they don't say anything useful to the end user ?
So I guess they can be removed from the source file ?

**Comment by iml-v** [comment]
@teolemon  thanks
