### ISSUE TITLE
Make it possible to rename the package for Open Beauty Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#105]
Standardize and turn the package name into something that can be changed easily

It's currently:
openfoodfacts.github.scrachx.openfood

http://stackoverflow.com/questions/10569760/android-how-do-i-dynamically-set-the-package-name-at-build-time-for-an-open-so

**Comment by teolemon** [comment]
It has to be something different on the playstore to avoid namespace conflict.

**Comment by teolemon** [comment]
http://stackoverflow.com/questions/10569760/android-how-do-i-dynamically-set-the-package-name-at-build-time-for-an-open-so

**Comment by herau** [comment]
maybe using the maven resource filter feature (with replacement of `${xxx}` values)

**Comment by herau** [comment]
@teolemon maybe also rename the default package name to `org.openfoodfacts.android` (or something like that) instead of `openfoodfacts.github.scrachx.openfood`

**Comment by teolemon** [comment]
``òrg.openfoodfacts.scanner``` is the official name. We need to avoid clashes and confusion. I'd like to be able to have both versions on my phone i guess.
OBF is ``òrg.openbeautyfacts.scanner```

**Comment by herau** [comment]
maybe an option with `https://developer.android.com/studio/build/build-variants.html`

**Comment by teolemon** [comment]
Can you still change the ```applicationId``` ?

**Comment by teolemon** [comment]
Fixed.
