### ISSUE TITLE
Nutriscore not correctly shown in history

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1082]
![image](https://user-images.githubusercontent.com/1689815/36939379-3194624e-1f30-11e8-8426-97d31237fb81.png)

**Comment by jaztriumph** [comment]
@teolemon that history is old history right. can you confirm this?
Because there was no nutriscore column in schema 4 so old history nutriscore are null after upgrading.
I will work on this.
