### ISSUE TITLE
Those strings should be changed or removed.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1086]
Those strings should be changed or removed, translators are confused by them.
![image](https://user-images.githubusercontent.com/1689815/36939440-6a7a5194-1f31-11e8-8ce8-26d2fb626fa7.png)

**Comment by PrajwalM2212** [comment]
@teolemon  Those strings should not be translated . They are the keys used by preference activity . Removing or changing them will affect the working of preferences activity. 
I will set them to be non-translatable .
