### ISSUE TITLE
Issue in  time for the product in history page

### ISSUE THREAD

**Issue by ManavPoddar** [openfoodfacts/openfoodfacts-androidapp#1093]
**Summary:** 

the time shown is  "1 minutes ago" or "1 hours ago". Rather it should be "1 minute ago" or "1 hour ago".
**Steps to reproduce:** 

menu -> history -> see for an item viewed an hour ago or a minute ago

**Screenshots:** 

![screenshot_20180304-114035](https://user-images.githubusercontent.com/18038492/36942775-19bcd8c4-1fa1-11e8-95ce-52facbf97635.png)

**Comment by ManavPoddar** [comment]
I would love working on it

**Comment by PrajwalM2212** [comment]
You will have to add conditions to check cases of one second , one minute and one year .

**Comment by ManavPoddar** [comment]
yeah @PrajwalM2212 , do you know the exact file where I can make the changes ?

**Comment by PrajwalM2212** [comment]
In HistoryListAdapter there is a function called calcTime()

**Comment by ManavPoddar** [comment]
got it thanks @PrajwalM2212 :)
