### ISSUE TITLE
Clicking on 'Preferences' crashes the app when language is changed to Hindi

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#1097]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
When using the app in Hindi language and trying to go to the preferences screen the app crashes.

**Steps to reproduce:** 
Change the app language to Hindi, Open the Nav Drawer and click on the preferences option (the one with the settings icon). 

**Expected behavior:** 
Preferences screen should have been displayed.

**Observed behavior:** 
The app crashes.

**Comment by huzaifaiftikhar** [comment]
I am working on this.

**Comment by ManavPoddar** [comment]
Hi @huzaifaiftikhar, I am not facing this issue with my android version. I am using Noughat. Which android version are you using ?

**Comment by huzaifaiftikhar** [comment]
@vaishali51 I was already working on this issue. Please verify if someone else is working on the issue or not before submitting a PR to it :)

**Comment by vaishali51** [comment]
Okay, I will verify before submitting a PR next time :)

**Comment by huzaifaiftikhar** [comment]
@vaishali51 Please close your PR #1100 as this issue is fixed in #1088
