### ISSUE TITLE
barcode scanner sometimes reads wrong barcodes

### ISSUE THREAD

**Issue by fuddl** [openfoodfacts/OpenFoodFacts-androidApp#110]
The following enties have been created from the same product:
http://de.openfoodfacts.org/produkt/18151535/limited-no-8-birthday-edition-true-fruits
http://de.openfoodfacts.org/produkt/4260122390014

the actual barcode seems to be 4260122390014

**Comment by TaciteOFF** [comment]
Fixed; thanks.

**Comment by itchix** [comment]
@TaciteOFF can I close the issue?
