### ISSUE TITLE
Languages should only be translated into their own language

### ISSUE THREAD

**Issue by Karljoones** [openfoodfacts/openfoodfacts-androidapp#1102]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

When choosing a language, the items should only be translated into their own language, not the language that is currently set. 

**Steps to reproduce:** 

Choose a language in prefs

**Expected behavior:** 

The items should only be translated into their own language, not the language that is currently set. 

- français - fr
- English - en
- Español - es

**Observed behavior:** 

Languages are translated into language of the app.

See screenshot - I know that English is the top of the list, but I should be able to see English in English even if the app is set to Hindi. Only "Hindi" should be in Hindi

**Screenshots:** 

![screenshot mar 4 2018 10_11_06 am](https://user-images.githubusercontent.com/5596450/36944464-ae8ed8ba-1f94-11e8-8995-4c43ab0def85.jpg)

**Comment by l-o-b-s-t-e-r** [comment]
In progress)
