### ISSUE TITLE
Navigation drawer selection on language change

### ISSUE THREAD

**Issue by Karljoones** [openfoodfacts/openfoodfacts-androidapp#1103]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

When you change the language of the app, the app is "reset" and the Preferences item is still selected, Home should be selected as it is displayed.

**Steps to reproduce:** 

1. Preferences
2. Change language
3. Open navigation drawer

**Expected behavior:** 

Home should be selected on language change. OR, preferences can be reopened.

**Observed behavior:** 

Preferences is still selected on language change.

**Device and Android version:** 

OnePlus 5T Android 8

**Screenshots:** 

![screenshot mar 4 2018 10_20_03 am](https://user-images.githubusercontent.com/5596450/36944509-ce9ea72e-1f95-11e8-8543-2b367601cf77.jpg)

**Comment by iml-v** [comment]
@Karljoones i will correct this .
