### ISSUE TITLE
Make categories clickable on Product Page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1104]
One of the killer things on Open Food Facts web version is being able to browse from product to other product of the same category by clicking on the category field (eg: Caramel Stuffed Wafers)
It would be great to make the category field clickable

https://world.openfoodfacts.org/product/3438351360080/gaufres-fines-pur-beurre-caramel-au-beurre-sale-la-dunkerquoise

Example with Caramel Stuffed Wafers
https://world.openfoodfacts.org/category/caramel-stuffed-wafers
https://world.openfoodfacts.org/category/caramel-stuffed-wafers.json

**Comment by teolemon** [comment]
It should basically work like the EMB codes, using a Chrome Custom Tab (or perhaps a Recycler view, with the JSON API, if you're feeling more adventurous)

![image](https://user-images.githubusercontent.com/1689815/36944602-66411080-1fa0-11e8-80f8-91222074c06c.png)

**Comment by PrajwalM2212** [comment]
Working on it.
