### ISSUE TITLE
Make brands clickable on Product Page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1105]
One of the killer things on Open Food Facts web version is being able to browse all products of a same brand by clicking on the brand field on the product page (eg: Haldiram's)
It would be great to make the brand field clickable

https://world.openfoodfacts.org/product/8904063200013/aloo-bhijia-200g-kartoffelsnack-scharf-haldirams-haldiram-s

Example with Haldiram's
https://world.openfoodfacts.org/brand/haldiram-s
https://world.openfoodfacts.org/brand/haldiram-s.json

**Comment by teolemon** [comment]
It should basically work like the EMB codes, using a Chrome Custom Tab (or perhaps a Recycler view, with the JSON API, if you're feeling more adventurous)

**Comment by Shubham2320** [comment]
I would love to work on this :).

**Comment by teolemon** [comment]
You can proceed 👍
