### ISSUE TITLE
Make labels clickable on product page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1107]
One of the killer things on Open Food Facts web version is being able to browse all products of a same label by clicking on the label field on the product page (eg: Organic)
It would be great to make the brand field clickable

https://world.openfoodfacts.org/product/3560070575855/tofu-a-l-indienne-riz-basmati-et-lentilles-bio-carrefour-bio

Example with Organic
https://world.openfoodfacts.org/label/organic
https://world.openfoodfacts.org/label/organic.json

**Comment by shivanshsoni** [comment]
I would like to work on this issue

**Comment by PrajwalM2212** [comment]
Working on it.

**Comment by PrajwalM2212** [comment]
@shivanshsoni  I am already working on it.

**Comment by shivanshsoni** [comment]
@PrajwalM2212 Ok

**Comment by PrajwalM2212** [comment]
@shivanshsoni  Thanks .

**Comment by teolemon** [comment]
@shivanshsoni I opened another one for labels: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/1108

**Comment by teolemon** [comment]
@shivanshsoni also another one for countries, since labels was taken: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/1109

**Comment by shivanshsoni** [comment]
@teolemon That one is also taken :-(
