### ISSUE TITLE
Make packaging clickable on Product Page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1108]
One of the killer things on Open Food Facts web version is being able to browse all products of a same packaging by clicking on the packaging field on the product page (eg: Plastic)
It would be great to make the brand field clickable

https://in.openfoodfacts.org/product/8904063200945/haldirams-bhujia

Example with Plastic
https://world.openfoodfacts.org/packaging/plastic
https://world.openfoodfacts.org/packaging/plastic.json

**Comment by ManavPoddar** [comment]
I'll like to work on it

**Comment by teolemon** [comment]
Ok, go ahead :)

**Comment by ManavPoddar** [comment]
waiting for #1140 to merge so that there are no conflicts

**Comment by Karljoones** [comment]
@ManavPoddar are you working on this?

**Comment by SaumiaSinghal** [comment]
Hie @Karljoones, if it's still open and not yet fixed, i would like to work on it.

**Comment by teolemon** [comment]
It's actually done. But you have other open bugs in the "clickability of values" tag

**Comment by teolemon** [comment]
Implemented.Closing
