### ISSUE TITLE
Make country clickable on Product Page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1109]
One of the killer things on Open Food Facts web version is being able to browse all products of a same country by clicking on the Country field on the product page (eg: France)
It would be great to make the country field clickable

https://world.openfoodfacts.org/product/8904063200945/haldirams-bhujia

Example with India
https://world.openfoodfacts.org/country/india
https://world.openfoodfacts.org/country/india.json

**Comment by PrajwalM2212** [comment]
Working on it.

**Comment by teolemon** [comment]
Fixed with #1140

**Comment by PrajwalM2212** [comment]
This issue can be closed
