### ISSUE TITLE
Add a contributor tab to products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1110]
We display the Add date, the last edit date, and the list of contributors

```Product added on September 12, 2013 at 3:19:18 AM CEST by miles67off.
Last edit of product page on March 4, 2018 at 12:53:55 PM CET by kiliweb. 
Product page also edited by babaorome, jacob80, openfoodfacts-contributors, sebleouf, tacite.```

We miss information about contributors to a product.
https://en.wiki.openfoodfacts.org/API#Contributors

**Comment by Shubham2320** [comment]
I would love to work on it.

**Comment by teolemon** [comment]
You can go ahead.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/37566028-bbc27d96-2ab3-11e8-8169-4f5595992aec.png)
Here's a mockup.  Note that the unselected images should probably be on top

**Comment by teolemon** [comment]
- Existing images: the miniature of the previous tab, yes
- State of the product: same tab, I just didn't have any room left :-)
