### ISSUE TITLE
Make traces and substances causing allergies or intolerances clickable

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1112]
One of the killer things on Open Food Facts web version is being able to browse all products by clicking on the fields on the product page
It would be great to make the traces field, and the substances causing allergies or intolerances fields  clickable
https://world.openfoodfacts.org/product/3560070575855/tofu-a-l-indienne-riz-basmati-et-lentilles-bio-carrefour-bio

https://world.openfoodfacts.org/trace/eggs
https://world.openfoodfacts.org/trace/eggs.json

https://world.openfoodfacts.org/allergen/soybeans
https://world.openfoodfacts.org/allergen/soybeans.json

**Comment by PrajwalM2212** [comment]
@shivanshsoni  Do you want to work on it ?

**Comment by shivanshsoni** [comment]
Yes, I would like to work on this

**Comment by shivanshsoni** [comment]
Thanks @PrajwalM2212
