### ISSUE TITLE
Make stores clickable

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1114]
One of the killer things on Open Food Facts web version is being able to browse all products of a same store by clicking on the Store field on the product page (eg: Reliance Fresh)
It would be great to make the store field clickable

https://world.openfoodfacts.org/product/8904063200945/haldirams-bhujia

Example with Reliance Fresh
https://world.openfoodfacts.org/store/reliance-fresh
https://world.openfoodfacts.org/store/reliance-fresh.json

**Comment by ManavPoddar** [comment]
I am working on it

**Comment by ManavPoddar** [comment]
hey @teolemon , I would be implementing it within a recycler view. It will be much convenient for the user :)
