### ISSUE TITLE
Use new HTTPS api

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#112]
Example url:
https://ssl-api.openfoodfacts.org/api/v0/product/3045320057294/galettes-au-beurre-frais-bonne-maman

Works exactly as before.

**Comment by itchix** [comment]
It replace "http://world.openfoodfacts.org"?

**Comment by teolemon** [comment]
For now it's not possible. That's why @stephane is setting up a new server to get wildcard HTTPS

**Comment by Ekt0s** [comment]
So we need to update the application api calls to use the ssl urls ? Is that it ?

**Comment by teolemon** [comment]
Yes.
