### ISSUE TITLE
Not able to add Allergen

### ISSUE THREAD

**Issue by ManavPoddar** [openfoodfacts/openfoodfacts-androidapp#1134]
**Summary:** 

Not able to add an Allergen.
![videotogif_2018 03 06_21 36 09](https://user-images.githubusercontent.com/18038492/37043622-1ae22258-2187-11e8-8e91-7dfd7fb2239b.gif)

**Screenshots:**

**Comment by ManavPoddar** [comment]
I would love to work on it

**Comment by ManavPoddar** [comment]
@teolemon  The PR #1145 fixes this issue. But for some languages like Hindi, there is no allergen for it in the allergen list. Shall I add a toast or dialog asking the user -> No allergens found, Please change the language ?

**Comment by Shubham2320** [comment]
I think this issue would be resolved with the merging of #1115.

**Comment by ManavPoddar** [comment]
Hey @Shubham2320 , #1115 resolves many issues, can you exactly tell which commit is solving the problem. Also the problem was because of error in the strings-hi.xml file as is discussed in issue #1144. Which is solved in PR #1145. So I think it can be merged

**Comment by ManavPoddar** [comment]
So I think the issue can be closed after merging PR #1145
