### ISSUE TITLE
In ProductActivity Additives, Ingredients can be made clickable.

### ISSUE THREAD

**Issue by Shubham2320** [openfoodfacts/openfoodfacts-androidapp#1152]
In ProductActivity Additives can be made clickable and we can browse products containing these parameters.

**Comment by PrajwalM2212** [comment]
@Shubham2320 I have made countries clickable . I am already working on Labels and Categories .
I think @ManavPoddar and @shivanshsoni are working to make other items clickable.

**Comment by Shubham2320** [comment]
Oh I see, @PrajwalM2212  then only additives are left so I would just do that. Thanks

**Comment by PrajwalM2212** [comment]
@Shubham2320 Can you wait till https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/1140 is merged . We can develop on this .

**Comment by Shubham2320** [comment]
Yeah sure. :)

**Comment by teolemon** [comment]
#1140 has been merged.
I guess additives are a better candidate than all the ingredients. 
Making the whole ingredient list clickable feels like a bit overkill.
