### ISSUE TITLE
Make it possible to move the app to the SD Card

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#116]
- performance and data issues to consider, though

**Comment by itchix** [comment]
https://developer.android.com/guide/topics/data/install-location.html

**Comment by itchix** [comment]
Do you to install the app on SD Card by default? Or add the possibility to move the app at any moment?

**Comment by teolemon** [comment]
Add the possibility for people who have fully-loaded phones. Also useful for worldwide success (phones in emerging markets have smaller internal memory)

**Comment by teolemon** [comment]
So just the ability to move.

**Comment by herau** [comment]
@teolemon Regarding the current manifest file, it seems that the application can already be installed / moved on the external storage right ?

```xml
<manifest package="openfoodfacts.github.scrachx.openfood"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:installLocation="auto">
```

**Comment by itchix** [comment]
Yes I made this modification on the last push

**Comment by herau** [comment]
ok so the issue can be closed 👍

**Comment by herau** [comment]
@itchix I think there was a mistake in the commit message of your commit 48a07dfc44b0609c043f4dfa552e81761ae06e1f
only `close #127`in the commit message whereas this close #116 also :-)

**Comment by itchix** [comment]
Yes, you're right
My bad =)
