### ISSUE TITLE
Issues with timestamps in History

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1162]
![image](https://user-images.githubusercontent.com/1689815/37153887-6f3c4a24-22de-11e8-85e4-b0109c87df6b.png)

- no space after numeric value
- the translatable string is "minutes ago". 5 minutes ago. But in French for instance, we must say: "Il y a 5 minutes" >> include a placeholder for the number in the string

**Comment by iml-v** [comment]
@teolemon i am working on this

**Comment by Karljoones** [comment]
@iml-v are you working on this?

**Comment by huzaifaiftikhar** [comment]
Fixed in #1600
