### ISSUE TITLE
Be more precise about the country in the product list

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1165]
"Country where sold" should appear instead of "Country". Otherwise people will believe Mexican products sold in France are French products :-) 
![image](https://user-images.githubusercontent.com/1689815/37154109-402a0e14-22df-11e8-9655-3fb68293c386.png)
![image](https://user-images.githubusercontent.com/1689815/37154113-44f81774-22df-11e8-8f25-f1e33367f2d4.png)

**Comment by Shubham2320** [comment]
I 'll fix this.
