### ISSUE TITLE
network preference not working properly

### ISSUE THREAD

**Issue by jaztriumph** [openfoodfacts/openfoodfacts-androidapp#1173]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 

product info does open on scanning when upload using only wifi is opted.

**Steps to reproduce:** 

uncheck the 'upload on mobile data' checkbox and scan a known product.

**Device and Android version:** 

HTC 820 g+,KITKAT 4.4

**Screenshots:** 

![data](https://user-images.githubusercontent.com/22943390/37168626-776b562a-232b-11e8-920c-929177dabfb0.gif)

**Comment by jaztriumph** [comment]
I am working on this.

**Comment by Karljoones** [comment]
The network option is related to uploading history and new products to the database. Not retrieving data for the user

**Comment by jaztriumph** [comment]
@Karljoones problem is I can not get product information by scanning when I uncheck that check box .which should not happen, so it is an issue.
