### ISSUE TITLE
Typo in string files.

### ISSUE THREAD

**Issue by shivanshsoni** [openfoodfacts/openfoodfacts-androidapp#1179]
**Typo in strings:**

"You can add new products, even if you don't have an Internet connexion right now. " **must be changed to** "You can add new products, even if you don't have an Internet **connection** right now."

![screenshot_2018-03-10-09-50-34](https://user-images.githubusercontent.com/24546371/37238275-b0c18994-2448-11e8-99dc-c3d0367eba2d.png)

**Comment by shivanshsoni** [comment]
@ManavPoddar i have fixed it already. Just need to push changes

**Comment by ManavPoddar** [comment]
ok great, Go ahead :)

**Comment by shivanshsoni** [comment]
Done :-)
