### ISSUE TITLE
Complete crash of the application on startup related to the local database

### ISSUE THREAD

**Issue by Porkepix** [openfoodfacts/openfoodfacts-androidapp#1197]
**Summary:** 

Application crash at startup, can't even get to the home screen.

**Steps to reproduce:** 

Just starting the application

**Add system logs:**
Below, the lines related to the OpenFood Facts process from `adb logcat -v threadtime`

```
03-11 10:30:40.508 18667 18667 W System  : ClassLoader referenced unknown path: /data/app/openfoodfacts.github.scrachx.openfood-1/lib/arm
03-11 10:30:40.515 18667 18667 I MultiDex: VM with version 2.1.0 has multidex support
03-11 10:30:40.515 18667 18667 I MultiDex: Installing application
03-11 10:30:40.515 18667 18667 I MultiDex: VM has multidex support, MultiDex support library is disabled.
03-11 10:30:40.532 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.532 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.532 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.533 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.533 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.533 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.533 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.534 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.534 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.534 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.534 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.535 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.535 18667 18667 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>
03-11 10:30:40.545 18667 18667 I greenDAO: migrating schema from version 2 to 5
03-11 10:30:40.549 18667 18667 E SQLiteLog: (1) duplicate column name: quantity
03-11 10:30:40.554 18667 18667 D AndroidRuntime: Shutting down VM
03-11 10:30:40.555 18667 18667 E AndroidRuntime: FATAL EXCEPTION: main
03-11 10:30:40.555 18667 18667 E AndroidRuntime: Process: openfoodfacts.github.scrachx.openfood, PID: 18667
03-11 10:30:40.555 18667 18667 E AndroidRuntime: java.lang.RuntimeException: Unable to create application openfoodfacts.github.scrachx.openfood.views.OFFApplication: android.database.sqlite.SQLiteException: duplicate column name: quantity (code 1): , while compiling: ALTER TABLE history_product ADD COLUMN 'quantity' TEXT NOT NULL DEFAULT '';
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4809)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:234)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: duplicate column name: quantity (code 1): , while compiling: ALTER TABLE history_product ADD COLUMN 'quantity' TEXT NOT NULL DEFAULT '';
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:893)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:504)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at org.greenrobot.greendao.database.StandardDatabase.execSQL(StandardDatabase.java:37)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.models.DatabaseHelper.upgrade(DatabaseHelper.java:53)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.models.DatabaseHelper.onUpgrade(DatabaseHelper.java:30)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at org.greenrobot.greendao.database.DatabaseOpenHelper.onUpgrade(DatabaseOpenHelper.java:94)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at org.greenrobot.greendao.database.DatabaseOpenHelper.getWritableDb(DatabaseOpenHelper.java:59)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.OFFApplication.onCreate(OFFApplication.java:48)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806)
03-11 10:30:40.555 18667 18667 E AndroidRuntime: 	... 8 more
```

**Expected behavior:** 

Not having an application crash.

**Observed behavior:** 

A complete crash

**Device and Android version:** 

Sony Xperia Z3 Compact, official Sony ROM on Android 6.0.1.

Note: This is using the F-droid version of the application on version 0.8.2.

**Comment by l-o-b-s-t-e-r** [comment]
Which version was installed before?

**Comment by jaztriumph** [comment]
@Porkepix this has been resolved in #1075 it was merged only 8 days ago.

**Comment by teolemon** [comment]
@itchix Can you tag a new version for F-Droid ?

**Comment by Karljoones** [comment]
Second user reported with 
Os: fairphone open.

**Comment by mikini** [comment]
Also experiencing crash immediately on start-up  (quick glimpse of logo) on stock Samsung Galaxy S7 after upgrade from 0.7.4 to 0.8.2 from fdroid. Haven't looked at logs.

**Comment by dirtygardner** [comment]
Immediate crash on start-up after upgrading to Open Food Facts 0.8.2 (SAMSUNG-SGH-I747 Android 4.4.2).

**Comment by dirtygardner** [comment]
Immediate crash on start-up: Open Food Facts 0.8.5 (SAMSUNG-SGH-I747 Android 4.4.2).

**Comment by teolemon** [comment]
@dirtygardner can you provide a log ?

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/1343

**Comment by dirtygardner** [comment]
Immediate crash on start-up: Open Food Facts 0.8.5 (SAMSUNG-SGH-I747 Android 4.4.2). 

--------- beginning of /dev/log/system
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
--------- beginning of /dev/log/main
V/Term    (10490): onCreate
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
I/Term    (10490): Bound to TermService
I/TermService(10490): Activity binding to service
D/dalvikvm(10490): GC_CONCURRENT freed 3919K, 34% free 11829K/17840K, paused 3ms+21ms, total 77ms
D/dalvikvm(10490): GC_FOR_ALLOC freed 3567K, 52% free 8601K/17840K, paused 34ms, total 35ms
I/dalvikvm-heap(10490): Grow heap (frag case) to 12.392MB for 1127536-byte allocation
D/dalvikvm(10490): GC_CONCURRENT freed 67K, 46% free 9670K/17840K, paused 2ms+2ms, total 26ms
E/ViewRootImpl(10490): sendUserActionEvent() mView == null
E/ViewRootImpl(10490): sendUserActionEvent() mView == null
W/IInputConnectionWrapper(10490): showStatusIcon on inactive InputConnection
I/Term    (10490): Subprocess exited: 129
V/Term    (10490): onCreate
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
D/Term    (10490): TermService started
I/TermService(10490): Activity called onBind()
I/Term    (10490): Bound to TermService
I/TermService(10490): Activity binding to service
I/Term    (10490): waiting for: 11171
D/dalvikvm(10490): GC_CONCURRENT freed 595K, 44% free 9995K/17840K, paused 2ms+5ms, total 34ms
W/IInputConnectionWrapper(10490): showStatusIcon on inactive InputConnection
V/Term    (10490): onCreate
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
I/Term    (10490): Bound to TermService
I/TermService(10490): Activity binding to service
W/IInputConnectionWrapper(10490): showStatusIcon on inactive InputConnection
V/Term    (10490): onCreate
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
I/Term    (10490): Bound to TermService
I/TermService(10490): Activity binding to service
D/dalvikvm(10490): GC_CONCURRENT freed 1967K, 50% free 9008K/17840K, paused 2ms+7ms, total 33ms
D/dalvikvm(10490): WAIT_FOR_CONCURRENT_GC blocked 34ms
I/dalvikvm-heap(10490): Grow heap (frag case) to 12.791MB for 1127536-byte allocation
D/dalvikvm(10490): GC_CONCURRENT freed 23K, 44% free 10127K/17840K, paused 2ms+4ms, total 43ms
E/ViewRootImpl(10490): sendUserActionEvent() mView == null
W/IInputConnectionWrapper(10490): showStatusIcon on inactive InputConnection
I/Term    (10490): Subprocess exited: 129
V/Term    (10490): onCreate
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
D/Term    (10490): TermService started
I/TermService(10490): Activity called onBind()
I/Term    (10490): Bound to TermService
I/TermService(10490): Activity binding to service
I/Term    (10490): waiting for: 11691
D/dalvikvm(10490): GC_CONCURRENT freed 1064K, 45% free 9961K/17840K, paused 2ms+5ms, total 36ms
D/dalvikvm(10490): GC_CONCURRENT freed 2171K, 52% free 8705K/17840K, paused 4ms+5ms, total 37ms
D/dalvikvm(10490): GC_CONCURRENT freed 929K, 52% free 8716K/17840K, paused 2ms+10ms, total 49ms
D/dalvikvm(10490): GC_CONCURRENT freed 938K, 52% free 8719K/17840K, paused 2ms+8ms, total 46ms
D/dalvikvm(10490): GC_CONCURRENT freed 946K, 52% free 8725K/17840K, paused 3ms+6ms, total 52ms
D/dalvikvm(10490): GC_CONCURRENT freed 938K, 52% free 8726K/17840K, paused 5ms+7ms, total 40ms
W/IInputConnectionWrapper(10490): showStatusIcon on inactive InputConnection
V/Term    (10490): onCreate
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
I/Term    (10490): Bound to TermService
I/TermService(10490): Activity binding to service
D/dalvikvm(10490): GC_FOR_ALLOC freed 475K, 52% free 8688K/17840K, paused 30ms, total 31ms
I/dalvikvm-heap(10490): Grow heap (frag case) to 12.477MB for 1127536-byte allocation
D/AbsListView(10490): Get MotionRecognitionManager
D/dalvikvm(10490): GC_CONCURRENT freed 158K, 46% free 9643K/17840K, paused 3ms+3ms, total 35ms
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
W/ResourceType(10490): Invalid package identifier when getting bag for resource number 0xffffffff
D/AbsListView(10490): onDetachedFromWindow
W/InputEventReceiver(10490): Attempted to finish an input event but the input event receiver has already been disposed.
E/ViewRootImpl(10490): sendUserActionEvent() mView == null
D/dalvikvm(10490): GC_CONCURRENT freed 539K, 44% free 10030K/17840K, paused 3ms+9ms, total 55ms
D/dalvikvm(10490): GC_CONCURRENT freed 2229K, 52% free 8719K/17840K, paused 3ms+5ms, total 41ms
D/dalvikvm(10490): GC_CONCURRENT freed 920K, 52% free 8719K/17840K, paused 3ms+6ms, total 39ms
D/dalvikvm(10490): GC_CONCURRENT freed 909K, 52% free 8714K/17840K, paused 4ms+8ms, total 41ms
D/dalvikvm(10490): GC_CONCURRENT freed 918K, 52% free 8719K/17840K, paused 3ms+5ms, total 43ms
W/IInputConnectionWrapper(10490): showStatusIcon on inactive InputConnection
V/Term    (10490): onCreate
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
I/Term    (10490): Bound to TermService
I/TermService(10490): Activity binding to service
D/dalvikvm(10490): GC_CONCURRENT freed 866K, 51% free 8775K/17840K, paused 2ms+8ms, total 36ms
D/dalvikvm(10490): GC_CONCURRENT freed 980K, 52% free 8726K/17840K, paused 3ms+5ms, total 37ms
D/dalvikvm(10490): GC_CONCURRENT freed 900K, 52% free 8723K/17840K, paused 3ms+5ms, total 33ms
W/IInputConnectionWrapper(10490): showStatusIcon on inactive InputConnection
V/Term    (10490): onCreate
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
I/Term    (10490): Bound to TermService
I/TermService(10490): Activity binding to service
D/dalvikvm(10490): GC_CONCURRENT freed 859K, 51% free 8789K/17840K, paused 4ms+5ms, total 43ms
W/IInputConnectionWrapper(10490): showStatusIcon on inactive InputConnection
V/Term    (10490): onCreate
D/MultiPhoneWindow(10490): generateLayout : sMinimumStackBoundForPortraitOrientRect(0, 0 - 0, 0), sMinimumStackBoundForLandscapeOrient=Rect(0, 0 - 0, 0)
I/Term    (10490): Bound to TermService
I/TermService(10490): Activity binding to service
D/dalvikvm(10490): GC_CONCURRENT freed 924K, 51% free 8789K/17840K, paused 3ms+5ms, total 58ms
D/dalvikvm(10490): GC_CONCURRENT freed 886K, 51% free 8845K/17840K, paused 2ms+4ms, total 26ms
D/dalvikvm(10490): GC_CONCURRENT freed 921K, 51% free 8822K/17840K, paused 3ms+4ms, total 30ms
D/dalvikvm(10490): GC_CONCURRENT freed 915K, 51% free 8848K/17840K, paused 3ms+4ms, total 31ms
D/dalvikvm(10490): GC_CONCURRENT freed 920K, 51% free 8828K/17840K, paused 3ms+3ms, total 27ms
D/dalvikvm(10490): GC_CONCURRENT freed 903K, 51% free 8821K/17840K, paused 4ms+7ms, total 44ms
D/dalvikvm(10490): GC_CONCURRENT freed 910K, 51% free 8856K/17840K, paused 3ms+6ms, total 44ms
D/dalvikvm(10490): GC_CONCURRENT freed 923K, 51% free 8829K/17840K, paused 3ms+4ms, total 27ms
D/dalvikvm(10490): GC_CONCURRENT freed 906K, 51% free 8821K/17840K, paused 3ms+7ms, total 41ms
D/dalvikvm(10490): GC_CONCURRENT freed 927K, 51% free 8834K/17840K, paused 3ms+6ms, total 35ms
D/dalvikvm(10490): GC_CONCURRENT freed 922K, 51% free 8837K/17840K, paused 4ms+6ms, total 44ms
W/IInputConnectionWrapper(10490): showStatusIcon on inactive InputConnection

**Comment by Porkepix** [comment]
Closing, bugs fixed some times ago.
