### ISSUE TITLE
Weight should popup a numerical keyboard instead of a text keyboard

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#12]
and perhaps a way to set the units.

**Comment by teolemon** [comment]
Fixed, but now the problem is that the unit is not properly set. Perhaps a dropdown with common units ?

**Comment by itchix** [comment]
Certainly, I can do it

**Comment by itchix** [comment]
Fix in 630e2fa415d2c87a7d485266c9756dea58d59c54
