### ISSUE TITLE
Offer to store locally an history of scans

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#120]
Offer to store locally an history of scanned products.
Creating a view listing all scanned products.

**Comment by itchix** [comment]
You want all info of the product stored locally or just the name, barcode, image... ?

**Comment by teolemon** [comment]
perhaps just the barcode, and make the query whenever you look at the product.
Perhaps saving offline could be an option later.

**Comment by itchix** [comment]
Doing that this week-end

**Comment by itchix** [comment]
@teolemon the history view show all product scanned or only like the 5, 10 last product scanned?

**Comment by teolemon** [comment]
All history ? At some point, we could allow for deletion

**Comment by herau** [comment]
in my opinion, we should provide a full history of scanned products.
