### ISSUE TITLE
The app crash immediately

### ISSUE THREAD

**Issue by stemy2** [openfoodfacts/openfoodfacts-androidapp#1216]
Hello,

Since the version 0.8.2, i can't launch the app because it crashes at the splash screen.

Os: fairphone open.

**Comment by teolemon** [comment]
We released a fix for F-Droid yesterday evening. It should take a while to appear as an upgrade.

**Comment by Karljoones** [comment]
@stemy2 can you confirm if it is fixed in the latest update from F-Droid? If it is, we can close off this issue.

**Comment by stemy2** [comment]
Nope, the fixed version is not (yet) present.

**Comment by Karljoones** [comment]
I'm going to close this as it is being dealt with under #1197. Thanks for reporting @stemy2
