### ISSUE TITLE
Adaptative icons

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1230]
We're not quite there yet. 
![image](https://user-images.githubusercontent.com/1689815/37336579-23582a42-26b2-11e8-8dd8-3ce6d8ae2872.png)
![image](https://user-images.githubusercontent.com/1689815/37336583-275fc866-26b2-11e8-997b-33d415931985.png)
![image](https://user-images.githubusercontent.com/1689815/37336595-2c1f1334-26b2-11e8-95cf-dfd62fab30b3.png)

**Comment by PrajwalM2212** [comment]
@teolemon  Are these images from device running Android O

**Comment by teolemon** [comment]
I believe it's fixed.
