### ISSUE TITLE
Pull to reload on Product View

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1232]
**Summary:** 

Implement pull to reload on Product View

**Expected behavior:** 

When you drag/pull on one of the tabs of product view, it should reload the full product page, while staying on the same tab.

**Comment by shivanshsoni** [comment]
I am working on this

**Comment by Shubham2320** [comment]
I'm taking issues with product page.

**Comment by Shubham2320** [comment]
Okay @shivanshsoni you can proceed if you want to.

**Comment by shivanshsoni** [comment]
@Shubham2320 Ok go for it

**Comment by shivanshsoni** [comment]
@Shubham2320 This is related to product page. Are you sure that you don't want to go for it.

**Comment by Shubham2320** [comment]
@shivanshsoni okay then I'll work on it, thanks.

**Comment by alexaldev** [comment]
@Shubham2320 How is this going? Can I proceed with it ?

**Comment by Shubham2320** [comment]
@alexaldev actually I'm busy in my exams so I'm not able to complete it, you can proceed with this issue if you want.

**Comment by Shubham2320** [comment]
but before proceeding with it please wait for some PR's related to this page which is yet to be merged.

**Comment by alexaldev** [comment]
Sure, thanks !

**Comment by l-o-b-s-t-e-r** [comment]
I'm working on it
