### ISSUE TITLE
Performance issues on the Product Page (at first load ?)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1233]
**Summary:** 

Performance issues on the Product Page (at first load ?)
No logs so far. Possibly had spotty network when it occured. Also, first load after fresh compile.

**Expected behavior:** 

Load the product fast, even on a budget phone

**Observed behavior:** 

Open Food Facts isn't responding, even on a premium phone.

**Device and Android version:** 

Android Oreo, Google Pixel

**Screenshots:** 

![image](https://user-images.githubusercontent.com/1689815/37337083-92b42944-26b3-11e8-9c70-d66be85465f7.png)

**Comment by Karljoones** [comment]
There is a lot of information processed when the user opens up a product so to load all of that information and parse it all, it doesn't surprise me that we ran into some issues with it eventually. 

IMO: one of the first things that we should implement is the images being loaded on a separate thread, possibly breaking off some of the other parsing of information into another thread

**Comment by Shubham2320** [comment]
Actually we only get url of images in the Json response and then use that to load images using Picasso so it's already in the different thread please correct me if I'm wrong. And I was thinking to add a materialistic loading as right now we don't show that. I'm taking this one and work on it.

**Comment by l-o-b-s-t-e-r** [comment]
It means that some operations are working in the main(UI) thread.
For example saving, loading data from the local database. It should be moved to the background thread. I didn't implemented this, because my PR was already huge.
