### ISSUE TITLE
Search results page behaving erratically

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1234]
**Summary:** 

Search results page behaving erratically, loading or not loading

**Steps to reproduce:** 

Click on a facet

**Expected behavior:** 

Always display offline msg if offline
Always display results if online

**Device and Android version:** 

Android Oreo - Google Pixel

**Screenshots:** 
![image](https://user-images.githubusercontent.com/1689815/37338067-960c9ed4-26b6-11e8-869e-b03b72f723a6.png)
![image](https://user-images.githubusercontent.com/1689815/37338073-9ad08156-26b6-11e8-8f52-4fac29aec6df.png)

**Comment by Shubham2320** [comment]
I'm making changes in this activity so I'll update this too there itself. I'm taking this one.

**Comment by PrajwalM2212** [comment]
This a priority issue and must be resolved fast .

**Comment by Shubham2320** [comment]
This has happened because of in ProducTBrowsingListActivity there was no `break` statement in switch case for "search", "search by category" and "labels" , I've made a PR #1226 on it.

**Comment by PrajwalM2212** [comment]
![c](https://user-images.githubusercontent.com/30733262/37378748-85dd5b02-2756-11e8-9f0c-6f30217f8fe1.png)

@Shubham2320 After moving to single activity , the user can search products only from home . Like before we should allow  search in product list view also .

@teolemon @Karljoones @policorn Should we allow search option in product list view ?

**Comment by Shubham2320** [comment]
Okay @prajwal what are other use cases in which  the user can search products other then from home? I think we can modify this as per our requirements and the main reason to make a single activity was that if in future their is any requirement of making changes to this feature then we can do that by just making changes at a single place, otherwise it would be difficult to manage the code, however if you have any better approach then we can discuss on that.

**Comment by Shubham2320** [comment]
@PrajwalM2212 yes we can add a search bar to this activity as well.

**Comment by PrajwalM2212** [comment]
@Shubham2320 Thanks ! 
Suppose i search a product  and from that product i click categories and so on , i will have to press back that many times to reach the home to make another search . This would be really inconvinient from a users perspective.  
Sorry if it involves work , but this is really important from a users perspective.
