### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1241]
You must enter the characters of the barcode or send a product image when the barcode is visible.

>to>

You must enter the characters of the barcode or send a product image where the barcode is visible.

**Comment by PrajwalM2212** [comment]
Working on it

**Comment by Karljoones** [comment]
Thanks @PrajwalM2212! Could we ask you to bump #1238 into the same PR? This is a simple issue that just requires the removal of the strings from the main values.xml

**Comment by PrajwalM2212** [comment]
Sure ...i will get all three in one pull request .

**Comment by PrajwalM2212** [comment]
@Karljoones I am not able to find the string "You must enter the characters of the barcode or send a product image where the barcode is visible." in strings.xml

**Comment by Karljoones** [comment]
@PrajwalM2212 just had a look through the code myself, can't seem to find it, maybe @teolemon can shed some light on where he seen this string?

**Comment by teolemon** [comment]
Sorry, this was a server string. Closing this bug.
