### ISSUE TITLE
Allow users to categorize/filter product results in the App 

### ISSUE THREAD

**Issue by hismaeel** [openfoodfacts/openfoodfacts-androidapp#1251]
Hello. I was wondering it would be nice project to allow users search for products using filters and categories, just as it's done by the website;

![untitled](https://user-images.githubusercontent.com/25305892/37467064-83501d36-281c-11e8-9026-ce85f50dc001.png)

A user might just come to the app to search for product he/she can't remember. So if I type "broccoli", the app just gives hundreds of results, most not relevant to the location, store, and other preferences that I look for. Would be great to filter the results. Also, to build graphs and statistics as the website allows.

**Comment by PrajwalM2212** [comment]
@hismaeel  Allowing the user to search products by preferences is a GSoC project idea.  Comparing products using statistics is also a GSoC idea.

**Comment by PrajwalM2212** [comment]
@hismaeel  As we are doing this in GSoC i suggest you to not start working on this . 
Many people have already started writing proposals.
