### ISSUE TITLE
Offline mode is slow

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1258]
Saving a product in offline mode is slow. It should be instant, even if work is done on the background: People want to scan / save as many products as possible, very quickly.

**Comment by jaztriumph** [comment]
@teolemon I think saving the products in local database does not take time, but uploading takes time. Currently when the user saves the product, we are uploading the product and if there is no network or any other failure occurs we are saving it in offline edit. The updates we can make is that we will save the product with out uploading and then we will make a scheduler which will upload the products from time to time , in a similar way it is done in #887  . I will work on this after #1228 gets merged, If not there will be many merge conflicts.

**Comment by Karljoones** [comment]
@jaztriumph  are you working on this

**Comment by jaztriumph** [comment]
@Karljoones Currently I am not working on this.

**Comment by Karljoones** [comment]
Thank you for confirming

**Comment by huzaifaiftikhar** [comment]
Closed in #1712
