### ISSUE TITLE
Scanning can be slow

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1259]
Scanning can be slow, the viewfinder freezes for several seconds, probably when it's loading the JSON. We should directly jump to the page, and display a placeholder until it's loaded.

**Comment by PO15ON** [comment]
I will have a look at this.

**Comment by PO15ON** [comment]
@teolemon what do you mean by "the page"? the product page? what if there is no product exist?

**Comment by teolemon** [comment]
Yes, the product page if it exists.
The offline mode is also slow to load, but that's another issue.

**Comment by PO15ON** [comment]
But we don't know if it exists until we load the JSON, which is our problem here. The problem causing the scanner to freeze is when making a connection to the server.

**Comment by Karljoones** [comment]
@PO15ON are you working on this? A progress bar would work in this case.

**Comment by PO15ON** [comment]
@Karljoones I was trying to open the product page while it is loading, but the user will wait as before.
I will implement the progress bar. Thanks.

**Comment by Karljoones** [comment]
Thanks!

**Comment by Karljoones** [comment]
This was implemented with a loading dialog as part of the scanner, which i think looks fine, not the same as this issue but still solved the problem. Closing this issue.
