### ISSUE TITLE
Choose language when adding a new product

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/openfoodfacts-androidapp#126]
When adding a new product with the app, it seems the default langage for the product is english and we can't choose it. So if I add a french product, when I want to edit it on the website, its main langage is english, and I have to reupload the images as french, because elsewhere they don't appear on the product page.

So we shoud be able to choose the language when adding a new product, and we could add a default language in the settings for example.

**Comment by herau** [comment]
duplicate of #129 ?

**Comment by teolemon** [comment]
This one is easier and more important to implement, I guess. 

#129 is trying to be smart (and can be outsmarted, eg Chinese product scanned in France)
