### ISSUE TITLE
Both Jackson and Gson library is used in app. Should be one of them.

### ISSUE THREAD

**Issue by Shubham2320** [openfoodfacts/openfoodfacts-androidapp#1261]
At present both Jackson and Gson Library is used to handle JSON results whereas we can work with any one of them and remove the other which would help in reducing the APK's size.

**Comment by Karljoones** [comment]
Just going to leave this here to help with deciding which one should stay and which should go if either of them are to go: 
https://blog.takipi.com/the-ultimate-json-library-json-simple-vs-gson-vs-jackson-vs-json/

**Comment by teolemon** [comment]
@jinqian

**Comment by l-o-b-s-t-e-r** [comment]
My fault, I used GSON for deserialization.
I will try to remake.
