### ISSUE TITLE
Fragments keeps changing among them on back press

### ISSUE THREAD

**Issue by danzzen** [openfoodfacts/openfoodfacts-androidapp#1262]
Fragments keep changing between them in order they were called 

**Steps to reproduce:** 

1. Open the app
2. Click on Search by barcode
3. Click on Home
4. Click on Search by barcode
5. Click on Home again

repeat this and
 
Now press back button and `home `and `Search by barcode ` appears again and again.

**One problem is that when you press Home 5 time and now you want to exit the app you have to press the back button 5 times**

**Expected behavior:** 
From any fragment if back button is pressed it should return to home fragment.

**Screenshots:** 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22103919/37552930-3f33979e-29e4-11e8-978f-bc41b3d41b3f.gif)

**Comment by danzzen** [comment]
I would like to work on this

**Comment by PrajwalM2212** [comment]
@danzzen  Suppose i searched a product and from that product i clicked category .
Now i want to go back to the product page and not home . What to do now ?

**Comment by danzzen** [comment]
@PrajwalM2212 this is to reduce the overhead. Home is like main part and wherever you go you return to home.

**Comment by PrajwalM2212** [comment]
It is not wise to just return to  home from every fragment . It would be better if back stacking of fragments is managed properly  .

**Comment by PrajwalM2212** [comment]
@danzzen 
Can you please do some research on this . Check the youtube app . It does not return to home everytime  you press back .
