### ISSUE TITLE
It should be possible to slide out the intro slides

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1264]
It should be possible to slide out the intro slides, from the last slide. Currently you have to move your finger to Okay.

**Comment by iml-v** [comment]
@teolemon i will correct it

**Comment by PO15ON** [comment]
I'm working on it

**Comment by PO15ON** [comment]
@teolemon Travis shows: The job exceeded the maximum time limit for jobs, and has been terminated.
could you please review the PR.
