### ISSUE TITLE
Give padding in allergen alert list

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#1267]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
Deleting the last item in allergen alert can be difficult due to the overlapping of the floating action button and the delete button.

**Steps to reproduce:** 
Add a long list of allergens.

**Expected behavior:** 
Floating action button should be present below this list.

**Observed behavior:** 
Floating action button overlaps the Delete button.

**Screenshots:** 
![screenshot_20180317-232837](https://user-images.githubusercontent.com/10832531/37558643-d81e7980-2a3c-11e8-87cb-21f4143168d6.png)

**Comment by vaishali51** [comment]
I would like to work on it.
