### ISSUE TITLE
The Load Toast in Login keep showing loading

### ISSUE THREAD

**Issue by amanjeetsingh150** [openfoodfacts/openfoodfacts-androidapp#1270]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 

The Load Toast in LoginActivity keeps loading even after the incorrect password message has been shown. It should hide after getting the response from the server.

**Steps to reproduce:** 

Hiding the Load Toast in OnResponse after we get confirmation for the wrong credentials.

**Expected behavior:** 

The loader should hide after the wrong credentials message has been shown. Because there is no network call after that. 

**Observed behavior:** <br>
<img src="https://user-images.githubusercontent.com/12881364/37560552-9d3dd5c6-2a60-11e8-91ba-d08f198212ff.gif"/>
<br>
**Device and Android version:** 
Moto E Android Version 5.1

**Comment by amanjeetsingh150** [comment]
@teolemon @Karljoones  Can I fix this and send a quick PR?

**Comment by Shubham2320** [comment]
@amanjeetsingh150 you can send the PR if you're sure about this bug.   :)

**Comment by Karljoones** [comment]
@amanjeetsingh150 Go ahead!
