### ISSUE TITLE
Add a battery low mode in settings

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1273]
If battery low, we could disable image loading.

'''Disable image loading on low battery'''

```
PowerManager powerManager = (PowerManager)
    getActivity().getSystemService(Context.POWER_SERVICE);
if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP
        && powerManager.isPowerSaveMode()) {
    // Animations are disabled in power save mode, so just show a toast instead.
    Toast.makeText(mContext, getString(R.string.toast), Toast.LENGTH_SHORT).show();
}
```

**Comment by ManavPoddar** [comment]
I would like to work on it :)

**Comment by ManavPoddar** [comment]
Hey @teolemon, what I can understand is that we wont display the images if the low battery mode is turned on. So I was thinking of using shared preferences to add a check for the low battery and then using it in the respective views. Please correct me if I'm wrong. Also is there a better approach you can think of ?   :)

**Comment by Shubham2320** [comment]
@ManavPoddar  you could just add a helper function which you can call from every place before loading images. The helper function will check the battery and return a boolean value about the status to load images or not.
