### ISSUE TITLE
Add support for vitamins and minerals in products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1275]
We recently added support for vitamins and minerals in products.
In some cases, you will find what is below in a product:
```
Added vitamins:
Minerals:
Added amino acids:
Other nutritional substances added:
```

===== Vitamins and minerals detection =====

====== Vitamins ======
<pre>"vitamins_tags":["en:vitamin-a","en:cholecalciferol","en:vitamin-e","en:vitamin-c","en:thiamin","en:riboflavin","en:niacin","en:vitamin-b6","en:folic-acid","en:vitamin-b12","en:biotin","en:phylloquinone"]</pre>
====== Minerals ======
<pre>"minerals_tags":["en:calcium-citrate","en:potassium-citrate","en:sodium-citrate","en:magnesium-chloride","en:calcium-phosphate","en:potassium-phosphate","en:ferrous-sulphate","en:zinc-sulphate","en:cupric-sulphate","en:manganese-sulphate","en:sodium-carbonate","en:potassium-iodide"]</pre>

====== Amino acids ======
<pre>"amino_acids_tags":["en:l-tryptophan"]</pre>

====== Other nutritional substances =====
<pre>"other_nutritional_substances_tags":["en:taurine","en:inositol","en:choline-citrate","en:taurine","en:inositol","en:choline-citrate","en:taurine","en:inositol","en:choline-citrate"]<pre>

**Comment by amanjeetsingh150** [comment]
Working on this issue.
