### ISSUE TITLE
Show prepared values for prepared products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1288]
You need to concatenate _prepared to the regular values

Example:
https://world.openfoodfacts.org/product/3036812020704/gratinee-oignons-et-croutons-royco
https://world.openfoodfacts.org/api/v0/product/3036812020704.json

```{"salt_prepared_100g":0.850000000000001,"carbohydrates_unit":"","sodium_prepared":0.334645669291339,"fiber_prepared_value":"0.2","nutrition-score-fr":"3","proteins_prepared":0.6,"salt_prepared":0.850000000000001,"energy_prepared_serving":"292","fiber_prepared_serving":0.4,"sugars_prepared_value":"0.6","carbohydrates_prepared":"5","saturated-fat_prepared_value":"0.7","energy_prepared":"146","proteins_unit":"","fat_prepared_value":"1.4","sugars_prepared_100g":0.6,"sodium_prepared_serving":0.669,"nutrition-score-uk":"3","energy_prepared_value":"35","salt_unit":"","sodium_prepared_value":"0.334645669291339","nutrition-score-uk_100g":"3","salt_prepared_value":"0.85","saturated-fat_prepared_100g":0.7,"fat_unit":"","saturated-fat_prepared_serving":1.4,"carbohydrates_prepared_serving":"10","fat_prepared_serving":2.8,"sodium_prepared_100g":0.334645669291339,"proteins_prepared_100g":0.6,"sugars_prepared":0.6,"fat_prepared":1.4,"proteins_prepared_serving":1.2,"fiber_unit":"","salt_prepared_serving":1.7,"fiber_prepared_100g":0.2,"proteins_prepared_value":"0.6","fat_prepared_100g":1.4,"sugars_unit":"","sugars_prepared_serving":1.2,"energy_unit":"kcal","nutrition-score-fr_100g":"3","saturated-fat_prepared":0.7,"carbohydrates_prepared_100g":"5","carbohydrates_prepared_value":"5","saturated-fat_unit":"","energy_prepared_100g":"146","fiber_prepared":0.2}```

**Comment by teolemon** [comment]
It should probably be additional columns, but raises UX questions, since it can create up to 2 additional columns

**Comment by jaztriumph** [comment]
@teolemon what is the difference between 'fat_prepared_value' and 'fat_value'  or 'fat_prepared_serving' and 'fat_serving' ? some products have 'fat_prepared_value' like example you gave, but some doesn't have _prepared like 
https://world.openfoodfacts.org/api/v0/product/3073780258098.json

**Comment by teolemon** [comment]
@jaztriumph This is present only on products that need a preparation with milk or water. 
Most product won't have prepared.
Like Cake Mix, where you have fat_value for just the powder, and fat_prepared_value for the prepared version (Powder + Milk + Butter + Egg, for instance)

**Comment by jaztriumph** [comment]
@teolemon so should we need to display all the four columns is this the issue?

**Comment by jaztriumph** [comment]
@teolemon can you confirm whether we need to display all four columns?

**Comment by teolemon** [comment]
Either the four or find some creative way to expand or scroll them ?
