### ISSUE TITLE
Home screen lacks user-engagement content 

### ISSUE THREAD

**Issue by gulzar1996** [openfoodfacts/openfoodfacts-androidapp#1292]
On opening the app for the first time user is greeted with almost a blank screen with most of the features of the app hidden behind a navigation bar. This makes the experience dull.

- Instead we can show some items when the user opens the app for the first time like (most viewed food products and their nutritional value, top food products in the location and recently added products) (Similar to RecipeBook App) 
<img src="https://user-images.githubusercontent.com/11061198/37643819-ca03aaca-2c47-11e8-8d03-719a884f8acb.png" width="300" hspace="20">

- Show important features of the app in bottom bar. (because a user is more likely to click a bottombar than a navbar)
I want to make the home screen more engaging but is there any existing end points which I can use to display contents like (most viewed food products, top food products in location ) ?

**Comment by Shubham2320** [comment]
Yep, this would be a nice idea but this issue has already been opened in #704 and #706.

**Comment by Karljoones** [comment]
Closed duplicate
