### ISSUE TITLE
Issues with the intro slides of Open Pet Food Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1300]
The strings are cut half-way.

![screenshot_20180320-184334](https://user-images.githubusercontent.com/1689815/37707194-99a2f0c8-2d02-11e8-9000-5d13701c53f5.png)
![screenshot_20180320-184336](https://user-images.githubusercontent.com/1689815/37707195-99c002f8-2d02-11e8-9dba-71b749367c51.png)
![screenshot_20180320-184342](https://user-images.githubusercontent.com/1689815/37707196-99d8eb9c-2d02-11e8-8b93-17840bdcfe1a.png)

**Comment by PO15ON** [comment]
I can work on this
