### ISSUE TITLE
Image animations on Ingredient and nutrition images are not consistant with the new front animation

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1305]
Image animations on Ingredient and nutrition images are not consistant with the new front animation.

**Comment by amanjeetsingh150** [comment]
Will try to fix this :+1:

**Comment by huzaifaiftikhar** [comment]
@amanjeetsingh150 Are you still working on this?

**Comment by PrajwalM2212** [comment]
@huzaifaiftikhar  Sorry , I did not see the conversation before sending the PR .
