### ISSUE TITLE
Individual category doesn't load (Cloud icon) when the app is in French

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1306]
Individual category doesn't load (Cloud icon) when the app is in French.

Steps to reproduce:
- set the app in French (or some other language other than English, probably)
- Open the category browser
- Click on a category:

Result:
'Désolé une erreur s'est produite', 'Please retry'

Expected:
Proper loading, like in English

**Comment by ManavPoddar** [comment]
I'll fix it

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon

**Comment by Karljoones** [comment]
@ManavPoddar @l-o-b-s-t-e-r is anyone working on this?

**Comment by l-o-b-s-t-e-r** [comment]
@Karljoones 
I stopped to work on this, because I didn't get any answers on my questions.

**Comment by teolemon** [comment]
sorry for not replying earlier. 
- You have the canonical categories at https://static.openfoodfacts.org/data/taxonomies/categories.json
The url you gave is the canonical categories, plus the user imputed categories.
- Short story: we need to recompute all the categories for all the products server side, because we changed the taxonomies. It's on the TODO list.So basically the categories don't have as many products as they should.

**Comment by teolemon** [comment]
so basically, we need to wait for @stephanegigandet to recompute everything.

**Comment by teolemon** [comment]
(he's on holidays right now)

**Comment by teolemon** [comment]
@l-o-b-s-t-e-r it's actually a wrong call in languages, see #1644 for more details.
