### ISSUE TITLE
app:theme is now deprecated. Please move to using android:theme instead.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1328]
03-26 12:20:42.480 8077-8077/openfoodfacts.github.scrachx.openfood I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.

**Comment by alexaldev** [comment]
I can fix this.

**Comment by Karljoones** [comment]
@alexaldev are you working on this?

**Comment by VaiTon** [comment]
Is this fixed?

**Comment by teolemon** [comment]
A quick search shows that it's not, apparently:
https://github.com/openfoodfacts/openfoodfacts-androidapp/search?q=app%3Atheme&unscoped_q=app%3Atheme

**Comment by ravk1234** [comment]
I would like to work on this issue.

**Comment by teolemon** [comment]
You are very welcome to do so @ravk1234

**Comment by vibhuti019** [comment]
Is this fixed?
