### ISSUE TITLE
"Speichern" (save) text field

### ISSUE THREAD

**Issue by davidak** [openfoodfacts/OpenFoodFacts-androidApp#133]
is this a bug? or what should one put in there?

![screenshot_2016-09-23-14-45-15](https://cloud.githubusercontent.com/assets/91113/18816658/742ff99e-834e-11e6-9985-fbc3cec5ddf3.png)

---

Fairphone 2
Installed from F-Droid
german language

**Comment by herau** [comment]
This should be a translation of "Store" or "Magasin" in French

**Comment by davidak** [comment]
"speichern" is the correct translation for "store"/"save", but why is that a text input field? there is also a "send/save" button.

**Comment by herau** [comment]
the text input field is here for the Name of the shop or supermarket chain where you can buy it

**Comment by davidak** [comment]
@herau Ahh, okay!

In the Webinterface it is called "Läden", what is the plural of "Laden".

See http://de.openfoodfacts.org/produkt/4006574067674/64-peru-edelbitter-heilemann for example.

Maybe there is a technical solution to keep that in sync?

**Comment by herau** [comment]
Currently, the app allow to set only one store, so if you think it's clearer to use `Laden` instead of `speichern`, i will propose the changes

**Comment by davidak** [comment]
>if you think it's clearer to use Laden instead of speichern, i will propose the changes

Absolutely. Thanks!
