### ISSUE TITLE
Remove ": Wiki link present", it pollutes product reading

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1336]
![image](https://user-images.githubusercontent.com/1689815/37929771-25c98912-3141-11e8-965f-b8ccd416a56a.png)

Remove ": Wiki link present", it pollutes product reading

**Comment by Shubham2320** [comment]
So how do we distinguish between the items which has this feature and which don't?

**Comment by teolemon** [comment]
The current behaviour is fine: Open the search result if we have no wikidata link, otherwise, open the popup ?

**Comment by Shubham2320** [comment]
Okay seems good.
