### ISSUE TITLE
Generate screenshots of the app automatically using Fastlane, Screengrab and Espresso

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1342]
https://docs.fastlane.tools/getting-started/android/screenshots/

**Comment by Ekt0s** [comment]
I'm working on it :)

**Comment by Ekt0s** [comment]
@teolemon 
What are the screen you're willing to generate ? 
Can you list them please ?

**Comment by teolemon** [comment]
We can start with:
-Home screen, Summary tab of a product, Wikidata view (when you click on a category), Search view

All languages

Be able to load products from:
https://en.wiki.openfoodfacts.org/Translations/One_complete_typical_product

**Comment by teolemon** [comment]
fixed by @deniger 
issues were opened for final work to be done on this
