### ISSUE TITLE
Allow to filter the categories in the category browser

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1356]
Allow to filter the categories in the category browser. 
Currently you need to scroll and find the right category: it should be possible to type the first letters of the category to filter the list

**Comment by ManavPoddar** [comment]
Working on it

**Comment by l-o-b-s-t-e-r** [comment]
Working on it too

**Comment by teolemon** [comment]
Fixed by @l-o-b-s-t-e-r in https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/1467 , and merged
