### ISSUE TITLE
Add an ingredient analysis tab for Open Beauty Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1357]
Add an ingredient analysis tab for Open Beauty Facts

Option 1: We could either recreate the ingredient list in a clickable, colored version.
Option 2: Vertical list of all the ingredients, where each ingredient can clicked/expanded for more information.

![image](https://user-images.githubusercontent.com/1689815/45914521-6e297900-be46-11e8-85c7-23fb7ea99437.png)

1. Get the ingredient from the product JSON (I simplified the JSON request for legibility)
https://world.openbeautyfacts.org/api/v0/product/3282779063234.json?fields=ingredients,code
```
"ingredients":[  
   {  
      "id":"water",
      "text":"WATER",
      "rank":1
   },
   {  
      "id":"aqua",
      "text":"AQUA",
      "rank":2
   },
   {  
      "id":"sodium-laureth-sulfate",
      "text":"SODIUM LAURETH SULFATE",
      "rank":3
   },
   {  
      "id":"polysorbate-20",
      "text":"POLYSORBATE 20",
      "rank":4
   },
   {  
      "id":"ceteareth-60-myristyl-glycol",
      "text":"CETEARETH-60 MYRISTYL GLYCOL",
      "rank":5
   },
   {  
      "id":"cocamide-mipa",
      "text":"COCAMIDE MIPA",
      "rank":6
   },
   {  
      "id":"propylene-glycol",
      "text":"PROPYLENE GLYCOL",
      "rank":7
   },
   {  
      "id":"caramel",
      "text":"CARAMEL",
      "rank":8
   },
   {  
      "id":"cetrimonium-chloride",
      "text":"CETRIMONIUM CHLORIDE",
      "rank":9
   },
   {  
      "id":"disodium-edta",
      "text":"DISODIUM EDTA",
      "rank":10
   },
   {  
      "id":"fragrance",
      "text":"FRAGRANCE",
      "rank":11
   },
   {  
      "id":"parfum",
      "text":"PARFUM",
      "rank":12
   },
   {  
      "id":"green-3",
      "text":"GREEN 3",
      "rank":13
   },
   {  
      "id":"ci-42053",
      "text":"CI 42053",
      "rank":14
   },
   {  
      "id":"methylisothiazolinone",
      "text":"METHYLISOTHIAZOLINONE",
      "rank":15
   },
   {  
      "id":"methylparaben",
      "text":"METHYLPARABEN",
      "rank":16
   },
   {  
      "id":"phenoxyethanol",
      "text":"PHENOXYETHANOL",
      "rank":17
   },
   {  
      "id":"polyquaternium-22",
      "text":"POLYQUATERNIUM-22",
      "rank":18
   },
   {  
      "id":"propylparaben",
      "text":"PROPYLPARABEN",
      "rank":19
   },
   {  
      "id":"sodium-chloride",
      "text":"SODIUM CHLORIDE",
      "rank":20
   },
   {  
      "id":"sodium-hydroxide",
      "text":"SODIUM HYDROXIDE",
      "rank":21
   },
   {  
      "id":"urtica-dioica",
      "text":"URTICA DIOICA",
      "rank":22
   },
   {  
      "id":"nettle",
      "text":"NETTLE",
      "rank":23
   },
   {  
      "id":"extract",
      "text":"EXTRACT.",
      "rank":24
   }
]
```

2. Load the ingredient taxonomy just like we do for categories, labels…
https://static.openbeautyfacts.org/data/taxonomies/ingredients.json
```  
 "en:water":{  
      "wikidata":{  
         "en":"Q283"
      },
      "iupac":{  
         "en":"Water"
      },
      "inn":{  
         "en":"water"
      },
      "pheur":{  
         "la":"aqua"
      },
      "einecs":{  
         "en":"231-791-2"
      },
      "cas":{  
         "en":"7732-18-5"
      },
      "unii":{  
         "en":"059QF0KO0R"
      },
      "inci":{  
         "en":"AQUA"
      },
      "function":{  
         "en":"Solvent"
      },
      "name":{  
         "es":"Agua",
         "en":"Water",
         "de":"Wasser",
         "la":"Aqua",
         "fr":"Eau"
      }
   },
```

You can get the ingredient IDs from the product, and enrich them from the taxonomy, including the Wikidata system. A more simple version is to open the web version in a Web View 
```
{“text”:“URTICA DIOICA”,“rank”:22,“id”:“urtica-dioica”}
```
https://world.openbeautyfacts.org/ingredient/urtica-dioica

**Comment by PrajwalM2212** [comment]
I will work on it .

**Comment by PrajwalM2212** [comment]
Can i get more information on how this should work ?

**Comment by teolemon** [comment]
@PrajwalM2212 We just got an ingredients taxonomy live for Open Beauty Facts: https://static.openbeautyfacts.org/data/taxonomies/ingredients.json
So you can get the ingredient IDs from the product see above, and enrich them from the taxonomy, including the Wikidata system.

I'm not sure if a clickable ingredient list (or a list (like in the category explorer)) is the best solution.

**Comment by teolemon** [comment]
```   "en:water":{  
      "wikidata":{  
         "en":"Q283"
      },
      "iupac":{  
         "en":"Water"
      },
      "inn":{  
         "en":"water"
      },
      "pheur":{  
         "la":"aqua"
      },
      "einecs":{  
         "en":"231-791-2"
      },
      "cas":{  
         "en":"7732-18-5"
      },
      "unii":{  
         "en":"059QF0KO0R"
      },
      "inci":{  
         "en":"AQUA"
      },
      "function":{  
         "en":"Solvent"
      },
      "name":{  
         "es":"Agua",
         "en":"Water",
         "de":"Wasser",
         "la":"Aqua",
         "fr":"Eau"
      }
   },```

**Comment by teolemon** [comment]
@PrajwalM2212 The idea is that it would work very much like the current Wikidata system we have on click.
Option 1: We could either recreate the ingredient list in a clickable, colored version.
Option 2: Vertical list of all the ingredients, where each ingredient can be expanded for more information.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/45914521-6e297900-be46-11e8-85c7-23fb7ea99437.png)

**Comment by PrajwalM2212** [comment]
@teolemon I will take this issue. I will do this after additives explorer.

**Comment by teolemon** [comment]
@PrajwalM2212 I've been working on linking ingredients to Wikipedia for Open Food Facts as well. So this one has even a broader impact.

**Comment by teolemon** [comment]
https://static.openfoodfacts.org/data/taxonomies/ingredients.json

**Comment by balaji-ramavathu** [comment]
@teolemon i will work on this issue.

**Comment by teolemon** [comment]
Ok @balaji-ramavathu , you can go ahead :-)
