### ISSUE TITLE
Extract  "Error in creating fragment" in MainActivity.java

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1367]
Log.e("MainActivity", "Error in creating fragment");

Extract  "Error in creating fragment" in MainActivity.java as translatable string

**Comment by PrajwalM2212** [comment]
The user will not see these log statements . Should they be extracted ?

**Comment by teolemon** [comment]
Nope, indeed, you're right: I opened too many bugs in a row :-)
>> Closing
