### ISSUE TITLE
Improvements to the share with Open Food Facts feature

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1373]
- Always says it will upload the picture when the network is available (doesn't create any offline product, and the network is actually available in those cases)
- Doesn't work when selecting two or more pictures
- It should show the shared picture even when a barcode is detected
- It should let you zoom on the picture when no barcode is detected
- The Share menu should be named "Add to Open Food Facts" instead of just "Open Food Facts"

**Comment by teolemon** [comment]
cc @sowmya9029

**Comment by sowmya9029** [comment]
I'm working on this.

**Comment by teolemon** [comment]
@sowmya9029 are you still working on this ?
