### ISSUE TITLE
Search by name - be able to to return to the result list

### ISSUE THREAD

**Issue by herau** [openfoodfacts/openfoodfacts-androidapp#138]
Currently when we search a product by its name, we have a result list.
If i select an item, i can't be back to the result list and i have to do again the search.

**Comment by teolemon** [comment]
It goes back to home when clicking on the arrow.

**Comment by herau** [comment]
@teolemon ok but maybe more usefull to go back first to the result list, to choose another item ?

**Comment by teolemon** [comment]
Yes, indeed.

**Comment by Karljoones** [comment]
This has been resolved.
