### ISSUE TITLE
Convert the product view cards to proper material cards

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1403]
Convert the product view cards to proper material cards, with drop shadows
![image](https://user-images.githubusercontent.com/1689815/38413660-a3bcbc42-398c-11e8-8c05-fc4b0691fa7a.png)
![image](https://user-images.githubusercontent.com/1689815/38414127-ea5653a6-398d-11e8-8078-d80af2c350f5.png)

**Comment by teolemon** [comment]
Wet food for adult cats: common name
The Nutriscore should be displayed between the photo and the card, without any background, centered

**Comment by PrajwalM2212** [comment]
Working on it
