### ISSUE TITLE
"Sign in" appears in the drawer when the user is already signed in after re-launching app.

### ISSUE THREAD

**Issue by ross-holloway94** [openfoodfacts/openfoodfacts-androidapp#1410]
**Summary:** 

"Sign in" appears in the drawer when the user is already signed in after re-launching app.

**Steps to reproduce:** 

1. Sign in to Open Food Facts.
2. Close the app (and kill it).
3. Re-open and observe the drawer.

**Add system logs:**
NA

**Expected behaviour**

Button shows the "Logout" option with icon.

**Observed behavior:** 

Button shows "Sign In" still.

**Device and Android version:** 
NA

**Screenshots:** 

![screenshot_20180406-181725](https://user-images.githubusercontent.com/20950727/38434844-c37e1a7c-39c7-11e8-80e6-ded0af021679.jpg)

**Comment by PrajwalM2212** [comment]
Working on it
