### ISSUE TITLE
Remove confirmation step for new products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1414]
![image](https://user-images.githubusercontent.com/1689815/38440329-63f82e16-39e1-11e8-9231-d39c31e21483.png)
Of course they want to be part of food transparency :) Remove the confirmation step. People will be able to press back if they want to go back to the scan screen.

**Comment by PrajwalM2212** [comment]
Working on it

**Comment by teolemon** [comment]
step still exists in prod ??
![image](https://user-images.githubusercontent.com/1689815/40485519-09936e9c-5f5f-11e8-8fc1-5157c74cb8bb.png)
