### ISSUE TITLE
Probably: remove the loading transient info

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1415]
![image](https://user-images.githubusercontent.com/1689815/38440418-ae0f270c-39e1-11e8-9a48-e913d37135c9.png)

Two transient information overlap. Let's remove the loading one. Eventually the offline mode will be so fast we won't need it anyway :)

**Comment by jaztriumph** [comment]
I will remove that.

**Comment by jaztriumph** [comment]
@teolemon I think the Loading toast is already removed in the new master.

**Comment by Karljoones** [comment]
@jaztriumph can you confirm this? If so, this issue can be closed.

**Comment by jaztriumph** [comment]
@Karljoones Yes that's already removed.

**Comment by Karljoones** [comment]
Awesome. Closing this issue.
