### ISSUE TITLE
Take more pictures button can be material 

### ISSUE THREAD

**Issue by PrajwalM2212** [openfoodfacts/openfoodfacts-androidapp#1428]
The take more pictures button is not material and will look good if it is material .

![screenshot_1523287144](https://user-images.githubusercontent.com/30733262/38506489-a70312b8-3c37-11e8-82d1-6ac33553ffa6.png)

**Comment by PrajwalM2212** [comment]
@teolemon  Require your opinion if this issue is ok with you .

**Comment by Karljoones** [comment]
@PrajwalM2212 I agree, this could do with some work

**Comment by PrajwalM2212** [comment]
I will work on it @Karljoones

**Comment by teolemon** [comment]
Do you have an example image of a more material button ?

**Comment by PrajwalM2212** [comment]
@teolemon Probably the blue background button we use in the app.

**Comment by PrajwalM2212** [comment]
![screenshot_20180415-181808](https://user-images.githubusercontent.com/30733262/38778624-f3c5b226-40d9-11e8-83e8-2e178ab7c8ba.jpg)

@teolemon  I was thinking of replacing the bottom navigation by something like in the image above so that we can put all buttons into one . Would this be okay ?

**Comment by Karljoones** [comment]
@PrajwalM2212 the bottom navigation is something that we want to include in the product view, maybe for now we will just leave it as a bottom navigation bar.
