### ISSUE TITLE
Add ability to display an Open Beauty Facts product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#143]
There are a couple of changes with Open Beauty Facts:
- the API url is openbeautyfacts.org instead of openfoodfacts.org
- hide nutrition facts
- add period after opening
- add ingredient analysis
- the taxonomies are not the same

**Comment by itchix** [comment]
So you want a single app for both food and beauty?

**Comment by teolemon** [comment]
Nope, but since it will be the same codebase, we can as well code it into the OFF app ?

**Comment by teolemon** [comment]
and perhaps add a prompt to install Open Beauty Facts

**Comment by Karljoones** [comment]
@teolemon can this be closed as OBF is now a thing and there is a prompt to install from the navigation drawer?

**Comment by teolemon** [comment]
Ok. I wanted to merge both apps at some point.
