### ISSUE TITLE
Remove loading toast on splash screen 

### ISSUE THREAD

**Issue by PrajwalM2212** [openfoodfacts/openfoodfacts-androidapp#1430]
The load toast on splash screen can be removed .
![screenshot_1523287640](https://user-images.githubusercontent.com/30733262/38506910-c9ee9d5a-3c38-11e8-82b7-e2dd9be1cb74.png)

**Comment by PrajwalM2212** [comment]
@teolemon Require your opinion as to whether this issue is ok with you .

**Comment by huzaifaiftikhar** [comment]
This has already been taken care of in #1347
