### ISSUE TITLE
Cannot upload in airplane mode, even with wifi on

### ISSUE THREAD

**Issue by maroneze** [openfoodfacts/openfoodfacts-androidapp#1434]
**Summary:** 

Following #923, it is not possible to click on the "Upload all" button when in airplane mode, even when Wireless is enabled (Wifi is automatically disabled when Airplane mode is activated, but it can be manually re-enabled afterwards - Airplane mode is mainly concerned with disabling the cellular antenna).

I believe the condition implemented in https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/926 is too strict, since I can and frequently scan products while on Airplane mode. Maybe I don't see the exact usage scenario, but it seems that testing "Network connectivity" might be sufficient.

Overall, this is a minor issue since airplane mode can often be disabled without much issue, it's just a bit unexpected. Feel free to close this if not deemed worth of the effort.

**Steps to reproduce:** 

1. Scan products without connectivity (to add them to the Offline edit list)
2. Activate airplane mode
3. Enable wireless
4. Go to offline edit and click Upload All

**Expected behavior:** 

I should be able to click Upload All, since there is network connectivity via wireless.

**Observed behavior:** 

I got the message about "Airplane mode enabled" described in https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/926.

**Device and Android version:** 

Motorola Moto X Style, Stock Android 6.0 Marshmallow

**Screenshots:** 

(I uploaded the products after leaving airplane mode to test, so I don't have an Offline edit list anymore to easily reproduce it and capture a screenshot)

**Comment by teolemon** [comment]
This is fixed in the PR #3072 
Closing this bug
