### ISSUE TITLE
[Suggestion] Use hosted.weblate.org as translation system

### ISSUE THREAD

**Issue by agilob** [openfoodfacts/openfoodfacts-androidapp#144]
You can add your project for free to weblate https://hosted.weblate.org/ and get translations and verification of translations in many languages from contributors all over the world. Making fixes and/or adding new languages is automated by weblate. Please consider doing it :)

**Comment by teolemon** [comment]
We use Launchpad right now because it has a community of translators (especially from Ubuntu).
Is there a change to get translations for languages we don't have yet ?
I guess we could do a double sync if that is the case.

**Comment by teolemon** [comment]
translations.launchpad.net/openfoodfacts

**Comment by agilob** [comment]
I have very good experience with weblate, a few times happened that people came to my projects and just translated it into some languages. I didn't have to create a file for language or anything, they just opened the project and added missing language for them, did translations and left.

weblate is generic for opensource projects, not related to any community or project.

**Comment by teolemon** [comment]
I've started a migration to Crowdin

**Comment by mikini** [comment]
The README.md still mentions Launchpad, I reckon that is obsolete now (maybe also a2po?).
