### ISSUE TITLE
Number of results is duplicated each time when refreshing the list in the OpenBeautyFacts branch.

### ISSUE THREAD

**Issue by yeldartoktasynov** [openfoodfacts/openfoodfacts-androidapp#1454]
/Users/yurka/Downloads/4.png
Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by yeldartoktasynov** [comment]
I want to be assigned to this issue

**Comment by Karljoones** [comment]
Hi @yeldartoktasynov, I noticed that in a few of your issues created that you have not filled in much information in the report. Can you fill in some of the information in the bug report itself? Such as **Steps to reproduce** and **Expected behaviour**.

**Comment by teolemon** [comment]
@yeldartoktasynov Is that bug still occuring ?

**Comment by VaiTon** [comment]
Closing as not being able to reproduce without further details.
