### ISSUE TITLE
Number of results is duplicated each time when refreshing the list in the OpenBeautyFacts branch.

### ISSUE THREAD

**Issue by yeldartoktasynov** [openfoodfacts/openfoodfacts-androidapp#1455]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:** 

How can we reproduce the issue?

**Add system logs:**

Add log files here (if you are able to add).

**Expected behavior:** 

What did you expect the app to do?

**Observed behavior:** 

What did you see instead?  Describe your issue in detail here.

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?  What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it the stock version from the manufacturer or a custom ROM?

**Screenshots:** 
/Users/yurka/Downloads/1.png
Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by Karljoones** [comment]
Closed duplicate
