### ISSUE TITLE
[QUESTION] Why the project isn't the default app in the store ?

### ISSUE THREAD

**Issue by herau** [openfoodfacts/OpenFoodFacts-androidApp#146]
Why the default Open Food Facts Android App is still the old one ? and not built from this project 
![screen shot 2016-10-03 at 3 48 13 pm](https://cloud.githubusercontent.com/assets/2950666/19039594/ef23008c-8980-11e6-993e-e8b77ec890ac.png)

**Comment by teolemon** [comment]
Not usable enough yet. Especially for contribution. I've tagged a few bugs with hacktober.

**Comment by teolemon** [comment]
the Open Beauty Facts is using an old version of this code. We could try to update it first.
