### ISSUE TITLE
Add a little padding on top of the allergen alert

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1482]
![image](https://user-images.githubusercontent.com/1689815/39096443-816aa1c4-4650-11e8-8d99-80a6e97e1fa4.png)

**Comment by Orlandov87** [comment]
Hello, I would like to add padding on this to get accustomed to contributing. 

Thank you.

**Comment by huzaifaiftikhar** [comment]
@Orlandov87 Go ahead
