### ISSUE TITLE
Add a little padding on top of the add photo message

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#1484]
![screenshot_20180417-003416](https://user-images.githubusercontent.com/10832531/39096607-f5f0c568-466f-11e8-9bbf-b8fff24564b9.png)

**Comment by N00845855** [comment]
Yes I will work on this bug

**Comment by N00845855** [comment]
Which of the following components should have padding added?

![screenshot_2018-04-25-21-00-47 sm](https://user-images.githubusercontent.com/33704683/39311793-e633546e-493b-11e8-9057-5ebc31c91046.png)

Should the padding be added above the component (i.e. between two components in the layout) or should it be added around the text within the component? If the padding is to be added around the text within the component, should it be added only at top or to all four sides?

**Comment by huzaifaiftikhar** [comment]
@N00845855 padding is supposed to be added to the top of the card which says "only one photo is compulsory to send a new product". From your screenshot, I would say the first one you mentioned. No need to add padding anywhere else.

**Comment by N00845855** [comment]
Do you also want to me make"Only one photo is complusary to send a product" in the middle of the card as it is towards the top of the card?


![image](https://user-images.githubusercontent.com/33704683/39389022-a4a80cca-4a52-11e8-91ef-9eed383dfe97.png)
![image 1](https://user-images.githubusercontent.com/33704683/39389028-acb4fa72-4a52-11e8-834c-54af9155c4bf.png)

**Comment by huzaifaiftikhar** [comment]
@N00845855 The textual content in the middle looks more good to me. Also do not change the drawable which is at the starting of the card (leave it to be the green icon as it was before)

**Comment by N00845855** [comment]
I never changed the drawable. I updated my project to recent commits and I noticed this change too.

**Comment by huzaifaiftikhar** [comment]
Ohh okay then leave it as it is in this PR.
