### ISSUE TITLE
Clicking SignIn shows " already logged in dialog " even if not logged in

### ISSUE THREAD

**Issue by PrajwalM2212** [openfoodfacts/openfoodfacts-androidapp#1489]
![screenshot_1524422489](https://user-images.githubusercontent.com/30733262/39098608-0d7d6f4a-468b-11e8-9f2d-9d9f2e2959d5.png)
![screenshot_1524422492](https://user-images.githubusercontent.com/30733262/39098609-0fb67ebe-468b-11e8-9257-fdb0bffb9273.png)

**Comment by jaindiv26** [comment]
@PrajwalM2212 Clicking on Sign In does not produce "Already Logged In" dialogue.

**Comment by PrajwalM2212** [comment]
It has been resolved .
