### ISSUE TITLE
Addictives came from files not from API

### ISSUE THREAD

**Issue by herau** [openfoodfacts/OpenFoodFacts-androidApp#149]
Addictives files (english and french) came from the filesystem.
Why not fetch the Open food API ? cf http://world.openfoodfacts.org/additives.json

We also fetch both english and French during the first launch of the application; why not fetch only the locale one ?

**Comment by teolemon** [comment]
Also, a number of strings are not translated while the additives files permit doing that.
An offline version updated using the API would be nice.

**Comment by herau** [comment]
You mean there is a post-job on the current addictives files which add missing translations ? for other languages than english/french ?

The english version is available though `http://en.openfoodfacts.org/additives.json` but the french version doesn't exist `http://fr.openfoodfacts.org/additives.json` (404)

**Comment by teolemon** [comment]
There's not, AFAIK. @itchix your take on this ?

**Comment by herau** [comment]
OK but i don't understand why both english and french addictives files are saved in the DB (without a locale flag/field) ? 
So duplication items are in db and when you need one of them, we estimate that the first is french and second is english; which is not very secure. Then why not only add additives for the current locale ?

```java
final List<Additive> la = Additive.find(Additive.class, "code = ?", tm.toUpperCase());
            if (la.size() == 2) {
                ClickableSpan clickableSpan = new ClickableSpan() {
                    @Override
                    public void onClick(View v) {
                        Additive a;
                        if (Locale.getDefault().getLanguage().contains("fr")) {
                            a = la.get(0);
                        } else {
                            a = la.get(1);
                        }
                    // using a for display
                    }
                };
            }
```

**Comment by itchix** [comment]
I don't remember why I did this... :/
But I think we have to change it and improve it like you said =)

**Comment by herau** [comment]
Ok i will make you a proposal with a PR.
