### ISSUE TITLE
Add left and right padding to the offline edit view 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1491]
![image](https://user-images.githubusercontent.com/1689815/39116347-821b0dd6-46e4-11e8-8622-a5d15da0d1c4.png)

As a card, it shouldn't be edge to edge. Add a minimal amount of left and right padding so that it looks good.

**Comment by teolemon** [comment]
Also reword "Information" to "How does it work ?"

**Comment by SaumiaSinghal** [comment]
Hie @teolemon, I would like to work on this issue. Can you assign it to me?
