### ISSUE TITLE
Unproper commas in the contributor list

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1495]
Current:```moon-rabbit ,openfoodfacts-contributors```
Should be:```moon-rabbit, openfoodfacts-contributors```

![image](https://user-images.githubusercontent.com/1689815/39128275-ad254974-4707-11e8-9d44-2efb951b43f2.png)

**Comment by PrajwalM2212** [comment]
Will take this issue
