### ISSUE TITLE
Use the JSON states taxonomy to translate States

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1497]
We now have a JSON export of the states for the contributor tab:
https://static.openfoodfacts.org/data/taxonomies/states.json
You can enable the contributor tab in the app settings.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/46007506-81447f00-c0ba-11e8-9e96-5e841e183f08.png)

**Comment by vanshikaarora** [comment]
Hey @teolemon. I want to work on this.I can see two tasks in the above Issue:

- Improve the UI 
- Make the translations available in our own language

Shall I start working on this? Also for the UI do you have any particular suggestions in mind?

**Comment by teolemon** [comment]
If you're still in for this, there's a couple of suggestions:

- [ ] Fix the dark mode by removing the hardcoded white background: https://user-images.githubusercontent.com/1689815/87653900-80c91c80-c756-11ea-92bb-7cabbffa721f.png
- [ ] Remove the image card (we now have a dedicated tab for it)
- [ ] Create 2 states sections - DONE & TODO: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/1498

**Comment by kartikaysharma01** [comment]
> The current implementation uses the slugs present in the product instead of the translation in your language available in the taxonomy (and is a bit ugly)
> ![image](https://user-images.githubusercontent.com/1689815/46007506-81447f00-c0ba-11e8-9e96-5e841e183f08.png)



I have implemented the translation. Do you have any layout in mind for this? @teolemon 

![image](https://user-images.githubusercontent.com/71206228/104821559-bdd7ae00-5862-11eb-9d33-804a3646ea8a.png)
