### ISSUE TITLE
Color the product states green or red to make what's left clearer

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1498]
Color the product states green or red to make what's left clearer

Turn the states green or red depending on if they contain:

- red: "to be completed" or "to be uploaded" or "to be checked"
- green: all other states

**Comment by teolemon** [comment]
@PrajwalM2212 unassigning you, unless you still have an uncommited branch ;)

**Comment by kartikaysharma01** [comment]
I would like to work on this.  
@teolemon  Would creating two sections be better or just coloring the text would do the job?

**Comment by VaiTon** [comment]
> 
> 
> I would like to work on this.
> @teolemon Would creating two sections be better or just coloring the text would do the job?

I think creating two sections would be better.

**Comment by kartikaysharma01** [comment]
> > I would like to work on this.
> > @teolemon Would creating two sections be better or just coloring the text would do the job?
> 
> I think creating two sections would be better.

I agree. Do we have a mockup design for this?
