### ISSUE TITLE
Crash on usage

### ISSUE THREAD

**Issue by aeris** [openfoodfacts/OpenFoodFacts-androidApp#150]
Hi here !

I try to use Open Food Facts android app, but application crash every time I try to scan or search for a product.
My phone is a Cyanogen 12.1 with Android 5.1.1, and OFF version 0.2.5.

Below the crash stack trace :

`E/AndroidRuntime(12332): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference
E/AndroidRuntime(12332):        at openfoodfacts.github.scrachx.openfood.fragments.IngredientsProductFragment.cleanAllergensMultipleOccurence(IngredientsProductFragment.java:161)
E/AndroidRuntime(12332):        at openfoodfacts.github.scrachx.openfood.fragments.IngredientsProductFragment.cleanAllergensString(IngredientsProductFragment.java:178)
E/AndroidRuntime(12332):        at openfoodfacts.github.scrachx.openfood.fragments.IngredientsProductFragment.onViewCreated(IngredientsProductFragment.java:59)
E/AndroidRuntime(12332):        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1127)
E/AndroidRuntime(12332):        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
E/AndroidRuntime(12332):        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
E/AndroidRuntime(12332):        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1638)
E/AndroidRuntime(12332):        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
E/AndroidRuntime(12332):        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
E/AndroidRuntime(12332):        at android.support.v4.view.ViewPager.populate(ViewPager.java:1240)
E/AndroidRuntime(12332):        at android.support.v4.view.ViewPager.populate(ViewPager.java:1088)
E/AndroidRuntime(12332):        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
E/AndroidRuntime(12332):        at android.view.View.measure(View.java:17562)
E/AndroidRuntime(12332):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
E/AndroidRuntime(12332):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime(12332):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime(12332):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime(12332):        at android.view.View.measure(View.java:17562)
E/AndroidRuntime(12332):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
E/AndroidRuntime(12332):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime(12332):        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
E/AndroidRuntime(12332):        at android.view.View.measure(View.java:17562)
E/AndroidRuntime(12332):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
E/AndroidRuntime(12332):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime(12332):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime(12332):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime(12332):        at android.view.View.measure(View.java:17562)
E/AndroidRuntime(12332):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
E/AndroidRuntime(12332):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime(12332):        at android.view.View.measure(View.java:17562)
E/AndroidRuntime(12332):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
E/AndroidRuntime(12332):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime(12332):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime(12332):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime(12332):        at android.view.View.measure(View.java:17562)
E/AndroidRuntime(12332):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
E/AndroidRuntime(12332):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime(12332):        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2871)
E/AndroidRuntime(12332):        at android.view.View.measure(View.java:17562)
E/AndroidRuntime(12332):        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
E/AndroidRuntime(12332):        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
E/AndroidRuntime(12332):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
E/AndroidRuntime(12332):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime(12332):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
E/AndroidRuntime(12332):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(12332):        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(12332):        at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime(12332):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(12332):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(12332):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(12332):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(12332):        at android.app.ActivityThread.main(ActivityThread.java:5294)`

**Comment by itchix** [comment]
Do you have any barcode that make you crash? I want to test on my phone =)

**Comment by herau** [comment]
@itchix i fixed the NPE but i guess there is still an issue because the IngredientProductFragment is initialized but maybe without any Product in the State object ?

**Comment by aeris** [comment]
@itchix Any barcode or manual EAN leads to the crash.
