### ISSUE TITLE
The bottom bar is hiding the Wikidata info

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1517]
![image](https://user-images.githubusercontent.com/1689815/39353171-36ee2b60-4a07-11e8-808d-4d5a0fcda6de.png)

**Comment by ripetrescu** [comment]
I think this is not happening anymore after we changed the modal to use BottomSheetDialogFragment.

**Comment by teolemon** [comment]
indeed. closing thanks @ripetrescu :)
