### ISSUE TITLE
"Share to Open Food Facts" fails silently

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1518]
- Share a photo with barcode to Open Food Facts
- The app probably doesn't recognize any barcode
- It stays on the homepage without any message to type manually the barcode (already exists within the code)
- The app was in Italian

**Comment by teolemon** [comment]
Switching to English seems to solve the issue.

**Comment by jaindiv26** [comment]
@teolemon I'm using an image in the below screenshot and when I shared it in the app, it is able to recognize the barcode in the shared image. FYI I've set the language to Italino, Espaniol, and English and still app were able to recognize the image.

![screenshot_1525985486](https://user-images.githubusercontent.com/32436867/39893735-5863e080-54c2-11e8-9f4d-f4a4ecd52bb4.png)
![screenshot_1525985494](https://user-images.githubusercontent.com/32436867/39893736-58a1bd4c-54c2-11e8-87b5-1153de9ae92e.png)

**Comment by jaindiv26** [comment]
@teolemon Well, I'm working on this issue also, I've detected the root of the problem and if all goes well I'll be able to eliminate this issue. So please assign me this issue.

**Comment by teolemon** [comment]
Assigned. You can also see the nice to have improvements at
https://github.com/openfoodfacts/openfoodfacts-androidapp/labels/Share%20to%20Open%20Food%20Facts
