### ISSUE TITLE
"Share to Open Food Facts" always says it will upload the picture when the network is available

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1519]
Always says it will upload the picture when the network is available (doesn't create any offline product, and the network is actually available in those cases)

![image](https://user-images.githubusercontent.com/1689815/39353989-8c91eb36-4a09-11e8-9937-8da96423f2d5.png)

![image](https://user-images.githubusercontent.com/1689815/39353999-90b933d6-4a09-11e8-9c70-bb6cbd6851ab.png)

**Comment by jaindiv26** [comment]
How to reproduce the error?
