### ISSUE TITLE
Check if cacao is properly implemented in the nutrition table

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1521]
![image](https://user-images.githubusercontent.com/1689815/39354241-5831ef52-4a0a-11e8-9fc7-e486f17c4011.png)
Weird duplicate value: ```11 g```

**Comment by jaindiv26** [comment]
@teolemonIts cacao value is not properly implemented in nutrition table, it shows duplicated value in Per 100g serving and in Per serving. Check out the screenshots.

![screenshot_1525974819](https://user-images.githubusercontent.com/32436867/39885086-5f2b69f6-54a9-11e8-8840-2932cd5102c8.png)
![screenshot_1525974860](https://user-images.githubusercontent.com/32436867/39885088-615f9968-54a9-11e8-8e6a-3c55b2ed836c.png)
![screenshot_1525974895](https://user-images.githubusercontent.com/32436867/39885090-627dfc22-54a9-11e8-9eec-3910f6976818.png)

**Comment by teolemon** [comment]
Duplicate of #2178
