### ISSUE TITLE
Create a specific string for the icon name

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1533]
Renaming the string in flavors for better launcher icon legibility also renamed the name in the product detail view.
The official branding is "Open Food Facts", except on the launcher icon where we remove the spaces.

![image](https://user-images.githubusercontent.com/1689815/39408513-c3bc4104-4bd7-11e8-95be-d437d304e9a3.png)
![image](https://user-images.githubusercontent.com/1689815/39408515-cafb5be4-4bd7-11e8-8a4d-d2de70a9be6b.png)

**Comment by huzaifaiftikhar** [comment]
Working on this.

**Comment by huzaifaiftikhar** [comment]
Fixed in #1537
