### ISSUE TITLE
Add thorough product addition

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#1553]
**Summary:** 

Adding more detailed product addition including its nutritional information, ingredients, EMB codes etc.

The designs which I plan to implement are : 

<kbd>![addition screen1 1](https://user-images.githubusercontent.com/10832531/39649247-d2318dc8-5002-11e8-92d0-95721c172ed6.png)</kbd>

<kbd>![addition screen2 2](https://user-images.githubusercontent.com/10832531/39649252-d4639e60-5002-11e8-8a35-f9a33f3d05af.png)</kbd>

<kbd>![addition screen3 1](https://user-images.githubusercontent.com/10832531/39649254-d7ed6e3a-5002-11e8-8c6b-4ec23dc5ef0e.png)</kbd>

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/41159607-5d98d444-6b2d-11e8-8b06-19a43d2bf90b.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/41159796-f9cce35a-6b2d-11e8-9020-0d210f6483a6.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/41159829-1617db0a-6b2e-11e8-9bd9-eba629a8be5f.png)
