### ISSUE TITLE
Open the edition page in a Chrome Custom Tab within the app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#156]
Open the edition page in a Chrome Custom Tab within the app on devices where it is possible.

https://developer.chrome.com/multidevice/android/customtabs

This enables to avoid leaving the app and we get automatic login if the user has already used Open Food Facts on the web.

**Comment by teolemon** [comment]
@herau this is the stuff I was talking about in the other bug.

**Comment by herau** [comment]
Not sure that the web site is fully responsive :-( and cloud be readable and useable in a mobile device. But it's a simple and faster way to handle the issue 👍

**Comment by teolemon** [comment]
This is to be binded to the ✎ in the product page.

**Comment by herau** [comment]
@teolemon Do you know how the website handle the user session ?
I want to push the authenticated user (on the app) onto the chrome custom tabs to avoid the user to re-authenticate before editing the product.

**Comment by teolemon** [comment]
I think you have to log in once on Chrome (either on the web or mobile).
`<form method="post" action="/cgi/session.pl">

		<input type="text" name="user_id">
	
		<input type="password" name="password">

		<input type="checkbox" name="remember_me" value="on">
		
<input type="submit" name=".submit" value="Sign-in" class="button small">
</form>`

**Comment by herau** [comment]
@teolemon currently not found the way to log in on the chrome with custom tabs

**Comment by teolemon** [comment]
Logging once shouldn't be too much hassle.

**Comment by herau** [comment]
ok so i will let @itchix merge the PR
