### ISSUE TITLE
Amazon Fire Phone (reversed AF)

### ISSUE THREAD

**Issue by hackerb9** [openfoodfacts/openfoodfacts-androidapp#1567]
### Summary

When I use the app to scan, I expect it to autofocus. It does not. In the three-dots menu, I can see that it says, **Auto Focus [ON]**.  If I click on it so it switches to **Auto Focus [OFF]**, then my camera does autofocus correctly.

### Device and Android version:

Amazon Fire Phone (model number SD4930UR)
Fire OS 4.6.6.1 (Amazon's fork of Android 4.4, KitKat)

The version of OpenFood I'm running is 0.8.9 (installed using [F-droid](https://f-droid.org)).

By the way, I do not think Issue #534 is related as that only changed the APK manifest, if I'm reading it right.

**Comment by teolemon** [comment]
Do you still have your phone. Is on issue fixed on the latest version ?

**Comment by teolemon** [comment]
@hackerb9

**Comment by hackerb9** [comment]
Yes, still have Amazon phone. The bug has been squashed. Thanks!
