### ISSUE TITLE
An "About" screen to make reporting bugs easier

### ISSUE THREAD

**Issue by hackerb9** [openfoodfacts/openfoodfacts-androidapp#1568]
Most apps have an "About" screen that shows information about the app. This app does not. It'd be nice if had one that included at least the following information: name, version, description, copyright, link to homepage, link to report a bug. For example,

> OpenFoodFacts Android App,  version 0.999,  December 2018
> Scan, search and contribute to the [OpenFoodFacts](http://openfoodfacts.org) collaborative database of food facts.
> Copyright 2018, for your rights, please read the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0.html)
> [Read more at OpenFoodFacts.org](http://openfoodfacts.org)
> [Report a bug in this app](http//github.com/openfoodfacts/openfoodfacts-androidapp/issues)

This will take the guesswork out of what version is being run and will make it easier to report bugs.

**Comment by balaji-ramavathu** [comment]
@teolemon @hackerb9 Hello!
Can I work on this issue?

**Comment by teolemon** [comment]
We've just fixed it. @balaji-ramavathu

**Comment by balaji-ramavathu** [comment]
Okay!

**Comment by teolemon** [comment]
closing, since fixed
