### ISSUE TITLE
The app goes back to home when trying to add a new product.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1579]
The app goes back to home when trying to add a new product.

**Comment by jaindiv26** [comment]
@teolemon Can you tell me on which build version this event occurs?

**Comment by teolemon** [comment]
Latest release 0.9.0, that has been deployed.

**Comment by teolemon** [comment]
New product addition. You can try with a book or something not in the db
for instance

**Comment by huzaifaiftikhar** [comment]
I am not able to reproduce the issue. I added a [product](https://world.openfoodfacts.org/product/8901491990028) and it was successfully added using the app.  However just a suggestion that there is no "Save" button and the product gets uploaded when we press the back button on the toolbar at the top. This is not user friendly and we should add a "Save/Upload product" button in the UI.

**Comment by teolemon** [comment]
Do you have any options like Quick Scan or Scan on Startup enabled ?

**Comment by huzaifaiftikhar** [comment]
No both these options were disabled during the time of product addition

**Comment by teolemon** [comment]
Are you using a build from source ? The play store build ?

**Comment by huzaifaiftikhar** [comment]
I am not using the playstore version. I'm building the app from latest version of master branch

**Comment by jaindiv26** [comment]
@teolemon Hey man, I've thoroughly checked both the source build and the play store build, but this issue can't seem to occur, maybe it happened to you because of the application cache. Otherwise, everything seems to work perfectly

**Comment by teolemon** [comment]
It has been fixed in 0.9.0.1
