### ISSUE TITLE
Rank allergens by alphabetical order in lists

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#158]
Rank allergens by alphabetical order in lists (the list to choose one, and the list of alerts)

**Comment by teolemon** [comment]
![screenshot_20161104-173508](https://cloud.githubusercontent.com/assets/1689815/20014198/4b14a686-a2b6-11e6-9312-56bfe2e0ca20.png)

**Comment by teolemon** [comment]
Actually we should have :

- a search box on top.
- very common allergies, in alphabetical order
- a line
- other allergen, also in alphabetical order

**Comment by ross-holloway94** [comment]
Alternatively you could use drill-down menus. i.e.
Nuts -> Peanuts, hazelnuts, cashews, pine etc (and select all option)
Dairy -> Milk, Egg

**Comment by teolemon** [comment]
Totally agree. I have no preconceived idea on what we should do. Itchix has tried a toggle based approach in the V2

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/31353802-3074e2a8-ad34-11e7-92a3-fd20749f1feb.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/31353835-523aa436-ad34-11e7-8047-aa3d6d35ec01.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/31353859-7212bc44-ad34-11e7-9721-8244d1293321.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/31353867-7e04cea2-ad34-11e7-8d74-42e0146cce77.png)

**Comment by ross-holloway94** [comment]
Appears to be fixed in release 0.8.9
