### ISSUE TITLE
Use the accentuated and non slugified version of allergens

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#159]
http://world.openfoodfacts.org/allergens.json
```
{"url":"http://world.openfoodfacts.org/allergen/fr:petit-epeautre","name":"fr:Petit-epeautre","id":"fr:petit-epeautre","products":5}
```
https://world.openfoodfacts.org/allergen/fr:petit-epeautre.json
Translations:
http://en.wiki.openfoodfacts.org/Global_allergens_taxonomy

**Comment by herau** [comment]
please add more details to know where you want to use the allergens names (maybe with a example of `before/after`)

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/issues/270
