### ISSUE TITLE
Contributor results load in and then disappear

### ISSUE THREAD

**Issue by Karljoones** [openfoodfacts/openfoodfacts-androidapp#1597]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

When going into Your Contributions, the results load and then are covered by the view that states that there are no results.

**Steps to reproduce:** 

- Open navigation drawer
- Your Contributions

**Expected behavior:** 

Results should be shown.

**Observed behavior:** 

Network error displayed.

**Device and Android version:** 

- OnePlus 5T (A5010)
- Android 8.1
- Oxygen OS 5.1.1
- OFF version: 0.9.0.1 (latest as of 20th May)

**Screenshots:** 

https://gfycat.com/WastefulTinyCuttlefish

**Comment by jaindiv26** [comment]
@Karljoones Can you give me your OFF user credentials, as that will help me a lot tracing the issue?
