### ISSUE TITLE
Share to Open Food Facts fails when the language is not English

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1599]
Share to Open Food Facts fails when the language is not English

**Comment by jaindiv26** [comment]
@teolemon In which language app fails and what build variant are you using obf, off, opf, opff ?

**Comment by teolemon** [comment]
OFF, French fails for instance.

**Comment by jaindiv26** [comment]
I've tried changing many many languages and share the OFF content to many platforms (Whatsapp, Facebook, SMS, copy to clipboard) but never faced this issue! Well, at this point I can't seem to reproduce this issue if I'm missing something so as to reproduce this issue do let me know.

**Comment by teolemon** [comment]
It's inbound sharing (Share to, and not from). You can share photos from
your photo roll to Open Food Facts, and if they have a barcode, Open Food
Facts will try to add them to the right product.
----------------------------------------
Pierre Slamich - pierre@slamich.net - (+33) 6 02 13 14 57

**Comment by jaindiv26** [comment]
@teolemon Do you also get the same result when the barcode is detected and when you click on the yes button, a toast pops up stating "Image will be uploaded when the network is available." but you are already connected to the network?

**Comment by teolemon** [comment]
Yes. That's another bug, even in English.

**Comment by jaindiv26** [comment]
@teolemon I'll try to solve this issue asap.

**Comment by brandenfung** [comment]
@teolemon Can you describe how Share to Open Food Facts fails? Does the app crash?

**Comment by teolemon** [comment]
So you need (phone/off ?) to be in German, French, (eg not English) and share one or several images, including one with a barcode and select "Share to Open Food Facts".
The expected result is that it will either 
- ask you to type manually the barcode (if no barcode was detected) (and the proceed to next steps)
- add the pictures to an existing product (if a barcode is detected and the product exists)
- add the pictures to a new product (if a barcode is detected and the product does not exists)

**Comment by teolemon** [comment]
In languages other than english; it will fail silently.
this feature is very useful for Scan parties, when users take many pictures using their camera

**Comment by brandenfung** [comment]
Does this #1873 fix this issue?

**Comment by teolemon** [comment]
I'm still not able to upload products (will be uploaded when you get network), but at least the modal now appears everytime.
