### ISSUE TITLE
Move ingredient picture to ingredient tab, nutrition picture to nutrition tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#161]
Move ingredient picture to ingredient tab, nutrition picture to nutrition tab
Add a button to add more photos on each tab

**Comment by teolemon** [comment]
https://files.slack.com/files-tmb/T02KVRT1Q-F2LQCT89H-efcaabba63/dsc_2251-01_720.jpg

**Comment by teolemon** [comment]
@herau @itchix proposal for product view:
remove the carousel, and put each picture in the matching tab, with a button in each tab to add a photo if no picture is available (one button for the ingredient photo, one for the nutrition photo, one in the main tab)

**Comment by herau** [comment]
I'm ok with that; the 5C indicator should be also displayed in the first tab (summary)
In the official app, this indicator is in the first place in the display.

**Comment by teolemon** [comment]
Also, what we currently have is a button to add photos not assigned to a field. That avoids brutally overwriting a product which is complete, while still gathering fresh information

![screenshot_20161115-145239](https://cloud.githubusercontent.com/assets/1689815/20308411/13be1a50-ab44-11e6-8ca1-70b56a0aef6b.png)

**Comment by teolemon** [comment]
Solved. The add photos thing has been moved to another bug.
