### ISSUE TITLE
Crash after entering the barcode, manually or by scan

### ISSUE THREAD

**Issue by stemy2** [openfoodfacts/openfoodfacts-androidapp#1610]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 
When i scan or enter manually the barcode, the app crash.

**Steps to reproduce:** 

Scanning or entering manually a barcode.

**Expected behavior:** 

Showing me the scan results

**Observed behavior:** 
The app crashes.

**Device and Android version:** 

Fairphone open on Fairphone 2.

**Screenshots:** 

Doesn't work for me.

**Comment by teolemon** [comment]
If it's version 0.9.0 from F-Droid, and that you're in French (or some language other than English), and that the app goes back to the main screen for new products, then a fix has been sent to F-Droid (and is live on the Play Store)
