### ISSUE TITLE
Sign up button not working

### ISSUE THREAD

**Issue by jubreal** [openfoodfacts/openfoodfacts-androidapp#1612]
#### How to reproduce
1.     Install, Launch and grant all necessary permissions   2.     Click on the menu slider icon (located in the top   left corner of the app)   3.     Click on “sign in” option   4.     Click on the “sign up”       It will be observed   that there is no response from the app, while the other buttons such as “sign   in” and “forgot password” worked perfectly.
 
* Browser/App version: app   version 0.9.0.1
*Operating system: Android 6.0
* Device: Infinix Note 3
#### GitHub Account
https://github.com/jubreal

**Comment by teolemon** [comment]
See: https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/1361
We need it fixed and merged

**Comment by teolemon** [comment]
@jubreal is your system language English ?

**Comment by jubreal** [comment]
Yes, it is English language.

**Comment by jubreal** [comment]
@jaindiv26 I've uninstalled and re-installed, but the issue still persist

**Comment by jaindiv26** [comment]
@jubreal is there any other bugs in the app..?

**Comment by jubreal** [comment]
I don't know yet. Because I'm yet to encounter any other bugs, but I'll
report it once I encounter another one.

**Comment by teolemon** [comment]
We are using Chrome custom tabs. There should be a fall back when chrome is not installed. 
So digging this way is perhaps the solution.

**Comment by jubreal** [comment]
I am using chrome browser

**Comment by teolemon** [comment]
going to close this one. @jubreal feel free to reopen if it's still happening for you.
