### ISSUE TITLE
The first image is not displayed in the "Share to Open Food Facts" modal 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1625]
![image](https://user-images.githubusercontent.com/1689815/40485330-86be7dfe-5f5e-11e8-994a-979a7389a857.png)
The first image is not displayed in the "Share to Open Food Facts" modal. It didn't have a barcode.

**Comment by teolemon** [comment]
Maybe if no barcode is detected within it.

**Comment by brandenfung** [comment]
Added in #1873
