### ISSUE TITLE
Ability to create list of products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#163]
- Ability to create lists of products from the product page or from the history
- Ability to give them a name
- Ability to export them

**Comment by KarthikRIyer** [comment]
@teolemon what does exporting mean here?

**Comment by KarthikRIyer** [comment]
@teolemon could you please clarify this issue? I'd like to work on it.

**Comment by serpico** [comment]
Duplicate of #2158
