### ISSUE TITLE
The additives warning modal is always in French.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#165]
It says modérément toxique in the German version.

**Comment by Ekt0s** [comment]
Im on it, I'll push something at lunch

**Comment by Ekt0s** [comment]
@teolemon After looking the code, I didnt see how you got french :/ 
You should have the english version

**Comment by teolemon** [comment]
I was switching languages, so perhaps the JSON didn't get reloaded or something.

**Comment by teolemon** [comment]
We disabled it. Closing since we'll replace it with something more scalable
