### ISSUE TITLE
Reenable additives detection for Open Beauty Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1659]
Reenable additives detection for Open Beauty Facts.

**Comment by teolemon** [comment]
The code should already be there, so it should be an easy fix.

**Comment by vanshikaarora** [comment]
Hey @teolemon @deniger I have resolved this Issue here #2644 Can you please review the PR:)

**Comment by teolemon** [comment]
@vanshikaarora I was actually thinking about additives in the product view. That will teach me to do more explicit bugs :-)
