### ISSUE TITLE
Make vitamins, minerals and other substances clickable

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1663]
Make vitamins, minerals and other substances clickable 
https://static.openfoodfacts.org/data/taxonomies/minerals.json
https://static.openfoodfacts.org/data/taxonomies/vitamins.json

**Comment by SaumiaSinghal** [comment]
Hie @teolemon, I would like to work on this issue..

**Comment by teolemon** [comment]
You can go ahead. The behaviour is very much the same as additives, and you can reuse code from there, but the taxonomies used are the ones above.

**Comment by SaumiaSinghal** [comment]
Hie @toelman, i was wondering, should I create a separate database for Minerals and Vitamins, just like the one for additives..?

**Comment by teolemon** [comment]
I guess so (like Categories, Labels, Additives, if I'm right).

**Comment by KarthikRIyer** [comment]
@teolemon is this done? If not, I'll work on this.

**Comment by teolemon** [comment]
It's up for grabs.
