### ISSUE TITLE
On a LineageOS 14.1 scanning a barcode shows no camera image.

### ISSUE THREAD

**Issue by SantosSi** [openfoodfacts/openfoodfacts-androidapp#1664]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 
On a LineageOS 14.1 (= Android 7.1.2) scanning a barcode shows no camera image.

**Steps to reproduce:** 
Open the app and tap the red barcode scanner icon in lower right corner.

**Expected behavior:** 
A camera image is displayed and the barcode is then recognized.

**Observed behavior:** 
No image with the red barscanner line in the middle.

**Device and Android version:** 
This works fine on the same model (Samsung Galaxy S6) with stock Android 7.0, both run the app in version 0.9.0.2 from the F-Droid store.
On the LineageOS smartphone the app does not crash, it simply does not show both the front and rear camera's image. The difference might be the camera app that is org.cyanogenmod.snap (2.0.002)

**Comment by teolemon** [comment]
- Was 0.9.0.1 working ?
- We're about to change the scanning library. Willing to test the experimental version ?

**Comment by SantosSi** [comment]
No. Not sure since when I tested, but it never worked on LineageOS on that smartphone model.
Sure, if I can download the compiled apk.

**Comment by teolemon** [comment]
@SantosSi Does 0.9.0.3 work better ?

**Comment by SantosSi** [comment]
Dear Pierre,
Yes, it is working now: it shows the 
camera image and also successfully 
scans barcodes.
