### ISSUE TITLE
Scanned products that do not exist in Open Food Facts do not appear in history

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#168]
Scanned products that do not exist in Open Food Facts do not appear in history.
Perhaps keep them, but with a "Product Unknown" placeholder.

**Comment by Karljoones** [comment]
We could work this so when the user tries to open an "unknown" product that it brings them to the activity that they would see should they decide to add it at the time of scan

**Comment by N00845855** [comment]
can I work on this issue?

**Comment by teolemon** [comment]
@N00845855 if you're still up for it, please do 🙂

**Comment by rsi2m** [comment]
@teolemon @Karljoones Is this problem still relevant? If yes, then I could fix it as part of #hacktoberfest

**Comment by teolemon** [comment]
It seems fixed if you decide to add a product. 
You can pick some other issue
