### ISSUE TITLE
Travis-Ci Build error

### ISSUE THREAD

**Issue by SaumiaSinghal** [openfoodfacts/openfoodfacts-androidapp#1683]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 

Travis-ci is giving a build error while it is working fine on the local machine. Maybe, something is wrong with the build configuration.

**Expected behavior:** 

The app should pass the travis-ci tests successfully.

**Observed behavior:** 

Travis-ci is, instead, giving a build error.

**Device and Android version:** 

It works fine on the local machine.

**Comment by huzaifaiftikhar** [comment]
Already fixed in #1681
