### ISSUE TITLE
Error when uploading additional photos with mobile Firefox on Android/LineageOS

### ISSUE THREAD

**Issue by SantosSi** [openfoodfacts/openfoodfacts-androidapp#1686]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
Error when uploading additional photos with mobile Firefox on Android/LineageOS

**Steps to reproduce:** 
In the Andriod app scan existing product's barcode. Tap edit. Tap Add image. Take a picture and confirm it.

**Expected behavior:** 
The taken picture should appear in the pictures list. 

**Observed behavior:** 
The message appears: "error - missing product code"

**Device and Android version:** 
2 x Galaxy S6: stock Android 7.0 and LineageOS 14.1 (= Android 7.1.2), Firefox 60.0.1 and 60.0.2

**Comment by teolemon** [comment]
This is a server-side bug, but leaving it open until we fix it. Can you tell me: any reason you didn't use the "Add more photos" button ?

**Comment by SantosSi** [comment]
Now this works directly in the new version of the app. Before the app redirected to mobile Firefox where this problem appeared.
