### ISSUE TITLE
Words cropping in the tagline 'the free food products database'

### ISSUE THREAD

**Issue by rudrankriyam** [openfoodfacts/openfoodfacts-androidapp#1695]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
Cropped Title in launch screen and main page 

**Expected behavior :** 
The height should be increased a little in the tagline 'the free food products database'

**Observed behavior :** 
The words are cropping a little in the tagline 'the free food products database'

**Device and Android version:** 
OnePlus 5 running 8.1.0

**Screenshots:** 

![whatsapp image 2018-06-11 at 03 03 15 2](https://user-images.githubusercontent.com/30552772/41206602-1ca992ea-6d24-11e8-9bd0-a86bfe42347a.jpeg)
![whatsapp image 2018-06-11 at 03 03 15 1](https://user-images.githubusercontent.com/30552772/41206603-1e372320-6d24-11e8-83e2-0bcc01923c12.jpeg)
![whatsapp image 2018-06-11 at 03 03 15](https://user-images.githubusercontent.com/30552772/41206604-1f7f33e4-6d24-11e8-8b08-9ade24ad9d03.jpeg)

**Comment by SaumiaSinghal** [comment]
Hie @snuff4, I tried to regenerate this issue on Google Pixel XL , running 8.1, but couldn't find any such problem. However, if we simply set the height of textview as wrap content and define a textsize then, i don't think that we'll face such kind of issue in future.

**Comment by snuff4** [comment]
Hello @SaumiaSinghal I used the beta version available on the Play Store. Let me build it on my phone on the latest master. 
And in the screenshot in #1696, I think the tagline of the logo should be in a single line, like this -
![screen shot 2018-06-13 at 6 58 24 am](https://user-images.githubusercontent.com/30552772/41325378-8af5dd4e-6ed7-11e8-8fb4-2d13edb63155.png)

**Comment by SaumiaSinghal** [comment]
Hie @snuff4, sorry for those unnecessary commits, but actually i was trying to fix the travis build error. But, as that is solved now, please test it with my latest commit. Thanks..:)

**Comment by snuff4** [comment]
@teolemon @huzaifaiftikhar isn't it in a single line?

**Comment by teolemon** [comment]
Yup. Justified with the edges of the barcode

**Comment by Karljoones** [comment]
Closed due to issue being resolved.
