### ISSUE TITLE
Allow searching for uncategorized product if the category is empty

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1714]
Allow searching for uncategorized products with the name of the category if the category is empty. 
A nice plus would be to allow the logged-in user to add some of the results of that search to the category

**Comment by subhanjansaha** [comment]
@teolemon I would like to work on this

**Comment by subhanjansaha** [comment]
@teolemon Could you give an example of how the search could work?

**Comment by teolemon** [comment]
Superseded by #2967
