### ISSUE TITLE
(Draft) Create a section to download list of additives risks

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1717]
(Draft) Create a section to download list of additives risks

This needs to : 
- propose available additives risks lists
- the available lists should be refreshable from the Open Food Facts server
- let the user delete downloaded lists
- let the user enable or disable display of downloaded lists on the product page

**Comment by VaiTon** [comment]
@teolemon any news on this?

**Comment by teolemon** [comment]
I'm moving this to a design document, it's not mature yet: https://docs.google.com/document/d/12z2OepuJID1HhrcrwOw6_5UT9s9EsapH5cumpB9mcpg/edit
