### ISSUE TITLE
Send text info to shopping list apps

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-androidapp#172]
Apparently the link button can send a link to OFF to any app that accepts images or text; even to the gallery, which receives a QR code image.  [OI Shopping List](https://f-droid.org/repository/browse/?fdfilter=shopping&fdid=org.openintents.shopping) also receives a link, which is not useful.  It would be useful to send to it something like the TITLE - BRAND - QTY you see in OFF's lists.

**Comment by teolemon** [comment]
Moved to : https://wiki.openfoodfacts.org/Mobile_App/Android/Ideas
