### ISSUE TITLE
Add ability to rotate and crop images (before sending)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#173]
![image](https://cloud.githubusercontent.com/assets/1689815/21975625/f955edea-dbcd-11e6-84c8-a0298e31d3ea.png)

Add ability to crop images
https://github.com/Yalantis/uCrop
https://github.com/jdamcd/android-crop
https://github.com/IsseiAoki/SimpleCropView

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21975625/f955edea-dbcd-11e6-84c8-a0298e31d3ea.png)

**Comment by Shubham2320** [comment]
I would like to work on it. Can I start?
