### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by Rutvikmodi** [openfoodfacts/openfoodfacts-androidapp#1757]
App shows logged in even if user enters wrong credentials.

Enter wrong credentials and then press Sign in button. As expected the the toast shows "Username or Password may be incorrect".
Then press back button from Toolbar and again press sign in option from side menu. The app produces alert message "Already logged in".

**Expected behavior:** 

Alert message should not occur.

**Device and Android version:** 

Xiaomi Redmi Note 4 , Android 7.0 , API 24.

![screenshot_2018-07-01-15-44-22-420_org openfoodfacts scanner](https://user-images.githubusercontent.com/34269503/42133428-9be4891a-7d47-11e8-9d70-233ded78e28c.png)
![screenshot_2018-07-01-15-44-31-344_org openfoodfacts scanner](https://user-images.githubusercontent.com/34269503/42133429-9c158876-7d47-11e8-943a-c04c50f94b13.png)
![screenshot_2018-07-01-15-44-38-160_org openfoodfacts scanner](https://user-images.githubusercontent.com/34269503/42133430-9c46d75a-7d47-11e8-82df-bee58326d736.png)

**Comment by resid9406** [comment]
With the latest version, I cannot replicate this problem for the application.
I guess this issue could be closed.

**Comment by ross-holloway94** [comment]
@Rutvikmodi would this have been fixed in #1762 ?

@resid9406 Latest release, or current build?

**Comment by ross-holloway94** [comment]
Fixed with #1762
