### ISSUE TITLE
Screenshots appear to be broken in readme.MD

### ISSUE THREAD

**Issue by ross-holloway94** [openfoodfacts/openfoodfacts-androidapp#1760]

**Comment by teolemon** [comment]
Weird:
![image](https://user-images.githubusercontent.com/1689815/42154673-abb5db60-7de6-11e8-8b6a-18b845d6b411.png)

**Comment by ross-holloway94** [comment]
![2018-07-02 09_57_48-greenshot](https://user-images.githubusercontent.com/20950727/42154735-730d4292-7dde-11e8-87ec-3390d560f4d0.png)
Firefox 61.0

**Comment by huzaifaiftikhar** [comment]
Reproducible on Firefox Web Browser 59.0.2 (64-bit)
Ubuntu 18.04 LTS
