### ISSUE TITLE
Unexpected Login of user 

### ISSUE THREAD

**Issue by Rutvikmodi** [openfoodfacts/openfoodfacts-androidapp#1761]
User enters wrong credentials then also when again entering the app it shows "Logout.." instead of "Sign in" in side menu. 

How can we reproduce the issue?

First enter wrong credentials for eg: username = "abcdefgh" password = "abcdefgh".

![screenshot_2018-07-02-15-15-47-490_openfoodfacts github scrachx openbeauty](https://user-images.githubusercontent.com/34269503/42157742-35abc7c4-7e0c-11e8-8ada-ebf65a242f47.png)

Now press the sign in button and as expected it shows error of "username or password is incorrect".

![screenshot_2018-07-02-15-13-08-680_openfoodfacts github scrachx openbeauty](https://user-images.githubusercontent.com/34269503/42158002-d8641958-7e0c-11e8-9ba5-44b86aaa7886.png)

Now close the app and again open it and press the navigation button from the homepage and it can be noticed that there is "Logout" written instead of "Sign in".There should be sign in as the credentials were wrong.

![screenshot_2018-07-02-15-14-21-397_org openfoodfacts scanner](https://user-images.githubusercontent.com/34269503/42158161-528a8190-7e0d-11e8-8222-e80a550593cd.png)

Now press that "Logout" choice and it can be noticed that dialog box appears "Are you sure you want to logout ?"

![screenshot_2018-07-02-15-14-28-595_org openfoodfacts scanner](https://user-images.githubusercontent.com/34269503/42158255-927ee17e-7e0d-11e8-83fc-168773d50c97.png)

What did you expect the app to do?

According to me this there should not be "Logout" as user have not registered yet. 

Xiaomi Redmi Note 4 , Android version 7.0 , API 24

**Comment by ross-holloway94** [comment]
assigned to @Rutvikmodi
