### ISSUE TITLE
Suggestion: Implement Google smart lock for login

### ISSUE THREAD

**Issue by ross-holloway94** [openfoodfacts/openfoodfacts-androidapp#1778]
> If you've never installed an app that supports Smart Lock, you may not realize how seamless it is, even moreso than relying on Autofill. You open the app the first time and if you've ever logged into that service from Chrome or another Android phone with Smart Lock enabled, you get a little pop-up asking you if you'd like to login using those saved credentials. No tapping on the user/email field to fill them up, no waiting and unlocking whichever Autofill app you use. It's a simple tap and you're logged in.

As suggested [here](https://www.androidpolice.com/2018/03/05/google-smart-lock-passwords-underused-underrated-wish-android-developers-implemented/)

**Comment by teolemon** [comment]
Does it require Google Play Services ? Is there a fallback ?

**Comment by ross-holloway94** [comment]
@teolemon I think I may have brought this up before somewhere actually. Not sure, I'd need to look into it more.

**Comment by jaindiv26** [comment]
@teolemon I've implemented the Google Smart Lock for Password. But should I trigger the credential dialogue box in onStart method or on email EditText click?

![screenshot_1533575260](https://user-images.githubusercontent.com/32436867/43730724-eb3db966-99c9-11e8-821f-4aec313d32db.png)

**Comment by ross-holloway94** [comment]
@jaindiv26 I would suggest onStart (or onCreate if it's called that) personally. Minimises user input that way. Thanks for working on it :)

**Comment by VaiTon** [comment]
I think this can be closed. @teolemon @deniger
