### ISSUE TITLE
Update the OpenFood app on Amazon App Store

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#178]
- It's several versions behind
- Rotate screenshots

**Comment by teolemon** [comment]
Poke @itchix

**Comment by hackerb9** [comment]
[Amazon Appstore](https://www.amazon.com/getappstore) version is still stuck at Open Food Facts from 2015. (I think it's version 0.2.1)

You can work around it by using fdroid.org to install the OpenFood app (version 0.8.9 at the moment), but most Amazon device users will not find that easy to do.

**Comment by teolemon** [comment]
updated. closing
