### ISSUE TITLE
Short term memory and comparison of products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1780]
Feature idea for Android app : a way for the app to remember what I scanned earlier and compare it with what I scan now.
For example, if I scan a bottle of Pepsi, then  a bottle of Lemonade 10 minutes after, it would be nice if the app tells me "It's 10% less sweet than the bottle of Pepsi"
Particularly useful at the supermarket when I can't choose between two products

**Comment by teolemon** [comment]
@tacitefood for the idea

**Comment by guyou** [comment]
Is there any comparison feature already?

I looked in the history tab and expected to be able to select two product and clic a *compare* button to have, at least, a side by side comparison.

**Comment by teolemon** [comment]
nope. this is something that would be really nice to have.

**Comment by subhanjansaha** [comment]
@teolemon This sounds like an interesting feature. Can I work on this?

**Comment by teolemon** [comment]
@subhanjansaha I would add a comparison menu in the sidebar, and allow to scan several products, and display the main facts in a new view side by side, as columns. It could work for 2 products, but potentially more, with horizontal scrolling. We could imagine allowing to browse other products from the same category

**Comment by subhanjansaha** [comment]
@teolemon Thank you so much for the idea. I would love to work on this feature.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/51252208-86944500-199b-11e9-9426-d8653650aef4.png)
I was thinking of something a bit like that

**Comment by teolemon** [comment]
with all the fields side by side.

**Comment by subhanjansaha** [comment]
Ok I am working on this, I will start a pull request once done

**Comment by teolemon** [comment]
Are you still on this feature ? @subhanjansaha

**Comment by subhanjansaha** [comment]
Yes I am developing this feature. Coherent UI is taking a little time to develop, but I am working on it and I'll open a PR very soon
