### ISSUE TITLE
Being able to send multiple pictures of a product in Offline mode / Initial product upload

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#18]
Currently, the offline mode in the app doesn't let the user send multiple pictures of a product. 
To achieve parity with the current app, it should let the user upload as many images as he wishes.
Bonus points if he can define which one it is :-)

**Comment by friedger** [comment]
Does it mean that the user adds images to an existing product? Or does it mean that he adds more images in the offline edit activity?

**Comment by teolemon** [comment]
Both use cases make sense I guess.

**Comment by itchix** [comment]
44b5f2f160657cebedd9f471fa8df16812b021d2
