### ISSUE TITLE
use a Search view for search product by name or by barcode

### ISSUE THREAD

**Issue by herau** [openfoodfacts/openfoodfacts-androidapp#180]
Currently the user has to open the drawer, then click on `search by name` or `search by barcode`.
Then in the new fragment the user fill the input and click on the validate button.

Why not insert a menu item on the home screen and attach on it a [search view](https://developer.android.com/training/search/setup.html) ?

we could search a product but also any kind of content like ingredients, allergens etc
We could also show during the search the history of the user.

I took an example with the `Inbox` app which as a great search behavior:

![](http://img.talkandroid.com/uploads/2014/10/Google_Inbox_App_Screenshot_02.png)
![](http://www.androidpolice.com/wp-content/uploads/2016/08/nexus2cee_InboxSearchUI.png)

**Comment by teolemon** [comment]
- Looks like a really great idea. 
- I love universal search, but not sure how hard it is to implement. (is there a FOSS implementation somewhere)
- For photos, in many cases we have them (for products), and for categories, we are linked to Wikidata, which has them.

**Comment by teolemon** [comment]
it's been fixed for a while. 
Closing
