### ISSUE TITLE
Make the quickview displayed in the scanner slide up to display the complete product details

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#1813]
**Summary:** 
When scanning a product the key information is displayed on the bottom sheet (quick view). Clicking this opens the complete details about that product. Instead of this behaviour make the bottom sheet swipe up (similar to Google Maps and Play Music) to display the complete details about the instead of clicking it.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/45918440-47d7fd80-be87-11e8-8ea5-855f046f7cc7.png)

**Comment by prashantkh19** [comment]
Is this still open? I would like to work on it.

**Comment by huzaifaiftikhar** [comment]
Yes, you can go ahead.

**Comment by prashantkh19** [comment]
I have made a pull request. Kindly review.
