### ISSUE TITLE
Show the barcode when saying the product is not in the db and asking if you want to add it

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-androidapp#183]
Maybe the code was recognized incorrectly.

**Comment by teolemon** [comment]
This one is rather important actually, and easy to fix.

**Comment by teolemon** [comment]
We could show it just above the image addition form, with a button to go back to scanning "Scan again"

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/25136935/9e58fcda-2456-11e7-921b-1fe299562431.png)
Being implemented by @ChasakisD

**Comment by policorn** [comment]
Hi @teolemon, as far as I can tel this was fixed by PR#577, can we close this as fixed?

**Comment by teolemon** [comment]
Yup :-)
