### ISSUE TITLE
Change the comment string according to Flavor

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1830]
Change the comment string according to Flavor

Official OFF Android app (for Open Food Facts)
Official OBF Android app (for Open Beauty Facts)
Official OPF Android app (for Open Products Facts)
Official OPFF Android app (for Open Pet Food Facts)

https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/39d33af3f3715c94508b8ee5329278f1a2e8418b/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/OpenFoodAPIService.java#L33

This needs to be customized based on the android flavour

…

**Comment by jaindiv26** [comment]
@teolemon I don't understand what this is. Can you elaborate which comment string you are referring to and what kind of changes has to be done?

**Comment by VaiTon** [comment]
Is this still an issue?

**Comment by teolemon** [comment]
@VaiTon yes it is: https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/OpenFoodAPIService.java#L34

I released refreshed versions of OPF and OPFF. I held back for OBF because of #2056
