### ISSUE TITLE
Investigate Google Glass support

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#184]
This is a long term bug :-)

https://github.com/karanbalkar/GlassCounter
http://en.wiki.openfoodfacts.org/Experiments/Google_Glass

**Comment by herau** [comment]
A scan with Google glass ? ;-) is the Google glass still available ^^ ? Don't see anyone with this kind of devices except in labs or conferences.

**Comment by teolemon** [comment]
It seems that a V2 is planned. Microsoft has something called the Hololens.
We'll get there at some point ;-)

**Comment by Karljoones** [comment]
I'm going to close this off because Google Glass is not a thing anymore :)
