### ISSUE TITLE
The allergen field behaves weirdly

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1846]
The allergen field behaves weirdly
![screenshot_20180816-231247](https://user-images.githubusercontent.com/1689815/44303209-f1811780-a33a-11e8-9218-c6aae6ade8b0.png)

**Comment by brandenfung** [comment]
Looks like a problem with the regex pattern:
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/b9d6142e435cacea2529fde6f632e8c1794234bf/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ingredients/IngredientsProductFragment.java#L82
This doesn't allow for allergen names that contain more than one word, e.g. lécithine de soja, bleu d'Auvergne.
