### ISSUE TITLE
Display a dismissable little message on the home screen if the translation is not complete

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1848]
Display a dismissable little message on the home screen if the translation is not complete

"Help make Open Food Facts better in your language by translating it"
"Help make Open Food Facts better in Hindi by translating it"

There would be a link to https://translate.openfoodfacts.org or better yet to https://crowdin.com/project/openfoodfacts/hi#

**Comment by subhanjansaha** [comment]
@teolemon I'll be working on this

**Comment by teolemon** [comment]
We have found a more generic way to do this, and there's a PR for this already @subhanjansaha 
I'm closing this bug.
