### ISSUE TITLE
Turn the summary tab into an actual summary

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1849]
![image](https://user-images.githubusercontent.com/1689815/44311279-b63b2300-a3e4-11e8-9d33-f2cb11898368.png)

**Comment by huzaifaiftikhar** [comment]
What about the information currently displayed in the summary tab? Should it be moved to a new tab under a separate heading?

**Comment by teolemon** [comment]
We have already many tabs, just pushing it below those three elements should do.
That way, 90% of users will only need 1st and 2nd tab.

**Comment by PrajwalM2212** [comment]
Can i get more information about this. What do you mean by turn summary tab to actual summary ?

**Comment by teolemon** [comment]
Basically, showing the most interesting parts in the first tab. 
- the scores
- the nutrition lights
- the additives

**Comment by balaji-ramavathu** [comment]
Can I work on this issue?

**Comment by teolemon** [comment]
Yes, you can go ahead :-)
