### ISSUE TITLE
Add Direct Share for Marshmallow+ devices

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#185]
https://github.com/googlesamples/android-DirectShare

**Comment by teolemon** [comment]
Actually, it seems to be retro-compatible. Here's a tutorial
https://www.bignerdranch.com/blog/implementing-android-marshmallow-direct-share/

**Comment by Ekt0s** [comment]
Yep It's already prepared I have to commit and do the pull request

**Comment by teolemon** [comment]
@Ekt0s any update on that one ?

**Comment by Karljoones** [comment]
Fixed #779
