### ISSUE TITLE
Add maximum to nutrition values

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1857]
Add maximum to nutrition values. Tacite reported values of 10000 kcal inputed by users.

**Comment by huzaifaiftikhar** [comment]
What should be the maximum permissible input value?

**Comment by teolemon** [comment]
Let's do simple: 
- if per 100g, every weight should be capped at 100g (or 1000mg, or 10000microgram).
- if per portion (and portion is filled), every weight should be capped at portion weight

**Comment by huzaifaiftikhar** [comment]
What about the maximum energy? That's what the issue description says.

**Comment by teolemon** [comment]
A max of 2000kcal/100g should be enough (it's actually closer to 900kcal per 100g)

**Comment by teolemon** [comment]
8300 kilojoules (3700) per 100g

**Comment by KarthikRIyer** [comment]
@teolemon Can I work on this?

**Comment by KarthikRIyer** [comment]
@teolemon is this still open?

**Comment by teolemon** [comment]
I'm not sure if it was implemented (my phone has no battery left at the moment) @huzaifaiftikhar ?

**Comment by KarthikRIyer** [comment]
With the current master branch this doesn't seem to be implemented.

**Comment by KarthikRIyer** [comment]
@teolemon is it necessary to show the feedback or can we just clamp the values as soon as the value in the editText goes out of bounds. Why I'm asking is that, if we do not clamp the values immediately, we'll have to disbale the save button until all values are within limit. This will be fine for the nutrients present initially, but I think this won't be as feasible when other nutrients are added manually.
