### ISSUE TITLE
Allow the user to rotate a picture from product edition

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1860]
Allow the user to rotate a picture from product edition

**Comment by teolemon** [comment]
This is for existing pictures, and it's a bit longer than what it looks like (it requires using the image read and write API to rotate existing images)

**Comment by teolemon** [comment]
https://en.wiki.openfoodfacts.org/API/Write#Manipulating_photos_for_a_product

**Comment by KarthikRIyer** [comment]
@teolemon I'll look into this.

**Comment by teolemon** [comment]
https://en.wiki.openfoodfacts.org/API/Write/Photos
