### ISSUE TITLE
Changing languages changes connexion status in side menu

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1869]
Changing languages changes connexion status in side menu
Switching from English to French will show different connexion status.

**Comment by jaindiv26** [comment]
@teolemon Can you upload a screenshot in reference to this issue?

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/50601842-b597ba80-0eb5-11e9-8e0f-302928b5bae5.png)
![image](https://user-images.githubusercontent.com/1689815/50601859-c34d4000-0eb5-11e9-9937-1c357448c501.png)

**Comment by jaindiv26** [comment]
@teolemon Understood the issue, I'll be working on this.
