### ISSUE TITLE
Pull to Refresh doesn't work after product edition

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1884]
Categories are not refreshed on successful edit.
I am adding categories and they don't appear on the product page when the product is saved, even after a pull to refresh

**Comment by subhanjansaha** [comment]
@teolemon Isn't this the same issue as #2156 ?

**Comment by brandenfung** [comment]
Yes, it's probably similar to #2156. In general, views containing product data should be updated on return from editing the product.

**Comment by deniger** [comment]
@teolemon  should be fixed with https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2494
