### ISSUE TITLE
Add the current product count on the home screen

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1895]
Add the current product count on the home screen

**Comment by PrajwalM2212** [comment]
current product count on the home screen. Total products in the entire database ?

**Comment by teolemon** [comment]
@stephanegigandet Do we have some kind of an API for that ?

**Comment by PrajwalM2212** [comment]
@jaindiv26 Do you want to solve this ?

**Comment by jaindiv26** [comment]
@PrajwalM2212 Yes, please.

**Comment by PrajwalM2212** [comment]
@teolemon @jaindiv26  You can use this api https://ssl-api.openfoodfacts.org/.json for getting total number of products.  
<img width="342" alt="screen shot 2018-09-18 at 10 24 04 am" src="https://user-images.githubusercontent.com/30733262/45665165-344a3100-bb2d-11e8-8d85-48197ee1d864.png">

**Comment by PrajwalM2212** [comment]
Hope that clarifies all doubts

**Comment by jaindiv26** [comment]
@PrajwalM2212 Thanks for the API.

**Comment by stephanegigandet** [comment]
I guess that works, but the /.json url is weird. It might be better to use https://world.openfoodfacts.org/1.json so that's it's more obvious that it's requesting the 1st page of results.
