### ISSUE TITLE
Selecting an empty category from the categories list displays network error

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#1907]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
Clicking a category from the categories list displays network error when the category you clicked is empty (no products in OFF falls under that category).
Example of an [empty category](https://ssl-api.openfoodfacts.org/category/en:acesulfame-potassium/1.json?fields=product_name,brands,quantity,image_small_url,nutrition_grade_fr,code).

**Steps to reproduce:** 
1) Change the app's language to French.
2) Try clicking **Acésulfame potassium** in the categories list.

**Expected behavior:** 
I would expect something like: “Oh no, we don’t have any product in this category, can you add one ?”

**Observed behavior:** 
No internet connection error is shown.

**Reported By:** 
@teolemon

**Comment by teolemon** [comment]
Looks good to me.
