### ISSUE TITLE
Add a user agent for Scan and requests made by the app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1921]
Add a user agent for Scan and requests made by the app
Something that tells it's the official client, and the version of the client. That enables us to differentiate actual scans from automated API calls, and is thus essential to rank products by scan.

**Comment by teolemon** [comment]
https://stackoverflow.com/questions/26509107/how-to-specify-a-default-user-agent-for-okhttp-2-x-requests/27840834#27840834

**Comment by subhanjansaha** [comment]
So, the Http request headers have to be modified so as to distinguish them, right? Could you please clarify?

**Comment by huzaifaiftikhar** [comment]
@subhanjansaha This is already a work in progress #2035
