### ISSUE TITLE
Create a list of products added by the user

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#194]
This allows the user to find products he has contributed to, and finish completing them.

**Comment by teolemon** [comment]
Products you added or edited
http://world.openfoodfacts.org/contributor/teolemon
http://world.openfoodfacts.org/contributor/teolemon.json

Products you added that need to be completed
http://world.openfoodfacts.org/contributor/teolemon/state/to-be-completed
http://world.openfoodfacts.org/contributor/teolemon/state/to-be-completed.json

Products you took pictures for
http://world.openfoodfacts.org/photographer/teolemon
http://world.openfoodfacts.org/photographer/teolemon.json

Products you took pictures for that need to be completed
http://world.openfoodfacts.org/photographer/teolemon/state/to-be-completed
http://world.openfoodfacts.org/photographer/teolemon/state/to-be-completed.json

Products you added information for
http://world.openfoodfacts.org/informer/teolemon
http://world.openfoodfacts.org/informer/teolemon.json

Products you added information for that need to be completed
http://world.openfoodfacts.org/informer/teolemon/state/to-be-completed
http://world.openfoodfacts.org/informer/teolemon/state/to-be-completed.json

**Comment by PrajwalM2212** [comment]
Looking into it .

**Comment by Karljoones** [comment]
@PrajwalM2212 How is this coming along?

**Comment by PrajwalM2212** [comment]
@Karljoones  I have not started working on it yet . I had other issues to solve as well .
I am busy writing my proposal and also have tests from 17th . So i can start working only after 22nd .

**Comment by PrajwalM2212** [comment]
@Karljoones  I will send this out as soon as i can

**Comment by PrajwalM2212** [comment]
@Karljoones Finished! Will send a PR soon .
