### ISSUE TITLE
Add advanced settings in a Chrome Custom Tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#195]
http://world.openfoodfacts.org/cgi/user.pl?userid=teolemon&type=edit

Include it in the settings view

**Comment by teolemon** [comment]
"Advanced Settings"
"Change your password, and more"

**Comment by herau** [comment]
@teolemon what is the settings view ? the left menu ?

**Comment by herau** [comment]
Ok and why the settings option is on the right whereas we have a left menu ?

**Comment by teolemon** [comment]
100$ question :-)

**Comment by herau** [comment]
@teolemon the url `http://world.openfoodfacts.org/cgi/user.pl?userid=teolemon&type=edit` doesn't works if the user is not authenticated. Do you know if it is possible to add the credentials in the url to authenticate the user and then redirect to edit page ?

**Comment by herau** [comment]
ideally if the user is connected on the android App, we could add the cookie in the Chrome custom tabs to allow the user to go to the user edit url 

https://bugs.chromium.org/p/chromium/issues/detail?id=539240&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

**Comment by teolemon** [comment]
removing the user id is a bad idea and a shown a bug in Product Opener.
Hide the link if the user is not logged in yet ?
Credentials in the url doesn't seem to work. Can you raise the issue to Stéphane ?

**Comment by herau** [comment]
@teolemon
I don't want to remove the user id.
The user, even if he is connected on the android app, is not authenticated on the openfood website; so he will get an "Permission denied". 

The only use cas when it will works will be if the user was previously signed-in on the website before to go to edit url from the android app.

@stephanegigandet what's do you think about this issue ?

**Comment by stephanegigandet** [comment]
I'm not sure that I understand everything, so what I'm going to suggest may not work.

The user is connected in the app, and the app has access to the "session" cookie set by openfoodfacts.org ?

But in the custom tab, you can't pass that session cookie?

If so, maybe I could allow to pass the content of the session cookie as urls parameters: user_id and user_session

Would that work for you?

**Comment by herau** [comment]
perfect ;-) 

indeed we can't currently set the cookie with the chrome custom tab component. 

if we can use query parameters for the user session value it will works with the CCT. 

I have to check if we can retrieve the cookie with the user session value after the login on the app but i guess it's ok

**Comment by herau** [comment]
@stephanegigandet the user id is already available through the `userid` query parameter.

i will put user_session value as query parameter.

**Comment by herau** [comment]
@teolemon what do you think about this screenshot (second panel from the left) for the link to the "manage account" on open food facts ?

![d](https://raw.githubusercontent.com/mikepenz/MaterialDrawer/develop/DEV/github/screenshots1.jpg)

**Comment by teolemon** [comment]
Yup, looks good.
Also: 
- In our current sidebar, part of the items are grey, other are black >> hamonization
- Reuse as many standard icons as possible. Looks like the wheel are different in your example and in my system
- Change the Anchor thing to the official offline icon (can be seen in Google Maps, otherwise airplane mode icon)

**Comment by herau** [comment]
@teolemon the PR is ready. 
Waiting the dev from @stephanegigandet to be merge.

sample of URI : `http://fr.openfoodfacts.org/cgi/user.pl?userid=herau&type=edit&user_session=1Od88[...]`

**Comment by stephanegigandet** [comment]
Currently in test in production. ;-)  You need to pass both user_id (not userid as in the comments above) and user_session.

**Comment by herau** [comment]
thanks @stephanegigandet but it is weird to have both `user_id` and `userid` parameters in the same url isn't it ?

http://fr.openfoodfacts.net/cgi/user.pl?userid=XXX&user_id=XXX&type=edit&user_session=YYYY

Moreover, it's the same value for the both query parameters
