### ISSUE TITLE
Add account creation in Chrome Custom tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#196]
http://world.openfoodfacts.org/cgi/user.pl

Bind it to the Sign Up button that's available in the Sign In view
Bind it to a new entry in the settings area

**Comment by herau** [comment]
i will copy the [googleChrome](https://github.com/codepath/android_guides/wiki/Chrome-Custom-Tabs#enable-pre-starting-and-pre-fetching) custom tabs shared code to be able to add a fallback for device without chrome custom tabs (Apache Licence 2 is required)

Maybe also see to use the pre-fetch option to optimize the loading of the page

**Comment by herau** [comment]
@teolemon what do you mean for `Bind it to a new entry in the settings area` ? 

bind to the `left menu` in the user part ? (just below `log in`)

**Comment by teolemon** [comment]
Thinking of adding a second place where you could create an account (in settings, if not logged)

If we can automate sign in all the best, otherwise, we need to put a reminder to do so. Otherwise "Where are all my products ?" "openfoodfacts-conributors, who is openfoodfacts-contributors ?"

**Comment by herau** [comment]
@teolemon currently we are not able to log in the user after its account creation. 
The user had to close the Chrome custom tab also when the account creation is done. i didn't find any way in the CCT to handle a form submission and then close the CCT. 

The best option, in my opinion, would be to create a dedicated android UI to be able to manage the complete workflow.
