### ISSUE TITLE
"permission denied after going to manage account"

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-androidapp#1965]
_Originally reported by @rbigueras as openfoodfacts/openfoodfacts-server#1305_

**Summary:** 

permission denied after going to manage account

**Steps to reproduce:** 

log in, click on manage account, it diverts back to openfoodfacts.org webpage and gives me an error permission denied 

**Expected behavior:** 
let me manage my account 
**Observed behavior:** 

and error message denying me permission

**Comment by huzaifaiftikhar** [comment]
@teolemon I am unable to reproduce with the above steps. I guess this is an old issue and we close this one too.

**Comment by deniger** [comment]
How could we reproduce it ?

**Comment by teolemon** [comment]
Going to the side menu. Click on the arrow right to your username. Click on "Manage account"
