### ISSUE TITLE
"I logged in and I'm still under anonymous"

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-androidapp#1966]
_Originally reported by @rbigueras as openfoodfacts/openfoodfacts-server#1306_

**Summary:** 
I logged in and I'm still under anonymous 

**Steps to reproduce:** 

use the android app beta, and click on anonymous, 
the app asks to log in, 
log in
once logged in the user's name is still anonymous
and when you try to relog in, it says you already are.
**Add system logs:**

Add logcat files here (if you are able to add).

**Expected behavior:** 
log in see name
**Observed behavior:** 
log in, see anonymous

**Comment by huzaifaiftikhar** [comment]
@teolemon I guess this issue was in an earlier version of the app. It must have been fixed at some point. Should we close this?

**Comment by teolemon** [comment]
I think it must have been NULL values passed to the URL when the user had just logged in. Ok to close.

**Comment by teolemon** [comment]
Ok to close if not reproducible

**Comment by deniger** [comment]
Could be closed or it's reproductible ?

**Comment by teolemon** [comment]
I'm closing, I think it's been closed
