### ISSUE TITLE
Include missions as a hamburger menu item

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#197]
Missions on web are not fixed yet. When they are, include a menu item (in the hamburger menu) for Missions (can open a Chrome Custom tab first)
world.openfoodfacts.org/missions

**Comment by Karljoones** [comment]
Hey @teolemon is there anything happening with the missions web page? Doesn't look like anything has been done with it. Can we close this?

**Comment by teolemon** [comment]
Yup, we'll reopen once it's fixed, I guess
