### ISSUE TITLE
Add a mechanism to automatically close a issue when PR is merged

### ISSUE THREAD

**Issue by PrajwalM2212** [openfoodfacts/openfoodfacts-androidapp#1970]
Add a way to automatically close a issue when PR is merged.
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by huzaifaiftikhar** [comment]
We already do this. @Karljoones suggested this long back.

**Comment by PrajwalM2212** [comment]
Yes, already sent a PR

**Comment by Karljoones** [comment]
@PrajwalM2212 The 'fixes #' needs to be in the title of the PR, I manually fix some of them in order to make sure that the issue does close automatically when someone forgets to add it in :)
