### ISSUE TITLE
Vitamins and Minerals shows like 0

### ISSUE THREAD

**Issue by RiQuY** [openfoodfacts/openfoodfacts-androidapp#1984]
I've just added a product to the database and if I look at the Vitamins and Minerals in the app it is in 0, but if I check it through the website the values are shown correctly.

App Screenshot:
![screenshot_2018-10-24-02-54-51-274_openfoodfacts github scrachx openfood](https://user-images.githubusercontent.com/26349954/47399569-9b5c9600-d728-11e8-88a1-eb275b1bd05a.png)

Browser Screenshot:
![screenshot_2018-10-24-02-57-43-363_org mozilla firefox_beta](https://user-images.githubusercontent.com/26349954/47399574-a0b9e080-d728-11e8-85ce-5f80dad2d6bd.png)

Product: https://world-es.openfoodfacts.org/producto/8480017371676

I downloaded the app from F-Droid, I'm logged in and my app version is: 2.9.7

**Comment by teolemon** [comment]
Thanks a lot for the report @RiQuY 
@brandenfung very much looks like a unit error (Vitamin E shows 10 time less than what it should be)

**Comment by monsieurtanuki** [comment]
It looks like a problem on the server side.

If you go to [https://fr.openfoodfacts.org/api/v0/product/8480017371676.json](https://fr.openfoodfacts.org/api/v0/product/8480017371676.json), you'll find the following values for sodium:
````json
"sodium":0.133858267716535,
"sodium_serving":0.133858267716535,
"sodium_value":"0.13385826771653545",
"sodium_unit":"g",
"sodium_100g":0.446,
````
Which matches the values displayed in [https://world-es.openfoodfacts.org/producto/8480017371676](https://world-es.openfoodfacts.org/producto/8480017371676).

But having a look again at the json, but for vitamin B2:
````json
"vitamin-b2":0.00042,
"vitamin-b2_serving":0.00042,
"vitamin-b2_value":"0.42",
"vitamin-b2_100g":0.0014,
"vitamin-b2_unit":"mg",
````
we find that there's some kind of undesired mg-to-g-conversion for fields `"vitamin-b2"`, `"vitamin-b2_serving"` and `"vitamin-b2_100g"` (with an incoherence with the other field `"vitamin-b2_value"`), with `"%_serving"` and `"%_100g"` being the values displayed in the app by `NutrimentsRecyclerViewAdapter`.

**Comment by brandenfung** [comment]
@monsieurtanuki You might be right, values in `vitamin-b2_100g` for this product seems to be in grams and not mg.

**Comment by RiQuY** [comment]
@teolemon Please reopen, issue is still unsolved.
I just checked the same product today in the latest version and still show ups wrong.
