### ISSUE TITLE
Does not display carbon footprint value

### ISSUE THREAD

**Issue by brandenfung** [openfoodfacts/openfoodfacts-androidapp#1996]
For example
https://world.openfoodfacts.org/product/3222473808946/lasagnes-au-chevre-et-aux-epinards-casino

In grams (g)

**Comment by KarthikRIyer** [comment]
I'll be looking into this issue.

**Comment by teolemon** [comment]
It seems this has already been fixed. @KarthikRIyer is fixing the apparence, and we'll be closing this.

**Comment by deniger** [comment]
Could be marked as fixed
