### ISSUE TITLE
Errors with % in Nutrition Facts

### ISSUE THREAD

**Issue by dirtygardner** [openfoodfacts/openfoodfacts-androidapp#2003]
Input item in database (Barcode: 0834266007424, last edit by me: 2018-11-13-03.05.00-UTC)

Errors (in "per serving" values):
Calcium: 0.15 % DV (label value is 15% DV)
Magnesium: 0.02% DV (label value is 6% DV)
Iron: 0.00% DV (label value is 8% DV)
Phosphorus: 0.15% DV (label value is 15%)

Inputting label values and "Save Edits" doesn't fix errors.

OpenFoodFacts version 2.9.7
LineageOS version 15.1
Android version 8.1.0

**Comment by teolemon** [comment]
@deniger

**Comment by deniger** [comment]
Fixed with https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2455
