### ISSUE TITLE
Adding a tweakable call to action in home

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2007]
Adding a tweakable call to action in home that would use a file on the Open Food Facts server, and that we could update on the fly.

![image](https://user-images.githubusercontent.com/1689815/48661748-66b5d300-ea77-11e8-8685-fa1dbe6aa669.png)

**Comment by jaindiv26** [comment]
@teolemon Here's just a sample how it would look, Do we also need to update this textView if not please give a suggestion about what would be the proper text for this, and also I need the API that would give a proper json for opening the SummaryProductFragment.

![screenshot_2018-12-03-22-56-24-650](https://user-images.githubusercontent.com/32436867/49390587-65f78f00-f74f-11e8-8577-e9b3c3235546.jpeg)

**Comment by shiv07tiwari** [comment]
@teolemon  Hello !
Can I work on this issue ?
If yes, what exactly do we need to show in the web page that we will open ?

**Comment by jaindiv26** [comment]
@shiv07tiwari I'm already working on this feature.

**Comment by shiv07tiwari** [comment]
Okay no issue.
