### ISSUE TITLE
Add prompts to get the NutriScore for uncomplete products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2015]
Add prompts to get the NutriScore and Nova groups for uncomplete products
- Add a prompt for the category that turns into the category edit field 'Add a category to compute the Nutri-Score'
- Add a prompt for the Nutrition table that turns into the nutrition tab 'Add the nutrition values to compute the Nutri-Score'

**Comment by prashantkh19** [comment]
Explanation (by steps to reproduce)?

**Comment by teolemon** [comment]
Some products don't have nutrition facts (there is an option to indicate that in the Edit mode, and there's a specific value in the JSON when that's the case)
As a result:

Nutrition tab (if no nutrition facts are indicated) : 
Add the nutrition values to compute the Nutri-Score
This product doesn't have nutrition facts
