### ISSUE TITLE
Samsung Galaxy S9: camera image freezes

### ISSUE THREAD

**Issue by SantosSi** [openfoodfacts/openfoodfacts-androidapp#2025]
**Summary:** 
The image captured from the camera is frozen after adding a new or editing an existing product.

**Steps to reproduce:** 
- Scan a new product
- Add data
- Save
OR:
- Scan an existing product
- Tap the pencil icon
- Save

**Expected behavior:** 
Continue to capture the live camera image.

**Observed behavior:** 
A still image highly probable from when the edit icon was tapped. This is even the case after successfully taking pictures to fill the product details in between. Going back and tapping the barcode icon reactivates capturing the live image from the camera, without the need to close the app.
This does *not* happen when discarding changes.

**Device and Android version:** 
Happens on a Samsung Galaxy S9 with stock Android 8.0.0
Does not happen on a Galaxy S6 with LineageOS 14.1

**Comment by teolemon** [comment]
@SantosSi Can you still reproduce the bug ?

**Comment by SantosSi** [comment]
No.
