### ISSUE TITLE
Image upload fails when the app is in Brazilian portuguese

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2026]
Image upload fails when the app is in Brazilian portuguese (and possibly other languages in the form of XX_xx)
the server only accepts 2 letters.

**Comment by jaindiv26** [comment]
@teolemon I'll try to debug and reproduce this issue.

**Comment by jaindiv26** [comment]
@teolemon I've selected Portueges(Brasil), upload an image, it works fine, If it's occurring at ay specific screen please tell.

![screenshot_2018-12-22-22-08-46-321_openfoodfacts github scrachx openfood](https://user-images.githubusercontent.com/32436867/50376703-a81d3d80-0636-11e9-9eeb-c4d95962a355.png)

**Comment by teolemon** [comment]
Can you try with the ingredients and nutrition, possibly in edit mode.

**Comment by jaindiv26** [comment]
@teolemon I've run various combination, but none of them makes app crash. Can you upload the deobfuscation file maybe that will help to trace this issue properly.

**Comment by teolemon** [comment]
fixed server side
