### ISSUE TITLE
Immediately attempt to reload the product when ingredient are added or modified

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2029]
- Immediately attempt to reload the product when ingredient are added or modified
- Usually we can compute additives, allergens, and the Nova groups, and they need to appear instantly.

**Comment by subhanjansaha** [comment]
Could you please elucidate as to what is required to be done? (if possible, include steps to reproduce the fault)

**Comment by teolemon** [comment]
Hey @subhanjansaha 
1. Edit a product without the ingredients and add the ingredients.
2. The ingredients don't appear after save. Pull to refresh makes it appear, but additives and NOVA don't appear.
3. Expected result: additives and NOVA should appear.
