### ISSUE TITLE
Immediately attempt to reload the product when the category is added or modified

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2030]
- Immediately attempt to reload the product when the category is added or modified. That way it will show the Nutri-Score
- Usually we can compute the Nutri-Score if nutrition is here, and it needs to appear instantly.

**Comment by prashantkh19** [comment]
Can you please explain this? (possibly by some steps or screenshots)

**Comment by teolemon** [comment]
1. Add a new product (without the category)
2.Scan it and go to its full page
3. Edit and add the category.
4. The category doesn't appear after save. Pull to refresh doesn't make it appear.

5. Expected result: pull to refresh should make it appear.

**Comment by prashantkh19** [comment]
Got it! I am working on this.
