### ISSUE TITLE
Add a small "Take Nutrition Photo" and "Take Ingredient photo" to the first tab when ingredent and/or nutrition photo are missing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2042]
Add a small "Take Nutrition Photo" button to the first tab (similar to the one in Nutrition tab) when nutrition photo is missing and "no_nutrition_data" is not True.

Add a small "Take Ingredients Photo" button to the first tab (similar to the one in Ingredients tab) when nutrition photo is missing

They could be right and left of the button/existing photo for front

Rationale: the Take Nutrition Photo is on the 4th tab, and a result there's no quick way to know if we have a picture or not

**Comment by prashantkh19** [comment]
A button below 'TAKE MORE PICTURES' would be fine?
