### ISSUE TITLE
Add a small prompt "Extract ingredients" when there's an ingredient photo but no ingredient text

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2043]
On the ingredient tab, add a small prompt "Extract ingredients" when there's an ingredient photo but no ingredient text.
It should open the edit mode, go to the ingredient section and start the OCR process.

**Comment by teolemon** [comment]
@subhanjansaha can you formally claim the bug ?

**Comment by subhanjansaha** [comment]
I'm not sure I follow, how do I claim an issue?
