### ISSUE TITLE
Enable contributors to select, rotate and crop images from product page on long press

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2044]
Enable contributors to select, unselect, rotate and crop images from product page (in the summary, ingredients, nutrition tabs) on long press.
Enter an edit mode that enables to crop and rotate the current image, as well as select, rotate and crop one of the other images.
@PrajwalM2212 has already created a PR #2019  for a more general image selection tab that can be leveraged.

**Comment by prashantkh19** [comment]
I am working on this.

**Comment by prashantkh19** [comment]
- Is there any API to get all the images associated with a product? 
(as to select an image for let say Front, I need to display all the images in android)

**Comment by deniger** [comment]
A new edit button is now available to change the image
if the user click on the image, he is able to rotate/crop the image
