### ISSUE TITLE
Add a "Show your support" link in settings

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#205]
Add a "Show your support" link in settings to enable users to rate the app the Play Store (hide if Play Store not installed)

**Comment by Shubham2320** [comment]
Working on it.

**Comment by roydipayan003** [comment]
Can I work on it?

**Comment by Karljoones** [comment]
@roydipayan003 there is already someone working on this one, but feel free to choose another issue that nobody else has claimed :)

**Comment by roydipayan003** [comment]
I'm new to git...so thanks for the guidance :)

**Comment by Karljoones** [comment]
No problem. If someone has commented on it it usually means someone is working on it! Ping me on [Slack](openfoodfacts.slack.com) if you need any help :)
