### ISSUE TITLE
OpenFoodFacts keeps stopping

### ISSUE THREAD

**Issue by kujaw** [openfoodfacts/openfoodfacts-androidapp#2052]
- OFF version 2.9.8 from FDroid.
- Android 7.1.2

During opening I get the error "OpenFoodFacts has stopped", after clicking "Open app again" I get "OpenFoodFacts keeps stopping".
How can I get any logs to help you?

**Comment by teolemon** [comment]
Do you use the app in Polish, by any chance ?

**Comment by kujaw** [comment]
I have English language set systemwide, but I use it in Poland.

**Comment by teolemon** [comment]
What about the app itself. English ?

**Comment by teolemon** [comment]
If you're unfamiliar with logging, you can install Android Studio, connect your device with a USB Cord, and look for the error.
1. Enable usb debugging
https://developer.android.com/studio/debug/dev-options
2.Look for the Logcat tab at the bottom of Android Studio after installing it, filter on Errors. Filter on "openfood" and you should see the error.

**Comment by teolemon** [comment]
@kujaw Can you try wiping your cache ?

**Comment by teolemon** [comment]
@kujaw I have found the reason. It will be fixed in the next release :-)

**Comment by kujaw** [comment]
Damn, sorry @teolemon , totally forgot about this. Do you still need logs?

**Comment by teolemon** [comment]
It is fixed, and you can update from master if you want. I don't need logs anymore :-)
Thanks for the vigilance and follow up 👍

**Comment by teolemon** [comment]
fixed
