### ISSUE TITLE
Add an explicit 'Take another photo' button in edit mode next to the photo currently selected

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2053]
Add an explicit `Take another photo` button in edit mode next to the photo currently selected in the Summary, ingredients and nutrition steps. Currently, you have to long press the photo to take another, which is not intuitive enough.

**Comment by jaindiv26** [comment]
@teolemon I'll be working on this.

**Comment by teolemon** [comment]
@stephanegigandet the bug already exists.
@jaindiv26 are you still working on this ?

**Comment by jaindiv26** [comment]
Sorry, but will not be working on this.

**Comment by teolemon** [comment]
I believe it's fixed (We have "Send an updated image" as a button)
