### ISSUE TITLE
Adding support for recycling instructions

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2065]
We have two new fields for some products:
```
recycling_instructions_to_discard_fr
recycling_instructions_to_recycle_fr
```
(You can append language for language specific versions)

**Comment by teolemon** [comment]
Sample product: https://world.openfoodfacts.org/product/3222472114031/cacahuetes-grillees-et-salees-250g-casino

**Comment by prashantkh19** [comment]
working on this.
