### ISSUE TITLE
Small issue with the store field

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2073]
![image](https://user-images.githubusercontent.com/1689815/50897423-52a1a880-140c-11e9-9899-11072ace9463.png)
It seems that an extra space is introduced on the 2nd and 3rd value. It ain't like that on other fields.

**Comment by teolemon** [comment]
Example barcode: 3245412051661

**Comment by teolemon** [comment]
https://barcode.tec-it.com/en/EAN13?data=3245412051661

**Comment by subhanjansaha** [comment]
I'll work on this.

**Comment by teolemon** [comment]
it was fixed. closing
