### ISSUE TITLE
Trash icon visible after swiping in History section

### ISSUE THREAD

**Issue by tronku** [openfoodfacts/openfoodfacts-androidapp#2086]
**Summary:** 

In the history section, the trash icon used to delete an item is visible even after deleting the item.

**Steps to reproduce:** 

Go to History section from Navigation Drawer. Swipe any item to the left and click the trash icon visible on the right. The item will get deleted but the trash icon will be still visible.

**Expected behavior:** 

After clicking the trash icon, it should be gone.

**Observed behavior:** 

The trash icon found by swiping the item to the left is visible even after deleting the item.

**Device and Android version:** 

Model - Mi Redmi Note 5
Android version - Android Oreo (8.1)
ROM - Custom

**Screenshots:** 

![whatsappvideo20190111at84](https://user-images.githubusercontent.com/31654207/51043670-4290f100-15e5-11e9-85a8-36699bb58794.gif)

**Comment by Shritesh99** [comment]
Working on it.
