### ISSUE TITLE
Load taxonomies in the background

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2105]
Currently, users have to wait a long time on 1st use for taxonomies to load. I suspect this is loosing us contributors, especially people on slow connexions.
Can we load the taxonomies in the background ? The latest versions of Android are agressive on background processes, and this is bug prone.
Also extra care should be applied because people might load features that require taxonomies, at a time when they are not downloaded and installed.

**Comment by prashantkh19** [comment]
This can be applied to issue#2069 to download product in background as well. I will work on it..
