### ISSUE TITLE
Send an updated image sends to the Contribution tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2111]
Send an updated image sends to the Contribution tab

**Comment by PrajwalM2212** [comment]
Can I get more information about this ?

**Comment by teolemon** [comment]
There's this "Take an updated photo" on the ingredient tab.

**Comment by teolemon** [comment]
when you already have a picture it seems

**Comment by PrajwalM2212** [comment]
@teolemon So you want me to hide this button if ingredient already exists

**Comment by teolemon** [comment]
I was more thinking putting it at the bottom of the page, and actually opening the photo viewfinder, rather than switching tabs
