### ISSUE TITLE
Create a fast addition mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2118]
It would only require 3 photos, product name, brand and weight.

**Comment by prashantkh19** [comment]
working on it.

**Comment by subhanjansaha** [comment]
I can work on this

**Comment by teolemon** [comment]
@prashantkh19 I was considering starting from the existing addition mode, and hiding everything but those fields.
Perhaps we should include categories, ingredients and nutrition so that people can get the Nutri-Score and Nova groups immediately.

**Comment by prashantkh19** [comment]
Yeah, that'd be good. I will make only these fields visible.

**Comment by teolemon** [comment]
I was thinking to hide them only during addition, and perhaps have a "Show full edition mode" option in Settings for those who want a full addition mode.
Edit mode should have all the fields, in all circumstances.
