### ISSUE TITLE
Nutrition facts - wrong transformation?

### ISSUE THREAD

**Issue by Creebo** [openfoodfacts/openfoodfacts-androidapp#2121]
Updated nutrition facts for product 4000540011081 and somehow the units are wrong. In the app I could update e.g. Mg with the unit [mg] and in the overview it comes wrong. 134 mg --> 0,13 mg ? 

Using Samsung Note 9 with Android 9

**Comment by subhanjansaha** [comment]
I'll look into it.

**Comment by deniger** [comment]
Fixed with https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2455
