### ISSUE TITLE
Remove the exclamation mark in History when there is no Nutri-Score

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2124]
Remove the exclamation mark in History when there is no Nutri-Score. It's ugly and not very helpful.
Also, in "Products to Be Completed", 3250392243876 displays a A nutriscore, while none is actually computed.
![image](https://user-images.githubusercontent.com/1689815/51438862-00854080-1cb2-11e9-880c-4b6f3b1694a4.png)

**Comment by subhanjansaha** [comment]
I'll work on this.
