### ISSUE TITLE
Add pull to refresh to Listviews & Product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#213]
PullToRefresh-ListView - Easy to use pull-to-refresh functionality for ListViews. Download and install as a library project.

**Comment by teolemon** [comment]
https://github.com/erikwt/PullToRefresh-ListView
https://github.com/erikwt/PullToRefresh-ListView/archive/master.zip
http://imgur.com/a/N8baF

**Comment by herau** [comment]
https://guides.codepath.com/android/Implementing-Pull-to-Refresh-Guide

**Comment by PrajwalM2212** [comment]
I am working on it.
