### ISSUE TITLE
Put the Nova Score also in the ingredient tab, with more explanations

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2130]
Put the Nova Score also in the ingredient tab, with more explanations
``` Nova classification on food processing (from 1 to 4)``` 
```
Group 1 - Unprocessed or minimally processed foods
Group 2 - Processed culinary ingredients
Group 3 - Processed foods
Group 4 - Ultra-processed food and drink products
```
Add an explicit link to the Nova methodology. "Read more about the science behind Nova"

**Comment by KarthikRIyer** [comment]
I'll work on this
