### ISSUE TITLE
The send updated image is redirecting to the Contributions tab (if enabled)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2133]
The send updated image is redirecting to the Contributions tab (if enabled). It should instead open the edit mode and offer to take a new ingredient picture (The current way to do it is to click edit, go to the ingredient tab, long press on the existing ingredient image, which allows you to take a new one and redo the OCR)

**Comment by subhanjansaha** [comment]
I can work on this
