### ISSUE TITLE
Nutrient name should always be visible in edit mode (even if we have a value)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2138]
Nutrient name should always be visible in edit mode (even if we have a value)
Currently, it's hidden if we have a value

**Comment by subhanjansaha** [comment]
Working on this.

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/src/main/res/layout/fragment_add_product_overview.xml


  |   | app/src/main/res/layout/fragment_add_product_photos.xml
  |   | app/src/main/res/layout/fragment_add_product_overview.xml
  |   | app/src/main/res/layout/fragment_add_product_ingredients.xml
  |   | app/src/main/res/layout/fragment_add_product_nutrition_facts.xml

**Comment by deniger** [comment]
Is it the same point than #2403 ?

**Comment by teolemon** [comment]
Yes. I tend to double file bugs :-)

**Comment by deniger** [comment]
Closed with #2403
