### ISSUE TITLE
Add infinite scroll to product lists

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#214]
**Steps to reproduce**
- Search for Nutella
- You get 20-something results
- You can't get additional results

**Proposed solutions**
- Auto infinite scrolling, loading the next JSON page
- Link to load more results

**References**
GridListViewAdapters - Easily build unlimited Grid cards list like play-store. (ListView working as unlimited GridView)

https://github.com/birajpatel/GridListViewAdapters

**Comment by teolemon** [comment]
https://github.com/birajpatel/GridListViewAdapters

**Comment by asmoth360** [comment]
It would be useful too to display the number of matching products, like on the website. For example if you'd get "200 products", you would know that your request is imprecise and it's unlikely you'll find the product you want quickly.

**Comment by herau** [comment]
@asmoth360 you are right, we can add an sub-header in the list of results to display to number of matching results. 

we can handle this feature in this issue i guess (we have enough issues ^^)

**Comment by herau** [comment]
need #397 to use the recyclerView for infinite scroll

**Comment by itchix** [comment]
![unnamed-2](https://cloud.githubusercontent.com/assets/2846894/21956803/f823d202-da88-11e6-9b99-02356dcf4976.png)

![unnamed](https://cloud.githubusercontent.com/assets/2846894/21956808/00ab8e38-da89-11e6-978f-a884f8fce7de.png)

**Comment by herau** [comment]
@itchix what do you think to remove the `Number of results` when the user scrolling down ? to enable the user to have more space to see the results ?
