### ISSUE TITLE
Do not display a question mark on product page if the Nutri-Score is not available

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2142]
![image](https://user-images.githubusercontent.com/1689815/51680137-32afde80-1fe1-11e9-9f14-344cf2db4e68.png)

**Comment by subhanjansaha** [comment]
On it 👍

**Comment by teolemon** [comment]
Same issue on the nutrition tab

**Comment by subhanjansaha** [comment]
Alright I will open a PR for both of them
