### ISSUE TITLE
When adding a category, the product page is not reloaded properly

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2156]
![image](https://user-images.githubusercontent.com/1689815/51789043-29f80d80-2185-11e9-98ce-4b3dc2ab2513.png)

- The Nutri-Score doesn't appear on the main tab immediately
- It appears on pull to refresh (or immediately, not sure about that) in the nutrition tab, but the button to add the category is still there.

**Comment by subhanjansaha** [comment]
I'll work on this

**Comment by deniger** [comment]
Will be fixed with https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2494
