### ISSUE TITLE
Let users add products to lists

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2158]
Let users add products to lists

There would be 2 standard preloaded lists: "Eaten products" and "Products to buy", as well as the ability to create custom lists.

There would be a dropdown button on the product pages to add the product to a given list (or to add to a new list).

**Comment by subhanjansaha** [comment]
I can work on this.

**Comment by balaji-ramavathu** [comment]
I love this idea! I'll work on it.

**Comment by teolemon** [comment]
I guess technically @subhanjansaha you were first, so you have a right of precedence, but @balaji-ramavathu seems very enthusiastic about it. :-)

**Comment by PrajwalM2212** [comment]
@subhanjansaha You should claim issues after you submit a PR to a already reserved issue. This way every contributor gets a chance to choose issues.
You have more than 5 issues lined up. It is optimal to have not more than 2 issues reserved at a time.

**Comment by subhanjansaha** [comment]
@PrajwalM2212 Yes, I completely agree. I have a lot on my plate as it is.
@balaji-ramavathu Please go ahead with this, I don't mind at all! :-)

**Comment by balaji-ramavathu** [comment]
thanks @subhanjansaha :-)
