### ISSUE TITLE
Let users rotate Ingredients, Front and Nutrition image left and right from the "Product photos" tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2164]
Display  Ingredients, Front and Nutrition images in the "Product photos" tab

Let users rotate Ingredients, Front and Nutrition image left and right from the "Product photos" tab

**Comment by KarthikRIyer** [comment]
I'll look into this

**Comment by theLimitBreaker** [comment]
Can I work on this ? Please .

**Comment by teolemon** [comment]
Fixed by @deniger in some other way
