### ISSUE TITLE
Let user crop images after selecting in the "Product photos" tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2165]
Let users crop images after selecting in the "Product photos" tab. This needs to be done with the server side api, a bit like in #2092

**Comment by Shritesh99** [comment]
I will work in this.

**Comment by Shritesh99** [comment]
Hi, @teolemon can you provide the documentation of https://world.openfoodfacts.org/cgi/product_image_crop.pl for crop the image.

**Comment by teolemon** [comment]
Hey
https://world.openfoodfacts.org/cgi/product_image_crop.pl?code=1&imgid=2&id=front_en&x1=14&y1=14&x2=45&y2=45

code : barcode
imgid : the image you wish to crop
id : the field you wish to crop it into (front_fr, ingredients_en, nutrition_hi…)
x1, y1, x2, y2: the crop coordinates

**Comment by joshhazelhurst123** [comment]
@Shritesh99 can you assign this issue to yourself. Thanks.

**Comment by deniger** [comment]
@teolemon maybe could be closed with the last PR...

**Comment by teolemon** [comment]
@deniger I just discussed with @stephanegigandet and we agreed it would be way more sane for server space to have server-side cropping, rather than filling the hard-drives with duplicates.

**Comment by teolemon** [comment]
Fixed by @deniger
