### ISSUE TITLE
Add a "Take a photo of the ingredients in XXX" button

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2191]
On the ingredient page, add a "Take a photo of the ingredients in XXX" button if the product doesn't have an ingredient photo in the locale of your phone.

Example:
- product in French, phone in Dutch, showing "Take a photo of the ingredients in Dutch"
- uploading and selecting the photo as ingredients_nl

**Comment by subhanjansaha** [comment]
I can work on this.

**Comment by teolemon** [comment]
You can go ahead. Actually you can use the same style as when there's no ingredient picture at all (with the + camera icon).
This also requires tweaking the network call.

**Comment by subhanjansaha** [comment]
I understand, and yes, the same prompt can be used. I'll look into it. Thank you for the suggestion.
