### ISSUE TITLE
Expand the home message to OBF/OPF/OPFF

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2193]
We're expanding the home message to the other projects.
The urls will be:
https://world.openfoodfacts.org/files/tagline/tagline-off.json
https://world.openfoodfacts.org/files/tagline/tagline-obf.json
https://world.openfoodfacts.org/files/tagline/tagline-opff.json
https://world.openfoodfacts.org/files/tagline/tagline-opf.json

**Comment by teolemon** [comment]
@jaindiv26 ? @stephanegigandet can you deploy the new files ?

**Comment by jaindiv26** [comment]
@teolemon @stephanegigandet The tagline url for other flavors should be like this:
https://ssl-api.openbeautyfacts.org/files/tagline/tagline.json
https://ssl-api.openproductsfacts.org/files/tagline/tagline.json
https://ssl-api.openpetfoodfacts.org/files/tagline/tagline.json

**Comment by jaindiv26** [comment]
@teolemon @stephanegigandet Any updates?

**Comment by teolemon** [comment]
I've copied the tagline like so: 
```https://world.openfoodfacts.org/files/tagline/tagline-off.json
https://world.openfoodfacts.org/files/tagline/tagline-obf.json
https://world.openfoodfacts.org/files/tagline/tagline-opff.json
https://world.openfoodfacts.org/files/tagline/tagline-opf.json``` 
It's really much easier to manage, since there's no file folder for other projects.
