### ISSUE TITLE
Change the Anchor thing to the official offline icon

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#220]
- Change the Anchor thing to the official offline icon (can be seen in Google Maps, otherwise airplane mode icon)

**Comment by teolemon** [comment]
![screenshot_20161113-115740](https://cloud.githubusercontent.com/assets/1689815/20256344/2f826de2-aa43-11e6-9065-802190cdd51e.png)

**Comment by teolemon** [comment]
Alternatively:
https://material.io/icons/#ic_airplanemode_active

**Comment by Karljoones** [comment]
Were you originally referring to this one: [https://material.io/icons/#ic_cloud_off](https://material.io/icons/#ic_cloud_off)?

**Comment by teolemon** [comment]
They had a specific icon with a thunderbolt, but the airplane icon is
working well in the end

----------------------------------------
Pierre Slamich - pierre@slamich.net - (+33) 6 02 13 14 57

**Comment by Karljoones** [comment]
Well in that case, I will close this off :)
