### ISSUE TITLE
Bind new field in HTML card in the Environnment tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2205]
We have added a new experimental field: `environment_infocard`to give the carbon impact of a product.
https://fr.openfoodfacts.org/api/v0/produit/3560070573998/lasagnes-a-la-bolognaise-grand-jury?fields=environment_infocard
Whenever this field is not empty, the environment tab should be shown, and the basic HTML that it contains should be put in a card using this technique:
https://stackoverflow.com/questions/2116162/how-to-display-html-in-textview

**Comment by subhanjansaha** [comment]
I will work on this.

**Comment by teolemon** [comment]
👍
