### ISSUE TITLE
Display colored CO2 icon depending on the Carbon impact in the scanner view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2206]
Depending on whether 
https://fr.openfoodfacts.org/api/v0/produit/3560070573998/lasagnes-a-la-bolognaise-grand-jury
`environment_impact_level_tags` is `en:high` `en:medium` or `en:low`, display a Red, Orange or Green CO2 icon
(https://drive.google.com/open?id=1pyHX6SHwPSa8Pizmm8PiZnjYMi8ANhZP) in the Scan card

If `environment_impact_level_tags` is absent, do not display anything

**Comment by teolemon** [comment]
https://fr.openfoodfacts.org/api/v0/produit/3560070573998/lasagnes-a-la-bolognaise-grand-jury?fields=environment_impact_level_tags

**Comment by teolemon** [comment]
https://drive.google.com/open?id=1pyHX6SHwPSa8Pizmm8PiZnjYMi8ANhZP

**Comment by balaji-ramavathu** [comment]
I'll work on it.

**Comment by teolemon** [comment]
thanks @balaji-ramavathu 👍 this one is going to be experimental, but awesome

**Comment by teolemon** [comment]
@balaji-ramavathu can you integrate it as well in your compare branch next to the Nutri-Score and Nova ?

**Comment by balaji-ramavathu** [comment]
Are you referring to this comparision feature? https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2180 That wasn't done by me, But If that PR gets merged, I can display CO2 icon in the comparison activity.

**Comment by teolemon** [comment]
Not enough sleep; sorry :-)

**Comment by balaji-ramavathu** [comment]
It's fine :-) Where exactly should I display the icon in the scan card?

**Comment by teolemon** [comment]
I would put it on the right of the Nova score. It's increasingly difficult to put stuff in there :-)
Also, if you can take advantage to put the logo on the summary tab, on the right on the Nova, that would be perfect.
Server side, we're computing the score for all the products in the DB as we speak. We'll be presenting the feature on Tuesday at the French National Assembly :-)

**Comment by balaji-ramavathu** [comment]
That's awesome !
