### ISSUE TITLE
Add a search history to the search bar

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2209]
Add a search history to the search bar. It should be deletable, and it should be clear it's only stored locally (on first search, a suggestion might appear "Your last searches will appear here. They are stored on your phone and you can delete them at any time in Settings. They will never be associated with any personal information."

**Comment by subhanjansaha** [comment]
I can work on this.

**Comment by prajurock** [comment]
can i work on this?@subhanjansaha@teolemon
