### ISSUE TITLE
Reuse as many standard icons as possible

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#221]
- Reuse as many standard icons as possible. Looks like the wheel are different in your example and in my system. It might reduce apk size

**Comment by teolemon** [comment]
http://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html#application
For login :  account-add

**Comment by herau** [comment]
icons came from the drawer component. maybe switch to default Android drawer...

**Comment by Karljoones** [comment]
Closed as #398 was created, leaving the later one open for more exposure
