### ISSUE TITLE
Press back button twice to exit from application

### ISSUE THREAD

**Issue by prajurock** [openfoodfacts/openfoodfacts-androidapp#2219]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

Press back button twice to exit from application

**Device and Android version:** 
Android 8.1 (API 27) Asus Zenfone MAx M1 pro

**Comment by prajurock** [comment]
I would like to work o this

**Comment by teolemon** [comment]
Can you clarify what you mean ? Is there currently an issue ?

**Comment by prajurock** [comment]
If user presses back button accidentally then message will come to press the back button twice.

**Comment by brandenfung** [comment]
I'm not sure if this feature is needed for OFF. This pattern is usually used for immersive content (like mobile games, or certain fullscreen apps).

**Comment by prajurock** [comment]
Yes but i noticed this feature in some shopping app also
