### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by joshhazelhurst123** [openfoodfacts/openfoodfacts-androidapp#2226]
Hi,
I have noticed there is quite a bit of people taking on issues and not assigning the issue to themselves. Can the readme.md be updated so that it says on the main page to assign the issue to yourself if you will have a go at fixing it. That way it saves times for other's looking to tackle issues. Thanks. Josh

**Comment by brandenfung** [comment]
I think you can only assign issues if you have write access to a repo. https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/

**Comment by PrajwalM2212** [comment]
When someone comments that they want to work on a issue it means they are asigned to the issue. 
I understand that you want the issues assigned so that you can save time by not searching others already assigned issues. 
We can assign it for you if you want.

**Comment by joshhazelhurst123** [comment]
@PrajwalM2212 yes I saw a few issues that I would of liked to of worked on but there was someone that commented that they wanted to work on the issue. So I am just bringing up the issue that maybe if it could be assigned to that user then that would be easier for other's looking to get involved. The assignee would show up on the issues page etc. Thanks for your comments.

**Comment by teolemon** [comment]
I'm currently creating a roadmap to avoid this.
