### ISSUE TITLE
Change the wording of popup in offline mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#223]
"The product doesn't exist" >> unless we have a local list of existing barcodes (and even so), we can't say that for sure.

In that case, say that we can't display the product while in offline mode and propose to add photos.

Or better yet:
- jump to an empty product page
- display the add photos button
-display below it a  "more information if available, when you get a connexion again" text
-display below that a "reload page"

**Comment by jaindiv26** [comment]
When a barcode is searched in offline mode, it displays a popup stating "The product you scanned does not exist yet in Open Food Facts. Please add it. (Yes, no)". What do you propose, what should be the ideal popup info, as after clicking on Yes button, does exactly what you stated in the description.
