### ISSUE TITLE
Ask questions about incomplete products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2234]
Ask simple questions to users about incomplete products

https://github.com/shivasurya/FeedbackDialog

For barcode: 00024907 and if the UX is in French
https://robotoff.openfoodfacts.org/api/v1/questions/00024907?lang=fr

Then depending on the answer, POST request:
https://robotoff.openfoodfacts.org/api/v1/insights/annotate

The request type must be application/x-www-form-urlencoded.
```
- insight_id (str, required) - ID of the insight
- annotation (int, required) - Annotation of the prediction: 1 to accept the prediction, 0 to refuse it, and -1 for "unknown".
- update (int, optional) - Send the update to Openfoodfacts if update=1, don't send the update otherwise. This parameter is useful if the update is performed client-side.
```

**Comment by teolemon** [comment]
This should only appear on request, a bit like this:
![image](https://user-images.githubusercontent.com/1689815/52977241-d61bc580-33cc-11e9-9b67-eb240cd00477.png)

**Comment by subhanjansaha** [comment]
I can work on this.

**Comment by prashantkh19** [comment]
@subhanjansaha are you still working on it?

**Comment by subhanjansaha** [comment]
Yes, I am. I'll open a PR very soon
