### ISSUE TITLE
The project tagline should always fit on one line

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2244]
The project tagline should always fit on one line. It's handled ok on the splash screen, but not on the home screen.

![image](https://user-images.githubusercontent.com/1689815/53015641-d0b19000-344b-11e9-9a6e-cd3df43370a5.png)
![image](https://user-images.githubusercontent.com/1689815/53015719-06567900-344c-11e9-8a12-d2965986b645.png)

**Comment by balaji-ramavathu** [comment]
I'll fix it.
