### ISSUE TITLE
Add a bottom bar to home

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2245]
![image](https://user-images.githubusercontent.com/1689815/53016963-318e9780-344f-11e9-9b58-080387c83e0d.png)

**Comment by jaindiv26** [comment]
I'll work on this.

**Comment by teolemon** [comment]
@jaindiv26 I've made a similar design for the product page, where we keep the same color for contrast, we move the search button on the top left (where people usually expect it to be), thus reducing the number of icon from 5 to 4 (and prevent the fab ovelay on the history)
![image](https://user-images.githubusercontent.com/1689815/53045030-e8f5cf00-348c-11e9-85b5-63c53665ad86.png)

**Comment by jaindiv26** [comment]
Got the idea, I'll work accordingly.

**Comment by teolemon** [comment]
@jaindiv26 Any progress on this one ? This is one of the changes I'd really like to get into the next version.

**Comment by jaindiv26** [comment]
I'll submit it in the morning.

**Comment by teolemon** [comment]
@jaindiv26 should I reassign this one ? Do you have some code somewhere ?
