### ISSUE TITLE
Add a counter to products in list

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2251]
Allow the user to add a number on products in lists. Ideally, the user could input fractions, so that it can work for:
I have 2 bottles of coke in my fridge
I have eaten 1/10 of the Nutella jar :-)

**Comment by prashantkh19** [comment]
I will work on this

**Comment by Krusty27** [comment]
Is this feature actually present in the Android app? How can I use it?

**Comment by teolemon** [comment]
Hey @Krusty27 I think we had a number of technical issues and it might have been disabled
