### ISSUE TITLE
Reformat product header

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2255]
![image](https://user-images.githubusercontent.com/1689815/53047275-5e17d300-3492-11e9-9d27-aa1093cf56ce.png)

**Comment by jaindiv26** [comment]
I'll work on it.

**Comment by teolemon** [comment]
I forgot the common name, that we can put below, or like this:
![image](https://user-images.githubusercontent.com/1689815/53047692-468d1a00-3493-11e9-8f4f-997b343b2d31.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/53047763-70ded780-3493-11e9-9117-d7315e078fe3.png)

**Comment by jaindiv26** [comment]
How about if we cardify this something like, 
Common Name : Ham and cheese sandwich with guerande salt 
Above the Club Jambon...

**Comment by teolemon** [comment]
Why not, keep in mind that the common name is not always available though.
![image](https://user-images.githubusercontent.com/1689815/53048423-0169e780-3495-11e9-8da6-83a02d1a7a28.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/53048518-3a09c100-3495-11e9-94e6-bdc3c4649407.png)

**Comment by teolemon** [comment]
@jaindiv26 you are free to choose the design that seems to work best. 
Keep in mind:
- common name is not always available
- images can be vertical, or horizontal

**Comment by jaindiv26** [comment]
@teolemon I'll make sure of it, I'll push my changes soon.

**Comment by teolemon** [comment]
https://user-images.githubusercontent.com/1689815/54564828-14f16b00-49cd-11e9-8eb2-3d0379c12b0e.png

**Comment by teolemon** [comment]
@raphael0202 @jaindiv26
