### ISSUE TITLE
App tagline is displayed in English when the language is set to Hindi in Home

### ISSUE THREAD

**Issue by balaji-ramavathu** [openfoodfacts/openfoodfacts-androidapp#2260]
**Summary:** 

Though we have tagline translation in Hindi which is well displayed in splash activity, it is being displayed in English in Home when the app language is set to Hindi.

**Screenshots:**

![hindi2](https://user-images.githubusercontent.com/26673203/53083946-d9769480-3525-11e9-9296-70fdd6ce2d6f.jpg)
![hindi1](https://user-images.githubusercontent.com/26673203/53083945-d9769480-3525-11e9-9c16-39c8a5cbdb24.jpg)

**Comment by teolemon** [comment]
fixed
