### ISSUE TITLE
Add scroll bar to preferences

### ISSUE THREAD

**Issue by mustaqmustu** [openfoodfacts/openfoodfacts-androidapp#2265]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)
when we open preferences,there is no scroll bar.Adding a scroll bar might be better.

**Steps to reproduce:** 
1.Open the app
2.Go to preferences

**Expected behavior:** 

A scroll bar must be present in preferences.

**Observed behavior:** 

There is no scroll bar.

**Device and Android version:** 
Device is asus 3s max.OS is 7.1.
**Screenshots:** 
![20190220_173437](https://user-images.githubusercontent.com/43813438/53091651-822def80-3538-11e9-825e-a279da32d2bd.gif)

**Comment by mustaqmustu** [comment]
I want to work on this issue

**Comment by teolemon** [comment]
You can go ahead. We should probably also allow to filter settings

**Comment by teolemon** [comment]
![](https://i.imgur.com/DHoJDQD.png)
