### ISSUE TITLE
No option to add products to lists

### ISSUE THREAD

**Issue by prashantkh19** [openfoodfacts/openfoodfacts-androidapp#2266]
**Summary:** 
There is no '+' button on top right of the product page to add the product to list.

**Screenshots:** 
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/27685757/53094902-65e28080-3541-11e9-81ae-4f03f99d4d2d.gif)

**Comment by subhanjansaha** [comment]
I want work on this.

**Comment by prashantkh19** [comment]
@teolemon Please check if there is any other way, otherwise I will look into it

**Comment by teolemon** [comment]
It doesn't appear in scan mode, it seems, you are right.

**Comment by prashantkh19** [comment]
It doesn't show on the productFragment, I will fix it.
