### ISSUE TITLE
Splash screen is not appearing

### ISSUE THREAD

**Issue by mustaqmustu** [openfoodfacts/openfoodfacts-androidapp#2268]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

Splash screen is not appearing

**Expected behavior:** 

splash screen must appear

**Observed behavior:** 

splash screen is not appearing

**Device and Android version:** 
samsung j8.os 8.1

screenshots:
![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/43813438/53107455-101ad200-355b-11e9-8d71-26670b44679d.gif)

**Comment by teolemon** [comment]
This is related to the homepage "Discover Open Beauty Facts" which is not cached in trunk.

**Comment by refactor-droidyy** [comment]
I am a Beginner can i work on this issue.

**Comment by teolemon** [comment]
This has been solved by caching the tagline. Closing
