### ISSUE TITLE
The environment infocard is blank (master)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2270]
Still seems to be working server side:
https://fr.openfoodfacts.org/api/v0/produit/3560070573998/lasagnes-a-la-bolognaise-grand-jury?fields=environment_infocard_fr

Barcode to reproduce:
https://barcode.tec-it.com/en/EAN13?data=3560070573998

**Comment by teolemon** [comment]
Also side note: if nothing is displayed, the tab should disappear as well.

**Comment by subhanjansaha** [comment]
I want to work on this.

**Comment by teolemon** [comment]
You can go ahead. :+1:
