### ISSUE TITLE
Add a white background on the contributor image

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#228]
![image](https://cloud.githubusercontent.com/assets/1689815/20257354/5668ca9a-aa49-11e6-9ed2-2967f35a7444.png)

**Comment by asmoth360** [comment]
Where can we found the current image ? If needed I can create the new one with the white background, should be easy.

**Comment by teolemon** [comment]
http://world.openfoodfacts.org/discover

**Comment by asmoth360** [comment]
Thanks, I thought the circle was part of the image. So currently the image is supperimposed to the circle which is in the background, right ?

**Comment by asmoth360** [comment]
Does that do the trick?
![opendata-crowd-icon-white](https://cloud.githubusercontent.com/assets/19469836/21425689/fa6bb91c-c84a-11e6-90d9-194cc39e6516.png)

**Comment by teolemon** [comment]
Not sure. @itchix, is it as simple as copy pasting the image with a white background. Wouldn't a perfect square be better ?
