### ISSUE TITLE
The environnement tab is not scrollable on some screens

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2286]
The environnement tab is not scrollable on some screens. Initially reported by @stephanegigandet

**Comment by subhanjansaha** [comment]
I want to work on this.

**Comment by teolemon** [comment]
@stephanegigandet can you still reproduce ?
https://world.openfoodfacts.org/product/3270160235322/lasagne-bolognaise-picard

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/84596695-84b80500-ae5f-11ea-8332-8aff01391cd0.png)

**Comment by kartikaysharma01** [comment]
Could not reproduce on latest develop for the given barcode.  
This can be closed. @VaiTon @teolemon
