### ISSUE TITLE
Blank bottom card in some cases

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2289]
Blank bottom card in some cases. @stephanegigandet is experiencing this. It might be a first use issue, or a network issue.

**Comment by prashantkh19** [comment]
I will look into it..

**Comment by prashantkh19** [comment]
@teolemon Which bottom card are you talking about?

**Comment by teolemon** [comment]
The scan mode card, completely blank. Haven't found a pattern yet.
@stephanegigandet can you share a barcode ?
possibly different screen densities, or network issues ?

**Comment by teolemon** [comment]
a perhaps a failed query ?

**Comment by prashantkh19** [comment]
> The scan mode card, completely blank. Haven't found a pattern yet.
> @stephanegigandet can you share a barcode ?
> possibly different screen densities, or network issues ?

yeah, sharing the barcode would be helpful to track the bug. I have tried with different products, didn't find this issue. I will go through the code once again, check if there is any unhandled exception.

**Comment by deniger** [comment]
is it fixed with https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/2297 ?

**Comment by teolemon** [comment]
yes it is @deniger , thanks :-)
