### ISSUE TITLE
Add scroll view to the "your lists" category.

### ISSUE THREAD

**Issue by mustaqmustu** [openfoodfacts/openfoodfacts-androidapp#2304]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

There is no scroll view for "Your lists" segment.Add scroll view to it.

**Steps to reproduce:** 

1.Go to menu.
2.Click on your lists.
3.see the error.

**Expected behavior:** 

Adding a scroll view will be the best.

**Observed behavior:** 
There is no scroll view.

**Device and Android version:** 
asus 3s max,OS 7.1

**Screenshots:** 

![scroll](https://user-images.githubusercontent.com/43813438/53340058-095ed700-392e-11e9-834d-ea2fb92812df.gif)

**Comment by mustaqmustu** [comment]
I want to work on this

**Comment by Karljoones** [comment]
This is not a bug, the RecyclerView implements a Scrollview, so this scrolls by default.

https://developer.android.com/reference/android/support/v7/widget/RecyclerView
