### ISSUE TITLE
Add advanced search in a Chrome Custom Tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#231]
Adding http://world.openfoodfacts.org/cgi/search.pl to a Chrome Custom Tab
Adding a hamburger menu entry with "Advanced Search"

**Comment by teolemon** [comment]
This will enable advanced search , graph generation and search on a map
![image](https://cloud.githubusercontent.com/assets/1689815/20642039/7c724a7a-b405-11e6-883a-12022a6071b5.png)
![image](https://cloud.githubusercontent.com/assets/1689815/20642044/a7fa4ada-b405-11e6-820a-979394abbee6.png)

**Comment by PrajwalM2212** [comment]
I am working on it .

**Comment by teolemon** [comment]
Ok, you may use this icon: ic_insert_chart

**Comment by teolemon** [comment]
And it it fits: "Advanced Search & Charts"

**Comment by PrajwalM2212** [comment]
@teolemon Should this be added in navigation drawer or settings ?

**Comment by teolemon** [comment]
In the Search section of the drawer.
