### ISSUE TITLE
Add icons to the various buttons on the product page to make it more lively

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2318]
- Compare product: swap_horiz
![image](https://user-images.githubusercontent.com/1689815/53490288-adae5e00-3a93-11e9-9685-172d12b93fd6.png)
- Take more photos / Send updated photo
![image](https://user-images.githubusercontent.com/1689815/53490509-231a2e80-3a94-11e9-809a-01a1737fafb1.png)

**Comment by mustaqmustu** [comment]
I want to work on this issue

**Comment by teolemon** [comment]
ok to go ahead :-)
