### ISSUE TITLE
"I'm eating this" should be removed -> replaced by "Add to list"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2321]
![image](https://user-images.githubusercontent.com/1689815/53522104-00ab0400-3ada-11e9-835d-33c1e6a441fe.png)
I expected the button to be on the summary tab in view mode, not edit mode.

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java#L789

**Comment by teolemon** [comment]
@balaji-ramavathu

**Comment by balaji-ramavathu** [comment]
Okay, I'll solve it :-)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/53697647-d60bc480-3dd3-11e9-82a9-193c154fc466.png)
Position of the button (or at the bottom of the tab)
