### ISSUE TITLE
Add dividers to some of the preferences

### ISSUE THREAD

**Issue by mustaqmustu** [openfoodfacts/openfoodfacts-androidapp#2327]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

There are no dividers for some of the segments of preferences.

**Steps to reproduce:** 

1.Go to preferences.
2.Click on any preferences which has sub categories
3.See the error.

**Expected behavior:**
Adding dividers will make it look better.

**Device and Android version:** 

Asus 3s max.OS 7.1

**screenshots
![shot1](https://user-images.githubusercontent.com/43813438/53645036-07628400-3c5e-11e9-9b5e-d76c0be9f38c.jpg)
![shot2](https://user-images.githubusercontent.com/43813438/53645051-0af60b00-3c5e-11e9-9783-2ab84a4d940f.jpg)
![shot3](https://user-images.githubusercontent.com/43813438/53645054-0df0fb80-3c5e-11e9-93cb-f52265b6820a.jpg)

**Comment by Karljoones** [comment]
This is not part of any android design guidelines. I would recommend against adding dividers into this dialog.

**Comment by mustaqmustu** [comment]
@Karljoones So can I close it.
