### ISSUE TITLE
String only partially using placeholders

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2330]
```<string name="last_editor_history">Last edit of product page on %1$s at %2$s CEST by </string>``` 
in /main/res/values/strings.xml

There's a part of the sentence which isn't using placeholders.

**Comment by teolemon** [comment]
<string name="creator_history">Product added on %1$s at %2$s CET by</string>

**Comment by teolemon** [comment]
@PrajwalM2212 
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/ContributorsFragment.java

**Comment by Abhisek2090** [comment]
I'd like to work on this.

**Comment by teolemon** [comment]
Hey @Abhisek2090 👋 
I just assigned it to you :-)
