### ISSUE TITLE
Make this string translatable (Lists)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2343]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/60c0babd25cdda44d251a295cfdbb62d2f0ca95a/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/ProductListsActivity.java#L66

**Comment by raphael0202** [comment]
Fixed in f37c937dafb3043275236f9525a413f5db28acf6
