### ISSUE TITLE
Hide newly added fields from quick addition mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2349]
![image](https://user-images.githubusercontent.com/1689815/53698205-d1e2a580-3dd9-11e9-8bd6-7a8fdab1ff5c.png)
Everything until (and including categories) is relevant. The rest below should be hidden from quick addition mode

**Comment by teolemon** [comment]
@raphael0202 related one

**Comment by raphael0202** [comment]
Fixed in 8c939d5f9d4f3c34b2594eb490a6ceed39e71a14
