### ISSUE TITLE
Traces are not translated

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2359]
This is the same taxonomy as for the Allergen field (just above in the screenshot)

![image](https://user-images.githubusercontent.com/1689815/53738446-84287480-3e8f-11e9-893a-4c86237d1ea3.png)

**Comment by deniger** [comment]
trace were not translated...
![image](https://user-images.githubusercontent.com/47569605/55320552-9c33e980-5477-11e9-9c4d-263eec43cdb3.png)
