### ISSUE TITLE
Nutrition units incorrectly managed

### ISSUE THREAD

**Issue by verdy-p** [openfoodfacts/openfoodfacts-androidapp#2374]
While entering nutrition info, it forces the input for 100g even if we indicate a portion. The conversion bet, even kilojoules and kilo calories are incorrect. Units in milligrammes for example vitamins are recorded but incorrectly displayed divided by 1000, as if they were in grams, but displayed still as milligrams...

The results is completely unreliable. Does not match the actual input. 

Notations are then incorrectly computed!!

Please fix the measurement units in the Android app!!!

**Comment by teolemon** [comment]
Thanks a lot @verdy-p 
Are you using the regular version or the beta ?

**Comment by verdy-p** [comment]
The regular Android App; this is not the beta.

Le ven. 8 mars 2019 à 15:24, Pierre Slamich <notifications@github.com> a
écrit :
