### ISSUE TITLE
Add bottom bar to the History

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2396]
![image](https://user-images.githubusercontent.com/1689815/54090583-fdcfcf00-4375-11e9-9593-f8945e7c7eb4.png)

**Comment by teolemon** [comment]
@jaindiv26 is already working on a bottom bar for home. Can you wait so that the implementation can be coherent ?

**Comment by AntonisFaros** [comment]
@teolemon Can i work on this?

**Comment by teolemon** [comment]
👌 if you can mutualize the code with what you've already done, as suggested by @deniger

**Comment by AntonisFaros** [comment]
Alright

**Comment by deniger** [comment]
It seems there is no way to mutualize the XML code for that... Let's try at least to mutualize the java part...

**Comment by jaindiv26** [comment]
Sorry, but will not be working on this.

**Comment by deniger** [comment]
![image](https://user-images.githubusercontent.com/47569605/57789243-cb0cd300-7738-11e9-88c8-e4e36d1c2170.png)

Est-ce que l'ordre a un impact ?

**Comment by huzaifaiftikhar** [comment]
@deniger Ideally the order should be same throughout the app. If this is the order which is being followed everywhere then this is good to go.

**Comment by teolemon** [comment]
See the allergen view (with 5 items, should we stick to 4 ?)

**Comment by deniger** [comment]
We can have 5 items.  I removed the history item as we are in the history view. 


---- On Wed, 15 May 2019 23:47:58 +0200 notifications@github.com wrote ----



See the allergen view (with 5 items, should we stick to 4 ?)

**Comment by teolemon** [comment]
We should keep the current item, otherwise the order becomes unpredictable

**Comment by deniger** [comment]
![image](https://user-images.githubusercontent.com/47569605/57843095-f988bd80-77cd-11e9-841f-c068b4583b56.png)
![image](https://user-images.githubusercontent.com/47569605/57843131-05747f80-77ce-11e9-8547-1f6d30129455.png)

Should I add it to the home page too ?

**Comment by teolemon** [comment]
Yup

**Comment by huzaifaiftikhar** [comment]
In scan it will hide when the bottom card will be displayed. Also the current should be highlited somehow to show that it is selected. Maybe by changing the front or icon color.

**Comment by teolemon** [comment]
I thought we could display the bottom card above it ?

**Comment by deniger** [comment]
Yes, I modified the layout for that. Let's test


---- On Thu, 16 May 2019 21:26:48 +0200 notifications@github.com wrote ----



I thought we could display the bottom card above it ?

**Comment by teolemon** [comment]
fixed by @deniger
