### ISSUE TITLE
Add bottom bar to the Allergen alert

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2397]
![image](https://user-images.githubusercontent.com/1689815/54090599-29eb5000-4376-11e9-840d-c998b7d5041c.png)

**Comment by mustaqmustu** [comment]
I want to work on this

**Comment by teolemon** [comment]
@jaindiv26 is already working on a bottom bar for home. Can you wait so that the implementation can be coherent ?

**Comment by mustaqmustu** [comment]
@teolemon Sure :)

**Comment by AntonisFaros** [comment]
@teolemon I worked on this and this is my result, any comments before creating a pull request?

![Screenshot_1557404841](https://user-images.githubusercontent.com/32640209/57453541-4d941f00-726f-11e9-9d1e-e7bfbb083ad9.png)

**Comment by teolemon** [comment]
Yup, couple of little remarks:
- color scheme (same blue as in the product view)
- Both icon and text should be visible for all icons, at all time (like in the product view)
- icons are `compare_arrows` for Compare and `playlist_add` for list addition

**Comment by AntonisFaros** [comment]
@teolemon does this look ok?
![Screenshot_1557582692](https://user-images.githubusercontent.com/32640209/57570670-35f29d00-740d-11e9-9f2f-98f5503de76f.png)

**Comment by teolemon** [comment]
@raphael0202 @stephanegigandet what do you think about it ?
@AntonisFaros I would probably take advantage to turn the circular button into an inline button on top of the allergen list with something like "+ Add an allergen"

**Comment by stephanegigandet** [comment]
Looks good! I agree with @teolemon regarding the circular + button.

**Comment by AntonisFaros** [comment]
Great ! Already fixed that  @teolemon @stephanegigandet 
![Screenshot_1557597321](https://user-images.githubusercontent.com/32640209/57573391-b75b2700-742f-11e9-9a33-47f803e0be4a.png)
