### ISSUE TITLE
Add a "Send update nutrition photo" button below nutrition image

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2400]
Add a "Send update nutrition photo" button below nutrition image

**Comment by mustaqmustu** [comment]
@teolemon If possible,can u keep a screenshot of the page where should we add the button

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/54122984-d5d87e00-43fe-11e9-9e4e-75ada13d7ed3.png)

**Comment by mustaqmustu** [comment]
can in work on this?

**Comment by teolemon** [comment]
Yes. Same model as the button in the ingredient list tab.

**Comment by mustaqmustu** [comment]
@tolemon can u allow me to work on this for some more time as I having some issues with my git branch.I have already completed the code work related to it.I will make PR as soon as I solve those git issues.

**Comment by teolemon** [comment]
👍
