### ISSUE TITLE
Show the "Products to be completed" page in a Chrome Custom Tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#241]
http://world.openfoodfacts.org/state/to-be-completed

- This shows the latest products added on Open Food Facts that need to be completed. 
- Useful for demos, for admins (monitor issues)
- Useful to get instant feedback/gratification for your contribution.

**Comment by PrajwalM2212** [comment]
I am working on it
 Should it be on the navigation drawer or settings ?
