### ISSUE TITLE
Put more emphasis on the Scores

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2410]
![image](https://user-images.githubusercontent.com/1689815/54204775-418d1a80-44d5-11e9-9400-1369980351eb.png)
Put more emphasis on the Scores, less on products details (brands and quantity)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/54204908-86b14c80-44d5-11e9-890e-8128f0f25bed.png)

**Comment by stephanegigandet** [comment]
Let's make the logos even bigger: the brand and quantity is useless, the real value is the Nutri-Score, NOVA and CO2.

![app-big-nutriscore](https://user-images.githubusercontent.com/8158668/54206468-a5fda900-44d8-11e9-97f2-5902f010a525.png)

What is the meaning / use of the button in the blue circle? It's not clear to me.
