### ISSUE TITLE
Add a large, edge to edge scan a product button ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2422]
@stephanegigandet wants a large, edge to edge `scan a product` button.

We're adding a bottom bar with a scan button as well. How can the 2 live together on the home screen ?

**Comment by stephanegigandet** [comment]
With the same icon for the 2 buttons, the large one with the text makes it clear what it is "scan a product" and what the main use of the app is. I don't think it's a problem to have 2 buttons for scanning on the home screen.

**Comment by teolemon** [comment]
@stephanegigandet managed to get one in Smoothie. Closing this one.
