### ISSUE TITLE
In expanded scan mode, infinite refresh loop

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2443]
1. Scan a product and expand
2. Drag down to refresh
3. Endless loop

![image](https://user-images.githubusercontent.com/1689815/54567913-bed4f580-49d5-11e9-80b7-c2534cb4634f.png)

**Comment by paulocoe** [comment]
I see from the app that this is still an issue. Can I work on it?

**Comment by VaiTon** [comment]
Sure @paulocoe! I'm assigning you!

**Comment by teolemon** [comment]
Can't reproduce anymore, closing. Thanks @VaiTon
