### ISSUE TITLE
Server issue seems to be causing NPEs

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2446]
![image](https://user-images.githubusercontent.com/1689815/54601571-a13c7600-4a3f-11e9-9253-0939e8183c52.png)
![image](https://user-images.githubusercontent.com/1689815/54601594-b1ecec00-4a3f-11e9-986a-cf20e90b8c59.png)

**Comment by deniger** [comment]
is it possible to have some other logs ? It's difficult to find the cause only with the current info :)

**Comment by teolemon** [comment]
I'm closing this one. I tend to open bugs too easily :-)
