### ISSUE TITLE
Labels are missing in the Product View

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#245]
Labels and their associated logos, such as Bio, AB, AOC… are missing

**Comment by teolemon** [comment]
The Place to look at is summary. 
https://github.com/openfoodfacts/OpenFoodFacts-androidApp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/SummaryProductFragment.java

**Comment by herau** [comment]
@teolemon I don't find any information about the link of label images.

I see example like:

- http://static.openfoodfacts.org/images/lang/fr/labels/bio-europeen.135x90.png
- http://static.openfoodfacts.org/images/lang/fr/labels/ab-agriculture-biologique.74x90.svg

But i don't know if there is a standard way to fetch labels images.

I guess we have also to fetch all the labels names (with `http://world.openfoodfacts.org/labels.json`).

**Comment by herau** [comment]
The label API doesn't contains links between labels, like in the website http://fr.openfoodfacts.org/label/bio-europeen

**Comment by teolemon** [comment]
filed: https://github.com/openfoodfacts/openfoodfacts-server/issues/559

**Comment by teolemon** [comment]
filed at https://github.com/openfoodfacts/openfoodfacts-server/issues/560

**Comment by teolemon** [comment]
Good news, the labels images are now available : 
https://world.openfoodfacts.org/labels.json
