### ISSUE TITLE
Show both NOVA and Nutri-Score in the various product lists

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2458]
Show both NOVA and Nutri-Score in the various product lists, with the official logos instead of the rounded version we currently show for the Nutri-Score.
This will harmonize the display with the iPhone version that currently has the behaviour, and will be useful for people who care about food processing.

![image](https://user-images.githubusercontent.com/1689815/54881571-9889dc80-4e51-11e9-8475-2060a8953372.png)

I think we should do that:

search results
scan history
products lists
facets (when you click on the value from a product page)

**Comment by mustaqmustu** [comment]
@teolemon nutri score should be added in product search results or my lists?

**Comment by deniger** [comment]
I have made a PR to refactor the way the nutriscore image is obtained.
It will be better for me if the PR is validated before this issue ;)
@teolemon your want to replace the small image (only the letter) by the big one?

**Comment by teolemon** [comment]
@deniger @mustaqmustu I think we should do that:
- search results
- scan history
- products lists
- facets (when you click on the value from a product page)

**Comment by teolemon** [comment]
Postponing this to a future release

**Comment by teolemon** [comment]
This one is mostly fixed. Thanks @VaiTon :-)
