### ISSUE TITLE
Add link to show more info about traffic lights (high, low, average)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#247]
http://fr.openfoodfacts.org/reperes-nutritionnels

**Comment by aleksejrs** [comment]
That link is French-only?  Though it contains a link to a PDF file in English.

**Comment by teolemon** [comment]
fair point: http://world.openfoodfacts.org/nutrient-levels

It has not been translated to other languages, and it gives a 404. Bug to file against Product Opener.

**Comment by herau** [comment]
where do you want to show this link ? Nutrition tab or Advanced Nutrition tab ?

**Comment by teolemon** [comment]
we show the nutrition lights in the nutrition tab, so the reference should be right next to it.
I remember that you wanted to put the nutriscore in a more visible position (eg summary). If so, then there.

**Comment by balaji-ramavathu** [comment]
Can I work on this issue ?
