### ISSUE TITLE
Tap on export list notification has no effect

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/openfoodfacts-androidapp#2479]
**Summary:** 

Tapping on the notification displayed after export doesn't show the exported file, the user need to use the file explorer to locate the file.

The notification won't go away either...

**Steps to reproduce:** 

Export any list then, tap on the notification

**Expected behavior:** 

- Tap on the notification display the exported file on the file explorer
- After tap, the notification is no longer displayed

**Observed behavior:** 

None of the above

**Device and Android version:** 
Samsung SM-G361F
Android 5.1.1

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by kartikaysharma01** [comment]
@VaiTon @teolemon This can be closed.
