### ISSUE TITLE
the scanner does not scan properly when I use the APK on windows

### ISSUE THREAD

**Issue by karimfares1131** [openfoodfacts/openfoodfacts-androidapp#2480]
when I am using the apk on bluestacks for windows, although the application is working fine, when I scan the barcode using the webcam nothing happens.

**Comment by teolemon** [comment]
Bluestack is a specific emulator. Does the camera otherwise work for you ?
Can you get a trace ?

**Comment by karimfares1131** [comment]
![image](https://user-images.githubusercontent.com/34647711/55280371-1b64d880-5325-11e9-91b2-d46e1235c8f6.png)

**Comment by karimfares1131** [comment]
the camera works but it does not detect the barcode.

**Comment by teolemon** [comment]
It's probably because there's no autofocus/too low resolution on your laptop.
The workaround is to type the barcode. We could create a machine learning based barcode scanner, but this is a huge endeavour currently beyond our scope.
