### ISSUE TITLE
We display categories in French when the app is in Portuguese

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2483]
![image](https://user-images.githubusercontent.com/1689815/55089916-8062c900-50ae-11e9-9c6e-82639fca572d.png)

It doesn't seem to be a server side issue, since we have the translation:
https://pt.openfoodfacts.org/aditivo/e300-acido-ascorbico

**Comment by deniger** [comment]
I tried with Sumol Maracujá and it seems ok: 
![image](https://user-images.githubusercontent.com/47569605/55148633-dedc8580-5148-11e9-8e3e-c07c427db46f.png)
The additives are loaded when you change the language in the preferences and a bug could be that the portugese file can't be loaded. 
In the log file, did you have an error like ""Unable to import additives from ..." ?

**Comment by teolemon** [comment]
I think the app needs restarting for some of the fields.

**Comment by teolemon** [comment]
Plus some of the features are checking system locale instead of app locale `Locale.getDefault().getLanguage()`

**Comment by deniger** [comment]
In fact, we should never use `Locale.getDefault().getLanguage()`?

**Comment by deniger** [comment]
@teolemon will do a global find and replace (manual) Locale.getDefault().getLanguage() should be replaced by the language set in appli preferences. Ok ?
