### ISSUE TITLE
Weird photo when no nutrition data

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#249]
![screenshot_20161115-130508](https://cloud.githubusercontent.com/assets/1689815/20306078/f3811982-ab38-11e6-8aef-ae69558f7838.png)

**Comment by naofum** [comment]
This image is drawable-hdpi/error_image.png.
![error_image](https://cloud.githubusercontent.com/assets/8462938/20860195/bf31cd3a-b9b5-11e6-88b5-6a8a2bae4e1b.png)
Change to another image? for example, ic_action.png
![ic_action](https://cloud.githubusercontent.com/assets/8462938/20860207/ffbf6812-b9b5-11e6-84e0-f10f74d6ccc6.png)

**Comment by teolemon** [comment]
If the product explicitly has no nutrition data, I wouldn't put any image at all.
Otherwise, a button to send a nutrition photo ? "Add nutrition photo"

**Comment by teolemon** [comment]
thanks @naofum
