### ISSUE TITLE
Clean method MainActivity#detectBarCodeInImage

### ISSUE THREAD

**Issue by deniger** [openfoodfacts/openfoodfacts-androidapp#2493]
- inputStream is opened but not closed. Suggestion, use the auto-close approach:
` try(InputStream imageStream=getContentResolver().openInputStream(uri)){....`
 
- Replace ` e.printStackTrace();` by Log.w(....,e)

**Comment by tomdaly** [comment]
Thought I'd fix this while as I was already working on #2444, PR incoming
