### ISSUE TITLE
The strings are sometimes displayed with missing characters

### ISSUE THREAD

**Issue by karimfares1131** [openfoodfacts/openfoodfacts-androidapp#2501]
![tas1](https://user-images.githubusercontent.com/34647711/55276761-9a431c80-52f7-11e9-9b98-3520936cfd69.png)

**Comment by teolemon** [comment]
Do you have a bit more context ?
- Android version
- App version (does it still happen in master ? F-Droid or Play Store)
- Custom theme ?
- device language ? Open Food Facts language ?

**Comment by karimfares1131** [comment]
I am using the APK 
 BlueStacks on windows

**Comment by teolemon** [comment]
Closing as it is most probably a bluestacks issue
