### ISSUE TITLE
It would be good to add a feature to import images not only taking photos.

### ISSUE THREAD

**Issue by karimfares1131** [openfoodfacts/openfoodfacts-androidapp#2502]
![tas2](https://user-images.githubusercontent.com/34647711/55276874-4df8dc00-52f9-11e9-88d9-b78d394bd15d.png)

**Comment by teolemon** [comment]
You can share images from your photoroll to Open Food Facts by using "Share to Open Food Facts"

**Comment by karimfares1131** [comment]
It is about sharing images in general I am just proposing to add shortcut.
example of Issue: when I was adding a new product to the database I didn't have a good camera, but I had good photos on my machine and did not have the opportunity to use them directly.

**Comment by stephanegigandet** [comment]
On your machine? Not a phone you mean? With a computer, you can upload images more easily using the web site : https://world.openfoodfacts.org

**Comment by karimfares1131** [comment]
Actually, I am using the APK on an emulator "bluestacks"!

**Comment by teolemon** [comment]
fixed in the latest version, for product with existing images.
