### ISSUE TITLE
Bad layout in product view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#251]
At the bottom 
![screenshot_20161115-132739](https://cloud.githubusercontent.com/assets/1689815/20306265/aaa3b372-ab39-11e6-8019-0a842d631903.png)

**Comment by herau** [comment]
@teolemon come from 4e38d40471383d95d011f89e9d831efd9526f3bd

I guess i can remove the linearLayout ? don't really understand the benefit of using it

**Comment by teolemon** [comment]
I guess so. @itchix, any reasons for using it ?

**Comment by teolemon** [comment]
Still seems like an issue

**Comment by herau** [comment]
@teolemon i also fix an issue when no ingredients image (by removing the image container if no image data)
