### ISSUE TITLE
Add link to official product website if present

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#253]

**Comment by herau** [comment]
@teolemon 
in the website, the information is displayed like this: 

`Link to the product page on the official site of the producer: http://www.ferrero.fr/nutella`

Maybe find another way to display the link in the android app?

**Comment by teolemon** [comment]
Perhaps a globe button with Producer website ?

**Comment by teolemon** [comment]
```🔗  Product page on the official site of the producer```

**Comment by huzaifaiftikhar** [comment]
@teolemon @herau I guess we can close this now :slightly_smiling_face:

**Comment by teolemon** [comment]
Thanks @huzaifaiftikhar
