### ISSUE TITLE
Nutri-Score is broken on the scan card.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2530]
![image](https://user-images.githubusercontent.com/1689815/55685920-a49a9180-595b-11e9-8711-625ceffa2dac.png)
![image](https://user-images.githubusercontent.com/1689815/55685922-a9f7dc00-595b-11e9-972f-e4efe4aa91fe.png)

**Comment by teolemon** [comment]
https://barcode.tec-it.com/en/EAN13?data=3350033032361

**Comment by teolemon** [comment]
@deniger could it be related to Nutri-Score display refactoring ?

**Comment by deniger** [comment]
Yes it could ...I will have a look tomorrow


---- On Sun, 07 Apr 2019 21:41:35 +0200 notifications@github.com wrote ----



@deniger could it be related to Nutri-Score display refactoring ?

**Comment by teolemon** [comment]
Fixed by @deniger in a8e2de0c2a49159341b1cc333429fa9648b7edf2
