### ISSUE TITLE
Replace "Open Beauty Facts" by "Install Open Beauty Facts" when not installed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2533]
Replace "Open Beauty Facts" by "Install Open Beauty Facts" when not installed.
We need that to be compliant with app-stores policies.

![20190804_120048_PDT](https://user-images.githubusercontent.com/1689815/55750327-56f95400-5a43-11e9-9cf8-825409eaf9b4.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/55750430-9031c400-5a43-11e9-8fb8-37fadfd2b4be.png)

**Comment by Jantzilla** [comment]
If it's alright, I would like to be assigned this issue.
