### ISSUE TITLE
Crash when scanning

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/openfoodfacts-androidapp#2551]
[logcat.txt.](https://github.com/openfoodfacts/openfoodfacts-androidapp/files/3067390/logcat.txt)

**Summary:** 

Tried with 3 different products, crash with all 3
Tried with the same version on a  Samsung SM-G361F ( Android 5.1.1 ) --> doesn't crash

Same apparent behavior (crash) with the previous beta version 3.0.7 ( sorry no traces )

**Device and Android version:** 

Samsung GT-I9195
Android 4.2.2

**Comment by teolemon** [comment]
Did you try with 3.0.8 that I pushed yesterday evening ?

**Comment by serpico** [comment]
Yeah, sorry I wasn't clear enough, the bug report is for for version 3.0.8 ( with traces) just updated this morning. 
What I meant was, the behavior looked the same ( straight crash when scanning but no traces ) yesterday with 3.0.7.
Thanks

**Comment by teolemon** [comment]
Do you have the barcodes by any chance ?

**Comment by serpico** [comment]
@teolemon I can give you the numbers?

3450970006767 https://world-fr.openfoodfacts.org/produit/3450970006767  works with both the searchbar on the website ( typed and looked up "RIZ LONG ECO+" or the barcode number ) or through scanning from the app 3.0.8 but on the Samsung SM-G361F ( Android 5.1.1 )

3450970001144 https://fr.openfoodfacts.org/produit/3450970001144/tomates-entieres-pelees-au-jus-eco ( works with both the searchbar on the website ( typed and looked up "tomates entières éco+" or the barcode number) and or through scanning from the app 3.0.8 on the Samsung SM-G361F ( Android 5.1.1 ) 

3760133730058 https://fr.openfoodfacts.org/produit/3760133730058/10-oeufs-frais
( works with both the searchbar ( typed and looked up the barcode number ) on the website and the app 3.0.8 on the Samsung SM-G361F ( Android 5.1.1 )

**Comment by teolemon** [comment]
```  D/PowerManagerService(  761): setKeyboardVisibility: false
E/AndroidRuntime(11290): FATAL EXCEPTION: main
E/AndroidRuntime(11290): java.lang.NoSuchMethodError: android.support.v4.view.ViewPager.setNestedScrollingEnabled
E/AndroidRuntime(11290): 	at openfoodfacts.github.scrachx.openfood.views.product.ProductFragment.a(Unknown Source)
E/AndroidRuntime(11290): 	at android.support.v4.app.j.b(Unknown Source)
E/AndroidRuntime(11290): 	at android.support.v4.app.p.a(Unknown Source)
E/AndroidRuntime(11290): 	at android.support.v4.app.p.e(Unknown Source)
E/AndroidRuntime(11290): 	at android.support.v4.app.p.a(Unknown Source)
E/AndroidRuntime(11290): 	at android.support.v4.app.d.g(Unknown Source)
E/AndroidRuntime(11290): 	at android.support.v4.app.p.b(Unknown Source)
E/AndroidRuntime(11290): 	at android.support.v4.app.p.a(Unknown Source)
E/AndroidRuntime(11290): 	at android.support.v4.app.p.b(Unknown Source)
E/AndroidRuntime(11290): 	at android.support.v4.app.p.g(Unknown Source)
E/AndroidRuntime(11290): 	at android.support.v4.app.p$1.run(Unknown Source)
E/AndroidRuntime(11290): 	at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime(11290): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(11290): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(11290): 	at android.app.ActivityThread.main(ActivityThread.java:5306)
E/AndroidRuntime(11290): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(11290): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(11290): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
E/AndroidRuntime(11290): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
E/AndroidRuntime(11290): 	at dalvik.system.NativeStart.main(Native Method)
W/ContextImpl(  761): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1346 com.android.server.am.ActivityStack.startPausingLocked:1398 com.android.server.am.ActivityStack.finishActivityLocked:5869 com.android.server.am.ActivityStack.finishActivityLocked:5783 com.android.server.am.ActivityManagerService.handleAppCrashLocked:9539 
D/STATUSBAR-NetworkController( 1102): onSignalS  ```

**Comment by deniger** [comment]
feedback from @teolemon:

`Android 4.4 (API level 20) and lower doesn't support vector drawables. If your minimum API level is set at one of these API levels, you have two options when using Vector Asset Studio: generate Portable Network Graphic (PNG) files (the default) or use the Support Library.`

some raster images are missing:

- ic_add_a_photo_blue_18dp
- ic_add_box_blue_18dp
- ic_add_a_photo_black_18dp
- ic_add_a_photo_black_48dp
- bg_edittext_til (?)
- bg_edittext (?)
- ic_help_outline_orange_24dp

**Comment by teolemon** [comment]
https://developer.android.com/studio/write/vector-asset-studio

**Comment by teolemon** [comment]
yes but:
``` 
We are also excited to offer backwards compatibility for your vector assets in Android Studio 1.4. Once you have a vectorDrawable image in your res/drawable, the Gradle plugin will automatically generate raster PNG images for API level 20 and below during build time. This means you only need to update and maintain your vector asset for your app project and Android Studio can take care of image conversion process.
```

**Comment by deniger** [comment]
Ok :) on my env, it seems these PNG were not generated


---- On Tue, 23 Apr 2019 18:19:08 +0200 notifications@github.com wrote ----



yes but:

We are also excited to offer backwards compatibility for your vector assets in Android Studio 1.4. Once you have a vectorDrawable image in your res/drawable, the Gradle plugin will automatically generate raster PNG images for API level 20 and below during build time. This means you only need to update and maintain your vector asset for your app project and Android Studio can take care of image conversion process.

**Comment by serpico** [comment]
Since update to version 3.1.2 (automatically updated by Play Store)
Samsung GT-I9195
Android 4.2.2

[logcat.txt.](https://github.com/openfoodfacts/openfoodfacts-androidapp/files/3129826/logcat.txt)

It can load the "card" at the bottom ( see screenshot ), not completely ( see the loading sign instead of a thumbnail ) then crash right after.
![Screenshot_2019-04-30-04-42-59](https://user-images.githubusercontent.com/1227077/56939046-34200400-6b06-11e9-9015-6bf5cabf3e4e.png)

Same behavior when instead of scanning I go to the drawer > History then tap on any product in the history, freeze for about 6-7 seconds and crash

**Comment by teolemon** [comment]
```
E/AndroidRuntime( 3344): FATAL EXCEPTION: main
E/AndroidRuntime( 3344): android.view.InflateException: Binary XML file line #277: Error inflating class Button
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:710)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 3344): 	at openfoodfacts.github.scrachx.openfood.fragments.b.a(Unknown Source)
E/AndroidRuntime( 3344): 	at openfoodfacts.github.scrachx.openfood.views.product.summary.SummaryProductFragment.a(Unknown Source)
E/AndroidRuntime( 3344): 	at android.support.v4.app.j.b(Unknown Source)
```

**Comment by deniger** [comment]
I encountered this issue on a emulator with Android 4. I didn't find a solution to fix it: it seems it's an issue with scalar assets that are not supported by Android 4.?

Normally there is a workaround for this and it seems it's applied on OFF but no...


---- On Tue, 30 Apr 2019 09:48:21 +0200 notifications@github.com wrote ----


E/AndroidRuntime( 3344): FATAL EXCEPTION: main
E/AndroidRuntime( 3344): android.view.InflateException: Binary XML file line #277: Error inflating class Button
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:710)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
E/AndroidRuntime( 3344): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 3344): 	at openfoodfacts.github.scrachx.openfood.fragments.b.a(Unknown Source)
E/AndroidRuntime( 3344): 	at openfoodfacts.github.scrachx.openfood.views.product.summary.SummaryProductFragment.a(Unknown Source)
E/AndroidRuntime( 3344): 	at android.support.v4.app.j.b(Unknown Source)

**Comment by serpico** [comment]
@deniger no worries, it's nice enough of you to have looked into it and tried the PR to solve it.
@teolemon out of curiosity, what's the breakdown of users still using the app with Android 4. ?

**Comment by teolemon** [comment]
@deniger https://stackoverflow.com/questions/47366882/resourcesnotfoundexception-android-4-4

**Comment by deniger** [comment]
I tried to use srcCompat.. but the library androidx... has some weird impact
So I set drawable via java methods -> ok

I'm able to launch OFF on Android 4.2 and edit a product

**Comment by teolemon** [comment]
Did we introduce AndroidX already in the project ??
