### ISSUE TITLE
Cities where bought is in fact the city associated with the packager code

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#256]
**ISSUE:**"`Cities where bought:`" displays the city where the product was packaged.`Amiens`
**SOLUTION:** It should display "`Packager code :` " with the Raw value of the packager code (`FR 45.533.33 CE` or `EMB 54365`) and then the city name currently displayed.
**Example:**`FR 45.533.33 CE - Amiens`

"`Country where sold:`" actually contains the city AFAIK ("`City, state and country where purchased`" in the web version)

**Comment by teolemon** [comment]
Priority bug since it's currently misleading the user.

**Comment by teolemon** [comment]
We are currently giving false information. Turning into a very high impact bug as a result.

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/product/3270190025658/tarama-au-saumon-carrefour

**Comment by teolemon** [comment]
Bonus points if you make the packager code and city clickable:
https://world.openfoodfacts.org/packager-code/fr-45-093-006-ec (has a nice map of the factory and the other products made in the same factory)
https://world.openfoodfacts.org/city/chevilly-loiret-france

**Comment by huzaifaiftikhar** [comment]
@teolemon May I try this?

**Comment by teolemon** [comment]
you can go ahead.
Relevant API parts:
-https://en.wiki.openfoodfacts.org/API#Packager_codes
