### ISSUE TITLE
Nutrition tab: calories always zero

### ISSUE THREAD

**Issue by Flint4** [openfoodfacts/openfoodfacts-androidapp#2562]
In nutrition tab, calories are always shown as zero on my device. All products affected. "Preferred energy unit" is set to kcal in the settings. Language English, same issue in German. 

OFF Android App 3.0.8
LG G7 ThinQ, Android 8.0.0. Stock ROM. 

![Screenshot_2019-04-22-18-04-35(1)_1280x720](https://user-images.githubusercontent.com/9900799/56510633-a4d58800-652a-11e9-8ada-b9713957b153.png)

**Comment by teolemon** [comment]
Hey, can you provide the barcode you're scanning ?
