### ISSUE TITLE
Product Edit: Nutrition Facts radio buttons unselected

### ISSUE THREAD

**Issue by Flint4** [openfoodfacts/openfoodfacts-androidapp#2563]
In the Edit mode at Nutrition Facts, both radio buttons "For 100g / 100ml" and "Per serving" look like unselected when editing an already existing product. In the screenshot below (EAN 5060108450508), the "For 100g / 100ml" radio button should be active. All products affected. 

OFF Android App 3.0.8
LG G7 ThinQ, Android 8.0.0. Stock ROM.

![2019-04-22 20_59_11-Screenshot_2019-04-22-20-56-58](https://user-images.githubusercontent.com/9900799/56520011-afe8e200-6543-11e9-8c4a-be6a193fe598.jpg)

**Comment by deniger** [comment]
solution found here:
https://stackoverflow.com/questions/46516506/android-nougat-why-do-checkboxes-on-fragment-have-incomplete-state-when-selecte
