### ISSUE TITLE
Display the carbon footprint when available

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#257]
eg: 3700214610466
http://world.openfoodfacts.org/product/3700214610466/pate-a-tartiner-bio-perou-alter-eco

**Comment by herau** [comment]
@teolemon where do you want to display this information (in which fragment - summary, ingredients, nutrition ..)?

**Comment by teolemon** [comment]
The Place to look at is summary. 
https://github.com/openfoodfacts/OpenFoodFacts-androidApp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/SummaryProductFragment.java

**Comment by herau** [comment]
@teolemon what do you think about that ?
![](https://dl2.pushbulletusercontent.com/j26sONemswWsb5C62mDFhOF4i2W01VPO/Screenshot_20161223-142444.png)

**Comment by herau** [comment]
@teolemon i just add a space before the carbon value

**Comment by teolemon** [comment]
superb. It's not like we'll have a lot of products with it. perhaps below the salt thing (nutrition related first, then other stuff ?)

**Comment by herau** [comment]
@teolemon currently is quite difficult to add view after the list view (which contains the nutrition facts). 
The carbon text view is not visible if no data exist for the product
or you ok with that ?

**Comment by teolemon** [comment]
yes, let's keep it above then.
if no info: invisible.
