### ISSUE TITLE
Trying to add a nutrition image on an existing product crashes the camera

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2583]
Trying to add a nutrition image on an existing product crashes the camera on my Google Pixel on Android Q (Preview 2)
It works fine for front and ingredients though

**Comment by teolemon** [comment]
I can't reproduce

**Comment by deniger** [comment]
impossible to install Android Q on my env :(
We should use 3.5 Preview:

- https://developer.android.com/preview/setup-sdk
- https://stackoverflow.com/questions/55598318/cant-get-emulator-x86-images-for-android-q-says-unable-to-resolve-dependencie

**Comment by teolemon** [comment]
I'm not even able to reproduce here, so i'd be tempted to let slip

**Comment by ripetrescu** [comment]
@teolemon just checked on my Pixel 2 with Android Q Beta (the latest one) and everything works as expected (no crashes) :)

**Comment by teolemon** [comment]
closing this one since I haven't had a bug in a while
