### ISSUE TITLE
Change the general color scheme to match the web version

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#259]
The web version of Open Food Facts uses grey (#EFEFEF for the topbar and #fafafa for the sidebar)

We should move to those colors to match the website (and the previous versions).

**Comment by herau** [comment]
maybe choose the color with a material design palette ?

**Comment by teolemon** [comment]
https://material.google.com/style/color.html#color-color-palette
We're more looking at the same light gray as shown on the website (300 and 400 ?)
