### ISSUE TITLE
64-bits compliance

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2598]
![image](https://user-images.githubusercontent.com/1689815/57083941-a147bb00-6cf9-11e9-83ac-3d72b8af5355.png)

**Comment by deniger** [comment]
https://developer.android.com/distribute/best-practices/develop/64-bit
// Your app's build.gradle
apply plugin: 'com.android.app'

android {
   compileSdkVersion 27
   defaultConfig {
       appId "com.google.example.64bit"
       minSdkVersion 15
       targetSdkVersion 28
       versionCode 1
       versionName "1.0"
       ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'

**Comment by teolemon** [comment]
fixed.
