### ISSUE TITLE
Display additives as a structured list

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#260]
Display additives as a structured list, with their full name

![screenshot_20161115-145016](https://cloud.githubusercontent.com/assets/1689815/20308358/c8f5281a-ab43-11e6-868b-64f30ef6ae63.png)

**Comment by sowmya9029** [comment]
![device-2018-02-20-133501](https://user-images.githubusercontent.com/11407233/36454314-366fb162-1650-11e8-8004-a6c4affa7bd0.png)
Is this what you are expecting?
