### ISSUE TITLE
OBF Android app 3.1.2 crashes when swiping to ingredients #73

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2604]
OBF Android app 3.1.2 crashes when swiping to ingredients #73

**Comment by deniger** [comment]
Do you have info about Android version and or the product code ?

**Comment by VaiTon** [comment]
Is this still an issue?

**Comment by teolemon** [comment]
no it's not. I'm closing the issue.
