### ISSUE TITLE
Load the brand taxonomy to offer brand suggestions

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2626]
Load the brand taxonomy to offer brand suggestions
https://static.openfoodfacts.org/data/taxonomies/brands.json

**Comment by teolemon** [comment]
Now also available for OBF: https://static.openbeautyfacts.org/data/taxonomies/brands.json

**Comment by teolemon** [comment]
Now really available for OBF (there was a build error)

**Comment by kartikaysharma01** [comment]
Can you please assign this to me
