### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#2627]
**Log**
```
...
...
...
Waiting for emulator to start
Waiting for emulator to start
Waiting for emulator to start
Timeout (360 seconds) reached; failed to start emulator
The command "android-wait-for-emulator" failed and exited with 1 during .
```

**Comment by deniger** [comment]
if someone could find a solution here :) I gave up...

**Comment by deniger** [comment]
Should be ok now: 
https://travis-ci.org/openfoodfacts/openfoodfacts-androidapp/builds/535168851

I copy the configuration from 
https://github.com/ankidroid/Anki-Android/blob/master/.travis.yml

**Comment by teolemon** [comment]
🎊
