### ISSUE TITLE
Don't return a result if the scanned barcode matches the server-side blacklist

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2629]
The barcode scanner will return invalid barcodes due to bright reflexions, poor lighting, etc…While those barcodes are theoretically valid EAN-8 barcodes, they are not attributed. We are thus putting in place a server side blacklist of common invalid barcodes, so that the app doesn't return a prompt to add a blacklisted product, or return a result for an invalid product once someone has created it.

https://world.openfoodfacts.org/data/invalid-barcodes.json

The wished behaviour is to do as it nothing had been scanned (and also probably to not send the query.)

**Comment by teolemon** [comment]
``` 
15600703    2704
16130357    1398
16256866    1300
13297703    1034
10836813    687
323673    816
12562213    386
2575405    418
10232903    391
16256163    347
10576403    318
total    9799
```

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/data/invalid-barcodes.json

**Comment by huzaifaiftikhar** [comment]
@teolemon Is the invalid barcodes json is only for OFF right now at the backend? We can have this check only when the build flavor is OFF in that case.

**Comment by teolemon** [comment]
(iOS equivalent bug: https://github.com/openfoodfacts/openfoodfacts-ios/issues/304)
