### ISSUE TITLE
Add option to disable image loading

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#264]
![image](https://cloud.githubusercontent.com/assets/1689815/22603449/c30144e6-ea47-11e6-8bc9-a0571dace312.png)
On slow or metered connexions, downloading product images can eat data (Countries where unlimited data costs a lot).

Add options in settings 
- "Don't load product images"
- "Don't load product images if not on WiFi"

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/24750849/ac13c668-1ac7-11e7-987e-bf0d59d94b7b.png)
Twitter has a smart way to do this

**Comment by PrajwalM2212** [comment]
Working on it

**Comment by Karljoones** [comment]
Feature was added
