### ISSUE TITLE
[Bottom Bar] Some devices don't show the labels below the icons

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2668]
![image](https://user-images.githubusercontent.com/1689815/58433406-7877d300-80b7-11e9-9030-9c6fefc76267.png)

**Comment by vanshikaarora** [comment]
Hey @teolemon I would like to work on this issue:)

**Comment by vanshikaarora** [comment]
Hey @teolemon I would like to work on this issue:)

**Comment by vanshikaarora** [comment]
@teolemon Can you please tell which emulator are you using?

**Comment by vanshikaarora** [comment]
@teolemon Can you please tell which emulator are you using?

**Comment by teolemon** [comment]
obsolete
