### ISSUE TITLE
I should not have to wait for the product to upload (esp. when I have no or little network)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2677]
![image](https://user-images.githubusercontent.com/1689815/58473263-6eea7b80-8148-11e9-85f8-db614fe81ea6.png)

**Comment by teolemon** [comment]
It should save the product immediately, attempt to upload it in the background, and notify me if there are any conflicts to solve

**Comment by vanshikaarora** [comment]
@teolemon in this issue shouldn't we detect if there is no network and display a dialog "no network detected. Try re-connecting your network" ?

**Comment by teolemon** [comment]
No. It's annoying. We should save to the local database, display a success in the UI, and then try to upload.

**Comment by teolemon** [comment]
will be fixed by @philippeauriach in #3072
