### ISSUE TITLE
handle signin and signout correctly

### ISSUE THREAD

**Issue by herau** [openfoodfacts/OpenFoodFacts-androidApp#268]
Update correctly the menu when the user sign in. 
Switch the action menu from "sign in" to "logout".

**Comment by teolemon** [comment]
Perhaps hide the login link in the main menu when logged in and make logout appear in the collapsible menu.
Also, I think my contributions should be in the main menu. Otherwise it's not discoverable (I thought it had not been merged, and then I discovered it by chance).

**Comment by herau** [comment]
@teolemon 
in the menu, i can even disable the link or remove it (and add it after new login). What do you prefer ?
Same question for the contribution link

**Comment by teolemon** [comment]
Remove it and replace it by Logout (and vice versa ?)

**Comment by herau** [comment]
ok and what about the contribution link ? default not displayed and add it after login ?

**Comment by teolemon** [comment]
Or default displayed, and a nag to create an account ?
