### ISSUE TITLE
'equals()' between objects of two inconvertible types

### ISSUE THREAD

**Issue by RajaVamsi11** [openfoodfacts/openfoodfacts-androidapp#2687]
**Summary**

Presently, in the project, there is `.equals()` method between the target and arguments which are of incompatible types i.e... between String and CustomValidatingEditTextView. While such a call might theoretically be useful, most likely it represents a bug.

These types of inconvertible types between two objects must be resolved.

**Comment by deniger** [comment]
solved in a previous PR
