### ISSUE TITLE
New guided mode for new products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#269]

**Comment by teolemon** [comment]
![1](https://cloud.githubusercontent.com/assets/1689815/20456697/c176babe-ae7b-11e6-8f8d-0fef96b8f0e0.png)
![2](https://cloud.githubusercontent.com/assets/1689815/20456698/c17dc44e-ae7b-11e6-8200-250e281f8e27.png)
![3](https://cloud.githubusercontent.com/assets/1689815/20456699/c187a702-ae7b-11e6-94c3-ef7c3a8c2a62.png)

**Comment by herau** [comment]
the 'done' button should only appears when the photo has been taken.

**Comment by teolemon** [comment]
or from gray to blue ?

**Comment by teolemon** [comment]
Also, the 3 bottom buttons on the 1st one are mistakes

**Comment by herau** [comment]
maybe also a mark icon instead of `done` / `Ingredients` / `Nutrition` / `Done`

**Comment by teolemon** [comment]
Auto mode that would give you 10 seconds at each time to put the product correctly for front, ingredients and nutrition, and then take a photo. It would overlay instruction in the view finder.
![image](https://cloud.githubusercontent.com/assets/1689815/21746075/015d1ec2-d53a-11e6-8ca6-56d5f60a7be3.png)

**Comment by asmoth360** [comment]
@teolemon I don't like the idea of an picture taken automatically every 10s... When I take pictures I try to place the product and my camera well and often I take the pic again because it was not straight, blurred, had reflects or whatever... Taking photos automatically would be horrible, in my opinion...

**Comment by teolemon** [comment]
@asmoth360 Have you received the new update by the way ? Care to discuss it ?

**Comment by asmoth360** [comment]
@teolemon Yes, big update as I can see. A lot a good things but I'll probably open some issues too :)

**Comment by herau** [comment]
@teolemon your first mockup is good. maybe implement it with the MD Steppers.
