### ISSUE TITLE
Stuck on a loop in edit mode in trunk

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2693]
1. crop an image
2. Type on backspace to exit
![image](https://user-images.githubusercontent.com/1689815/58663900-c1d15800-832d-11e9-954c-839cd92811de.png)
3. Error: 
![image](https://user-images.githubusercontent.com/1689815/58663928-d7468200-832d-11e9-8fd6-0cc847a11dc5.png)
4. You can't escape. You're stuck in edit mode Foreveeeer !

**Comment by teolemon** [comment]
@deniger I think we won't escape server side cropping.

**Comment by deniger** [comment]
You can't escape if you try to save your changes with the too small image, correct ?
In this case the user should discard his changes or take a new photo.

Another solution could be to check the image before the user click on crop and reject the modification...

**Comment by deniger** [comment]
What is the minimum allowed size  of the image ?

**Comment by teolemon** [comment]
old. closing until someone complains again.
