### ISSUE TITLE
Never ask whether to add the product when coming from history

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2694]
Never ask whether to add the product when coming from history (or search results by the way)

![image](https://user-images.githubusercontent.com/1689815/58663998-052bc680-832e-11e9-929f-da9c97c2cf94.png)

This happens when there's no or little network. The app wants to be helpful. It would make sense if we had a local list of existing products like implemented in the offline PR

**Comment by deniger** [comment]
should be fixed with https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2705
If the exception is a IOException, just display a message
