### ISSUE TITLE
The green co2 label is displayed for a product without ingredients. TO BE CLOSED

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2695]
![image](https://user-images.githubusercontent.com/1689815/58664114-4de37f80-832e-11e9-815a-949391ad81f8.png)
![image](https://user-images.githubusercontent.com/1689815/58664130-5340ca00-832e-11e9-8216-d6b2eb7130b7.png)

**Comment by vanshikaarora** [comment]
Hey @teolemon I would like to work on this issue can you please help. Is there any object containing ingredient information in the SummaryProductFragment

**Comment by deniger** [comment]
Same issue in the PR: https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2666

Product code: 20211394

**Comment by deniger** [comment]
@teolemon:

https://world.openfoodfacts.org/api/v0/product/20211394.json?fields=environment_impact_level_tags

The field environment_impact_level_tags is equals to en:low. Is it normal ?

**Comment by deniger** [comment]
It's a server issue...

**Comment by VaiTon** [comment]
Can we close this?

**Comment by deniger** [comment]
Yes


---- On Mon, 10 Jun 2019 21:42:21 +0200 notifications@github.com wrote ----



Can we close this?

**Comment by teolemon** [comment]
Fixed server side. Closing
