### ISSUE TITLE
In case of no internet connection tapping on any product in History shoukd display a proper error message

### ISSUE THREAD

**Issue by vanshikaarora** [openfoodfacts/openfoodfacts-androidapp#2696]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 
Currently tapping on any item in history, takes to the product activity Except in offline mode when nothing happens due to tapping the item. It should show a proper dialog message of no internet connection.

**Steps to reproduce:** 
- Go to History
- Switch off the internet connection
- Tap on any item

**Expected behavior:** 

A popup should appear that there is no internet connection

**Device and Android version:** 
vivo 1713 Android version 7.0

**Comment by vanshikaarora** [comment]
@teolemon  @deniger @VaiTon I have solved this issue here #2700. Can you please review:)

**Comment by teolemon** [comment]
Why should a popup appear ? Most likely the user knows that she or he is offline or has poor network. I'm not quite sure of the value a popup like this brings to the table.

**Comment by VaiTon** [comment]
> Why should a popup appear ? Most likely the user knows that she or he is offline or has poor network. I'm not quite sure of the value a popup like this brings to the table.

Otherwise the user will never know why nothing is happening, it's just a friendly reminder that the app still got his input.

**Comment by vanshikaarora** [comment]
> Why should a popup appear ? Most likely the user knows that she or he is offline or has poor network. I'm not quite sure of the value a popup like this brings to the table.

Yeah I felt the same. I have added a toast [here](https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2700). @teolemon If you think that toast is better shall I rename this Issue?
