### ISSUE TITLE
Shake phone to go back to scan mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#270]
Shaking the phone would bring back the app to scan mode. Perhaps make this optional

**Comment by herau** [comment]
yes it should be optional

**Comment by teolemon** [comment]
http://jasonmcreynolds.com/?p=388

**Comment by Shubham2320** [comment]
I am taking this one. I just wanna know where to place the option to allow this feature.

**Comment by teolemon** [comment]
Settings I guess. Checkbox, probably ?
