### ISSUE TITLE
3.1.6: no longer offering to crop or diplay photos after taking them

### ISSUE THREAD

**Issue by grrrrr** [openfoodfacts/openfoodfacts-androidapp#2701]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

After scanning an item that does not exist in the database, Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:** 

- Scan an item that does not exist in the OFF db
- take a photo (product image, ingredients or nutrition
- OFF-android skips the option to crop/rotate image
- goes straight to uploading the image
- after the image is upload it is never displayed in the app

**Expected behavior:** 

- Scan an item that does not exist in the OFF db
- take a photo (product image, ingredients or nutrition)
- OFF-android gives the option to crop/rotate image 
- image is displayed in app
- image is upload

(This behavior is observed in OFF 3.1.2)

**Observed behavior:** 

After taking photo no option is given to crop and rotate. Image is not displayed after returning to OFF app

**Device and Android version:** 

Samsung Galaxy S9
Android 9
OpenCamera 1.46
OpenFoodFacts 3.1.6 (freshly installed)

**Comment by deniger** [comment]
Should be fixed with https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2705
A preference is now available:
![image](https://user-images.githubusercontent.com/47569605/58985238-2a5f7f80-87db-11e9-8146-f60995d77daa.png)

**Comment by grrrrr** [comment]
thank you @deniger that works perfectly.
