### ISSUE TITLE
[Question] new release precedence "policy" between F-Droid and Google Play Store?

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/openfoodfacts-androidapp#2702]
I changed phone recently so I am a little fuzzy on the details, however I kinda remember I subscribed to the beta version program on Play Store since the F-Droid version was behind at the time.
Now I can't seem to find the beta version on Play Store ( version 3.1.5 installed  )  while 3.1.6 has been on F-Droid for 4 days...

Which release "canal" should I preferably use if I want the most up-to-date released version and avoid switching between Play Store and F-Droid and back?

PS: Personal preference for F-Droid.

Thanks

**Comment by teolemon** [comment]
We usually release F-Droid a bit early.
There might be exceptions, but it's usually:
beta-testing on the playstore beta, stable release on F-Droid, stable release on the PlayStore.
