### ISSUE TITLE
Document java files which require documentation

### ISSUE THREAD

**Issue by vanshikaarora** [openfoodfacts/openfoodfacts-androidapp#2715]
### Description

The following java files need documentation:

- [ ] Common API Manager.java
- [ ] OpenFoodAPIClient.java
- [ ] WikidataApiClient.java
- [ ] CategoryRepository.java
- [ ] FileDownloader.java
- [ ] CategoryFragmentViewModel.java
- [ ] AdditiveFragmentHelper.java

_Please comment name of few more classes that needs documentation_

**Comment by RajaVamsi11** [comment]
@vanshikaarora There are many files in the whole project which requires documentation.

**Comment by vanshikaarora** [comment]
@RajaVamsi11 Can you please add more suggestions to the list :)

**Comment by RajaVamsi11** [comment]
@vanshikaarora Instead of naming all java files here we can create different issues for different packages like a dagger, jobs, models, etc.,
