### ISSUE TITLE
Document the files in openfood/category package

### ISSUE THREAD

**Issue by RajaVamsi11** [openfoodfacts/openfoodfacts-androidapp#2717]
**Summary:**

Document the files in openfood/category package: [https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/category](https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/category)

**Comment by vanshikaarora** [comment]
Thanks for creating individual packages @RajaVamsi11. I am currently working on few of the classes and will send  a PR soon :)
