### ISSUE TITLE
Document the files in openfood/dagger package

### ISSUE THREAD

**Issue by RajaVamsi11** [openfoodfacts/openfoodfacts-androidapp#2718]
**Summary**

Document the files in openfood/dagger package: [https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/dagger](https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/dagger)

**Comment by vanshikaarora** [comment]
@RajaVamsi11 the dagger package has mostly interfaces does it needs a documentation?

**Comment by RajaVamsi11** [comment]
@vanshikaarora Let's leave it to mentors. @deniger @teolemon Whar are your views on the dagger package documentation.
