### ISSUE TITLE
Document the files in openfood/fragments package

### ISSUE THREAD

**Issue by RajaVamsi11** [openfoodfacts/openfoodfacts-androidapp#2719]
**Summary**

Document the files in openfood/fragments package : [https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments](https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments)

**Comment by vanshikaarora** [comment]
Thanks for creating individual packages @RajaVamsi11. I am currently working on few of the classes and will send a PR soon :)
