### ISSUE TITLE
Document the files in openfood/jobs package

### ISSUE THREAD

**Issue by RajaVamsi11** [openfoodfacts/openfoodfacts-androidapp#2720]
**Summary**

Document the files in openfood/jobs package: [https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/jobs](https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/jobs)

**Comment by vanshikaarora** [comment]
Thanks for creating individual packages @RajaVamsi11. I am currently working on few of the classes and will send  a PR soon :)

**Comment by RajaVamsi11** [comment]
@vanshikaarora please refer my comment in #2725

**Comment by RajaVamsi11** [comment]
@teolemon @deniger I am currently working on this issue.
