### ISSUE TITLE
Document the files in openfood/models package

### ISSUE THREAD

**Issue by RajaVamsi11** [openfoodfacts/openfoodfacts-androidapp#2721]
**Summary**

Document the files in openfood/models package: [https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/models](https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/models)

**Comment by vanshikaarora** [comment]
Thanks for creating individual packages @RajaVamsi11. I am currently working on few of the classes and will send  a PR soon :)
