### ISSUE TITLE
Document the files in openfood/network package

### ISSUE THREAD

**Issue by RajaVamsi11** [openfoodfacts/openfoodfacts-androidapp#2722]
**Summary**

Document the files in openfood/network package: [https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/network](https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/network)

**Comment by vanshikaarora** [comment]
Thanks for creating individual packages @RajaVamsi11. I am currently working on few of the classes and will send  a PR soon :)
