### ISSUE TITLE
Document the files in openfood/utils package

### ISSUE THREAD

**Issue by RajaVamsi11** [openfoodfacts/openfoodfacts-androidapp#2724]
**Summary**

Document the files in openfood/utils package: [https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/utils](https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/utils)

**Comment by vanshikaarora** [comment]
Thanks for creating individual packages @RajaVamsi11. I am currently working on few of the classes and will send  a PR soon :)
