### ISSUE TITLE
Document the files in openfood/views package

### ISSUE THREAD

**Issue by RajaVamsi11** [openfoodfacts/openfoodfacts-androidapp#2725]
**Summary**

Document the files in openfood/views package: [https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/views](https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/views)

**Comment by vanshikaarora** [comment]
Thanks for creating individual packages @RajaVamsi11. I am currently working on few of the classes and will send  a PR soon :)

**Comment by RajaVamsi11** [comment]
@vanshikaarora There are many packages to work on. So don't work on all packages at a time. Complete one package documentation and move on to next package. So can you please comment on one package in which you are working presently. 
After completing that package, you can document another one.

**Comment by vanshikaarora** [comment]
@RajaVamsi11 I have cuurently done the network package and also while working with #271. I have gone through the fragment package :). I'll raise a PR for these shortly.

**Comment by RajaVamsi11** [comment]
@teolemon @deniger I am currently working on this issue.
