### ISSUE TITLE
App language resets to OS language when scanning a product

### ISSUE THREAD

**Issue by Flint4** [openfoodfacts/openfoodfacts-androidapp#2735]
When scanning a product, the app resets its language to the language of the OS. This happens when a different language is choosen in OFF than in the OS. 
Example: Phone OS in English, OFF language is set to German. After product scan OFF language is English again. 

1. Go to Preferences > Languages
2. Choose a language which is different from your OS 
3. Return to the main screen
4. Scan a product
5. Language has changed

 - Device: LG G7 ThinQ
 - OS: Android 8.0
 - App version 3.1.6

**Comment by deniger** [comment]
Should be fixed with https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2776
