### ISSUE TITLE
The non-clickable button on top of the scan card is confusing users

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2737]
The non-clickable button on top of the scan card is confusing users. We could either remove it completely or expand the card when it's clicked. 
Also, when the product does not exist, we should make clear that the card can be clicked.

**Comment by huzaifaiftikhar** [comment]
@teolemon which button are you talking about? Can you provide a screenshot of the same or else we can close this issue if it is outdated?
