### ISSUE TITLE
Improvements to the new image selector

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2746]
- [ ] Add the ability to report images in the new image selector

- [ ] Add a button to open product edit view and launch the OCR (on the selected ingredient image, and in the matching language)

- [x] Timestamp the selectable images so that the user can select the most recent possible

- [x] Allow in settings to replace native languages names by langcodes (I have a hard time finding Bulgarian, written in Cyrillic)

- [ ] It's impossible to open the selector when the product has no image selected at all in the current language (happens sometimes)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/59524961-6b3f4e80-8ed5-11e9-8c60-c5e205c0f3d9.png)

**Comment by deniger** [comment]
@teolemon do you have the product barcode ?

**Comment by deniger** [comment]
Could it be a solution ?
![image](https://user-images.githubusercontent.com/47569605/59678430-b2c32480-91cc-11e9-9305-0f1fdd9d63b2.png)

**Comment by deniger** [comment]
report images / ocr we should add 2 new buttons in this view....

**Comment by teolemon** [comment]
yup for the selector 👍 
product with null, example: 7750526000307 https://barcode.tec-it.com/en/EAN13?data=7750526000307

**Comment by deniger** [comment]
The product has no available name...

![image](https://user-images.githubusercontent.com/47569605/59678889-d470db80-91cd-11e9-8214-4ff60d7d053a.png)

**Comment by deniger** [comment]
https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=7750526000307

**Comment by deniger** [comment]
If not image selected, the icon is:
![image](https://user-images.githubusercontent.com/47569605/59679260-a344db00-91ce-11e9-88bb-b06e5b1ff1bf.png)
