### ISSUE TITLE
Remove unused resources

### ISSUE THREAD

**Issue by deniger** [openfoodfacts/openfoodfacts-androidapp#2760]
Use the Refactor action "remove unused resources" from Android studio to track all unused resources:

![image](https://user-images.githubusercontent.com/47569605/59907382-3f5b2600-940b-11e9-9f4b-c546701711eb.png)

**Comment by RajaVamsi11** [comment]
@deniger Can I work on this issue?

**Comment by RajaVamsi11** [comment]
@deniger I inspected the whole project for unused resources using Analyze option. It seems like they have been removed. Can you please confirm that these unused resources still exist?

**Comment by deniger** [comment]
On Android studio, If you select the Res folder and launch the analyser, you should find some unused resources


---- On Sun, 23 Jun 2019 08:07:31 +0200 notifications@github.com wrote ----



@deniger I inspected the whole project for unused resources using Analyze option. It seems like they have been removed. Can you please confirm that these unused resources still exist?

**Comment by RajaVamsi11** [comment]
Found them @deniger. Can I proceed by removing all the unused resources?

**Comment by deniger** [comment]
Let's try.
Your should test all the flavor then


---- On Sun, 23 Jun 2019 11:53:20 +0200 notifications@github.com wrote ----



Found them @deniger. Can I proceed by removing all the unused resources?
