### ISSUE TITLE
ANR related to the ingredients taxonomies

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2761]
![image](https://user-images.githubusercontent.com/1689815/59962691-20cb5c80-94e9-11e9-8385-9895d29101e5.png)
![image](https://user-images.githubusercontent.com/1689815/59962701-36408680-94e9-11e9-801b-421817b6da67.png)

**Comment by stephanegigandet** [comment]
The ingredients taxonomy is huge, and it is going to become more and more huge. What features of the app use it?

**Comment by teolemon** [comment]
@dobriseb

**Comment by dobriseb** [comment]
Well, when I first suggested my "diet add-on", the first things I was told was to make it with taxonomy.
For the moment nothing use the ingredients taxonomy but in a future (I'd like to be soon) you will be able to use Diet in OFF to be sure no forbiden ingredients are used into a product.

**Comment by dobriseb** [comment]
It could also be use to translate ingredients.

**Comment by dobriseb** [comment]
I'm going to suspend the default download and make it optionaly with an warning for the users.

**Comment by dobriseb** [comment]
PR 2785
