### ISSUE TITLE
Dutch tagline is not centered on every screen density

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2768]
![image](https://user-images.githubusercontent.com/1689815/81393899-656fde80-9121-11ea-87d0-798e21bc0041.png)
![image](https://user-images.githubusercontent.com/1689815/81393914-6b65bf80-9121-11ea-975c-0f0d9356c3c7.png)

**Comment by mrudultora** [comment]
@VaiTon This issue is fixed. I had already checked the layout file and its looking correct for **ldpi screens (240x320)**. May be someone had corrected it.

**Comment by VaiTon** [comment]
Let's close for now.
