### ISSUE TITLE
Bind Open Food / Open Beauty Facts behaviour to a single variable

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#279]
Bind Open Food / Open Beauty Facts behaviour to a single variable so that we can keep the codebase as united as possible

**Comment by herau** [comment]
@teolemon what are we suppose to do with this issue ?

**Comment by teolemon** [comment]
I've created multiple issues for all three features that need to be modified. This one is about the variable to switch then on and off. 
The rationale is to avoid painful forking and branching

**Comment by teolemon** [comment]
@herau @itchix  does the approach of trying to keep a single codebase make sense ?

**Comment by herau** [comment]
My first though will be to say that we have to define a fork per additional project (Beauty, Fashion).

I'll try to find oher open source projects which maybe has the same requirement (The same code base but multiple apps)

**Comment by herau** [comment]
if all the apps share the same code but only change for app names, app icons and themes i think it's ok to have the same code base.

**Comment by teolemon** [comment]
there will be minor behaviour here and there (like some tabs in the product view, api urls…) but nothing that intrusive imo

**Comment by herau** [comment]
what about the data model ? no différence between the both app? 

maybe we could also exclude some resources with a flag: for exemple remove OBF resources when we build the OFF artifact; don't know if possible

**Comment by teolemon** [comment]
We have fields added and removed (added: Period after opening plus ingredient detection) (removed: nutrition stuff)
