### ISSUE TITLE
The new quantity system for list is buggy

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2792]
![image](https://user-images.githubusercontent.com/1689815/60250573-32d14480-98c7-11e9-97f3-04ec04e0663c.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/60250643-52686d00-98c7-11e9-96e3-ae91c1032717.png)

**Comment by deniger** [comment]
@teolemon  what should we do ? add a new line, truncate the quantity ?
