### ISSUE TITLE
Appearence of the side menu changed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2822]
![image](https://user-images.githubusercontent.com/1689815/60711215-a8b35c80-9f14-11e9-8bc5-56d3c28d38be.png)

**Comment by deniger** [comment]
Should be ok now:
![image](https://user-images.githubusercontent.com/47569605/61073154-08c66900-a415-11e9-96f1-ec9b83ed46fb.png)
