### ISSUE TITLE
Add trim() method to all EditText objects in the project

### ISSUE THREAD

**Issue by RajaVamsi11** [openfoodfacts/openfoodfacts-androidapp#2837]
**Summary:**

Add .trim() method to all EditText objects in the whole project. This method returns a copy of the string, with leading and trailing whitespace omitted. The Unicode value of space character is ‘\u0020’. The trim() method in java checks this Unicode value before and after the string, if it exists then removes the spaces and returns the omitted string.

**Example**
For example, In the edit text field, we wrote something like "  issue    " and submitted. When there is no trim method applied on that string, the string will be stored as "  issue    " with spaces included at the first and last of the string. But when a trim method is applied the string is stored as "issue" with spaces removed from before and after the string. This is how it looks like after applying:

                       @BindView(R.id.et_username)
                       EditText etUsername;
                       etUserName.getText().toString().trim()

This must be implemented in whole project. You can refer [here](https://www.geeksforgeeks.org/java-string-trim-method-example/) and [here](https://www.tutorialspoint.com/java/java_string_trim.htm) for more information.

**Comment by RajaVamsi11** [comment]
@teolemon @deniger Can I work on this issue?

**Comment by deniger** [comment]
@teolemon I believe the server is doing this job no ?
It could be used for locale data. Is there a way to add this feature without modifying all fragments/activities ( a kind of Aspects or something like that) ?

**Comment by teolemon** [comment]
Yes. The server is doing the trimming and normalization job. No need to add trimming everywhere.

**Comment by RajaVamsi11** [comment]
@teolemon @deniger  Great to hear that server doing trimming and normalization. We can close this issue as it is not valid. Thank you for your responses.
