### ISSUE TITLE
Crash when taking picture after changing product language

### ISSUE THREAD

**Issue by chk1** [openfoodfacts/openfoodfacts-androidapp#2842]
**Steps to reproduce the behavior**
1. Scan a new product, tap add/edit to visit the editor
2. Tap camera icon to take a picture
3. Do not take and submit a picture, tap the back button
4. Change product language
5. Tap camera icon again, take picture, tap accept/checkmark
8. App crashes

**Smartphone**
 - Device: Xiaomi Redmi 4X
 - OS: LineageOS 15.1 / Android 8.1
 - Camera app: Open Camera v1.46 (net.sourceforge.opencamera)
 - OpenFoodFacts app version 3.2.2 from Google Play

**Logcat**

```
07-22 21:36:23.279 16594 16594 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=131275, result=-1, data=Intent { (has extras) }} to activity {org.openfoodfacts.scanner/openfoodfacts.github.scrachx.openfood.views.AddProductActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.a(AddProductOverviewFragment.java:951)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.a(AddProductActivity.java:1185)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.a(AddProductActivity.java:58)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity$9.a(AddProductActivity.java:1101)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.a.c.a(EmptyDisposable.java:78)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.d.b$a.a(SingleDoOnSubscribe.java:65)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.d.h$a.a(SingleObserveOn.java:57)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.c.k$a.a(ObservableSingleSingle.java:58)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.c.l.b(ObservableSubscribeOn.java:34)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.g.a(Observable.java:12268)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.c.k.b(ObservableSingleSingle.java:35)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.k.a(Single.java:3603)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.d.h.b(SingleObserveOn.java:35)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.k.a(Single.java:3603)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.d.b.b(SingleDoOnSubscribe.java:41)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.k.a(Single.java:3603)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.a(AddProductActivity.java:1050)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.a(AddProductActivity.java:1043)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.a(AddProductOverviewFragment.java:922)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.jobs.b.a(PhotoReceiverHandler.java:105)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.jobs.b.a(PhotoReceiverHandler.java:39)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.jobs.b.a(PhotoReceiverHandler.java:31)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.a(AddProductOverviewFragment.java:940)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.support.v4.app.k.onActivityResult(FragmentActivity.java:156)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7276)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	... 9 more
```

**Additional information**
This issue might be related, but stack trace has changed due to code refactoring? (I'm not familiar with the code base) https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/1540

**Comment by mustaqmustu** [comment]
> **Steps to reproduce the behavior**
> 
>     1. Scan a new product, tap add/edit to visit the editor
> 
>     2. Tap camera icon to take a picture
> 
>     3. Do not take and submit a picture, tap the back button
> 
>     4. Change product language
> 
>     5. Tap camera icon again, take picture, tap accept/checkmark
> 
>     6. App crashes
> 
> 
> **Smartphone**
> 
>     * Device: Xiaomi Redmi 4X
> 
>     * OS: LineageOS 15.1 / Android 8.1
> 
>     * Camera app: Open Camera v1.46 (net.sourceforge.opencamera)
> 
>     * OpenFoodFacts app version 3.2.2 from Google Play
> 
> 
> **Logcat**
> 
> ```
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=131275, result=-1, data=Intent { (has extras) }} to activity {org.openfoodfacts.scanner/openfoodfacts.github.scrachx.openfood.views.AddProductActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.a(AddProductOverviewFragment.java:951)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.a(AddProductActivity.java:1185)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.a(AddProductActivity.java:58)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity$9.a(AddProductActivity.java:1101)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.a.c.a(EmptyDisposable.java:78)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.d.b$a.a(SingleDoOnSubscribe.java:65)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.d.h$a.a(SingleObserveOn.java:57)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.c.k$a.a(ObservableSingleSingle.java:58)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.c.l.b(ObservableSubscribeOn.java:34)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.g.a(Observable.java:12268)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.c.k.b(ObservableSingleSingle.java:35)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.k.a(Single.java:3603)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.d.h.b(SingleObserveOn.java:35)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.k.a(Single.java:3603)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.e.e.d.b.b(SingleDoOnSubscribe.java:41)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at b.a.k.a(Single.java:3603)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.a(AddProductActivity.java:1050)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.a(AddProductActivity.java:1043)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.a(AddProductOverviewFragment.java:922)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.jobs.b.a(PhotoReceiverHandler.java:105)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.jobs.b.a(PhotoReceiverHandler.java:39)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.jobs.b.a(PhotoReceiverHandler.java:31)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.a(AddProductOverviewFragment.java:940)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.support.v4.app.k.onActivityResult(FragmentActivity.java:156)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7276)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
> 07-22 21:36:23.279 16594 16594 E AndroidRuntime: 	... 9 more
> ```
> 
> **Additional information**
> This issue might be related, but stack trace has changed due to code refactoring? (I'm not familiar with the code base) #1540

could you please upload any screenshot or gif related to it ? Because it is working fine for me

**Comment by mustaqmustu** [comment]
@chk1 could you please add a screenshot or gif related to it ? Because it is working fine for me.

**Comment by mustaqmustu** [comment]
@chk1 
![image](https://user-images.githubusercontent.com/43813438/69072085-18a02a80-0a51-11ea-9ffd-373b82e88fce.png)

**Comment by mustaqmustu** [comment]
@chk1
![doc_2019-11-18_22-17-25](https://user-images.githubusercontent.com/43813438/69072369-877d8380-0a51-11ea-8b46-b0dece52de0d.GIF)

**Comment by mustaqmustu** [comment]
@chk1 
[egza.zip](https://github.com/openfoodfacts/openfoodfacts-androidapp/files/3859705/egza.zip)

**Comment by chk1** [comment]
It works fine now for me as well, thanks for testing it out @mustaqmustu
