### ISSUE TITLE
Scan button in bottom menu should close product card

### ISSUE THREAD

**Issue by chk1** [openfoodfacts/openfoodfacts-androidapp#2844]
**Is your feature request related to a problem? Please describe.**
After scanning a product and expanding the card to full view, the only way to return to the scan view is by swiping the card down from the top. Alternatively, tapping back returns to the "welcome screen" and I have to tap scan again. Tapping scan should return to scan mode immediately.

**Describe the solution you'd like**
The scan button on the bottom nav should minimize or close the card and return to scan view.

![image](https://user-images.githubusercontent.com/828496/61664920-1d87e400-acd4-11e9-9890-1d148a50dd5b.png)

**Comment by teolemon** [comment]
This is a sensible idea. Thanks @chk1 👍

**Comment by sank20** [comment]
Hi, I'd like to take up this issue. I'll send a PR soon.
