### ISSUE TITLE
Add label for vegetarian/vegan/palm products

### ISSUE THREAD

**Issue by SuperMeepBoy** [openfoodfacts/openfoodfacts-androidapp#2852]
**Is your feature request related to a problem? Please describe.**
It is always a pain to shop when you're a vegan beginner. You have to read the whole package meaning first find the list of ingredients, then compare, read it twice to be sure etc. Moreover, when you're a complete beginner you may not know some things. Some additives aren't necessarily vegan (for example E101 if I make no mistake). Adding a label "Vegan" would help everyone and could also teach beginners things if the reason can be added ("E101 is from animal source")

**Describe the solution you'd like**
It would be cool to have a label to tell us if a product is vegan or not once scanned. Also for the non-vegan products, it would be nice if the reason can be listed. This for an educational purpose + because some vegans don't really agree on whether some product is vegan or not (honey for example).

**Describe alternatives you've considered**
I don't see any other alternative ? Except another app fully dedicated to vegans.

**Comment by teolemon** [comment]
`https://world.openfoodfacts.org/api/v0/product/3564700459447.json?fields=ingredients_analysis_tags,ingredients`

**Comment by teolemon** [comment]
monkey >> palm oil
vegan >> leaf
vegetarian >> egg

**Comment by ripetrescu** [comment]
Pushed against this branch https://github.com/openfoodfacts/openfoodfacts-androidapp/tree/vegetarian_vegan_palm

**Comment by teolemon** [comment]
This is fixed by @ripetrescu 
closing
