### ISSUE TITLE
Add a button on new product addition card

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2859]
![image](https://user-images.githubusercontent.com/1689815/63003110-c8c12e80-be77-11e9-9584-3f051e76d776.png)

**Comment by alistairholmes** [comment]
Hi there :wave: has this been added to the app already?

**Comment by teolemon** [comment]
Hey @alistairholmes, no it hasn't, and you're welcome to claim it 👍

**Comment by alistairholmes** [comment]
Great thanks. Just so that I understand correctly, I have to add a button on activity_add_product.xml. What is the expected behavior when the button is clicked?

**Comment by teolemon** [comment]
@alistairholmes Not sure about the proper layout file. @deniger ?
the current behaviour is located at : 
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/346f26018817bad1fddcb62ad12b8de7a3c8bc7e/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/ContinuousScanActivity.java#L383

It's about making it more intuitive with a button.

**Comment by huzaifaiftikhar** [comment]
![image](https://user-images.githubusercontent.com/10832531/66706131-d5b1af80-ed4c-11e9-9a9e-0ba1cecbb518.png)
@teolemon Earlier we had this button, instead of the tick icon we displayed the (+) icon on the floating action button. Why did we remove that? Any specific reason or just design improvements?

**Comment by teolemon** [comment]
It wasn't working. I got a lot of feedback it was confusing people. The new design seems to work better, no confusion possible (you click on the button because it says "Add a new product")

**Comment by huzaifaiftikhar** [comment]
Ohh okay
