### ISSUE TITLE
Move image taking buttons to 1st tab of product addition

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2860]
![image](https://user-images.githubusercontent.com/1689815/63003759-315cdb00-be79-11e9-8b12-d5df4018c15d.png)
Move (or possibly clone) image taking buttons to 1st tab of product addition

**Comment by VaiTon** [comment]
Why? Right now it's very organized.

**Comment by teolemon** [comment]
Because some people don't want to put 5 min of effort into a product. The bare minimum before they leave are the images
That way, when and if the person moves to the ingredient section, the OCR is ready.

**Comment by deniger** [comment]
Do we clone or move the buttons to the first tab ?
this new feature is available in addition and in modificatio or only in addition mode ?

**Comment by teolemon** [comment]
Cloning is good (we need to ensure that photos taken are shown immediately on the other tabs, so that we don't get "Where has my photo gone ??")
Both mode are useful, for quick photo updating (when the packaging changes)

**Comment by teolemon** [comment]
This bug is superceded by https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/2350
