### ISSUE TITLE
Add an in-app changelog

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2870]
- Add an in-app changelog that's triggered when opening the app after an upgrade (or series of upgrades) to let the user know what's new from the last time he/she used the app
- Proposed library to use: https://github.com/TonnyL/WhatsNew
- We can either hardcode it, or we can have a JSON file on the server, or somewhere in the code like @VaiTon suggested

**Comment by hmuhammadazeem** [comment]
Hey, I'm interested to work on this. Can I get some details on it?

**Comment by VaiTon** [comment]
@hmuhammadazeem we could create a file CHANGELOG.md and then display it after every update in-app or maybe fetch the details from github.

**Comment by VaiTon** [comment]
Oh my bad, the file CHANGELOG already exists. The second part of my sentence is still valid though.

**Comment by rprager18** [comment]
Hello. I am new to open source and wanted to start my first project. Do you guys think I can take a crack at this

**Comment by VaiTon** [comment]
@rprager18 yes you are very welcome to do so! 

@teolemon recommends this library (https://github.com/TonnyL/WhatsNew). Take a look!

**Comment by naivekook** [comment]
@teolemon @VaiTon Hi!
Is it still TBD? Can I take it?

also do we have another source of changelog?
In current case we need to parse `CHANGELOG.md` via gradle task on each build to get the new changes and store them in application and it quite tricky because this file doesn't have stable formatting.

**Comment by teolemon** [comment]
We can do something special with the format you'd like @naivekook

**Comment by VaiTon** [comment]
> @teolemon @VaiTon Hi!

Hey hi @naivekook and welcome!

> Is it still TBD? Can I take it?

Sure you can!

> also do we have another source of changelog?
> In current case we need to parse `CHANGELOG.md` via gradle task on each build to get the new changes and store them in application and it quite tricky because this file doesn't have stable formatting.

We could use the file used by the playstore maybe, I really do not know.
