### ISSUE TITLE
unrecognized languages in gradle

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2912]
``` 
Your App Bundle targets the following unrecognized languages: me, rs, ry, sh. The list of supported language codes can be found in the IANA registry. Invalid languages caused by third-party libraries can be excluded using the resConfigs Gradle property.
```
https://developer.android.com/studio/build/shrink-code#unused-alt-resources
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

**Comment by teolemon** [comment]
https://stackoverflow.com/questions/57859122/invalid-splitapkbundle-the-bundle-targets-unknown-languages-gr-google-play

**Comment by VaiTon** [comment]
@teolemon try https://stackoverflow.com/a/57868194
