### ISSUE TITLE
"Loading" message next to the Labels 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2913]
"Loading" message next to the Labels. It might be related to the taxonomy loading.

![image](https://user-images.githubusercontent.com/1689815/67622390-fd5b4a00-f819-11e9-8cc3-56a16e995a24.png)

**Comment by VaiTon** [comment]
Cannot reproduce on 4de719e7e5eb3ef1cfc8effc76d114f01763f3de

**Comment by teolemon** [comment]
Duplicate of #3772 > closing
