### ISSUE TITLE
Lists are not properly shown on the product page

### ISSUE THREAD

**Issue by slarti-zak** [openfoodfacts/openfoodfacts-androidapp#2923]
**Describe the bug**
In #2250 it was added that the lists that a product is part of are displayed in the summary screen of that product. It seems that this behavior is not available and more.

**To Reproduce**
1. Add a product to a list
2. Go to the summary page of that product
3. No lists are displayed

**Expected behavior**
As it was already implemented, I would expect the lists of that product to be displayed.

**Screenshots**
![device-2019-11-16-132202](https://user-images.githubusercontent.com/13180178/68993259-42512a00-0876-11ea-8085-4916db3a5e0b.png)

**Smartphone (please complete the following information):**
 - Device: LG G6
 - OS: Android 7
 - Version Open Food Facts 3.2.5 (set to german)

**Additional context**
Not sure if it is a bug, bit I listed it as a bug, as it was already present in the past.

**Comment by teolemon** [comment]
Thanks for the report @slarti-zak 👍 
What happens if you click on the grey squares, by the way ?

**Comment by slarti-zak** [comment]
They open up the palm oil/vegan/vegetarian status info:

![device-2019-11-17-092455](https://user-images.githubusercontent.com/13180178/69005206-f73f2180-091e-11ea-8e77-fc17b8c2fc17.png)

**Comment by teolemon** [comment]
Icons should be there. What version of Android are you using ? 4 ?

**Comment by slarti-zak** [comment]
@teolemon You mean the missing images? Yes, I they are displayed now but i upgraded to android 9 so I can't say what fixed it.

**Comment by teolemon** [comment]
@CharlesNepote can you reproduce ?

**Comment by teolemon** [comment]
@VaiTon  possibly a similar SSL issue

**Comment by huzaifaiftikhar** [comment]
Closed via #3544
