### ISSUE TITLE
Icons missing in the Ingredient detection mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2926]
![image](https://user-images.githubusercontent.com/1689815/69006454-7b010a00-092f-11ea-9008-9fa3819c266f.png)

**Comment by teolemon** [comment]
as spotted in https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/2923

**Comment by slarti-zak** [comment]
Update: it was broken on an android 7 device but works after upgrading to android 9. It was also affecting product images as mentioned in #2937 which are also working after updating android from 7 to 9.

**Comment by teolemon** [comment]
Merging into #3524
