### ISSUE TITLE
Improve 'shopping list' (products to buy) discoverability

### ISSUE THREAD

**Issue by CloCkWeRX** [openfoodfacts/openfoodfacts-androidapp#2927]
The app features a shopping list feature, but its not obvious unless the user navigates to the "lists" UI.

Consider promoting this to the landing page as a call to action:
"I want to add products to my shopping list" -> navigate to your lists, shopping list if present.

**Comment by teolemon** [comment]
It's now visible both on the product page, and on the top level navigation.
