### ISSUE TITLE
Make Robotoff questions visible to non-logged in users

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2931]
![image](https://user-images.githubusercontent.com/1689815/69482793-173f7b00-0e20-11ea-864b-15f597ad56f9.png)

**Comment by teolemon** [comment]
There should be a setting to disable/enable the prompts for not logged in users

**Comment by teolemon** [comment]
- [ ] Move the IF LOGGED-IN condition from the whole Robotoff question block in the product page to the Answer buttons in the modal that appears to answer.
- [ ] IF LOGGED-IN (perform the usual Robotoff network call) ELSE (open a new modal with a link to signup, and another link to login)

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/0d5a3db02ed972d4ed774386283d0a26a3e91d6b/app/src/main/java/openfoodfacts/github/scrachx/openfood/utils/QuestionDialog.java

**Comment by VaiTon** [comment]
Partially fixed by #3324.

Now the dialog displays "login" and "register". 

Actually register does not lead anywhere so we have to implement this.

> There should be a setting to disable/enable the prompts for not logged in users

We also have to do this.

---
- [ ] Implement register button
- [ ] Create preference to disable the dialog for non logged in

**Comment by teolemon** [comment]
Register leads to the HTML form right now ?

**Comment by VaiTon** [comment]
Actually it doesn't work. It leads nowhere.

**Comment by teolemon** [comment]
meeh… I could swear it worked for me when I tested

**Comment by teolemon** [comment]
Thanks @VaiTon for the fix. Closing that one, and we'll make refinements in other issues.
