### ISSUE TITLE
:app:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#294]
:app:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by herau** [comment]
just warnings in unit tests code
