### ISSUE TITLE
Better handle JSON issues

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2941]
![image](https://user-images.githubusercontent.com/1689815/70851014-bdffc000-1e90-11ea-9422-39669e33f445.png)

**Comment by teolemon** [comment]
Solution probably like this:
![image](https://user-images.githubusercontent.com/1689815/70851081-39617180-1e91-11ea-9ef1-680b522ae59b.png)

**Comment by ripetrescu** [comment]
@teolemon  please check it https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2943
