### ISSUE TITLE
Make "image upload" message more explicit on Product Addition

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2945]
![image](https://user-images.githubusercontent.com/1689815/71366190-98b23680-25a1-11ea-8c1d-1a5b0221958f.png)
Make "image upload" toast message more explicit on Product Addition.
Replace "Image uploaded successfully" by "Ingredient image uploaded successfully" or "Nutrition image uploaded successfully" or "Front image uploaded successfully"

**Comment by pratyaksh1610** [comment]
@VaiTon I would like to work on this issue.
Please assign this issue to me.

**Comment by pratyaksh1610** [comment]
@VaiTon  In this we need to change the "Image uploaded successfully" by one of the options mentioned above or change them according to the fragments (summary / ingredients / photos)

**Comment by VaiTon** [comment]
Yes, change the test of the toast should do it for now, as using another view is not something we can do with Toasts AFAIK

**Comment by pratyaksh1610** [comment]
So change needs to be done in `strings.xml` only , replacing with one of the options mentioned above.
If yes,
Then I think `Product image uploaded successfully` would be a better option.

**Comment by VaiTon** [comment]
@pratyaksh1610 no it's not. First we have to create different strings for the different kind of images and then we have to use them while creating the Toasts

**Comment by pratyaksh1610** [comment]
@VaiTon Got it , thanks.
