### ISSUE TITLE
Enhance the success message to make it more motivating

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2949]
![image](https://user-images.githubusercontent.com/1689815/71352159-d4370b80-2575-11ea-8c6e-3812afbf62ac.png)
Differentiate the message between initial upload and product editing

**Comment by VaiTon** [comment]
Partially fixed.
It now displays a good upload messages.
However it doesn't distinguish first upload and editing.

**Comment by teolemon** [comment]
Thank you @VaiTon for closing that one
