### ISSUE TITLE
Remove the field around the barcode value to make it clear it cannot be edited

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2952]
![image](https://user-images.githubusercontent.com/1689815/71353146-7fe15b00-2578-11ea-8263-ace8c9bd4eaa.png)

**Comment by stephanegigandet** [comment]
I don't see the value of showing the barcode here, why don't we remove it completely?

**Comment by teolemon** [comment]
Because it's essential to spot scanning mistakes. We've already discussed this.

**Comment by stephanegigandet** [comment]
Then it should be the first field, above everything. But frankly I doubt that many people are actually checking the barcode that is displayed. They just assume it works. And if it didn't work and you are shown a wrong barcode, and you actually notice it, then you just conclude that the scanner is broken.

Every field should be up for discussion, even if it has been discussed before. It would be nice to have a central place for that actually.

**Comment by teolemon** [comment]
Yes but our scanner doesn't work well. #2629 for a (PARTIAL) solution.

**Comment by mrudultora** [comment]
@VaiTon This issue can be closed. It is also resolved.
