### ISSUE TITLE
Shorten the tab labels to be one line only in English and French

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2954]
![image](https://user-images.githubusercontent.com/1689815/71353659-02b6e580-257a-11ea-897e-0d8d56259ce0.png)

Shorten the tab labels to be one line only in English and French (at least) and add comment asking translators to be concise.

**Comment by mrudultora** [comment]
@teolemon It's already fixed. Issue can be closed

**Comment by teolemon** [comment]
Fixed for French. Closing.
