### ISSUE TITLE
Categories are always displayed in French

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#296]
Categories are always displayed in French, although we have translations for them.

**Comment by herau** [comment]
where are the translations ? in the api result ?

**Comment by teolemon** [comment]
http://en.wiki.openfoodfacts.org/API#Categories
The best way to do that is to do
http://fr.openfoodfacts.org/categorie/en:baby-foods.json (and you get the local value)

**Comment by teolemon** [comment]
The best way would be a new translation API. Otherwise, we can parse the translation file.

**Comment by teolemon** [comment]
@hangy any way we could have a translation api based on this (perhaps with a paramater multilingual )
http://world.openfoodfacts.org/cgi/suggest.pl?lc=fr&tagtype=categories&string=a

the same, but with all available languages

**Comment by teolemon** [comment]
@herau : working solution: they both have the ```en:baby-foods``` id with the localized name 
- https://world.openfoodfacts.org/categories.json
``` {"url":"https://world.openfoodfacts.org/category/baby-foods","name":"Baby foods","id":"en:baby-foods","products":670} ```
- https://world-fr.openfoodfacts.org/categories.json
``` {"url":"https://world-fr.openfoodfacts.org/categorie/aliments-pour-bebe","name":"Aliments pour bébé","products":670,"id":"en:baby-foods"}```

**Comment by policorn** [comment]
Hi @teolemon, should we display only the categories matching the user language?

**Comment by teolemon** [comment]
If we have a translation in the user's language, yes, otherwise fallback to English, and if no English, the original language of the product.

**Comment by teolemon** [comment]
1. Display categories in user language if available
2. Otherwise display categories in English if available
3. Otherwise display categories in the product main's language
