### ISSUE TITLE
Add labels to icons in image editing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2962]
![image](https://user-images.githubusercontent.com/1689815/71366572-9f8d7900-25a2-11ea-851e-eb7eaf024f5d.png)

**Comment by pratyaksh1610** [comment]
@VaiTon I have inspected the layout , in this we need to add text views for the expected behaviour.
PTAL.
Thanks.
![asa](https://user-images.githubusercontent.com/76740999/183475325-5740eb9d-544a-4661-a69f-ede09f0157d1.png)

**Comment by VaiTon** [comment]
@pratyaksh1610 we should put the text inside the buttons

**Comment by pratyaksh1610** [comment]
@VaiTon In that case we need to increase dimensions of image view and put text view inside it ?
PTAL

**Comment by pratyaksh1610** [comment]
@VaiTon 
Image inside text view as drawable.
PTAL.
Thanks.
![opene](https://user-images.githubusercontent.com/76740999/183571561-3d0a7467-88c2-4ba9-a6ee-e219bef9f3a5.png)

**Comment by VaiTon** [comment]
@pratyaksh1610 yes, that's ok!
