### ISSUE TITLE
Add onboarding tooltip on first use for image editing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2963]
![image](https://user-images.githubusercontent.com/1689815/71366971-d3b56980-25a3-11ea-817c-ab9c31f6916a.png)

Add onboarding tooltip on fist use for image editing

**Comment by teolemon** [comment]
Here's a code pointer for a similar tipbox already in trunk : https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/6bb72d0d0b03d4c8a4ec911a9e0f70be1bdb4c3c

**Comment by Varsha-29** [comment]
I will work on this feature

**Comment by teolemon** [comment]
This is fixed 🎉 
thanks @Varsha-29 and @VaiTon
