### ISSUE TITLE
INT vs STR issues still make unit display unreliable

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2965]
![image](https://user-images.githubusercontent.com/1689815/71402284-c2646f80-262c-11ea-910d-4610aa4666bf.png)
![image](https://user-images.githubusercontent.com/1689815/71402368-ec1d9680-262c-11ea-8e2b-a2316eace787.png)

INT vs STR issues still make unit display unreliable in the nutrition summary and in the nutrition table.
We need to add a client side check, and make a server side fix.

**Comment by stephanegigandet** [comment]
Why would INT vs STR issues affect the unit display? Units are always the same. The app should use the some-nutrient_100g value, and display everything in grams.

**Comment by teolemon** [comment]
I have no idea. The error is transient, depending on the product

**Comment by VaiTon** [comment]
@teolemon could you check last develop on this one?

**Comment by naivekook** [comment]
I checked it on latest develop and looks like it is already fixed. Maybe you have a name of specific product for this bug?
Phone: HTC U11 (en-ru)

**Comment by teolemon** [comment]
I'm closing until I find another example
