### ISSUE TITLE
Add a label to the "Add to Open Food Facts modal"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2966]
![image](https://user-images.githubusercontent.com/1689815/71406476-a070ea00-2638-11ea-86bc-4299009f11b7.png)
The line looks like a separator. Add a field title to make it clear where to type

**Comment by pratyaksh1610** [comment]
@teolemon It would be great if you can share the translated version (English) of the above image, as I am unable to search for the required file.

Thanks.

**Comment by pratyaksh1610** [comment]
@teolemon  Looks like I found it in https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/1632 , this will help.

**Comment by VaiTon** [comment]
@pratyaksh1610 the issue is that there should be some label/placeholder indicating the field

**Comment by pratyaksh1610** [comment]
@VaiTon Thankyou for the clarification.
I would like to have some insight on the following,

1. The default size of TextView is 14sp so is there any particular dimens to use or I can adjust accordingly, and I can see the text must be bold, and
2. The localised string should be translatable or not .

Thanks !

**Comment by pratyaksh1610** [comment]
I would like to work on this issue.
Please assign this issue to me.
Thanks.

**Comment by VaiTon** [comment]
@pratyaksh1610 
1. You can adjust accordingly. You don't even need to use bold if not necessary. Just post a screenshot with the PR so that we can see the result.
2. It should be localizable as it is a text that users will see.

Do not hesitate to ask if in doubt!

**Comment by pratyaksh1610** [comment]
@VaiTon I have made a PR . Please review. 
Thanks.
