### ISSUE TITLE
You can't click the link to the ADEME website

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2968]
![image](https://user-images.githubusercontent.com/1689815/71415900-5d297200-265e-11ea-9bbb-232fc01dd057.png)
You can't click the link to the ADEME website in the Environment tab.

**Comment by Daver19999** [comment]
> ![image](https://user-images.githubusercontent.com/1689815/71415900-5d297200-265e-11ea-9bbb-232fc01dd057.png)
> You can't click the link to the ADEME website in the Environment tab.

**Comment by namanrana16** [comment]
I would like to work on this

**Comment by MadMax-M** [comment]
I would love to work on this

**Comment by VaiTon** [comment]
@MadMax-M @namanrana16 sure! I'm adding you!

**Comment by kartikaysharma01** [comment]
is someone working on this issue?

**Comment by VaiTon** [comment]
@kartikaysharma01 not at the moment. Would you like to work on this?

**Comment by kartikaysharma01** [comment]
@teolemon  @VaiTon  Can you elaborate the issue?? 
How to get to the screen attached as screenshot?

**Comment by VaiTon** [comment]
I think I fixed this, anybody can check?

**Comment by teolemon** [comment]
Still here in latest internal build @VaiTon

**Comment by VaiTon** [comment]
> @teolemon @VaiTon Can you elaborate the issue??
> How to get to the screen attached as screenshot?

The link "ADEME" that you can see in the screenshot is not clickable

**Comment by mrudultora** [comment]
@kartikaysharma01 Are you working on this ?

**Comment by kartikaysharma01** [comment]
> @kartikaysharma01 Are you working on this ?

No @mrudultora , you can go ahead and take this up.

**Comment by mrudultora** [comment]
@VaiTon Fixed this. I am using default browser to open the link. Is it ok or should I use webview ?
