### ISSUE TITLE
Can't sign-in with long password

### ISSUE THREAD

**Issue by jo-so** [openfoodfacts/openfoodfacts-androidapp#2969]
**Describe the bug**
I can't sign-in, while the sign-in on the web site works. My password has 24 characters. Is this a problem for the app?

**Comment by mustaqmustu** [comment]
@teolemon can  I work on this?

**Comment by teolemon** [comment]
@mustaqmustu have you managed to establish a preliminary diagnosis/analysis ?

**Comment by mustaqmustu** [comment]
@teolemon as u labeled it...I thought it was a valid issues ...but I have made a new account and checked it...there is no issue with long password :)
![animation](https://user-images.githubusercontent.com/43813438/71449400-b7672780-2771-11ea-90fa-dd543d7d1613.gif)

**Comment by jo-so** [comment]
I tried it again, today and got it running. I've must done something wrong on the first try. Sorry to have bothered you.

**Comment by teolemon** [comment]
no worries @jo-so :-) 
Feel free to join the chat room :-) https://slack.openfoodfacts.org
