### ISSUE TITLE
Add icons to summary fields and reduce their length

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2970]
![image](https://user-images.githubusercontent.com/1689815/71443448-49881500-270b-11ea-99c1-37970e71ee51.png)

**Comment by VaiTon** [comment]
Any idea for the icons? @teolemon

**Comment by teolemon** [comment]
Those ones are from the noun project. Ping me to discuss this issue further as I'm not comfortable with the mock-up yet.

**Comment by teolemon** [comment]
https://thenounproject.com/search/?q=label&i=2265527

**Comment by teolemon** [comment]
https://thenounproject.com/search/?q=award&i=1659855

**Comment by teolemon** [comment]
https://thenounproject.com/search/?q=map&i=1605387
