### ISSUE TITLE
The Bottom navigation should be visible from the settings

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2974]
![image](https://user-images.githubusercontent.com/1689815/71522856-c57a8c80-28c6-11ea-9089-02ae2f7e4609.png)
The Bottom navigation should be visible from the settings. Otherwise, there's a timeloss involved for the user (tapping back)

**Comment by LuGO0** [comment]
I can work on this !!

**Comment by VaiTon** [comment]
@LuGO0 yup go ahead

**Comment by LuGO0** [comment]
@VaiTon  due to issue #2977 home button wont work in the preference fragment as well.Should I do it anyway?

**Comment by VaiTon** [comment]
@LuGO0 if you manage to do it, even if the home button doesn't work, it would be good.

**Comment by LuGO0** [comment]
Just one last question 
should I change the MainActivity's layout and encorporate a bottomNavigation as a child view of relative layout so that every fragment dosent need to have its own bottom Navigation and setting up its listener or 
should I do it the difficult way of extending the Preference class and then creating a custom Preference ?

**Comment by LuGO0** [comment]
and I have done the easier way around and it looks something like this
<img src="https://user-images.githubusercontent.com/30355336/71561786-2b227080-2aa1-11ea-8635-cd2afc5a4cb8.jpeg" width="200" length="300"> &nbsp; &nbsp;<img src="https://user-images.githubusercontent.com/30355336/71561815-ae43c680-2aa1-11ea-8be6-cec3982cfb5c.jpeg" width="200" length="300">

**Comment by VaiTon** [comment]
> 
> 
> Just one last question
> should I change the MainActivity's layout and encorporate a bottomNavigation as a child view of relative layout so that every fragment dosent need to have its own bottom Navigation and setting up its listener or
> should I do it the difficult way of extending the Preference class and then creating a custom Preference ?

I think the first is good for now.
