### ISSUE TITLE
Ask logged-in users to rate the app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2975]
![image](https://user-images.githubusercontent.com/1689815/71544246-f87f5780-297c-11ea-8961-b2c8d00c9289.png)
- We should disable this if the package name is the package name used for F-Droid (assuming those users either don't have the PlayStore or don't want to use it)
- This is a picture showing best practises. We should adapt it to our own app and design.

**Comment by harshlele** [comment]
should the dialog be shown only after the user has used the app for some time?

**Comment by teolemon** [comment]
I think we should only show it for logged in users.

**Comment by harshlele** [comment]
i have done most of the other stuff, wheres the feedback form? @teolemon

**Comment by teolemon** [comment]
Here it is: it's not finished: https://forms.gle/SWnx6h6QSUHcmFMy7

**Comment by harshlele** [comment]
thanks. so should i remove the feedback dialog since the form is not finished?

**Comment by teolemon** [comment]
no, we'll be able to update it on the fly, since it's a webpage.

**Comment by harshlele** [comment]
ah ok.

**Comment by teolemon** [comment]
This was merged. Can someone confirm this works well ?

**Comment by VaiTon** [comment]
Working but sometimes i get the modal even on first run.

**Comment by teolemon** [comment]
fixed
