### ISSUE TITLE
deleting Lists from "Your lists" section.

### ISSUE THREAD

**Issue by LuGO0** [openfoodfacts/openfoodfacts-androidapp#2978]
I guess there should be a way to delete Lists which we add to this section, so that we could delete any List we dont want anymore from this section .

**Comment by teolemon** [comment]
There is a (not very intuitive) way to do it by sliding across:
![image](https://user-images.githubusercontent.com/1689815/71557109-e3b8c780-2a41-11ea-83d0-f18867440ba9.png)

**Comment by LuGO0** [comment]
oh ok got it !!

**Comment by teolemon** [comment]
I have opened a bug to improve onboarding: 
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/2979
Ok to close this one ?

**Comment by LuGO0** [comment]
ya sure !!
