### ISSUE TITLE
Add onboarding tooltip for list deletion

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2979]
![image](https://user-images.githubusercontent.com/1689815/71557154-7b1e1a80-2a42-11ea-9068-6bae893839b7.png)
Add onboarding tooltip for list deletion
"Hint: you can delete a list by swiping left."

**Comment by teolemon** [comment]
Here's a code pointer for a similar tipbox already in trunk : https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/6bb72d0d0b03d4c8a4ec911a9e0f70be1bdb4c3c

**Comment by Bartoshr** [comment]
Hey. This issue was created long time ago. Is it still needed ? Can I take it ?

**Comment by VaiTon** [comment]
Yes, it is needed. Sure you can take it! I'm assigning you, thanks.
