### ISSUE TITLE
Issues with multilinguality 

### ISSUE THREAD

**Issue by sashabrava** [openfoodfacts/openfoodfacts-androidapp#2982]
**Describe the bug**
If we take a product, which description was made in German, I can add description in another language. However, there is a problem with images. 

![Screenshot_2019-12-30-11-46-11-928_org openfoodfacts scanner](https://user-images.githubusercontent.com/11160215/71579231-f394e200-2afb-11ea-91d8-ab43122b7b0a.png)

If I try to extract text from image, already existing for product, it will message me "Unable to extract ingredients from picture", and it happens because image belongs to German language while I want to make description in different language (for example Polish).

This situation gives an idea for a couple more questions for the situation, when product has ingredients list written in 5 languages.
1. Should user make 1 image of ingredients (but which language should be specified?) or make 5 small ones and add each image to its language description?

From one side, it makes sense to make one good description, and it should be enough for translation on all other languages. You made similar thing with "nutrition facts" tab, where data is international. 
However, as for that product, ingredients list contained non-translated German words. 
![Screenshot_2019-12-30-11-50-03-578_org openfoodfacts scanner](https://user-images.githubusercontent.com/11160215/71579665-f98bc280-2afd-11ea-9a38-aea34a56ac45.png)

**To Reproduce**
1. Open https://world.openfoodfacts.org/product/5411188112709 in Android app
2. Click on Edit
3. Switch language to English and visit tab "Ingredients"
4. Push the button "Extract ingredients"

**Expected behavior**
Getting list of ingredients

**Unexpected behaviour**
Getting error message 

**Smartphone (please complete the following information):**
 - Device: Xiaomi
 - OS: Android 5.1.1
 - App version 3.2.3

**Comment by teolemon** [comment]
Making the language more explicit (with a mockup): https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/2984
OCR bug (reported for French): https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/2698

**Comment by teolemon** [comment]
closing, since we have 2 more granular bugs
Making the language more explicit (with a mockup): #2984
OCR bug (reported for French): #2698
