### ISSUE TITLE
Confusing behaviour for the navigation bottom bar.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2990]
![image](https://user-images.githubusercontent.com/1689815/71661446-78773a00-2d4e-11ea-9992-bd12b31c3484.png)

**Comment by LuGO0** [comment]
In fact if we follow the same sequence of actions with any activity (offlineEdit ,BarcodeSearch...) navigable from the mainActivity the bottomNavigation bar clings on to the lists icon (in this case).

**Comment by LuGO0** [comment]
Something to do with the onResume() in MainActivity I guess !!

**Comment by VaiTon** [comment]
We should only switch fragments, not activities

**Comment by LuGO0** [comment]
But some of the buttons in bottom nav lead to different activities not fragments ,we'll have to change that !!

**Comment by LuGO0** [comment]
Or we could uncheck every option whenever the MainActivity resumes .

**Comment by VaiTon** [comment]
> 
> 
> But some of the buttons in bottom nav lead to different activities not fragments ,we'll have to change that !!

That's what i want to change. Is there any reason for not using fragments in all the 5 activities covered by the bottom navigation.

**Comment by VaiTon** [comment]
Ok, wrong idea. I looked at the code and we use Intents everywhere so this is not a good solution.

**Comment by LuGO0** [comment]
@VaiTon  if we remove all those tabs from the side-navigation drawer which are all ready present in the bottom navigation drawer then we can possibly do away with the intents problem and use 5 fragments for each of the bottom navigation buttons.

<img src="https://user-images.githubusercontent.com/30355336/72637971-69b49800-3988-11ea-94a6-9c7c38629f86.jpeg" size="300" width="400">

**Comment by teolemon** [comment]
@VaiTon I guess I have no issue with that

**Comment by LuGO0** [comment]
@teolemon  so should I remove those tabs and create all the bottom nav activities as fragments ??

**Comment by LuGO0** [comment]
or Instead of doing this tedious refactoring we could make an invisible item in the bottom nav and select it whenever we are not selecting any of the 5 bottom nav fragments.
temp fix but will make things consistent !!

**Comment by teolemon** [comment]
fixed
