### ISSUE TITLE
Refactoring for excluding redundant BottomNavigation setups in fragments

### ISSUE THREAD

**Issue by LuGO0** [openfoodfacts/openfoodfacts-androidapp#2991]
**Is your feature request related to a problem? Please describe.**
After #2983 bottom navigation for all the fragments is setup only once in the MainActivity only but there is still code which sets it up in those fragments [ homeFragment,OfflineEditFragment ... more ] redundently once they are swooped in the MainActivity. 

**Describe the solution you'd like**
All those code sections should be refactored or removed!!

![Capture](https://user-images.githubusercontent.com/30355336/71670357-9f0c9380-2d95-11ea-925b-e386ec3fe347.PNG)

**Comment by harshlele** [comment]
can i work on this?

**Comment by teolemon** [comment]
@LuGO0 Since you reported, are you working already on this ?

**Comment by LuGO0** [comment]
Yeah Im on it
