### ISSUE TITLE
Store the whole database (or a subset) locally

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#30]
Would be great for contributors if they could 
- know the state of a product when they're offline or in a foreign country (to contribute)
- read about the product offline (no 3G, poor 3G, or expensive data - either in supermarkets, or in 3G less countries or areas)

**Comment by teolemon** [comment]
200 MB for the whole DB currently. Approaches
- has to go on the SD card if available
- we have to be smart about fields we download (some are duplicates)
- we have to be smart about products selected for offline (popularity, by country)

**Comment by teolemon** [comment]
@addrum has coded this feature for Can I eat this. 
https://github.com/addrum/CanIEatThis
@itchix @jinqian : any way to ingrate it properly ?

**Comment by addrum** [comment]
More specifically:
```
CsvParserSettings settings = new CsvParserSettings();
settings.getFormat().setDelimiter('\t');
settings.setMaxCharsPerColumn(10000);
// limits to barcode, name, ingredients and traces
settings.selectIndexes(0, 7, 34, 35);

CsvParser parser = new CsvParser(settings);

// call beginParsing to read records one by one, iterator-style.
parser.beginParsing(new FileReader(products));

String[] info = null;
String[] row;
while ((row = parser.parseNext()) != null) {
    if (StringUtils.leftPad(row[0], 13, "0").equals(barcode)) {
        info = row;
        parser.stopParsing();
    }
}
```

Uses [Univocity Parsers](https://github.com/uniVocity/univocity-parsers) library which has a lot of useful features and is also "the fastest" csv parser apparently.

**Comment by Ekt0s** [comment]
Why not import a pre-generated database via the api and store it in the private folder of the application ? after that we would only to synchronize the database

**Comment by addrum** [comment]
@Ekt0s that's what I currently do (it's not in the snippet above). I pull the CSV dump and store it in the apps folder and then do the above.

You can take a look [here](https://github.com/addrum/CanIEatThis/blob/master/app/src/main/java/com/adamshort/canieatthis/Utilities.java) (method timeForUpdatePrompt) and [here](https://github.com/addrum/CanIEatThis/blob/master/app/src/main/java/com/adamshort/canieatthis/MainActivity.java) (method showDownloadPrompt) for how I let the user choose when to update the CSV (as it's done nightly). Can also check out the settings activity for the update frequency choices.

**Comment by teolemon** [comment]
Since Moodstock will discontinue the offline image recognition, we need to implement offline storage.

**Comment by aleksejrs** [comment]
This would be useful when I want to buy something that hasn't been added yet.  Because I don't use cellular Internet access often, it can cost as much as buying a duplicate product.

**Comment by teolemon** [comment]
@aleksejrs yes, having the status of products offline would be helpful for targeted contributions from stores.

A more important thing is for zones / countries with unreliable / unexistant connexion

**Comment by herau** [comment]
@teolemon you really want to download the entire products items and store it locally ?

Why not store a JSON file instead of a csv ? 
Currently our domain objects are already managed in the JSON format.

**Comment by teolemon** [comment]
@herau @addrum has an implementation where he gets the latest snapshot of the db and then syncs it daily (using the JSON API ?).
For size:
- @addrum lets you select the country to reduce the size. 
- we must make sure to try and store this on the SD card
- we shouldn't store the images (might be possible on very large SD cards, mine is 128GB)

@addrum would you consider contributing the offline part to the official app ?

**Comment by addrum** [comment]
@teolemon I don't use the JSON API for the db, I just download the CSV which is a really crap way of doing it but it works. Is there a way to download it in JSON format so I can reduce the size of the download? I can make my repo public again if someone wants to use what I have.

I can't commit time to contributing code right now as I don't have any!

**Comment by teolemon** [comment]
![screenshot_20161121-092240](https://cloud.githubusercontent.com/assets/1689815/21386258/3f50a86e-c772-11e6-9bc0-c3ffb3b4c84a.png)

**Comment by teolemon** [comment]
![screenshot_20161020-195217](https://cloud.githubusercontent.com/assets/1689815/21388033/ca30a602-c77a-11e6-939c-955f9ba65299.png)
![screenshot_20161020-195226](https://cloud.githubusercontent.com/assets/1689815/21388034/ca48b328-c77a-11e6-86dd-e396a84be720.png)

**Comment by teolemon** [comment]
https://github.com/wmentzel/dump-creator

**Comment by teolemon** [comment]
The database is now 600MB (due to the US and Swiss imports, mostly). tacite says that selecting the 1st 15 columns reduces that to 60MB.

**Comment by teolemon** [comment]
world.openfoodfacts.org/data/output-small.csv
Database at 1GO, new export: 87MB
