### ISSUE TITLE
Error while trying to set my account’s preferences (Permission refused)

### ISSUE THREAD

**Issue by Mbodin** [openfoodfacts/openfoodfacts-androidapp#3013]
**Describe the bug**
Clicking on « Gérer mon compte » (handle account) leads to an error.

**To Reproduce**
1. Go to the main screen of OpenFoodFacts.
2. Click on the sandwich icon on the upper left.
3. Click on the user name.
4. A tooth appear « Gérer mon compte ». Click on it.
5. I get redirected to https://world-fr.openfoodfacts.org/cgi/user.pl?type=edit&userid=MartinShadok&user_id=MartinShadok&user_session=null
6. This webpage just says « Erreur Permission refusée. » (Error, unallowed).

**Expected behavior**
I would have expected something else than an error. Typically a way to set my user account options.

**Screenshots**
Step 4: ![Screenshot_2020-02-09-12-44-04-542_openfoodfacts github scrachx openfood](https://user-images.githubusercontent.com/1829786/74102287-16bea280-4b3a-11ea-88e9-9ee664ca50c3.jpg)
Step 6: ![Screenshot_2020-02-09-12-44-12-287_org mozilla firefox](https://user-images.githubusercontent.com/1829786/74102289-19b99300-4b3a-11ea-9f96-697dbe3d4ea8.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi 4X
 - OS: Android 7.1.2 N2G47H
 - Browser: I have several installed on the phone, I don’t think that it applies here.

**Comment by teolemon** [comment]
Duplicates: #2932 #1543 #1965

**Comment by Mbodin** [comment]
Sure. It reads “Application Android Open Food Facts 3.2.5”. From what I see, these bugs were solved after this version was released, so I guess that the bug can be closed.
