### ISSUE TITLE
Publish Open Beauty Facts on f-droid

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#302]
org.openbeautyfacts.scanner to be consistant with the playstore. Ownership to the contact address of OFF contact@ope…

**Comment by ArchangeGabriel** [comment]
Hum… https://f-droid.org/en/packages/openfoodfacts.github.scrachx.openbeauty/ So some renaming should be requested I guess?

**Comment by ArchangeGabriel** [comment]
But I guess you know about that… https://gitlab.com/fdroid/fdroiddata/issues/647 :p

**Comment by teolemon** [comment]
@ArchangeGabriel we won't be renaming them since all the userbase is on the old package name, and the transition would be very complicated.

**Comment by ArchangeGabriel** [comment]
That’s fine. ;)
