### ISSUE TITLE
Repair failing tests in master

### ISSUE THREAD

**Issue by diskostu** [openfoodfacts/openfoodfacts-androidapp#3020]
I just checked out master and ran the tests. Some tests fail.

[Test Results - java_in_app.zip](https://github.com/openfoodfacts/openfoodfacts-androidapp/files/4216091/Test.Results.-.java_in_app.zip)

**Comment by teolemon** [comment]
Thanks a lot @diskostu 👍 
![image](https://user-images.githubusercontent.com/1689815/74726085-27100500-523f-11ea-8f24-8d12fefe41db.png)

**Comment by teolemon** [comment]
https://static.openfoodfacts.org/files/android-debug/tests_java_in_app.html

**Comment by teolemon** [comment]
#3022

**Comment by LuGO0** [comment]
![openFoodFacts](https://user-images.githubusercontent.com/30355336/77752057-d6b17180-704c-11ea-8fdc-6423993c652a.PNG)
am I doing something wrong @teolemon since I am not getting any such failed tests??

**Comment by teolemon** [comment]
I think we close this one since the build is now green. Feel free to reopen if not.
