### ISSUE TITLE
Use the new Robotoff Question auth mechanism to give credit to contributors

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3024]
Use the new Robotoff Question auth mechanism to give credit to contributors instead of Robotoff
Send headers: [“Authorization”: “Basic \(base64Credentials)“] with username:password

**Comment by VaiTon** [comment]
Fixed with 18435ca7b9f8bad4998d6c909c182e9c00e42cd5
