### ISSUE TITLE
App shows the ingredients analysis of previous product if ingredients empty

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3026]
![image](https://user-images.githubusercontent.com/1689815/75030160-d0efcb80-54a3-11ea-95b0-294e049ee316.png)

**Comment by ripetrescu** [comment]
@teolemon createad a new pull request for this https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3028
