### ISSUE TITLE
Always display analysis boxes to ask for a photo in case it's missing for ingredient analysis

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3029]
Currently, we don't show any analysis boxes when the ingredients are missing and/or the ingredients photo is missing. There's no way to nudge the user about adding them.
Always display grey analysis boxes on the product and above the scan card so it gives us, when clicked to ask for a photo of the ingredient or ask for an extraction of the ingredients by the user.

- When clicking on a grey analysis box, if it is caused by missing ingredient photo(**state:ingredients-to-be-completed** && **state:photos-to-be-validated**), ask for a photo of the ingredients
- When clicking on a grey analysis box, if it is caused by missing ingredients (**state:ingredients-to-be-completed**), ask for an extraction of the ingredients

Make sure that the user is logged in for the extraction, otherwise, redirect to login screen.

![image](https://user-images.githubusercontent.com/1689815/75476576-209a2f80-599b-11ea-8f5a-48ed808119e2.png)

**Comment by ripetrescu** [comment]
@teolemon  created https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3035

**Comment by teolemon** [comment]
thanks @ripetrescu for fixing
I'm closing the issue
