### ISSUE TITLE
Notification to propose sending offline products that need to be sent

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#304]
When (Wifi) network is detected, add a notification to propose sending offline products that need to be sent.

**Comment by Karljoones** [comment]
This needs to be an option as some users may find this annoying. If the option for this is disabled and there are products that need uploading, how about adding an icon (maybe an exclamation mark) beside the "offline edit" menu item in the navigation drawer? Subtle yet alerts the user that action is needed.

**Comment by teolemon** [comment]
That's another bug I filed, it indeed needs to be optional, but I would love an optional nudge.

**Comment by Karljoones** [comment]
Gotcha! 

Notification should have an "upload all" button on it too in that case, make it super easy to upload them without even having to go into the app.
