### ISSUE TITLE
openBeautyFacts app pops up while USB debugging

### ISSUE THREAD

**Issue by LuGO0** [openfoodfacts/openfoodfacts-androidapp#3049]
@teolemon  kindof confusing for me but do we have some sort of build variants in place for both of these apps in openFoodFacts repo?? and how do I open up the openFoodFacts App while debugging and fixing issues!!

**Comment by teolemon** [comment]
In Android Studio, make sure to select OFF as the default flavor for Open Food Facts (OBF is Open Beauty Facts, OPF - Open Products Facts, OPFF - Open Pet Food Facts)
![image](https://user-images.githubusercontent.com/1689815/77749717-c6849c80-7022-11ea-90d2-17a864a7e7a6.png)

If you already have OFF in your device, you just have to open the LogCat section

**Comment by LuGO0** [comment]
thanks @teolemon for clarification 👍
