### ISSUE TITLE
Improve the login flow

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#305]
https://github.com/dmytrodanylyk/android-process-button

![image](https://cloud.githubusercontent.com/assets/1689815/20642861/b5dc51c4-b41a-11e6-83f9-f848c002bfc5.png)

**Comment by shushilkumarr** [comment]
@teolemon could you please elaborate on what is need to be done in this issue?

**Comment by teolemon** [comment]
I was thinking of removing the progress spinner that appears on top of the screen, and using the Android Process Button instead.

**Comment by shushilkumarr** [comment]
That is a great idea. I would like to work on it.

**Comment by shushilkumarr** [comment]
This is what i have implemented.


![success-login](https://user-images.githubusercontent.com/22811731/37565040-af7c0138-2ac7-11e8-9fde-7609019f7f24.gif)
![failed-login](https://user-images.githubusercontent.com/22811731/37565039-af1d4c92-2ac7-11e8-8184-66f30deb1444.gif)

**Comment by teolemon** [comment]
You have four ways to show state:
- the blue popup
- the text below the signup button
- the black overlay
- the black snackbar.

You need to choose one :-)

**Comment by shushilkumarr** [comment]
I'll remove the extra stuff and keep the button only

**Comment by shushilkumarr** [comment]
This is what it looks like now.

![success-login](https://user-images.githubusercontent.com/22811731/37593183-2037ef34-2b97-11e8-966f-50d117fc2a4a.gif)

![failed-login](https://user-images.githubusercontent.com/22811731/37593182-1fdb222c-2b97-11e8-83cf-721c92aa9bd7.gif)

**Comment by shushilkumarr** [comment]
@teolemon can you please review the changes made?

**Comment by teolemon** [comment]
looks good :)
