### ISSUE TITLE
Make the requests faster and less network intensive by using the ?fields= parameter

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3058]
Currently we send the following query when clicking on a Brand: `https://world.openfoodfacts.org/brand/Veuve%20Clicquot/1.json`  **(6.66 KB for 1 product)**

We should ask instead:
`https://world.openfoodfacts.org/brand/Veuve%20Clicquot/1.json?fields=brands,product_name_fr,product_name,image_small_url,image_front_thumb_url,quantity,nutrition_grades_tags` **(417 Bytes for 1 product)**

If you multiply the difference by a larger number of products (as is often the case, here there's a spelling mistake on the brand, thus only 1 product), you get a **much larger size difference** that's at least (6,2KB * N) (actually more, since there are no ingredients not nutrients on this champagne).
This might not matter on 5G or 4G, but it does matter on EDGE, 3G, and when you're in a supermarket with very bad network.

**Notes:**
- I added both image_small_url,image_front_thumb_url but in truth we can keep only the one we actually use.
- I added both product_name_XX and product_name to be able to display the product name in the language of the app, if available.

This should be done for  **Products to be completed** and **Facets** (the pages that appear when you click a value on a product page). Search and Scan have already been optimized

**Comment by teolemon** [comment]
OpenFoodAPIService.java 
eg: 
```   @GET("additive/{Additive}.json")
    Call<Search> byAdditive(@Path("Additive") String Additive);``` 

as opposed to an optimized query:
```
    @GET("cgi/search.pl?search_simple=1&json=1&action=process")
    Call<Search> searchProductByName(@Query("fields") String fields, @Query("search_terms") String name, @Query("page") int page);
```

**Comment by Varsha-29** [comment]
I'm taking up this issue

**Comment by teolemon** [comment]
I'm reopening this issue, as there are queries we can optimize:
Products to be completed
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/7aa6e6d25e76f538714236504c48a167baed7665/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/services/OpenFoodAPIService.java#L354 

Additives
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/7aa6e6d25e76f538714236504c48a167baed7665/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/services/OpenFoodAPIService.java#L333

States
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/7aa6e6d25e76f538714236504c48a167baed7665/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/services/OpenFoodAPIService.java#L339

**Comment by Varsha-29** [comment]
I will take up the issue

**Comment by Varsha-29** [comment]
Hi @teolemon , I have few queries 
1. [https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/7aa6e6d25e76f538714236504c48a167baed7665/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/services/OpenFoodAPIService.java#L333](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/7aa6e6d25e76f538714236504c48a167baed7665/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/services/OpenFoodAPIService.java#L333)

I guess this is being used currently in the unit test and not used in the application to display information from this in UI. Is my understanding right? 

2.[https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/7aa6e6d25e76f538714236504c48a167baed7665/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/services/OpenFoodAPIService.java#L339](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/7aa6e6d25e76f538714236504c48a167baed7665/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/services/OpenFoodAPIService.java#L339)

The necessary fields are added as a query parameter. May I know what needs to be changed here?

**Comment by teolemon** [comment]
1. my bad
2. Line 267, there's another state call
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/7aa6e6d25e76f538714236504c48a167baed7665/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/services/OpenFoodAPIService.java#L267

**Comment by Varsha-29** [comment]
> 
> 
>     1. my bad
> 
>     2. Line 267, there's another state call
>        https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/7aa6e6d25e76f538714236504c48a167baed7665/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/services/OpenFoodAPIService.java#L267

The second one is also used only in unit test I guess. Can I add the following fields and change the unit tests? 
Fields : brands,product_name_xx,product_name,image_small_url,quantity,nutrition_grades_tags
