### ISSUE TITLE
Use HTTPS for all connections

### ISSUE THREAD

**Issue by rugk** [openfoodfacts/OpenFoodFacts-androidApp#306]
HTTPS is still not used for all connections, e.g. for statistics.openfoodfacs.com it is still missing.

Please do not send any data in plaintext over the wire!

**Comment by teolemon** [comment]
Hi @rugk, there's no statistics.openfoodfacts.org that I know of.
The SSL part is a work in progress as you saw on the server part.

**Comment by teolemon** [comment]
Fixed. Will be released soon.
