### ISSUE TITLE
Bottom panel bug

### ISSUE THREAD

**Issue by sashabrava** [openfoodfacts/openfoodfacts-androidapp#3062]
You have a great update of app interface. However, there is a small problem on the bottom panel remained.
If I:
1. Open the app
2. Choose then "history" tab
3. Return back,

the bottom panel still highlights "History" button.

If I: 
1. Choose "Scan" tab
2. Return back,

the blue button highlight on bottom panel disappears.

**Screenshots**

![Screenshot_2020-04-11-17-35-40-993_org openfoodfacts scanner](https://user-images.githubusercontent.com/11160215/79220157-cc1c1800-7e53-11ea-9eb8-24dad16e9737.png)

**Smartphone:**
 - Device: Xiaomi Redmi 3
 - OS: Android 5.1.1
 - Version 3.2.9

**Comment by VaiTon** [comment]
Fixed in #3064.
