### ISSUE TITLE
History export does not seem to be working

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3076]
History export does not seem to be working. A transient tooltip says history is being exported. 

1. No confirmation that the export has completed
2. No notification to open the file (like in the list export feature)
3. No way to share the file using the Android Share Sheet.
4. Possibly a broken export.

We should try to fix or implement as much of 1, 2, 3 and 4 as possible.

**Comment by VaiTon** [comment]
We should refresh this issue.

**Comment by kartikaysharma01** [comment]
I think the history export and delete buttons have been disabled .
@VaiTon  @teolemon Does this issue need to be updated?

**Comment by teolemon** [comment]
mostly fixed, closing
