### ISSUE TITLE
On some Samsung Galaxy devices, the front image does not appear

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3079]
On some Samsung Galaxy devices, the front image does not appear in the product page. We need to try to reproduce that in an emulator. 
This is a screenshot from a contributor with the Galaxy s6 edge
![image](https://user-images.githubusercontent.com/1689815/80802022-626b7000-8bae-11ea-978b-86e546e7a470.png)

**Comment by CharlesNepote** [comment]
**Samsung Galaxy A5 2016 (SM-A510F)** - fresh install - Android 7.0:
* same issue as described
* also, pictures don't load when in search results

See video: https://drive.google.com/file/d/1-25KBluAgtqYckpOJTuWGsDo8Fv3xh_5/view?usp=sharing

**Samsung Galaxy A5 2017 (SM-A520F)** - recent install - Android 8.0:
* no issues

**Samsung Galaxy S9 (SM-G960F)** - recent install - Android 10:
* no issues

**Comment by huzaifaiftikhar** [comment]
Closed via #3544
