### ISSUE TITLE
Replace ButterKnife with the android Data Binding library.

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-androidapp#3092]
As the introduction of android view/data binding, Butter Knife is now a deprecated tool and will only be updated with critical bug fixes. This milestone is to keep track of our migration to view binding.

### Files to be changed:

 - [x] AddProductNutritionFactsFragment.java (#3093)
 - [x] AddProductOverviewFragment.java (#3158)
 - [ ] AddProductPhotosFragment.java
 - [x] AllergensAlertFragment.java (#3158)
 - [ ] BaseFragment.java
 - [ ] ContributorsFragment.java
 - [ ] FindProductFragment.java
 - [x] HomeFragment.java (#3158)
 - [ ] OfflineEditFragment.java
 - [ ] AdditivesExplorer.java
 - [ ] AddProductActivity.java
 - [ ] BaseActivity.java
 - [x] ContinuousScanActivity.java (#3091)
 - [x] HistoryScanActivity.java (#3091)
 - [x] ImagesSelectionActivity.java (#3091)
 - [x] WelcomeActivity.java (#3091)
 - [x] ImageZoomActivity.java (#3158)
 - [x] LoginActivity.java (#3093)
 - [ ] MainActivity.java
 - [x] ProductBrowsingListActivity.java (#3158)
 - [ ] ProductComparisonActivity.java
 - [x] ProductImageManagementActivity.java (#3158)
 - [x] YourListedProducts.java (#3158)
 - [ ] CategoryActivity.java
 - [ ] ProductActivity.java
 - [ ] ProductFragment.java
 - [ ] EnvironmentProductFragment.java
 - [x] IngredientsProductFragment.java (#3158)
 - [ ] IngredientsAnalysisProductFragment.java
 - [x] SplashActivity.java (#3091)

**Comment by VaiTon** [comment]
Closed with 52321d8bd2bfc5f48b32a595e721f09120d574b5

**Comment by teolemon** [comment]
👏
