### ISSUE TITLE
Make it possible to input all nutrition facts

### ISSUE THREAD

**Issue by Forger7** [openfoodfacts/openfoodfacts-androidapp#3099]
When adding nutrition facts you can't add certain types.
E.g. "Fruits, vegetables, nuts and rapeseed, walnut and olive oils" is only available if you try it on the website.

**Comment by teolemon** [comment]
Hi @Forger7 
currently, the nutrition list is hardcoded in the app. #2357 should solve your issue. Also, please note that an estimate of "Fruits, vegetables, nuts and rapeseed, walnut and olive oils" is now computed from the ingredient list.

**Comment by Forger7** [comment]
Thank you for clarifying. I can not follow on the estimate being computed, though. Doesn't do it for me on app version 3.2.9 or on the website.

**Comment by teolemon** [comment]
It's not shown for the same reason. I'm closing this issue, and putting a P1 on #2357 which will solve it.
