### ISSUE TITLE
A "NullPointerException" could be thrown; "textContent" is nullable here - EditTextUtils.java

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3101]
![image](https://user-images.githubusercontent.com/1689815/81499449-15814b00-92cc-11ea-8401-56251e432ee5.png)
https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-androidapp&open=AXGdyzDi3GLN02jDjcth&resolved=false&types=BUG

**Comment by raghulvaikundam** [comment]
@teolemon, I believe the file does not exist anymore in the master

**Comment by VaiTon** [comment]
> @teolemon, I believe the file does not exist anymore in the master

Exactly, that's what I was going to point out. Closing for now.
