### ISSUE TITLE
Use a thread-safe type; adding "volatile" is not enough to make this field thread-safe.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3102]
![image](https://user-images.githubusercontent.com/1689815/81499490-58dbb980-92cc-11ea-88ec-b1fac6404058.png)
https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-androidapp&open=AXGdyy_x3GLN02jDjctY&resolved=false&types=BUG

**Comment by raghulvaikundam** [comment]
@teolemon, I could not find the file and moreover sonarcloud does not show this error anymore

**Comment by teolemon** [comment]
Ok, thanks. Still unsure how I got those two obsolete issues. Closing the issue.
