### ISSUE TITLE
Truncate values to 2 digits after the comma

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3136]
Truncate values to 2 digits after the coma, so that we don't get ugly values like that.
![image](https://user-images.githubusercontent.com/1689815/82185556-ad44f180-98e9-11ea-8285-0d2104165c0d.png)

**Comment by VaiTon** [comment]
Should be fixed. @teolemon ?

**Comment by teolemon** [comment]
no it's not.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/90654480-b921b600-e240-11ea-863e-840a7542672b.png)
![image](https://user-images.githubusercontent.com/1689815/90654497-bd4dd380-e240-11ea-84f9-cfdf35583dc9.png)

**Comment by mrudultora** [comment]
@teolemon @VaiTon  I think this issue has been resolved. Attaching the screenshot of the same product.
![img](https://user-images.githubusercontent.com/65870389/105608096-f37f1880-5dc7-11eb-848f-7e59f88c16a9.jpeg)
