### ISSUE TITLE
Upgrade to JUnit 5

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-androidapp#3137]
And upgrade min java required to v8

**Comment by VaiTon** [comment]
Apparently as of Android plugin 3.0.0 Java 8 is supported.

**Comment by teolemon** [comment]
Does that include bumping the min version of Android ?

**Comment by VaiTon** [comment]
> 
> 
> Does that include bumping the min version of Android ?

No, android studio takes care of the "desugaring".

**Comment by teolemon** [comment]
👍 
I think we should at least do one more release with all fixes before we could consider version bumps. And also, it needs to bring something to the table feature wise, IMO.

**Comment by teolemon** [comment]
@VaiTon did we upgrade to Java8 ?

**Comment by VaiTon** [comment]
> 
> 
> @VaiTon did we upgrade to Java8 ?

Yup, I think we did it with the last AGP update.
