### ISSUE TITLE
Pictures are lost if sent anonymously

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#315]
**Steps to reproduce**
1. Log out your Open Food Facts account.
2. Scan a new product and take a front picture
3. Hit Send.

**Expected result**
Product appears with photo on server

**Result**
No photo arrives on the server

**Comment by herau** [comment]
how you logout from the android app ?

**Comment by teolemon** [comment]
1. You switch to a custom version ;)
2. You wipe the app cache (for various reasons, space being one)
3. You change your password online

**Comment by teolemon** [comment]
Or you don't login.

**Comment by herau** [comment]
ok and the expected behavior is to no able to send product if the user is not connected ?

**Comment by teolemon** [comment]
To be able to send them, even if the user is not connected. Which is not the case.

**Comment by teolemon** [comment]
Thanks @herau 
Can we release this as soon as possible ? This results in lost contributions.
