### ISSUE TITLE
Application Korean Translation

### ISSUE THREAD

**Issue by GaYoung0420** [openfoodfacts/openfoodfacts-androidapp#3150]
Is it possible to translate the application into Korean? If possible, how can I translate it?

**Comment by VaiTon** [comment]
You can contribute to translations on [Crowdin](translate.openfoodfacts.org).

Also join us [on Slack](slack.openfoodfacts.org)!

**Comment by GaYoung0420** [comment]
How can I join the slack? When I click on the link, there's not found on the page.
