### ISSUE TITLE
Nutriscore displayed in the history is different from the product page

### ISSUE THREAD

**Issue by Fabe56** [openfoodfacts/openfoodfacts-androidapp#3161]
Hi,
This not happen for every product, but I have sometimes noticed this inconsistency between the Nutriscore displayer in the history vs the product page.

For example, steps to reproduce the behavior:
1. Go to Lait écrémé - Envia - https://fr.openfoodfacts.org/produit/20842680/lait-ecreme-envia
2. Then click on 'history'
3. On history page, the Nutriscore displayed is D versus B on product page

**Screenshots**
![Screenshot_20200522-093050](https://user-images.githubusercontent.com/12115500/82661993-63cc0d80-9c2d-11ea-8c6f-24c8f5d07afb.png)
![Screenshot_20200522-093057](https://user-images.githubusercontent.com/12115500/82662001-662e6780-9c2d-11ea-9b2b-ad4a232cefa9.png)

**Smartphone (please complete the following information):**
 - Device: Essential Phone PH-1
 - OS: Android 10
 - Open Food Facts update from 12th of march 2020

**Comment by teolemon** [comment]
Hi, it's because a number of values are stored in the History, and not refreshed, including the product name, image, and Nutri-Score. We need to set up a refresh mechanism (on pull to refresh ?)

**Comment by teolemon** [comment]
@Fabe56 I opened #3162 which is a more general fix to your problem
