### ISSUE TITLE
Make it possible to refresh the history (causes big Nutri-Score problem)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3162]
Make it possible to refresh the history on pull down.
A number of values are currently stored in the History, and not refreshed, including 
- the product name
- image
- Nutri-Score. 
We got reports of users complaining the Nutri-Score was not the right one as a result, that the photos were not up-to-date…
We need to set up a refresh mechanism (on pull to refresh ?) so that we can have an up-to-date history. This includes altering the entries, and fetching the new values using the API

**Comment by VaiTon** [comment]
At the moment the scroll mechanism is very "spaghetti code". Everything is on BaseActivity I think.

I will investigate and update here.

**Comment by naivekook** [comment]
Is it still actual?

**Comment by VaiTon** [comment]
I think it is. We store history products in the db when we scan them/we open them. The app doesn't refresh them when swiping down on the history screen, it just re-queries the db. So yes, it is actual. @naivekook

**Comment by naivekook** [comment]
@VaiTon I can take it
as I understand correct on screen created and pull-to-refresh events I need to get all items from db, perform an API call `getProductByBarcode`, update database and show the info to the user? 
is it ok if will make a refactoring of screen? I want to move logic from activity to viewmodel class
