### ISSUE TITLE
Source text is wrong for the "Nutrition facts" tabs

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#318]
![screenshot_20161130-132007](https://cloud.githubusercontent.com/assets/1689815/20758460/2a013b76-b71a-11e6-904e-79c19474b17e.png)

The issue is present on trunk
https://github.com/openfoodfacts/OpenFoodFacts-androidApp/blob/986c897faab81fd6849b4a515feef82319b36ffc/app/src/main/res/values/strings.xml#L16
```
#. Nav Drawer Product Menu Items
msgctxt "nav_drawer_items_product:3"
msgid "Back to menu"
msgstr "Retour à l'accueil"
```
```
<!-- Nav Drawer Product Menu Items -->
    <string-array name="nav_drawer_items_product">
        <item>Summary</item>
        <item>Ingredients</item>
        <item>Nutrition</item>
        <item>Back to menu</item>
    </string-array>
```

**Comment by teolemon** [comment]
#. Nav Drawer Product Menu Items
msgctxt "nav_drawer_items_product:3"
msgid "Back to menu"
msgstr "Retour à l'accueil"

**Comment by teolemon** [comment]
<string-array name="nav_drawer_items_product">
        <item>Summary</item>
        <item>Ingredients</item>
        <item>Nutrition</item>
        <item>Back to menu</item>
    </string-array>

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/OpenFoodFacts-androidApp/blob/986c897faab81fd6849b4a515feef82319b36ffc/app/src/main/res/values/strings.xml#L16

**Comment by teolemon** [comment]
On trunk

**Comment by teolemon** [comment]
@itchix why is back to menu in the array ?

**Comment by herau** [comment]
@teolemon the master branch contains the right values.

You mentioned a code in the `dev` branch which has been merged in the master 8 month ago. I think we can delete it :-)

https://github.com/openfoodfacts/OpenFoodFacts-androidApp/blob/master/app/src/main/res/values-fr/strings.xml
