### ISSUE TITLE
 When adding a photo from the picture manager, the app redirects to an empty scan window

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3180]
**Describe the bug**
 When adding a photo from the picture manager, the app redirects to an empty Scan window. I'd expect to be back to the product, as it was the case before.

**To Reproduce**
scan -> swipe up -> tap picture -> tap chekcbox
resultats :
Playstore : return to product page & scan OK
Master : retour to scan KO

**Comment by teolemon** [comment]
slide up
tap the photo
tap on select new photo button
select new photo
tap on the checkbox to validate
you’re back to the scanner on master
and in prod, you’re back to the product page
(which is the desirable behaviour)

**Comment by runyud** [comment]
Hi I would like try to debug this issue if possible
