### ISSUE TITLE
Include brand and weight in search results.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#319]
![views-splashactivity-12012016115407](https://cloud.githubusercontent.com/assets/1689815/20791423/4519fe04-b7bd-11e6-977f-a8fded0dead6.png)

**Steps to reproduce:**
- Search by name
- Search for Nutella
- Be confused by many jars or Nutella. Which one is the 850g jumbo version ?

**Proposed solution**
- Include weight and brand, in addition to the product name

**Comment by teolemon** [comment]
(Nutella is one of the tops queries on Open Food Facts)

**Comment by herau** [comment]
@teolemon any specification about the UX ?

**Comment by teolemon** [comment]
Is the result view already using something standard in terms of library ? If not, is there a standard one we could use, where layout has been taken care of ?

**Comment by herau** [comment]
@teolemon does i have to wait the évolution of the search api (same result as jqm but in json) ?

**Comment by teolemon** [comment]
in the JSON version. You don't have to wait, indeed. As you wish. Opening the server bug right now.

**Comment by herau** [comment]
So does we wait the new version of the api or you want the evolution right now ?

**Comment by teolemon** [comment]
It can wait :-)
Contribution is the sore point.

**Comment by teolemon** [comment]
A bug has been opened for the new API at https://github.com/openfoodfacts/openfoodfacts-server/issues/554
