### ISSUE TITLE
Too much salt is very bad for the app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#320]
Product to reproduce: 8712100776403

![screenshot_20161202-124800](https://cloud.githubusercontent.com/assets/1689815/20833113/36d0f4a2-b88e-11e6-8c29-8d12fb747354.png)

**Comment by herau** [comment]
trash this view or why not a simple array with all the data ?

**Comment by asmoth360** [comment]
I don't like this view neither, but for this issue, a simple round to 2 or 3 decimals should be ok.

**Comment by herau** [comment]
@itchix could you handle this issue please ?
