### ISSUE TITLE
Weird behaviour on Carbon Footprint

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3206]
The size changes for some reason. Check if the bug is the same on the web and iPhone.
**Product where we compute the carbon footprint**
![image](https://user-images.githubusercontent.com/1689815/83656215-8c55ef00-a5bf-11ea-8aae-f638186ac563.png)
![image](https://user-images.githubusercontent.com/1689815/83656227-924bd000-a5bf-11ea-9fba-de912ad8e1dc.png)

**Products where I'm not that sure:**
![image](https://user-images.githubusercontent.com/1689815/83656321-ad1e4480-a5bf-11ea-890f-e47bc8696157.png)
![image](https://user-images.githubusercontent.com/1689815/83656341-b27b8f00-a5bf-11ea-922d-94ad74cad53d.png)
![image](https://user-images.githubusercontent.com/1689815/83656359-b90a0680-a5bf-11ea-871c-b098c74e1cd3.png)
![image](https://user-images.githubusercontent.com/1689815/83656374-bdceba80-a5bf-11ea-8fcb-2644011bb5e8.png)

**Comment by stephanegigandet** [comment]
My guess is that the size changes because the NOVA indication is larger because of the text:
"Sans additifs"
"5 additifs"

**Comment by teolemon** [comment]
I'd like a double check on the values we return in the API for those.

**Comment by stephanegigandet** [comment]
Salmon: https://world.openfoodfacts.org/api/v1/product/3302741858108?fields=code,product_name,environment_impact_level -> en:high

Soy: https://world.openfoodfacts.org/api/v1/product/3188720003727?fields=code,product_name,environment_impact_level -> en:low

Pork: https://world.openfoodfacts.org/api/v1/product/3188720001624?fields=code,product_name,environment_impact_level -> en:high

Everything looks as expected. I stand by my guess: it's just the "Sans additifs" text that is longer. I'm not sure what's the best way to solve it.

**Comment by teolemon** [comment]
ok, closing
