### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by Gongjuhyeon** [openfoodfacts/openfoodfacts-androidapp#3208]
Could you please Merge the Korean translation part through Crowdin?

**Comment by teolemon** [comment]
I'm doing that as we speak @Gongjuhyeon 👍  
Thanks a lot for all the work you've been doing. Are you on the Open Food Facts slack ?
http://slack.openfoodfacts.org/
It would be very useful to coordinate to translate ingredients and categories in Korean (they are not handled using Crowdin)

**Comment by teolemon** [comment]
done. Closing the issue
