### ISSUE TITLE
When using OBF, OPF or OPFF, mention you can login with an OFF account

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3209]
When using OBF, OPF or OPFF, there's no way to know that you can login with an OFF account.

if flavour = obf or opf or opff, we could add: "If you have an Open Food Facts account, you can login to Open Beauty Facts with it"

**Comment by kartikaysharma01** [comment]
@teolemon I have created a pull request for this. Let me know if there is any change to be made,
