### ISSUE TITLE
The Kotlin build is messing up with Android Studio and preventing me from building an AAB

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3247]
![image](https://user-images.githubusercontent.com/1689815/84563037-e8a3d600-ad58-11ea-8494-129df7eecddc.png)
![image](https://user-images.githubusercontent.com/1689815/84563041-f3f70180-ad58-11ea-9b90-8bc21d1f1a23.png)
![image](https://user-images.githubusercontent.com/1689815/84563043-fce7d300-ad58-11ea-8263-e875cc2c123c.png)
![image](https://user-images.githubusercontent.com/1689815/84563050-0c671c00-ad59-11ea-8535-bbba0b9bb428.png)

**Comment by teolemon** [comment]
```
It is not fully supported to define distributionSha256Sum in gradle-wrapper.properties.
Using an incorrect value may freeze or crash Android Studio.
Please manually verify or remove this property from all of included projects if applicable.
For more details, see https://github.com/gradle/gradle/issues/9361.

Use "3fd824..." as checksum for https://services.gradle.org/distributions/gradle-6.4.1-all.zip and sync project
Remove distributionSha256Sum and sync project
Open Gradle wrapper properties
```

**Comment by teolemon** [comment]
I clicked that, and it seems back to normal 🤷

**Comment by VaiTon** [comment]
For future reference see here: https://github.com/gradle/gradle/issues/9361#issuecomment-591685809
