### ISSUE TITLE
Impossible to delete a portion that I inputed by mistake

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3248]
I inputed kJ in the portion field by mistake. It's impossible to delete a portion that I inputed by mistake. An empty edit is sent to the server.

**Comment by VaiTon** [comment]
What do you mean? Don't we get that with an empty field?

**Comment by teolemon** [comment]
My understanding is that as the portion is now empty, it must somehow consider there's nothing to do.

**Comment by VaiTon** [comment]
Should had been fixed by 662de3a4b356dfcfc8b5ffcb553abf0a40360760.
