### ISSUE TITLE
Front product picture not showing in Open Beauty Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3262]
![image](https://user-images.githubusercontent.com/1689815/84907466-84b04300-b0b3-11ea-976d-ea55678b5426.png)
The images (and the take new image buttons) have been disabled in Open Beauty Facts. It was probably the extra white space we removed @VaiTon

**Comment by VaiTon** [comment]
Cannot replicate cc @teolemon

**Comment by teolemon** [comment]
Can't reproduce.
