### ISSUE TITLE
Replace the photo dropdown system by a flat one (temporary fix)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#327]
Replace the current dropdown by this. Does the same thing but much quicker.

![img_20161206_175008](https://cloud.githubusercontent.com/assets/1689815/20935116/c723d608-bbdd-11e6-9ad1-2a90ef382388.jpg)

**Comment by itchix** [comment]
Or using that : https://github.com/stepstone-tech/android-material-stepper
It's in the guideline of android material : https://material.io/guidelines/components/steppers.html

**Comment by teolemon** [comment]
I think steppers are a good idea for a guided mode. I see the current mode as a "I'm in a hurry" mode

- I'm in a hurry mode:   click on Add front photo, click to take photo, click on Add ingredient photo, click to take photo,  click on Add nutrition photo, click to take photo, type brand, weight and name: up to 6 clicks
- Steppers:  click to take photo, click next, click to take photo, click next, click to take photo, click next, type brand, weight and name, click done: 6 clicks

Steppers make you feel everything is compulsory. It can be a good thing in some cases, but also piss off power contributors, and deter contributions (it will take too much time)

cc @herau as well

**Comment by teolemon** [comment]
Here's the link to a guided mode feature proposal: https://github.com/openfoodfacts/OpenFoodFacts-androidApp/issues/269

Also, what we could do is jump to the product view, and let the user add pictures from the tabs.
![image](https://cloud.githubusercontent.com/assets/1689815/21749278/efc5ef42-d59b-11e6-8c57-a464d3189623.png)

**Comment by herau** [comment]
@teolemon in my opinion, i will put a floating photo button (like in the search branch with the scanner button)

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21965386/0f46fb04-db5f-11e6-9008-6d8434c3ee10.png)
![image](https://cloud.githubusercontent.com/assets/1689815/21965387/152d6fda-db5f-11e6-80e0-2fb6f66c4089.png)

**Comment by teolemon** [comment]
Fixed.
