### ISSUE TITLE
Ensure the crash reports can be deobfuscated

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3272]
Ensure the crash reports can be deobfuscated. It seems that maybe after the migration to Kotlin or a Gradle update, crash reports are now obfuscated.
We use proguard, but it seems that R8 took charge: https://developer.android.com/studio/build/shrink-code

**Comment by VaiTon** [comment]
https://developer.android.com/studio/build/shrink-code#decode-stack-trace

**Comment by teolemon** [comment]
https://docs.sentry.io/clients/java/integrations/#proguard

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/85195791-b6085900-b2d5-11ea-9605-2cbac161afd2.png)
The deobfuscation files are already in the AAB theoretically. So we might be putting the old Proguard instead of the R8 one ?

**Comment by philippeauriach** [comment]
It seems that crash reports are already deoffuscated in sentry ? (this should be part of the sentry gradle integration that I made). Is there a problem with a specific issue ? See this one for example : https://sentry.io/share/issue/6ecab9e534d2485b921ad3d077ae6184/ (yes, we can make public link to issues in sentry :D )

**Comment by teolemon** [comment]
There's a problem with this specific issue (and others) that appears obfuscated ?

**Comment by philippeauriach** [comment]
Which one ? The one I sent is deoffuscated (you can even switch between "symbolicated" and "Unsymbolicated")

**Comment by VaiTon** [comment]
On github the sentry bot reports the issues as "Unsymbolicated"

**Comment by VaiTon** [comment]
But on the dashboard i can see the deobfuscated stack trace.

**Comment by philippeauriach** [comment]
Where on github ?

**Comment by VaiTon** [comment]
> 
> 
> Where on github ?

See the issues made by the sentry bot.

**Comment by philippeauriach** [comment]
> > Where on github ?
> 
> See the issues made by the sentry bot.

I did, and I cannot find any example with offuscated data. See the latest for example : https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3282
