### ISSUE TITLE
Image manager not listing the "on-server" images anymore

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3293]
Image manager not listing the "on-server" images anymore
![image](https://user-images.githubusercontent.com/1689815/85333749-66df4580-b4da-11ea-846e-0ad67f01171d.png)

**Comment by VaiTon** [comment]
Any error in console?

**Comment by raphael0202** [comment]
I have the same error. Same issue (probably linked) in the image tab.
