### ISSUE TITLE
Stores autosuggest

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3301]
The Stores taxonomy is available: https://static.openfoodfacts.org/data/taxonomies/stores.json
It can be loaded for stores autocomplete in add/edit mode.

**Comment by CloCkWeRX** [comment]
I'd go further and suggest a one click UI control to "use same store as last product"; on the assumption you are in the same location for a series of products

**Comment by VaiTon** [comment]
https://static.openbeautyfacts.org/data/taxonomies/stores.json is 404

**Comment by teolemon** [comment]
404 fixed @VaiTon

**Comment by teolemon** [comment]
Postponing to a future release

**Comment by kartikaysharma01** [comment]
@teolemon I am working on this. Can you please assign this to me?
