### ISSUE TITLE
Let the user decide if products should be sent on 3G or Wifi

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#332]
Let the user decide if products should be sent on 3G or Wifi.
In some countries, users prefer to avoid Mobile networks because data isn't unlimited.

**Comment by teolemon** [comment]
@jinqian do you have any advice on this ?

**Comment by Karljoones** [comment]
I was thinking of having a look at this, we could just save the product offline if they do not wish to upload them. What do you think? @jinqian did you ever do anything with this?

**Comment by teolemon** [comment]
I was bugging Qian with too many questions at the time :)

**Comment by Karljoones** [comment]
@teolemon No worries, I'll take it over and hopefully have a PR for it this evening!
