### ISSUE TITLE
[GreenDAO] OfflineSavedProduct.java: #1 @56: Pb(646) Method references are allowed only at source level 1.8 or above

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3321]
The app does not build anymore

> Task :app:greendao FAILED
Found 1 problem(s) parsing "/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/OfflineSavedProduct.java":
#1 @56: Pb(646) Method references are allowed only at source level 1.8 or above (ID: 1610613382; error: true)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:greendao'.
> Found 1 problem(s) parsing "/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/OfflineSavedProduct.java". First problem:
  Pb(646) Method references are allowed only at source level 1.8 or above (1610613382 at line 56).
  Run gradle with --info for more details.

Might be related to : https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/73dda5fe330e473311ac169997a288e6668ff33a

**Comment by VaiTon** [comment]
https://github.com/greenrobot/greenDAO/issues/413 is blocking. Going for a workaround.

**Comment by softboy99** [comment]
@VaiTon ,what workaround do you use?
