### ISSUE TITLE
Additives browser broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3329]
![image](https://user-images.githubusercontent.com/1689815/87205140-05efa400-c307-11ea-9d00-7f6fd5a1410c.png)

**Comment by VaiTon** [comment]
I cannot reproduce the issue. What commit are you using?

**Comment by VaiTon** [comment]
I cannot reproduce the issue. What commit did you built?

**Comment by teolemon** [comment]
It looks fixed in the current build I have @VaiTon closing for now
