### ISSUE TITLE
Settings refinement proposal

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3340]
![image](https://user-images.githubusercontent.com/1689815/87650714-61c88b80-c752-11ea-84ae-00e59b8506fe.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/87650919-aeac6200-c752-11ea-87cd-ba1b0c9dcedc.png)

**Comment by WildOrangutan** [comment]
I can work on this. Do you have any preference, which library to use, for 3-way toggle button (in e.g. "Preffered energy unit")?
