### ISSUE TITLE
Add the Nutri-Score in the "Products to be completed" activity by refactoring it

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3341]
- [ ] Add the Nutri-Score in the "products to be completed" activity so that power users can see which new products have a Nutri-Score, and which ones don't have one
- [ ] Get the occasion to standardize the activity with the other list activities that already show the Nutri-Score

**Comment by Varsha-29** [comment]
I will take up this issue
