### ISSUE TITLE
Add a conditional photo button to collect labels

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3363]
Add a conditional photo button to collect labels
![image](https://user-images.githubusercontent.com/1689815/88376638-19d2e580-cd9e-11ea-8676-5e2864900f47.png)

**Comment by IpsumCapra** [comment]
I'd like to help with this, is this still open?

**Comment by VaiTon** [comment]
@IpsumCapra yes it is! I'm assigning you! 👍

**Comment by IpsumCapra** [comment]
Could you please give me a clearer idea what you'd like to see, what kind of image-assets are needed, what code is needed?

**Comment by VaiTon** [comment]
Sure! As you can see when you open a product without a foto, there is a button asking to take a photo of the front of the product. The same should happen for labels. Am I right @teolemon? Do we have a particular field for it on the API?

**Comment by teolemon** [comment]
@IpsumCapra @VaiTon https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3543 is better documented. Would you solve this one instead, and I close this one ?

**Comment by IpsumCapra** [comment]
While I'd love to help, I'm very low on time right now. I can take a look later but it'd be better not to assign it to me as i can't work on it now.

**Comment by VaiTon** [comment]
Closing in favor of #3543.
