### ISSUE TITLE
HEX color codes in settings ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3367]
HEX color codes in settings ?
![image](https://user-images.githubusercontent.com/1689815/88456089-25480e80-ce7b-11ea-9417-212dfd274389.png)

**Comment by teolemon** [comment]
Analysis by @philippeauriach :
instead of putting `android:summary=` : `android:summaryOn=` and  `android:summaryOff=` with the same text
But it should work with just: `android:summary=`: that's weird

**Comment by VaiTon** [comment]
I also saw this, confirmed.

**Comment by teolemon** [comment]
this seems fixed. closing
