### ISSUE TITLE
Double quotes (") in product name are replaced with “';”

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-androidapp#3376]
![image](https://user-images.githubusercontent.com/1689815/88927700-1943be80-d278-11ea-88f3-2af5864ef94f.png)

https://world.openfoodfacts.org/product/4600528343588/%D1%81%D0%BE%D1%83%D1%81-%D0%BC%D0%B0%D0%B9%D0%BE%D0%BD%D0%B5%D0%B7%D0%BD%D1%8B%D0%B9-%D1%81%D0%BC%D0%B5%D1%82%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9-%D1%81-%D0%B3%D1%80%D0%B8%D0%B1%D0%B0%D0%BC%D0%B8-%D0%B0%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F-astoria

### Part of
- #4170

**Comment by teolemon** [comment]
I cannot reproduce:
![image](https://user-images.githubusercontent.com/1689815/89124102-99fef680-d4d4-11ea-911c-c0926c006b86.png)

**Comment by VaiTon** [comment]
Can't reproduce. Feel free to open if encountering this error again!
