### ISSUE TITLE
Factorization or Deletion of Shake to Scan

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3382]
Factorize or Delete of Shake to Scan. We now have a good navigation. The only corner case I could think off are broken screens that don't register touch anymore.
https://github.com/openfoodfacts/openfoodfacts-androidapp/search?q=mShakeDetector.setOnShakeListener%28count+-%3E+%7B&unscoped_q=mShakeDetector.setOnShakeListener%28count+-%3E+%7B

**Comment by VaiTon** [comment]
What do you mean with "factorize"?

**Comment by teolemon** [comment]
As you may have seen, the code was duplicated in many views.
