### ISSUE TITLE
Android app crashes when adding a new product from scan

### ISSUE THREAD

**Issue by Telperion87** [openfoodfacts/openfoodfacts-androidapp#3418]
Since 3.4.2 update, when I scan a product which is not in the database yet, when I try to "add this product" the app send me back to the scan or crashes.

**To Reproduce**
1. go to scan or open the scan wia the widget
2. scan a product not in the database yet
3. click on "add this product"
4. the app sends you back to the scan or crashes

**Expected behavior**
it should open the form to add the new product

**Smartphone (please complete the following information):**
 - moto g7
 - android stock
 - 3.4.2

**Comment by teolemon** [comment]
Hey @Telperion87 
it probably is this issue: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3415

**Comment by teolemon** [comment]
@Telperion87 can you confirm it's fixed ?

**Comment by Telperion87** [comment]
yes that one is fixed

thanks

Il giorno mar 25 ago 2020 alle ore 13:04 Pierre Slamich <
notifications@github.com> ha scritto:
