### ISSUE TITLE
Reorder Ingredients and Nutrition in the dropdown menu for new product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#343]
- Front
- Ingredients
- Nutrition

It's that way in V1, in the Web view, and it's mentally disturbing for regular contributors

**Comment by teolemon** [comment]
Also please display it more like this:
![image](https://cloud.githubusercontent.com/assets/1689815/21385172/d2be8936-c76d-11e6-9e70-b84f5262cc92.png)

**Comment by ross-holloway94** [comment]
What is the name of the layout file to change this? I cannot seem to find it.

**Comment by teolemon** [comment]
activity_save_product_offline.xml

**Comment by ross-holloway94** [comment]
Fixed in #683
