### ISSUE TITLE
Adopt a card-based approach to the product view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#344]
![image](https://cloud.githubusercontent.com/assets/1689815/21385241/0a57cd6c-c76e-11e6-969f-9819f6be435a.png)
(This is taken from the Open Food app)

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21385386/9d8c33de-c76e-11e6-861e-8afc9915540c.png)

**Comment by asmoth360** [comment]
Where does come this view from ? It's not like that in the Open Food app, which one are you talking about ?

**Comment by teolemon** [comment]
It's a mockup made from the Open Food CH app (unrelated with OFF)

**Comment by teolemon** [comment]
Done.
