### ISSUE TITLE
Show lists of a product on the product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3458]
- [ ] Show lists which the product is part of. If we add a product to a list, we should see it on the product page.
- [ ] When clicking on a chip, the user should be redirected to the list view.

We fixed this in this PR that did not work: https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2271

### Mockup
<img src="https://user-images.githubusercontent.com/1689815/91161747-6f671e80-e6cb-11ea-9532-3cf143bc9dcb.png" width="400" />

**Comment by sujithTSR** [comment]
Can I try this?

**Comment by VaiTon** [comment]
@sujithTSR sure you can! I'm assigning you! 👍

**Comment by kartikaysharma01** [comment]
I am working on this.

**Comment by kartikaysharma01** [comment]
@teolemon @VaiTon Should the chips be placed below Nutriscore/Nova icons or above the nutrient level ?
In a general case there would be button or a textview  between the icons and nutrient level cardview.

**Comment by teolemon** [comment]
I would say that :
- Clicking on the chip should bring you to the lis
- I placed it there because the scores are IMO the most important thing.

Not sure what your mean by your second point. Not sure we should do a card per theme in the summary tab
