### ISSUE TITLE
The app seems to duplicate queries

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3465]
The app seems to duplicate queries
```
XXX.92 - - [23/Aug/2020:11:40:03 +0200] "GET /1.json?fields=null HTTP/2.0" 200 98979 "-" "Open Food Facts Official Android App 3.4.2"
XXX.92 - - [23/Aug/2020:11:40:03 +0200] "GET /files/tagline/tagline-off.json HTTP/2.0" 200 2164 "-" "Open Food Facts Official Android App 3.4.2"
XXX.92 - - [23/Aug/2020:11:40:03 +0200] "GET /files/tagline/tagline-off.json HTTP/2.0" 200 2164 "-" "Open Food Facts Official Android App 3.4.2"
XXX.92 - - [23/Aug/2020:11:40:03 +0200] "GET /1.json?fields=null HTTP/2.0" 200 98979 "-" "Open Food Facts Official Android App 3.4.2"
```

**Comment by stephanegigandet** [comment]
Whenever an user goes to the home screen, those 3 queries are made:

```
ip - - [24/Aug/2020:19:07:56 +0200] "GET /files/tagline/tagline-off.json HTTP/2.0" 200 2164 "-" "Open Food Facts Official Android App 3.4.3"
ip - - [24/Aug/2020:19:07:56 +0200] "GET /1.json?fields=null HTTP/2.0" 200 98979 "-" "Open Food Facts Official Android App 3.4.3"
ip - - [24/Aug/2020:19:07:56 +0200] "POST /cgi/session.pl HTTP/2.0" 200 6936 "-" "okhttp/3.12.11"

```
If the user clicks the "Home" screen button 10 times, then you get the queries 10 times.

**Comment by teolemon** [comment]
- The session.pl call seems other the top (what is it done for ?). It happens only when you're logged. So it's a proxy for Daily Logged Active Users.
- 1.json can probably be removed
- tagline-off.json is cached be reloaded everytime I think.
We need at least one of the last two as a proxy for Daily Actives.

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/f8a55a399903ba3dd3fc7f314e4f71581cddffd6/app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/HomeFragment.java#L87

**Comment by VaiTon** [comment]
Which call should we drop?

* The "session" is for checking that neither of user or password have changed.
* The "/1" is to get the products count.
* The tagline-off to display the tagline.

We do not have a caching mechanism for these simple ones since it would mean too much work. We could try to cache responses with okhttp though.

**Comment by naivekook** [comment]
Why we replace home fragment each time on botton navigation click?
should be something like `if current fragment != home fragment -> replace`

**Comment by VaiTon** [comment]
> Why we replace home fragment each time on botton navigation click?
> should be something like `if current fragment != home fragment -> replace`

Isn't it already the case?

**Comment by naivekook** [comment]
> Isn't it already the case?

looks like it doesn't
in MainActivity we have the next code and I don't see any check
```
if (newFragment != null) {
                    getSupportFragmentManager().beginTransaction()
                        .replace(R.id.fragment_container, newFragment)
                        .addToBackStack(null)
                        .commit();
                }
```

**Comment by VaiTon** [comment]
> 
> 
> > Isn't it already the case?
> 
> looks like it doesn't
> in MainActivity we have the next code and I don't see any check
> 
> ```
> if (newFragment != null) {
>                     getSupportFragmentManager().beginTransaction()
>                         .replace(R.id.fragment_container, newFragment)
>                         .addToBackStack(null)
>                         .commit();
>                 }
> ```

You should also check the lines where we set the value of `newFragment`. I think we already do this.

**Comment by naivekook** [comment]
I guess we don't
class CommonBottomListener, case `R.id.home_page, R.id.home` -> always replace fragment
you can do a simple check on phone, just press a few times on "Home" button in bottom bar and see how tagline is reloaded each time

it is not critical at all, but in case of duplicated queries - it is place to improvement

**Comment by VaiTon** [comment]
@naivekook ok then, a simple check is needed here. Could you work on it?

**Comment by naivekook** [comment]
@VaiTon sure, assign this ticket to me please
