### ISSUE TITLE
Handle errors gracefully

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#347]
Liked the idea of spilled milk (from Google Keep)
![screenshot_2015-12-18-13-53-08](https://cloud.githubusercontent.com/assets/1689815/21388219/94b0ac60-c77b-11e6-8324-aa8c16947f15.png)

**Comment by herau** [comment]
be able also to send the stackstrace to reproduce the bug. i guess some software already exist to do this
