### ISSUE TITLE
Move check user credentials to utils ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3482]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/f8a55a399903ba3dd3fc7f314e4f71581cddffd6/app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/HomeFragment.java#L135

**Comment by VaiTon** [comment]
This is used only in HomeFragment because we do check if the credentials are still right every time the app is opened. What would be an optimal behavior is to check a "token" that atm we don't have.
