### ISSUE TITLE
Deep link to the app is not working

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3498]
Deep link is not working. It's also not working for subdomains like fr.off, it.off…

1. Steps: click on a world.off.org link
2. Click on "Open in Open Food Facts"
3. See a black screen like this

![image](https://user-images.githubusercontent.com/1689815/91884162-db2a2800-ec85-11ea-886e-ec282ba733af.png)

**Comment by teolemon** [comment]
Probably this stack trace: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3500

**Comment by teolemon** [comment]
Example: https://world.openfoodfacts.org/product/3596710481262/fromage-frais-auchan

**Comment by teolemon** [comment]
Here's a link to the original PR: https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/13093feceda8eddab0d88412e5f11c0ed48dd735

**Comment by huzaifaiftikhar** [comment]
@teolemon This is not reproducible for me on Google Pixel 3, Android 10. The deep link opens as expected and the product page is displayed with the details, however, I noticed that when the link is for an invalid product and the server responds back with "product not found" then in that case the app crashes with NullPointerException. We need to handle those scenarios.
Example URL - https://world.openfoodfacts.org/product/012345678901/some-random-name
