### ISSUE TITLE
Make the search work in brands

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#35]
Looking for Picard won't return any results.

**Comment by itchix** [comment]
http://world.openfoodfacts.org/cgi/search.pl?search_terms=coke&search_simple=1 ==> search_terms doesn't search on brand field ?

**Comment by itchix** [comment]
Because I get results when I search for picard

**Comment by itchix** [comment]
Fix with 279e816fe9845e8cadee43da58ce2e10000468af
