### ISSUE TITLE
French translation issues

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/OpenFoodFacts-androidApp#351]
In the french version, several things are displayed in english instead of french :
In the left menu : 
"History" -> "Historique" ;
"Preferences" -> "Préférences" (with accents)

Also the preference screen is totally in english and should be translated.

Bonus : in the top right button, "Contributer" should be "Contribuer" in french.

**Comment by teolemon** [comment]
Already fixed in TRUNK. Waiting for release.
