### ISSUE TITLE
Search by name results with system font size large is completely broken

### ISSUE THREAD

**Issue by adrigrillo** [openfoodfacts/openfoodfacts-androidapp#3514]
When the application is set to Spanish, the results when searching by text are not shown properly. In concrete, the bottom bar, where the application's tabs are shown, goes to the middle of the screen and covers all the results, making the application unusable.
The behavior is shown in the first screenshot.  

**To Reproduce**
1. Set the language to Spanish in the application.
2. Go to the home tab.
3. Click on the search button.
4. Write any brand or food you want to look for.
5. See incorrect layout.

**Expected behavior**
The expected result can be obtained when the application is set to English. In this case, the bar stays in the expected position and the list of elements can be read.

**Screenshots**
Incorrect layout when set to Spanish:
![wrong-screen-es](https://user-images.githubusercontent.com/18198342/92329613-cc1dee00-f068-11ea-9949-42af723eb31a.jpg)

Expected layout when set to English:
![right-screen-en](https://user-images.githubusercontent.com/18198342/92329648-0dae9900-f069-11ea-869d-33a85a312ba1.jpg)

**Smartphone:**
 - Device: Nokia 7 Plus
 - OS: Android 10 August Security Patch
 - App: Open Food Facts 3.4.7

**Comment by Gosunet** [comment]
Hello, I tested it and I don't reproduce the bug. (Tested on Android 10)

<img width="359" alt="image" src="https://user-images.githubusercontent.com/11671046/94995311-c6e78c80-059d-11eb-855c-632e31530f62.png">

**Comment by adrigrillo** [comment]
What is your app version? Is it from the Play store or F-Droid?

**Comment by Gosunet** [comment]
From the Play store : version 3.4.8

**Comment by adrigrillo** [comment]
I found the cause of the problem. I have set the font size, in the android settings, to default and is working as expected. However, when you set the font to large the bug occurs.

**Comment by adrigrillo** [comment]
I can confirm that the issue also happens in the android emulator from android studio. The steps for reproducing are:

1. Set app language to Spanish.
2. Set the font size in android to large.
3. Perform an object search.

I will inspect what is the problem during these days.

**Comment by mrudultora** [comment]
@adrigrillo  It's working fine even on setting the font size to XXL (Tested on Android 10).

**Comment by adrigrillo** [comment]
I have recently changed the phone and seems to work fine again. I will close the issue. Thanks!
