### ISSUE TITLE
Image upload is not properly credited to the contributor

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3520]
### What
Image upload is not properly credited to the contributor

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/92960966-c5c7b180-f46e-11ea-8b2c-2e1d712f6d5e.png)

### Part of
- #4202

**Comment by VaiTon** [comment]
What do you mean? Is newt a user?

Does this happens always or just sometimes?

**Comment by teolemon** [comment]
This happens all the time, for logged in users. I'm able to reproduce by using the Image manager to crop images. This openfoodfacts-contributors is actually me, from my mobile phone, with latest develop
https://world.openfoodfacts.org/product/3528161506805/buche-glacee
![image](https://user-images.githubusercontent.com/1689815/147386962-3877ef10-61b5-4f9f-be5b-ecc50bce0bfe.png)

**Comment by teolemon** [comment]
@VaiTon did you have a chance to start investigations ? Did you find anything ?

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/SendProduct.java#L51

**Comment by g123k** [comment]
Well actually it seems that sometimes the app doesn't provide a password.
A fix is coming
