### ISSUE TITLE
Ingredient analysis icons not shown on Android 7

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3524]
Ingredient analysis icons not shown on Android 7

- [ ] Nginx server is the same as the rest of the files

![image](https://user-images.githubusercontent.com/1689815/93015522-8017ff80-f5ba-11ea-8270-ab65c8164d01.png)

**Comment by teolemon** [comment]
This might be related to underscores in URLs
https://github.com/square/picasso/issues/1570

**Comment by huzaifaiftikhar** [comment]
Closed via #3544
