### ISSUE TITLE
Add support for displaying the Eco-Score 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3529]
### Add support for displaying the Eco-Score. 

- [ ] Clone the system that displays Nutri-Score on the scan card renaming it 'Eco-Score'
- [ ] Change the server request url we do on scan to include the ecoscore field 
- [ ] If (and only if) the server sends back a proper value (a, b, c, d or e), hide the classic CO2 value and display the new score
`https://world.openfoodfacts.org/api/v0/product/3414280980209.json?fields=ecoscore` (Here it shows null)
- [ ] Please use the placeholders visuals already in the app as placeholders until we have the visuals. It would be better to download them on the fly so that we can remote update them.
https://static.openfoodfacts.org/images/icons/ecoscore-a.svg
https://static.openfoodfacts.org/images/icons/ecoscore-b.svg
https://static.openfoodfacts.org/images/icons/ecoscore-c.svg
https://static.openfoodfacts.org/images/icons/ecoscore-d.svg
https://static.openfoodfacts.org/images/icons/ecoscore-e.svg

### Places where it should be shown

The same actions have to be done on the summary tab, and on top of the `Environment` tab (where we also display the score)

- [ ] Scan card
- [ ] `Environment` tab
- [ ] Summary tab if attributes are not implemented yet

(server-side issue: https://github.com/openfoodfacts/openfoodfacts-server/issues/4262)

**Comment by teolemon** [comment]
Here are the placeholders with the right size.
https://static.openfoodfacts.dev/images/icons/ecoscore-a.svg
https://static.openfoodfacts.dev/images/icons/ecoscore-b.svg
https://static.openfoodfacts.dev/images/icons/ecoscore-c.svg
https://static.openfoodfacts.dev/images/icons/ecoscore-d.svg
https://static.openfoodfacts.dev/images/icons/ecoscore-e.svg

**Comment by teolemon** [comment]
Here's what it would look like with a placeholder. We would loose the product image for better legibility. cc @stephanegigandet @VaiTon 

![image](https://user-images.githubusercontent.com/1689815/97957895-6ae67280-1dac-11eb-92ef-1285a7288d91.png)

**Comment by teolemon** [comment]
Also please note that the scores are not the actual ones.

**Comment by VaiTon** [comment]
Good idea, the product photo is not that useful to be honest.
