### ISSUE TITLE
Add a "Update image" button in the summary tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3537]
Add a "Update image" button in the summary tab above the "Take another picture" button and rename the "Take another picture" button to "Take extra photos of the packaging"
The "Update image" should replace the front image for the current language.

**Comment by WildOrangutan** [comment]
I can implement this, if it's still open

**Comment by teolemon** [comment]
Yes, it is 
Some pointers:
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/res/layout/fragment_summary_product.xml
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/summary/SummaryProductFragment.java

Fell free to join the Slack at https://slack.openfoodfacts.org in the #android and #android-alerts channels

**Comment by WildOrangutan** [comment]
Ok, I will go ahead and start implementing it
