### ISSUE TITLE
Salt unit is wrong

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#354]
3560070517510 will indicate ```0.508null```
Online version for ref: http://world.openfoodfacts.org/product/3560070517510/crunchy-muesli-chocolat-caramel-dore-au-four-carrefour

**Comment by teolemon** [comment]
http://world.openfoodfacts.org/product/3560070517510/crunchy-muesli-chocolat-caramel-dore-au-four-carrefour

**Comment by asmoth360** [comment]
I just found the same issue on this product : http://fr.openfoodfacts.org/produit/5449000131805/coca-cola-zero
But 3 values are displayed like this : saturated fats (`0null`), sugar (`0null`) and salt (`0,0254null`). Strange.

**Comment by herau** [comment]
same answer than for the #357. The JSON response contains null values for the `*_unit` fields.

The server should not send this kind of values. 

@teolemon maybe create a server issue

**Comment by teolemon** [comment]
Can't reproduce. Closing
