### ISSUE TITLE
Issue with importing some symbols

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3542]
Issue with importing some symbols. I'm pretty sure I saw this before, and that we might have fixed it on release/*.

```
openfood/models/CategoryDao.java:158: error: cannot find symbol
    public boolean hasKey(Category entity) {
                          ^
  symbol:   class Category
  location: class CategoryDao
```

**Comment by huzaifaiftikhar** [comment]
Not a code issue can be closed.

**Fix**
Go to Build -> Clean Project

@teolemon can you try this close if it gets resolved?

**Comment by teolemon** [comment]
yup, worked. closing
