### ISSUE TITLE
"Back" behavior is not consistent

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/openfoodfacts-androidapp#355]
When you are in a view with a "back" button in the top left (left arrow), the "back" Android button does not do the same thing as tapping the top left button. Sorry if it's not clear, I don't know the proper terms in english, if they exist.

Steps to reproduce :
- Search for a product in the search view. The result list appears.
- Open a product view. Now the "back" top left button is present.
  - If you tap this button, you're redirected to the home view (with the "Scan" button).
  - But if you tap the physical "back" button of the smartphone, you're redirected to the previous result list.

I don't know if this is the intended behavior, but it's disturbing. For me the convenient solution is to redirect to the result list, even if you tap the left arrow in the app.

**Comment by teolemon** [comment]
Let's replace it with the hamburger button (it has a home menu which does the same thing)
@herau ?

**Comment by asmoth360** [comment]
I just found that it's already been reported in #138.

**Comment by teolemon** [comment]
@asmoth360 I believe this has been fixed since. Can you confirm ?

**Comment by mrudultora** [comment]
@VaiTon @teolemon This issue is resolved. Can be closed.

**Comment by teolemon** [comment]
@asmoth360 does the latest version work well for you ?

**Comment by teolemon** [comment]
I consider this fixed. Feel free to reopen
