### ISSUE TITLE
Show last edit date on product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#356]
![image](https://cloud.githubusercontent.com/assets/1689815/21977646/50dbbb68-dbd7-11e6-89d7-d412fa531752.png)

**Comment by herau** [comment]
do you want all informations like in the website ? 

> Produit ajouté le 21 mai 2014 à 14:06:57 CEST par sebleouf.
Dernière modification de la page produit le 22 décembre 2016 à 15:39:54 CET par date-limite-app. 
Fiche produit également modifiée par tacite.

**Comment by teolemon** [comment]
There's another bug for the full information thing. This one is for a glanceable version to let power contributors see the last edit date (and possibly the last picture date)

**Comment by teolemon** [comment]
Added a screenshot of the V1 for reference. We can do a little better:
Let's align on the website: 
```
Product added on February 28, 2014 at 7:38:43 PM CET by openfoodfacts-contributors.
Last edit of product page on January 16, 2017 at 8:16:42 AM CET by openfoodfacts-contributors. 
Product page also edited by aleene, miles67off, tacite.
```

```
Product added on {{date}} at {{time}} by {{contributor}}.
Last edit of product page on {{date}} at {{time}} by {{contributor}}. 
Product page also edited by {{contributor}}, {{contributor}}, {{contributor}}.
```

**Comment by teolemon** [comment]
This has been fixed as a tab, some closing
