### ISSUE TITLE
java.lang.RuntimeException at ProductsAPITest.java:258         Caused by: java.net.SocketTimeoutException at ProductsAPITest.java:47

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3561]
openfoodfacts.github.scrachx.openfood.network.ProductsAPITest > post_product FAILED
    java.lang.RuntimeException at ProductsAPITest.java:258
        Caused by: java.net.SocketTimeoutException at ProductsAPITest.java:47

**Comment by VaiTon** [comment]
Sometimes the dev server is unresponsive when queried. That makes the test fail.
