### ISSUE TITLE
Fat unit not displayed

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/openfoodfacts-androidapp#357]
For the product 3017620429484 (http://fr.openfoodfacts.org/produit/3017620429484/nutella-ferrero), the fat unit "g" is not displayed in the nutrition tab : it just show `fat : high (31.6)`. 
I searched for other products with this issue but found only this one for now.

**Comment by teolemon** [comment]
Can you add a screenshot ?

**Comment by teolemon** [comment]
Working here (I have filed a similar issue for salt, tough)

**Comment by asmoth360** [comment]
![screenshot_2016-12-21-23-36-14](https://cloud.githubusercontent.com/assets/19469836/21408709/bf23ecc2-c7d6-11e6-86a8-59d53abc42fb.png)

**Comment by herau** [comment]
in the JSON API `http://world.openfoodfacts.org/api/v0/product/3017620429484.json`, we use the field `fat_unit` which is not present for this product.

**Comment by teolemon** [comment]
added an API update required. It is very weird.

**Comment by teolemon** [comment]
Please do not edit the product, so that I can file a bug.

**Comment by herau** [comment]
In my opinion, the unit should be a global value for all nutriments... and not for each (except energy)

**Comment by herau** [comment]
@teolemon in the API doc 
> key_unit (string) - the units used in the other fields (eg in json: "carbohydrates_unit":"g"). Possible values are "kg", "g", "mg, "µg", "l", "ml", "%" or "";

**Comment by teolemon** [comment]
Can't reproduce. Closing
