### ISSUE TITLE
Autocomplete for Origins

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3571]
Origins have just been taxonomized. We can add autocomplete for it:

The live API is already working: https://fr.openfoodfacts.org/cgi/suggest.pl?tagtype=origins&term=nou
The JSON file has not been generated yet: https://static.openfoodfacts.org/data/taxonomies/origins.json

Note: we have methods to use JSON files or live APIs.

### Steps
- [ ] Use the live API to get the results.
- [ ] Cache the results into the offline app DB.

**Comment by kartikaysharma01** [comment]
I am working on this.

**Comment by kartikaysharma01** [comment]
This is already implemented and can be closed.
