### ISSUE TITLE
Is this even used?

### ISSUE THREAD

**Issue by mohsin** [openfoodfacts/openfoodfacts-androidapp#3574]
Looks like unreachable dead code.

https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/java/openfoodfacts/github/scrachx/openfood/utils/OfflineProductService.java#L243-L247

https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/edit/ProductEditActivity.java#L155-L163

**Comment by SaifurRahmanMohsin** [comment]
Oh, never mind, I found where it's being used now.

**Comment by VaiTon** [comment]
It's not. Cleaning it.
