### ISSUE TITLE
Space missing in nutrition tab

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/openfoodfacts-androidapp#358]
In french at least (and probably in english too), a space character should be present between the value and the unit : "20,5 g" and not "20,5g", but it's missing.

**Comment by ross-holloway94** [comment]
This appears to be fixed in current release.

![screenshot_20171016-151631](https://user-images.githubusercontent.com/20950727/31616728-655e1ca4-b285-11e7-8243-352f0b6b0c6a.png)

**Comment by teolemon** [comment]
@asmoth360 Can you confirm ?

**Comment by Karljoones** [comment]
Confirmed fixed
