### ISSUE TITLE
The Eco-Score sometimes does not appear on the full product page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3583]
The Eco-Score sometimes does not appear on the full product page.
https://fr.openfoodfacts.org/product/4056489207924/farine-de-ble-fluide-navarre
![image](https://user-images.githubusercontent.com/1689815/98934235-0d57d180-24e2-11eb-860e-6971658da499.png)

![image](https://user-images.githubusercontent.com/1689815/98934259-1779d000-24e2-11eb-91df-f36f2eca3327.png)
![image](https://user-images.githubusercontent.com/1689815/98934266-1ba5ed80-24e2-11eb-8890-6054411f8dd2.png)

**Comment by VaiTon** [comment]
Yeah I think I know why. We don't check for its presence before hiding the entire card.
