### ISSUE TITLE
Display the grey unknown icons when the scores are unknown

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3603]
We now have unknown icons for the NOVA or the Nutri-Score or the Eco-Score that can help stabilize layouts. We could show them on 

- [x] the scan card 

when the values are unknown 
https://static.openfoodfacts.org/images/misc/nutriscore-unknown.svg
https://static.openfoodfacts.org/images/misc/nova-group-unknown.svg
https://static.openfoodfacts.org/images/icons/ecoscore-unknown.svg

https://static.openfoodfacts.org/images/misc/nutriscore-unknown.png
https://static.openfoodfacts.org/images/misc/nova-group-unknown.png
https://static.openfoodfacts.org/images/icons/ecoscore-unknown.png

Clickling on them if they are unknown on the scan page would bring up the full product page where the user can get an explanation as to why they are not computed.
We already have good explanations for NOVA and Nutri-Score but not Eco-Score

![image](https://user-images.githubusercontent.com/1689815/99876800-8699a780-2bf9-11eb-9902-db2acbd8c76b.png)

**Comment by VicFinistere** [comment]
I am on it !

**Comment by teolemon** [comment]
Thank you @Zoeinfp I've assigned it to you.
Here's the starting pointer I mentionned: https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/java/openfoodfacts/github/scrachx/openfood/utils/Utils.java#L303

**Comment by VicFinistere** [comment]
Sorry I did not solve it  and I have no more time now.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/103355605-eadc4080-4aae-11eb-8133-5edbfdeaed41.png)

**Comment by VaiTon** [comment]
@teolemon could we get the svg versions?

**Comment by teolemon** [comment]
@VaiTon Those ones ? Something else ?

https://static.openfoodfacts.org/images/misc/nutriscore-unknown.svg
https://static.openfoodfacts.org/images/misc/nova-group-unknown.svg
https://static.openfoodfacts.org/images/icons/ecoscore-unknown.svg

**Comment by VaiTon** [comment]
@teolemon could you test latest develop for this?
