### ISSUE TITLE
Show the new packaging field values on the environment tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3608]
Show the new packaging field values on the environment tab

**Comment by kartikaysharma01** [comment]
I would like to work on it. Can you assign this to me?

**Comment by kartikaysharma01** [comment]
@teolemon  @VaiTon  What happens when the server returns values in a different locale than the one selected ?

**Comment by VaiTon** [comment]
> 
> 
> @teolemon @VaiTon What happens when the server returns values in a different locale than the one selected ?

It should not. Could you give us the URL that's causing this?

**Comment by kartikaysharma01** [comment]
From the API response, which is the new field for packaging? I might have misunderstood earlier.

**Comment by kartikaysharma01** [comment]
@VaiTon  The API response for ```packaging``` lacks consistency. 
Please refer to products ```3168930002987``` and ```3274080005003```

**Comment by VaiTon** [comment]
> 
> 
> @VaiTon The API response for `packaging` lacks consistency.
> Please refer to products `3168930002987` and `3274080005003`

cc @teolemon
