### ISSUE TITLE
Trying to open advanced search crashes the app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3610]
**Describe the bug**
Trying to open advanced search crashes the app

**To Reproduce**
1. Go to the sidemenu
2. Click on 'Advanced Search'
3. Click on 'Open with Open Food Facts'

**Comment by mrudultora** [comment]
@teolemon  Sir, please review this !

**Comment by VaiTon** [comment]
I'm sorry for @mrudultora but I didn't see the PR and fixed (in theory) the issue. @teolemon could you check when you have time?

**Comment by mrudultora** [comment]
> I'm sorry for @mrudultora but I didn't see the PR and fixed (in theory) the issue. @teolemon could you check when you have time?

@VaiTon That's alright! Btw, it was my first pull request in this repo so I was excited. I will try to solve another issue.

**Comment by teolemon** [comment]
@VaiTon I'm going to do a fresh build and try to reproduce.
I've linked the PR that will be closed when we confirm it is fixed.

**Comment by VaiTon** [comment]
> 
> 
> > I'm sorry for @mrudultora but I didn't see the PR and fixed (in theory) the issue. @teolemon could you check when you have time?
> 
> @VaiTon That's alright! Btw, it was my first pull request in this repo so I was excited. I will try to solve another issue.

Thank you for your work!

**Comment by mrudultora** [comment]
@teolemon  This issue can be closed. Fixed by #3615 .
