### ISSUE TITLE
Prevent people from adding an Additive several times

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#362]
![additives](https://cloud.githubusercontent.com/assets/1689815/21451559/4ab3715c-c900-11e6-8f40-aa5bda4e3e09.png)

**Comment by teolemon** [comment]
(Also: There's Gorgonzola, and Gorgone Hugo)

**Comment by asmoth360** [comment]
You seem to really don't like gorgonzola! :p

**Comment by teolemon** [comment]
La dose fait le poison - Paracelse :-)
