### ISSUE TITLE
Add a message if we have a category but no Eco-Score

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3624]
Add a message if we have a category but no Eco-Score.
`if states_tags == categories-completed and ecoscore_grade == Null`

_"We could not compute an Eco-Score for this product. It might be that the category is not specific enough or that we don't have supporting data for this category. If you believe this is an error, you can email contact@openfoodfacts.org"_

**Comment by teolemon** [comment]
`if "labels-to-be-completed" in states:`

`"The Eco-Score takes into account environmental labels. Please take them into photo or edit the product so that they can be taken into account"`

`if "origins-to-be-completed" in states:`
`"The Eco-Score takes into account the origins of the ingredients. Please take them into photo (ingredient list and/or any geographic claim or edit the product so that they can be taken into account"`

**Comment by kartikaysharma01** [comment]
@teolemon  If this is unassigned, I would like to work on this.

**Comment by teolemon** [comment]
You're very welcome. 

- The ecoscore is NULL for all products until release, but the Environment tab should already be shown.
- origins-to-be-completed does not exist yet (I've opened an issue for it, but we can code it anyway, without waiting) (server issue:  https://github.com/openfoodfacts/openfoodfacts-server/issues/4661 )

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/103416938-00be3400-4b89-11eb-926b-105e7b5d5149.png)
How about a 1 time message ?

and for the others, text rather than buttons, below the "Take additional photos" button ?
![image](https://user-images.githubusercontent.com/1689815/103416976-28ad9780-4b89-11eb-94a6-b0f6f6fcf86c.png)
@VaiTon ?

**Comment by kartikaysharma01** [comment]
How about toast?

**Comment by kartikaysharma01** [comment]
Ok so how about we keep one text view below the "take additional photo" button and keep it in a format like, "Note: The Eco-score...." and we can change the message as per the condition. 
@VaiTon  @teolemon

**Comment by VaiTon** [comment]
> 
> 
> Ok so how about we keep one text view below the "take additional photo" button and keep it in a format like, "Note: The Eco-score...." and we can change the message as per the condition.
> @VaiTon @teolemon

I agree, but please put it over the button :)

**Comment by kartikaysharma01** [comment]
If it is put over the button , then what happens in case , statesTags includes "categories-to-be-completed" and "labels-to-be-completed"
(the button would say "add a category to compute nutri-score" and the textview "The eco-score....")
should the button be given priority ?
@VaiTon @teolemon

**Comment by kartikaysharma01** [comment]
> If it is put over the button , then what happens in case , statesTags includes "categories-to-be-completed" and "labels-to-be-completed"
> (the button would say "add a category to compute nutri-score" and the textview "The eco-score....")
> should the button be given priority ?
> @VaiTon @teolemon

@teolemon @VaiTon What happens in this case?
