### ISSUE TITLE
inferred type is Locale? but Locale was expected (AbstractScreenshotTest.kt)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3630]
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/AbstractScreenshotTest.kt: (77, 36): Type mismatch: inferred type is Locale? but Locale was expected

https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/AbstractScreenshotTest.kt#L77

**Comment by VaiTon** [comment]
Fixed by 5f0b1ab536ac50ded4a3dcf9f889603cd21161a7
