### ISSUE TITLE
CountyTag vs. CountryTag

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3638]
CountyTag vs. CountryTag:
https://github.com/openfoodfacts/openfoodfacts-androidapp/search?q=County

![image](https://user-images.githubusercontent.com/1689815/103139010-14285580-46d8-11eb-822f-500fcf0c0ecf.png)

**Comment by VaiTon** [comment]
The problem is that the class is an entity, so an update would require a db migration, and that's useless just for a rename
