### ISSUE TITLE
country.CountriesWrapperTest > initializationError FAILED

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3640]
> Task :app:testObfDebugUnitTest

openfoodfacts.github.scrachx.openfood.models.entities.country.CountriesWrapperTest > initializationError FAILED
    org.junit.runners.model.InvalidTestClassError at ParentRunner.java:525

155 tests completed, 1 failed

**Comment by VaiTon** [comment]
Duplicate of #3648.
