### ISSUE TITLE
Show the Eco-Score in product lists

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3655]
Show the Eco-Score in 

- [x] Search (done by @VaiTon )
- [x] History (requires DB scheme edit)

 I have some vertical versions of the Nutri-Score to make some space
![image](https://user-images.githubusercontent.com/1689815/103442960-c624cc00-4c5a-11eb-8729-3f55007c0602.png)

https://raw.githubusercontent.com/openfoodfacts/openfoodfacts-server/nutriscore-variants/html/images/misc/nutriscore/nutriscore-vertical-border-a.svg
https://raw.githubusercontent.com/openfoodfacts/openfoodfacts-server/nutriscore-variants/html/images/misc/nutriscore/nutriscore-vertical-border-b.svg
https://raw.githubusercontent.com/openfoodfacts/openfoodfacts-server/nutriscore-variants/html/images/misc/nutriscore/nutriscore-vertical-border-c.svg
https://raw.githubusercontent.com/openfoodfacts/openfoodfacts-server/nutriscore-variants/html/images/misc/nutriscore/nutriscore-vertical-border-d.svg
https://raw.githubusercontent.com/openfoodfacts/openfoodfacts-server/nutriscore-variants/html/images/misc/nutriscore/nutriscore-vertical-border-e.svg

**Comment by VaiTon** [comment]
Search ✅

**Comment by teolemon** [comment]
updated the issue accordingly. Thanks @VaiTon

**Comment by VaiTon** [comment]
History requires DB scheme edit 😢 
I'm adding NutriScore atm

**Comment by VaiTon** [comment]
Fixed in 2382d65450c3327dee0aaed1b140a3e4724fe33a
