### ISSUE TITLE
UninitializedPropertyAccessException at ProductsAPITest.kt:167

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3658]
openfoodfacts.github.scrachx.openfood.network.ProductsAPITest > post_product FAILED
    java.lang.ExceptionInInitializerError at ProductsAPITest.kt:167
        Caused by: kotlin.UninitializedPropertyAccessException at ProductsAPITest.kt:167

https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/testOff/java/openfoodfacts/github/scrachx/openfood/network/ProductsAPITest.kt#L167

_Originally posted by @teolemon in https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3654#issuecomment-753522162_

**Comment by VaiTon** [comment]
This should be fixed now. @teolemon ?
