### ISSUE TITLE
Add bottom padding to the attributes view (impossible to scroll completely)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3665]
- [ ] Add bottom padding to the attributes view since it's impossible to scroll completely right now. 
- [ ] Also let's rename the tab to "Synthesis" while it's still in progress.

![image](https://user-images.githubusercontent.com/1689815/103479694-bda1d200-4dcf-11eb-87e3-559e149c4fc5.png)

**Comment by kartikaysharma01** [comment]
Unable to reproduce the scrolling issue.

**Comment by kartikaysharma01** [comment]
Can you provide the product link where you faced this?

**Comment by teolemon** [comment]
Pixel 4 - 3256225426584

![image](https://user-images.githubusercontent.com/1689815/103480070-618c7d00-4dd2-11eb-9419-7a210658f6bc.png)

**Comment by kartikaysharma01** [comment]
Working on it.
