### ISSUE TITLE
Crash when trying to edit a product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3666]
Crash when trying to edit a product
![image](https://user-images.githubusercontent.com/1689815/103480091-7e28b500-4dd2-11eb-8fc7-f5bc017358f5.png)

**Comment by kartikaysharma01** [comment]
I'd like to work on this. Can you assign this to me ?

**Comment by teolemon** [comment]
Yes @kartikaysharma01
