### ISSUE TITLE
The Eco-Score logo appears on top of the "Add new product card"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3667]
The Eco-Score logo appears on top of the "Add new product card"

![image](https://user-images.githubusercontent.com/1689815/103480192-2d658c00-4dd3-11eb-9fbe-4b90031e2b1c.png)

**Comment by VaiTon** [comment]
Fixed by 3dc2eef7cc16a4e6dd9fa0ef3110c864b5c0d29c
