### ISSUE TITLE
Scan crashes on some specific products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3668]
![image](https://user-images.githubusercontent.com/1689815/103480689-f6dd4080-4dd5-11eb-8c0b-94567e9012b1.png)
https://world.openfoodfacts.org/product/3270160862429/parmentier-de-colin-d-alaska-ecrase-de-pomme-de-terre-picard
![image](https://user-images.githubusercontent.com/1689815/103480560-5c7cfd00-4dd5-11eb-9596-e5a6d6bcc690.png)

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/product/3270160862429/parmentier-de-colin-d-alaska-ecrase-de-pomme-de-terre-picard

**Comment by VaiTon** [comment]
Any stacktrace?

**Comment by mrudultora** [comment]
It's working fine for this barcode. Tested in 2 devices. Please add the logs.
