### ISSUE TITLE
Impossible to validate input easily in the search by barcode view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#369]
![image](https://cloud.githubusercontent.com/assets/1689815/21465996/aed6f740-c9b8-11e6-87d1-86f1b7d2f1da.png)

**Comment by asmoth360** [comment]
Suggestion : remove the image "Yes we scan" to have a screen similar to the search by name.

**Comment by huzaifaiftikhar** [comment]
I am working on this
