### ISSUE TITLE
Ecoscore value is not shown in products to be completed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3705]
Ecoscore value is not shown in products to be completed (and possibly NOVA). The grey placeholder are working ok though.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/104089790-034c1800-5272-11eb-9892-2452433e4fe3.png)

**Comment by VaiTon** [comment]
Maybe we don't request the fields

**Comment by teolemon** [comment]
This is fixed. Thank you @VaiTon 👍
