### ISSUE TITLE
"Add to Open Food Facts" pretends it does not detect a barcode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3714]
"Add to Open Food Facts" pretends it does not detect a barcode, even when it detects one.
![image](https://user-images.githubusercontent.com/1689815/104120905-b7b17100-533a-11eb-91cb-7cd1f8f7178c.png)

**Comment by VaiTon** [comment]
Translation error @teolemon .

**Comment by teolemon** [comment]
Thanks. Added a PR fixing this.
