### ISSUE TITLE
NOVA grey logo not shown

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3715]
NOVA grey logo not shown
3245412697739
![image](https://user-images.githubusercontent.com/1689815/104126716-67e4a100-535e-11eb-99a2-7e02f171b3da.png)
https://world.openfoodfacts.org/product/3245412697739/maxi-poulet-crudites-carrefour

![image](https://user-images.githubusercontent.com/1689815/104126684-32d84e80-535e-11eb-9051-0ab5f410b255.png)

**Comment by kartikaysharma01** [comment]
I am working on this,
