### ISSUE TITLE
Skip and Next Button hides behind the on screen buttons

### ISSUE THREAD

**Issue by mrudultora** [openfoodfacts/openfoodfacts-androidapp#3723]
**Describe the bug**
Skip and Next Button hides behind the onscreen buttons. If the device is in fullscreen mode or the app is in debug mode then everything works fine. This happens in latest version of app downloaded from Google Play Store (v3.6.2).  

**Expected behavior**
This works in debug mode.
![img1](https://user-images.githubusercontent.com/65870389/104303804-8ed2dc80-54f0-11eb-982f-c60a4ea11c00.jpeg)

**Screenshots**
After installing from Play Store.
![img2](https://user-images.githubusercontent.com/65870389/104303886-a7db8d80-54f0-11eb-8781-1c6ea7d3ebac.jpeg)

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 7S]
 - OS: [e.g. Android 10]

**Comment by VaiTon** [comment]
Cannot reproduce I'm sorry

**Comment by mrudultora** [comment]
@VaiTon  I have tested it in 3 devices. All of them were of Redmi. And the Android versions were 8.1 and 10.

**Comment by kartikaysharma01** [comment]
@VaiTon This occurs in phones with virtual navigation buttons. 
Would you like to work on it? @mrudultora

**Comment by mrudultora** [comment]
@kartikaysharma01  Yes, I will work on this 😅
