### ISSUE TITLE
Layout issue on some attributes with long text

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3724]
Layout issue on some attributes with long text
![image](https://user-images.githubusercontent.com/1689815/104328274-f4709a00-54eb-11eb-8fb0-771ca4936d4b.png)

**Comment by varunvjha** [comment]
Can I work on this issue? Please assign this to me.

**Comment by VaiTon** [comment]
> 
> 
> Can I work on this issue? Please assign this to me.

Sure!
