### ISSUE TITLE
The Eco-Score is not clickable

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3734]
The Eco-Score is not clickable like NOVA or Nutri-Score. We should link to the methodology like we usually do.

https://world.openfoodfacts.org/eco-score-the-environmental-impact-of-food-products
https://fr.openfoodfacts.org/eco-score-l-impact-environnemental-des-produits-alimentaires

**Comment by kartikaysharma01** [comment]
Done. Will add a PR soon.
