### ISSUE TITLE
The ingredient photo is not displayed anymore

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3753]
The ingredient photo is not displayed anymore in the product page (ingredient tab)

**Comment by naivekook** [comment]
@teolemon Hi!
Can you add some more specific details?
upd: I tested it on latest master on emulator and I even can't click on item in list, it is not handle click event.

**Comment by kartikaysharma01** [comment]
@teolemon Is this product specific ?

**Comment by teolemon** [comment]
Not quite sure. It keeps happening in specific situations, and not others… 
Will try to narrow the conditions
