### ISSUE TITLE
Environment tab shows content of sysnthesis tab when opened first time

### ISSUE THREAD

**Issue by mrudultora** [openfoodfacts/openfoodfacts-androidapp#3754]
**Describe the bug**
Everytime I open a product and move to environment tab directly for the first time, then it shows the content of synthesis tab. After that, it works fine.

**Comment by kartikaysharma01** [comment]
possible duplicate of #3581 
I suspect the root cause  is same.

**Comment by mrudultora** [comment]
@kartikaysharma01 Okay !
