### ISSUE TITLE
"Take additional pictures" button does not work anymore (from scan mode)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3757]
"Take additional picture" button does not seem to work anymore. 
It lets you take a picture, and the uploading message appears, and spins forever.
This seems to happen when you open the product from scan mode

**Comment by teolemon** [comment]
Ok, I checked: 

- [ ] it does not work when expanding the view from the scan card
- [ ] it works when opening the product from history

**Comment by mrudultora** [comment]
@teolemon Can you please specify where is the button "Take additional picture".

**Comment by teolemon** [comment]
At the bottom of the Summary tab, in the product page. Note that this page can be accessed in 2 ways (either after a scan, or by search/history…)
What seems to be broken is the Scan usecase

**Comment by teolemon** [comment]
I believe this might have been fixed by @VaiTon
