### ISSUE TITLE
Allowing permission but a dialog box appears asking to activate it

### ISSUE THREAD

**Issue by mrudultora** [openfoodfacts/openfoodfacts-androidapp#3762]
**Describe the bug**
Inspite of allowing the permission during runtime, a dialog box appears to activate the permission from settings. (Permission is actually)

**To Reproduce**
1. Open any product
2. Click on _Take extra photos of packaging_ in Summary Tab.
3. Allow the permission.

**Expected behavior**
The camera must open.

**Comment by kartikaysharma01** [comment]
I think its the same as #3757

**Comment by mrudultora** [comment]
@kartikaysharma01 No! they are different.
