### ISSUE TITLE
Move the origins warning to the Environment tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3764]
Move the origins warning to the Environment tab. Otherwise it will be too obnoxious, repetitive and will overload the main tab 

![image](https://user-images.githubusercontent.com/1689815/105411288-7f137080-5c33-11eb-93b8-dd5214bfb562.png)

**Comment by kartikaysharma01** [comment]
@teolemon  The labels warning should be moved to environment tab too , right?

```The Eco-Score takes into account environmental labels. Please take them into photo or edit the product so that they can be taken into account```

**Comment by teolemon** [comment]
Yes, as well, good catch
