### ISSUE TITLE
OfflineSavedProduct.MapOfStringsToStringConverter in OfflineSavedProduct has to be static

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3777]
Execution failed for task ':app:greendao'.
> Inner class openfoodfacts.github.scrachx.openfood.models.entities.OfflineSavedProduct.MapOfStringsToStringConverter in OfflineSavedProduct has to be static. Only static classes are supported if converters or custom types (@Convert) are defined as inner classes.

**Comment by VaiTon** [comment]
We need to convert that class to Java as Kotlin is not supported.

**Comment by mrudultora** [comment]
@VaiTon Yes! https://github.com/greenrobot/greenDAO/issues/643#issuecomment-292943225

**Comment by mrudultora** [comment]
@VaiTon @teolemon I have converted **MapOfStringsToStringConverter.kt** to a java file. Build is successful. Will make a PR soon !
