### ISSUE TITLE
map_returnsListOfCorrectlyMappedLabels_SubElementsAreMappedCorrectly FAILED (LabelsWrapperTest.kt:65)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3787]
openfood.models.entities.label.LabelsWrapperTest > map_returnsListOfCorrectlyMappedLabels_SubElementsAreMappedCorrectly FAILED
com.google.common.truth.ComparisonFailureWithFacts at LabelsWrapperTest.kt:65

**Comment by kartikaysharma01** [comment]
Fixed.
