### ISSUE TITLE
map_returnsListOfCorrectlyMappedSubAllergens_LanguageCode FAILED - AllergensWrapperTest.kt:67

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3788]
openfood.models.entities.allergen.AllergensWrapperTest > map_returnsListOfCorrectlyMappedSubAllergens_LanguageCode FAILED
com.google.common.truth.ComparisonFailureWithFacts at AllergensWrapperTest.kt:67

 openfood.models.entities.allergen.AllergensWrapperTest > map_returnsListOfCorrectlyMappedSubAllergens_Names FAILED
com.google.common.truth.ComparisonFailureWithFacts at AllergensWrapperTest.kt:75

 openfood.models.entities.additive.AdditivesWrapperTest > map_returnsListOfCorrectlyMappedAdditives FAILED
com.google.common.truth.ComparisonFailureWithFacts at AdditivesWrapperTest.kt:46

**Comment by kartikaysharma01** [comment]
Fixed. Will make a PR soon.
