### ISSUE TITLE
Empty box in the nutrition table tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#379]
![screenshot_20170102-134231](https://cloud.githubusercontent.com/assets/1689815/21589456/43ce3846-d0f2-11e6-8e0b-ec716e9b4c1a.png)

The Empty boxes are hidden in the other tabs thanks to a recent commit, but the nutrition table has been forgotten.

**Comment by asmoth360** [comment]
I saw that too, and I was wondering... Could it be possible no not show the tab at all, if there is nothing to display ? For example, if no nutritional information is provided, only display the basic and ingredients tabs. That way, we wouldn't slide to an empty tab.
What do you think ?

**Comment by herau** [comment]
@asmoth360 Not sure this feature will improve the contribution.
I think we have to add some buttons and text to tell to the user that he can add information instead of dropping tabs

what do you think @teolemon ?

**Comment by teolemon** [comment]
I'm on the same line. I'd rather keep the tab and add a prompt/button to add data.

**Comment by teolemon** [comment]
Please see https://github.com/openfoodfacts/OpenFoodFacts-androidApp/issues/457 for more suggestions about that
