### ISSUE TITLE
Support for Open Beauty Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#38]
As Open Beauty Facts gets off the ground, it would be nice to be able to choose which project you want to contribute to.
Possibilites:
- 2 separate apps
- a global switch for the application
- a switch on product send, and "magic" for product read

**Comment by friedger** [comment]
UX-wise the third option is the desired one.

**Comment by itchix** [comment]
We have to think about the "magic", and how to do it ;)

**Comment by teolemon** [comment]
First draft. Magic might not work in the beginning, and we might have to go with separate app, but here's a braindump for a universal app.

### Duplicate the Product Detail view
- change some of the fields to match Open Beauty (or perhaps is it possible to just override the original with a "child view"
- change the output methods to the matching Open * (for the `Add Image` button or `Edit product` button in the product page, for the `Look at this product on Open **` share button)
### Product lookup
- Interrogate Open Beauty Facts and Open Food Facts at the same time, and see which one responds.
- If both respond, ask the user which product to see
- If only only one responds, show the product using the appropriate view
- If the product doesn't exist: see next section
### Product addition
- Works with manual edition, offline edit, prompt after scan or search by barcode if products doesn't exist
- Slider to choose which base to drop the product into

**Comment by teolemon** [comment]
As you've seen, I've made a crude clone at https://play.google.com/store/apps/details?id=org.openbeautyfacts.scanner
