### ISSUE TITLE
Enable the attributes for Open Beauty Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3805]
### What
Enable the attributes for Open Beauty Facts. We have updated the code, and Open Beauty Facts is now attributes capable.
### Part of
- #4168

**Comment by VaiTon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/f17cf0974faaeebec6df761db1660a8a53dfb382/app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/ProductViewActivity.kt#L264-L266

@teolemon isn't it already there?

**Comment by teolemon** [comment]
![Screenshot_20220327-163337.png](https://user-images.githubusercontent.com/1689815/160286486-6e597b2b-1bd4-4232-ac40-357b10da742e.png)

**Comment by teolemon** [comment]
@vaiton it is, we can indeed close
