### ISSUE TITLE
Autocomplete Materials input using taxonomies

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3813]
Autocomplete Materials input using taxonomies

https://static.openfoodfacts.org/data/taxonomies/packaging_materials.json
https://static.openfoodfacts.org/data/taxonomies/packaging_shapes.json

**Comment by kartikaysharma01** [comment]
@teolemon Are we asking user for packaging shapes at product edit/addition right now??

**Comment by teolemon** [comment]
No we're not. We're only asking for the photo of the recycling instructions

**Comment by teolemon** [comment]
@kartikaysharma01 I've made a mockup in #3909 . Going to close this one

**Comment by kartikaysharma01** [comment]
Thanks for the update @teolemon . I will re-visit that after my exams.
