### ISSUE TITLE
Prevent Sentry from blocking the F-Droid build

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3830]
Prevent Sentry from blocking the F-Droid build. Either by disabling it for F-Droid or making it work. We are 1 year (one year) late with the F-Droid version
https://gitlab.com/pierre.slamich/fdroiddata/-/jobs/1028085676#L2588

**Comment by kartikaysharma01** [comment]
@teolemon 
The way to make it work is by adding the auth.token value to sentry.properties file.
The token can be generated [here](https://sentry.io/settings/account/api/auth-tokens/).  Reference documentation: [here](https://docs.sentry.io/platforms/android/proguard/)

Keeping auth tokens exposed in code is not recommended though.

**Comment by kartikaysharma01** [comment]
I found a way to disable sentry for fdroid. Shall I implement that?

**Comment by teolemon** [comment]
We're thinking of creating a dimension `fdroid` to remove Sentry for F-Droid and deblock the year old failing build for Open Food Facts. Given that we already have 4 flavors, I'm a bit reluctant.

The DSN is already present in the manifest: https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/b9db22ebafc424312b4ae4684b948c9db74ce7f7/app/src/main/AndroidManifest.xml#L44

But it's not present in sentry.properties
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/sentry.properties

The error happens on mapping uploads during the F-Droid builds:
```
> compressing mappings
> uploading mappings
error: API request failed
  caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)
Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:persistSentryProguardUuidsForOffReleaseOff-release'.
> Process 'command '/tmp/.sentry-cli8515915559930329791.exe'' finished with non-zero exit value 1
* Try:
``` 

Having seen https://github.com/dmitriy-ilchenko/QrAndBarcodeScanner/issues/49 and this commit (https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7674/diffs?commit_id=1abd81c8589ee13898f1bdac29eb9857f923f19d), I felt hopeful we could pass the key in the build config on F-Droid. Is that possible ?

My understanding is that uploading needs AUTH while the APK only needs the URL where to upload crashes. 

- [ ] If so, can we disable uploading ? 
- [ ] What's the chance we won't be able to deobfuscate traces ?
- [ ] Is there a way to do a proper upload of symbol mapping within F-Droid ?


For reference, Sentry doc on the various ways to authenticate:
https://docs.sentry.io/platforms/java/configuration/

**Comment by naivekook** [comment]
@teolemon do we upload proguard mapping manually via `sentry-cli`?
if yes we can just remove gradle uploading and fix the build.

**Comment by teolemon** [comment]
@naivekook looks good to me
