### ISSUE TITLE
Scanning this barcode will crash the app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3842]
Scanning this barcode will crash the app
![image](https://user-images.githubusercontent.com/1689815/108627963-7394ae80-7458-11eb-809b-3438cdd6bc8a.png)

**Comment by teolemon** [comment]
The stacktrace should be around Sunday, February 21, 2021, 1:48 PM on a Pixel 4

**Comment by teolemon** [comment]
There's a stacktrace

**Comment by kartikaysharma01** [comment]
Are you able to reproduce this ? @teolemon
