### ISSUE TITLE
The app needs to add &lc=[UI lang] in the environnment tab HTML requests

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3848]
The app needs to add 
`&lc=[UI language]`
 in the environnement tab HTML requests

**Comment by VaiTon** [comment]
@teolemon we request the field when we initially get the product. Can we use the suffix with the language to get the desired language? I mean `<field>_en` for example.

**Comment by teolemon** [comment]
mmh… @stephanegigandet @VaiTon 
It does not currently work:
https://world.openfoodfacts.org/api/v0/product/0634065322366.json?fields=environment_infocard_en
https://world.openfoodfacts.org/api/v0/product/0634065322366.json?fields=environment_infocard_fr

**Comment by stephanegigandet** [comment]
&lc=[language code] should be added in all queries in fact
environment_infocard_[language code] does not work and is complex to implement server side

**Comment by VaiTon** [comment]
@stephanegigandet so we should query, for example
```
https://world.openfoodfacts.org/api/v0/product/0634065322366.json?fields=product_name&lc=it
```
Right?
