### ISSUE TITLE
Re-apply the Matomo PR on top of the Kotlin code

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3855]
Re-apply the Matomo PR on top of the Kotlin code.
We waited 6 months+ before merging and the Kotlin refactoring happened meanwhile.
As a result, rebase is complicated, so reapplying one by one the changes in the PR might be the right way to go.
- #3366

**Comment by naivekook** [comment]
I can do it

**Comment by VaiTon** [comment]
Sure you can! @naivekook

**Comment by naivekook** [comment]
```
        //TODO: pass matomo url and id from properties, with different values depending on flavor
        tracker = TrackerBuilder.createDefault("https://example.com/piwik.php", 1)
```

@teolemon which urls should I use?

**Comment by teolemon** [comment]
https://analytics.openfoodfacts.org/piwik.php

**Comment by teolemon** [comment]
Site id =1

**Comment by teolemon** [comment]
But we will need to create a separate one for Android

**Comment by naivekook** [comment]
do we need also create another one for debug mode?

**Comment by teolemon** [comment]
fixed
