### ISSUE TITLE
the page showing the results of a product search is truncated on a Huawei 2019

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3864]
### What
the page showing the results of a product search is truncated on a Huawei 2019
"While all other pages display correctly, the page showing the results of a product search is truncated on a Huawei 2019."
### Potential fix
https://stackoverflow.com/questions/41724100/why-is-my-bottombar-in-the-middle-of-the-screen
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/109430956-30ac7b00-7a04-11eb-80ff-716b189545ee.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/109431240-c563a880-7a05-11eb-9ee9-0ccdff04129a.png)

**Comment by teolemon** [comment]
"When I try to look up a product, I get a number like 1420 I see all the products, until I slide my keyboard down, then I only see 1 product.
This is also the case for to be processed products. How can I see all the products so that I can help you further! Tks (edited) "

**Comment by teolemon** [comment]
Samsung Galaxy A71

**Comment by teolemon** [comment]
https://stackoverflow.com/questions/41724100/why-is-my-bottombar-in-the-middle-of-the-screen

**Comment by nmetifiot** [comment]
This issue aim to fix the nav bar at the bottom ? 
Is there any possibility to test on this device ? Android studio do not offer this device on avd manager.

**Comment by teolemon** [comment]
fixed, I believe
