### ISSUE TITLE
Use compact API for History

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3873]
We could use just a single query by using the `code` field.
```
[...]/api/v2/search?code=<code1>,<code2>&fields=[...]
```

**Comment by VaiTon** [comment]
Blocked on #3840

**Comment by teolemon** [comment]
@VaiTon another use: it could allow to share lists for people without the app.
And the app could open any url like that as a list, and propose to save it locally

**Comment by VaiTon** [comment]
@teolemon actually we query only the local database when opening lists
