### ISSUE TITLE
ANR on first load

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3874]
ANR on first load

![image](https://user-images.githubusercontent.com/1689815/110236546-a352b480-7f36-11eb-925e-84e877d66932.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/112729537-e8ae4480-8f2c-11eb-9ec7-687cc97a2f8e.png)
One user is not happy at all

**Comment by VaiTon** [comment]
Should be fixed by 32d69fc0b41a226a4b300fdd3b54e261ac4c0c2b

**Comment by teolemon** [comment]
I still have an ANR at first start

**Comment by VaiTon** [comment]
Any log? @teolemon

**Comment by VaiTon** [comment]
@teolemon are you able to reproduce on latest develop?

**Comment by teolemon** [comment]
nope, I am not. Closing. Thanks @VaiTon
