### ISSUE TITLE
Query only necessary fields in product search

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3891]
Example of what the app is sending: https://world.openfoodfacts.org/contributor/g123k/1.json?nocache=1
As a result, some unexpected field provoke bugs as seen here: https://twitter.com/g123k/status/1370654639436234753

**Steps:**
- [ ] Find which field we do need to show the product search
- [ ] Make sure we query again when opening the product

**Comment by teolemon** [comment]
Using fields= for the query would solve this one. 
Double checking we had no regression on reduced queries would also be useful

**Comment by VaiTon** [comment]
But we have to consider the fact that with using the full result we can then use the JSON to show the product without making another request.

**Comment by VaiTon** [comment]
@teolemon we're getting 1000 ms as response if we query without fields, 222 ms if we query with fields. 🎉

**Comment by teolemon** [comment]
it does not make a difference server side in terms of execution, but the size of the payload seems to matter
