### ISSUE TITLE
The initial start is messy

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3906]
The initial start is messy. Now we have:

- [ ] The classic Onboarding screen
- [ ] The Changelog
- [ ] The Anonymous Analytics consent screen

We need a way to make it visually less overwhelming:
- [ ] Inline clickable cards on the hope screen for the last two ?
- [ ] Integrate them within the onboarding screen ?
- [ ] Something else ?

https://user-images.githubusercontent.com/1689815/112747021-0920e200-8fb3-11eb-943a-0a0fb021ed20.mp4

**Comment by teolemon** [comment]
Related issue: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3874

**Comment by vtanakov** [comment]
It is a good idea to integrate the Anonymous Analytics consent to onboarding flow, I vote for it.
About the changelog screen - maybe we should turn off automatic presenting and make a button for it? in burger menu or on home screen(it is empty anyway)
