### ISSUE TITLE
kcal, kJ, sat-fat entered values from the app are not stored in the database (Production & Beta feedback)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3919]
New beta feedback on Apr 4, 2021 at 2:43 PM GMT
kcal, kJ, saturated fat entered values from the app are not stored in the database.

**Comment by BathoryPeter** [comment]
I'm also affected by this bug. v3.6.3 (I think not beta) on Android 6.0, installed from Play Store.

**Comment by teolemon** [comment]
thanks @BathoryPeter bumping to P1 as a result

**Comment by VaiTon** [comment]
We send this query when updating a product:
```
code=5281026003670&
lang=fr&
code=5281026003670&
lc=en&
imageUrl=https://static.openfoodfacts.org/images/products/528/102/600/3670/front_fr.4.400.jpg&
nutrition_data_per=100g&
nutriment_energy-kj=20&
nutriment_energy-kcal=532&
nutriment_salt_unit=g&
nutriment_salt=2.9&
nutriment_fat_unit=g&
nutriment_fat=33.5&
nutriment_proteins_unit=g&
nutriment_proteins=20.7&
nutriment_saturated-fat_unit=g&
nutriment_saturated-fat=6.1&
nutriment_carbohydrates_unit=g&
nutriment_carbohydrates=35&
nutriment_sugars_unit=g&
nutriment_sugars=4.6
```
Isn't it correct? @teolemon

**Comment by teolemon** [comment]
why are we passing an image url ?

**Comment by teolemon** [comment]
and the code twice ?

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/116395140-04ef1b00-a824-11eb-915a-e7c146994d2f.png)

**Comment by teolemon** [comment]
More info in #3780 : this might be a race condition

**Comment by teolemon** [comment]
I also had issues on category edition when coming from scan.

**Comment by teolemon** [comment]
It seems to work now

**Comment by BathoryPeter** [comment]
@teolemon In which version? Android 3.6.3 is still wrong for me as you can see in in this test: https://hu.openfoodfacts.org/term%C3%A9k/5998094550080/uborka-savany%C3%BAs%C3%A1g-3-5-cm-regina?rev=16

**Comment by VaiTon** [comment]
> 
> 
> @teolemon In which version? Android 3.6.3 is still wrong for me as you can see in in this test: https://hu.openfoodfacts.org/term%C3%A9k/5998094550080/uborka-savany%C3%BAs%C3%A1g-3-5-cm-regina?rev=16

Could you try on latest beta? It should be fixed

**Comment by teolemon** [comment]
cc @BathoryPeter

**Comment by BathoryPeter** [comment]
I'm sorry for the late answer. It works fine with the latest beta from Play Store.

**Comment by VaiTon** [comment]
> 
> 
> I'm sorry for the late answer. 

Don't worry!

> It works fine with the latest beta from Play Store.

🚀
