### ISSUE TITLE
3 tests failing (SendProductTest.kt)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3927]
openfoodfacts.github.scrachx.openfood.models.SendProductTest > isEqualWithEqualProducts_returnsTrue FAILED
    com.google.common.truth.AssertionErrorWithFacts at SendProductTest.kt:59

openfoodfacts.github.scrachx.openfood.models.SendProductTest > isEqualWithProductsDifferById_returnsTrue FAILED
    com.google.common.truth.AssertionErrorWithFacts at SendProductTest.kt:69

openfoodfacts.github.scrachx.openfood.models.SendProductTest > copy_copiesFromAnotherSendProduct FAILED
    com.google.common.truth.ComparisonFailureWithFacts at SendProductTest.kt:47

**Comment by naivekook** [comment]
looks like this commit https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/0e06205848ed028061e346c9c1d23acca9a3c6ad broke the tests
cc @VaiTon
