### ISSUE TITLE
White card on 1st scan and then crash on 2nd scan (Internal release is broken)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3941]
From my father:
`I have reloaded the app several times and it still does not work correctly.  When I scan there is a blank screen the first time and when I scan again I have an error message that says the application always stops.`

White card on 1st scan and then crash on 2nd scan (Internal release is broken)

![image](https://user-images.githubusercontent.com/1689815/114315309-b55be000-9afe-11eb-9845-79afcd241053.png)

**Comment by naivekook** [comment]
Do we have this crash in sentry?

**Comment by naivekook** [comment]
Oh, maybe this one https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3938#issue-855096928

**Comment by VaiTon** [comment]
Able to reproduce this by scanning barcode `5281026003670` because of a malformed query:
```
https://ssl-api.openfoodfacts.org/api/v0/product/5281026003670.json?fields=Scan&lc=en
```
