### ISSUE TITLE
Improve Main activity UX

### ISSUE THREAD

**Issue by herau** [openfoodfacts/OpenFoodFacts-androidApp#397]
- Use SearchView with VoiceSearch button
<br />- Use Material Design light theme
<br />- Remove all menu item and put links in the text 
<br />- Update the scan button with a barcode icon and with a Material design ux (circle button)
<br />
<br />/cc @teolemon

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21645642/3cfbfb5a-d293-11e6-8361-5098a9410fbe.png)
![image](https://cloud.githubusercontent.com/assets/1689815/21645654/46aa643e-d293-11e6-8d4b-5b33e7c75a91.png)
![image](https://cloud.githubusercontent.com/assets/1689815/21645665/57dfc5fa-d293-11e6-9e2a-87e0c1d7479e.png)

**Comment by herau** [comment]
use the search icon in the sidebar for the searchview
