### ISSUE TITLE
No values saved when adding new products

### ISSUE THREAD

**Issue by ForGorNorPor** [openfoodfacts/openfoodfacts-androidapp#3982]
**Describe the bug**
I am unsure about what exactly happened but I noticed that products I entered from scratch were missing all entries except images, even if I entered details for all the editboxes. This happened for me with product [4260084346005](https://de.openfoodfacts.org/product/4260084346005)

**To Reproduce**
1. Scan unknown product
2. Enter all details, images, etc
3. Save product
4. View product in history and notice missing details

**Expected behavior**
Everything that I entered should be transferred to the server

 - OS: LineageOS 17.1
 - Version 3.6.8 (F-Droid)

**Additional context**
In another attempt to reproduce if this only happens on entering a new product or also when editing products, I tried to split adding with just a picture and entering all the stuff later on (see product 4013149151621). The result is:
- Product is visible in my history with the image I have taken
- Click on product does not do anything, except click feedback
- Scanning the barcode again shuts down the scanner process and throws me back to main screen
- On the website I cannot see the picture: [4013149151621](https://de.openfoodfacts.org/product/4013149151621)

**Comment by doublah** [comment]
Had this happen to me several times, it's really annoying. This seems to happen everytime i add an item, didn't happen on the previous version on F-Droid but that was 3.2.8.

Examples:
[5010482789725](https://world.openfoodfacts.org/product/5010482789725)
[5060254750101](https://world.openfoodfacts.org/product/5060254750101)

**Comment by ForGorNorPor** [comment]
Now that you mention it, it also started happening to me with the newest version. The previous version worked fine.

If there is anything that I can do to help track this error down, please let me know

Edit: Sorry for accidentally closing the issue

**Comment by teolemon** [comment]
Yes, help is welcome to solve it, I've set it to maximum priority

**Comment by ForGorNorPor** [comment]
I just tried, forked the depot and ran the project in debug mode and everything worked fine. Switching back to my installed app and it still does not work to update any data.
I have never done any Android development, is there a way to get log output from the released app? I tried attaching to the running process, but I did not see anything there and breakpoints were not hit.
But maybe the issue is already fixed and all that is needed is a new F-Droid release?

**Comment by SnorrenEnzo** [comment]
I have the same issue with the same OS and F-droid version of the app. The previous version on F-droid, 3.2.8, works better but still sometimes does not save values for certain products.

**Comment by teolemon** [comment]
I believe we fixed that in develop. The next release should have the fix

**Comment by natrius** [comment]
@teolemon 
I ran into this problem with the current f-droid version 3.6.8 - any information on when you going to update F-Droid? Its really annoying as i put it in twice now because i thought i made a mistake the first time. 
EDIT: Happened now with https://world.openfoodfacts.org/product/9100000690629
