### ISSUE TITLE
Duplicate string in Product View

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#401]
![image](https://cloud.githubusercontent.com/assets/1689815/21646253/b5be0c0c-d295-11e6-910e-f3ffe92c2e15.png)

**Comment by herau** [comment]
🔥 🚒

**Comment by teolemon** [comment]
🚰  💧  👍

**Comment by herau** [comment]
in the meantime, also fix another bug with ingredients list ^^ 558073d27d20b597b256f38b1ed39adbd8239f08
