### ISSUE TITLE
Interesting issues while building javadoc

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4018]
Constructing Javadoc information...
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/OfflineSavedProduct.java:18: error: cannot find symbol
import openfoodfacts.github.scrachx.openfood.network.ApiFields;
                                                    ^
  symbol:   class ApiFields
  location: package openfoodfacts.github.scrachx.openfood.network
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/OfflineSavedProduct.java:19: error: cannot find symbol
import openfoodfacts.github.scrachx.openfood.utils.FileUtilsKt;
                                                  ^
  symbol:   class FileUtilsKt
  location: package openfoodfacts.github.scrachx.openfood.utils
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/OfflineSavedProduct.java:21: error: cannot find symbol
import static openfoodfacts.github.scrachx.openfood.utils.Utils.firstNotEmpty;
                                                         ^
  symbol:   class Utils
  location: package openfoodfacts.github.scrachx.openfood.utils
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/OfflineSavedProduct.java:21: error: static import only from classes and interfaces
import static openfoodfacts.github.scrachx.openfood.utils.Utils.firstNotEmpty;
^
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/SendProduct.java:21: error: cannot find symbol
import openfoodfacts.github.scrachx.openfood.models.ProductImageField;
                                                   ^
  symbol:   class ProductImageField
  location: package openfoodfacts.github.scrachx.openfood.models
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/SendProduct.java:22: error: cannot find symbol
import openfoodfacts.github.scrachx.openfood.network.ApiFields;
                                                    ^
  symbol:   class ApiFields
  location: package openfoodfacts.github.scrachx.openfood.network
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/SendProduct.java:23: error: cannot find symbol
import openfoodfacts.github.scrachx.openfood.utils.Utils;
                                                  ^
  symbol:   class Utils
  location: package openfoodfacts.github.scrachx.openfood.utils
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/ToUploadProduct.java:8: error: cannot find symbol
import openfoodfacts.github.scrachx.openfood.models.ProductImageField;
                                                   ^
  symbol:   class ProductImageField
  location: package openfoodfacts.github.scrachx.openfood.models
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/ToUploadProduct.java:86: error: cannot find symbol
    public ProductImageField getProductField() {
           ^
  symbol:   class ProductImageField
  location: class ToUploadProduct
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/SendProduct.java:193: error: cannot find symbol
    public void compress(@NonNull ProductImageField field) {
                                  ^
  symbol:   class ProductImageField
  location: class SendProduct
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/repositories/Taxonomy.java:35: error: package openfoodfacts.github.scrachx.openfood.network.services does not exist
import openfoodfacts.github.scrachx.openfood.network.services.AnalysisDataAPI;
                                                             ^
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/repositories/Taxonomy.java:136: error: cannot find symbol
    public abstract <T> Single<List<T>> load(ProductRepository repository, long lastModifiedDate);
                                             ^
  symbol:   class ProductRepository
  location: class Taxonomy
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/SendProduct.java:31: error: package ApiFields does not exist
    @JsonProperty(ApiFields.Keys.BARCODE)
                           ^
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/SendProduct.java:34: error: package ApiFields does not exist
    @JsonProperty(ApiFields.Keys.PRODUCT_NAME)
                           ^
/Users/pierre/StudioProjects/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/entities/SendProduct.java:51: error: package ApiFields does not exist
    @JsonProperty(ApiFields.Keys.USER_ID)
                           ^
15 errors

"javadoc" finished with exit code 1

**Comment by VaiTon** [comment]
We should use [dokka ](https://github.com/Kotlin/dokka) as we are using Kotlin.

From the GitHub repo:
```kotlin
plugins {
    id("org.jetbrains.dokka") version "1.4.32"
}

repositories {
    mavenCentral()
}
```

**Comment by VaiTon** [comment]
> 
> 
> We should use [dokka ](https://github.com/Kotlin/dokka) as we are using Kotlin.

**Comment by teolemon** [comment]
@VaiTon I was wondering, beyond the tool we use, whether this was the sign of underlying issues in the code

**Comment by VaiTon** [comment]
> 
> 
> @VaiTon I was wondering, beyond the tool we use, whether this was the sign of underlying issues in the code

I think that javadoc cannot correctly reproduce the build. I'm trying dokka

**Comment by VaiTon** [comment]
@teolemon try to run `gradle dokkaHtml`
