### ISSUE TITLE
Bad clipping in "Too bad" button

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4020]
Bad clipping in "Looks good" button
![image](https://user-images.githubusercontent.com/1689815/118549183-620f2a00-b75b-11eb-8a4a-34287610b05b.png)

**Comment by VaiTon** [comment]
You mean the "cancel" button?

**Comment by teolemon** [comment]
Yup, indeed. Corrected thx @VaiTon
