### ISSUE TITLE
The history doesn't load

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4036]
The history doesn't load.
https://user-images.githubusercontent.com/1689815/119820236-8accb780-bef1-11eb-9b7e-5f769ead7591.mp4
After stopping the screen recording and coming back to the app, it shows the empty history screen.
![Screenshot_20210527-133611](https://user-images.githubusercontent.com/1689815/119820289-97e9a680-bef1-11eb-93d2-8b68bc4973c9.png)

**Comment by teolemon** [comment]
Still here in latest build

**Comment by VaiTon** [comment]
I cannot reproduce. Could you give me the exact same steps you followed?

**Comment by teolemon** [comment]
On a physical device, 

1. click on history.
2.  It takes quite a long while to load (on a fresh install)
3. and then loads eventually.

Are we refreshing something in the background ? 
Do we need to block the whole view while doing it ?
