### ISSUE TITLE
I got an empty ingredients tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4037]
I got an empty ingredients tab. I think I had just uploaded an image for ingredients, and everything disappeared.
![image](https://user-images.githubusercontent.com/1689815/119820417-be0f4680-bef1-11eb-8392-34179fba6080.png)

**Comment by VaiTon** [comment]
@teolemon are you able to reproduce? Any steps?

**Comment by teolemon** [comment]
nope, and not rememberings steps to reproduce, closing for now. Thx @VaiTon for the follow up
