### ISSUE TITLE
Replace r.string.txtOk by @android:string/ok

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4061]
```
Replace r.string.txtOk by @android:string/ok
Warning: Cancel/OK dialog button capitalization: The standard Android way to capitalize Ok is "OK" (tip: use `@android:string/ok` instead)
```

**Comment by teolemon** [comment]
Warning: Ellipsis string can be replaced with ellipsis character: Replace "..." with ellipsis character (…, &#8230;) ?

**Comment by VaiTon** [comment]
> 
> 
> Warning: Ellipsis string can be replaced with ellipsis character: Replace "..." with ellipsis character (…, …) ?

I think this happens in translated strings.xml. Isn't there a rule in Crowdin so that you have to put an'ellipsis instead of three points?
