### ISSUE TITLE
Exporting a list generates an empty csv file (0 bytes)

### ISSUE THREAD

**Issue by Telperion87** [openfoodfacts/openfoodfacts-androidapp#4075]
as title says, I'm trying to export my lists. unfortunately they generate empty files

**To Reproduce**
1. Go to "your lists" and then open a list
2. Click on the top/right download/export button  (downwward arrow on top of a line)
3. select a folder where to save the exported file

**Expected behavior**
the csv file should contain the list of the exported files

**Smartphone (please complete the following information):**
 - Device: Moto g7
 - OS: Android 10 stock

**Comment by teolemon** [comment]
Can you go in settings, and at the bottom, you should see your version (and possibly build number) of Open Food Facts ?

**Comment by Telperion87** [comment]
3.6.3, the last one available on google play.
I've also checked right now that on f-droid, version 3.6.8 is available.
What happens if I install it through f-droid? will I loose my lists and other saved settings?

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3794

**Comment by teolemon** [comment]
@Telperion87 This is fixed in develop, which is currently in beta on the playstore
