### ISSUE TITLE
Add more images to existing products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#41]
Add a button on the product page to add fresher or missing images to an existing product.
Here's a mockup of how it would ideally work: a button on each tab, with a language dropdown. It allows the user to direct an image to a function (ingredient/nutrition/front) and a language (product can have up to 20 languages)

The current photo of the ingredients (for example) would be display, or an informative text (There is no photo of ingredients in French)

![image](https://cloud.githubusercontent.com/assets/1689815/19220072/cd7caca0-8e24-11e6-967a-0a00fad94af6.png)

A button in each tab to add a photo if no picture is available 
- one in the main tab for the front image and additional images
- one button for the ingredient photo
- one for the nutrition photo

Behaviour: 
- if a front/ingredients/nutrition image is already selected for this language, show "Add more images" and upload images without selecting them
- if no front/ingredients/nutrition image is selected for this language, show "Add images" and upload images without selecting them (the server will do the job)

**Comment by teolemon** [comment]
should be the button on the summary tab.
Behaviour: 
- if a front image is already selected, show "Add more images" and upload images without selecting them
- if no front image is selected, show "Add images" and upload images without selecting them (the server will do the job)

**Comment by teolemon** [comment]
This one is important: adding more photos to existing products.

**Comment by teolemon** [comment]
Let's keep it simple: a **"Add more images"** button is a very good first step.

**Comment by teolemon** [comment]
Mockup with the latest UX
![image](https://cloud.githubusercontent.com/assets/1689815/22174407/0db6d894-dfde-11e6-8e11-a8f8cacd3dac.png)

**Comment by Shubham2320** [comment]
is it still an issue?
