### ISSUE TITLE
The rotating slogan is not visible in dark mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4119]
The rotating slogan is not visible in dark mode. Video comparison.

https://user-images.githubusercontent.com/1689815/127642749-f5db61b8-3dde-4236-b442-7435b283d46f.mp4

https://user-images.githubusercontent.com/1689815/127642779-7b34d790-b291-42dc-be09-718338f9fe2e.mp4

**Comment by lailajs** [comment]
Hello! Could I try to tackle this?

**Comment by pratyaksh1610** [comment]
@VaiTon This seems to be fixed , I have tested on emulator,
looks like this issue can be closed.
