### ISSUE TITLE
It's not possible to open a product from a list

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4121]
It's not possible to open a product from a list

**To Reproduce**
1. Go to a list with a product 
2. Click on the product
3. It won't open

**Comment by teolemon** [comment]
Related to this ANR: https://sentry.io/organizations/openfoodfacts/issues/2547094385/?project=5276851&query=is%3Aunresolved+release%3Aorg.openfoodfacts.scanner%403.6.6%2B505&statsPeriod=14d

**Comment by VaiTon** [comment]
Fixed by 7c195cf36f3c835998627e7f71087bd926ffc0de
