### ISSUE TITLE
ProductsAPITest.kt: (172, 18): Unresolved reference: blockingGet

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4127]
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/testOff/java/openfoodfacts/github/scrachx/openfood/network/ProductsAPITest.kt: (171, 18): Suspend function 'saveProduct' should be called only from a coroutine or another suspend function
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/testOff/java/openfoodfacts/github/scrachx/openfood/network/ProductsAPITest.kt: (172, 18): Unresolved reference: blockingGet

**Comment by VaiTon** [comment]
Fixed by 97653bd4c586630e5c1d6c4e2791e59347f08d9f
