### ISSUE TITLE
The language names do not show anymore (edit mode, language picker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4140]
The language names do not show anymore (edit mode, language picker)
![image](https://user-images.githubusercontent.com/1689815/128605448-85952250-9958-4660-a0d6-4202d0712847.png)

**Comment by teolemon** [comment]
See #2958 with a mockup
![](https://user-images.githubusercontent.com/1689815/71359523-f6885380-258c-11ea-8047-630a80b514ba.png)

**Comment by naivekook** [comment]
I can take this, which variant from mockups is preferable? Just name or name + code?

**Comment by teolemon** [comment]
I like the implementation from the image manager with name plus code

**Comment by teolemon** [comment]
Fixed. Thanks @naivekook
