### ISSUE TITLE
Improve edit mode by fixing "Next" and "Save" button at the bottom of the screen

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4141]
Improve edit mode by fixing "Next" and "Save" button at the bottom of the screen
![image](https://user-images.githubusercontent.com/1689815/128605502-dbe10795-413c-4fdb-ad10-0d8992072090.png)
![image](https://user-images.githubusercontent.com/1689815/128605523-e8d56c27-bda4-4578-a4b8-dfb9297d2c7e.png)

**Comment by sanchi0204** [comment]
Can I take this up @teolemon ?

**Comment by teolemon** [comment]
I've just assigned you @sanchi0204 👍

**Comment by teolemon** [comment]
@sanchi0204 Have you found where to look ?

**Comment by IshaanDasgupta** [comment]
can I work on this or is the last person still working ?
