### ISSUE TITLE
Editing a product with additional nutrients will erroneously change the recorded values of these nutrients on save

### ISSUE THREAD

**Issue by JeanFred** [openfoodfacts/openfoodfacts-androidapp#4145]
**Describe the bug**

When editing a product with additional nutrients recorded (eg Vitamin D), the additional Nutrient values will be changed on save (even when not edited),  

**To Reproduce**
1. Edit a product with at least one additional nutrient
2. Change something (eg a Label) (but not the nutrient)
3. Save

**Expected behavior**
The nutrient value do not get changed.

**Actual behaviour**
The nutrient value is divided by 1000.

**Example**
See my edits on the product https://world.openfoodfacts.org/product/4001497280001/ : 
* Original version was https://world.openfoodfacts.org/product/4001497280001/hohes-c-orange?rev=31 − 
** `Vitamin C (ascorbic acid) | 35 mg`
* Adding a label in https://world.openfoodfacts.org/product/4001497280001/hohes-c-orange?rev=32
** `Vitamin C (ascorbic acid) | 0.035 mg`
* Adding a packaging in https://world.openfoodfacts.org/product/4001497280001/hohes-c-orange?rev=33
** `Vitamin C (ascorbic acid) | 0 mg |  `

**Smartphone (please complete the following information):**
 - Device: Fairphone 3+
 - Version 3.6.8

**Comment by VaiTon** [comment]
More info: it happens only when selecting mg or ug

**Comment by VaiTon** [comment]
![immagine](https://user-images.githubusercontent.com/12072630/128714562-e2006b89-8f98-458e-a0a3-424e22256fd8.png)
@teolemon @stephanegigandet 

I inputed 10 mg and this is the result. Should we take the _value?

**Comment by teolemon** [comment]
Is this a sever side or client side issue @VaiTon ?

**Comment by stephanegigandet** [comment]
_value and _unit are internal data, they should not be read by the app. Use the _100g field instead. It is always in grams.

**Comment by VaiTon** [comment]
@stephanegigandet we need to use the _unit to set the unit spinner in the app. 

Otherwise what abount taking the value in 100g and then finding the most appropriate unit? 
cc @teolemon

**Comment by stephanegigandet** [comment]
> Otherwise what abount taking the value in 100g and then finding the most appropriate unit?

That's the best thing to do.

**Comment by teolemon** [comment]
Ok, so my edits do not seem taken into account
