### ISSUE TITLE
Compare mode crashes after 1st scan

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4151]
### What
Compare mode crashes after 1st scan, bringing me back to the empty compare mode screen

### Blocking
- #4164 

### Video
https://user-images.githubusercontent.com/1689815/128891462-18d2e5e6-d97d-4cd0-bf8e-ea2fe2957ee1.mp4

**Comment by VaiTon** [comment]
Any stacktrace? @teolemon

**Comment by naivekook** [comment]
Had the same behavior, no any crash in logcat
https://openfoodfacts.slack.com/archives/C02L15QLA/p1628512324026900

**Comment by naivekook** [comment]
will try to investigate
