### ISSUE TITLE
Bigger pictures in the product view

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/openfoodfacts-androidapp#418]
First of all, I like the new display of the product view in the 0.4 version, I think it's much better with each picture in its corresponding tab. The fact we can tap on the pic and zoom in is really great too. 

But I think currently, some improvents could be done to the layout :
- The photos are quite small, and I think some space is wasted. For example, the ingredients picture is often very "horizontal", and could be larger, making it more readable without taking much more vertical space.
- The same goes with the product main picture : when it's mainly vertical, it seems right, but when it's very large horizontally it looks like it could be bigger.
- Some space is wasted between the product picture and the product name.
- The framing could be thinner too, saving some space.

I took the liberty to illustrate with some edited screenshots.
Hoping it's not too complicated to do what I propose :)

![ingredients before-after](https://cloud.githubusercontent.com/assets/19469836/21755970/4071d706-d61b-11e6-89d7-77630d0ac047.png)
![ingredients too small](https://cloud.githubusercontent.com/assets/19469836/21756080/b152ff9e-d61c-11e6-8e8e-7ed374b58f2c.png)
![product before-after](https://cloud.githubusercontent.com/assets/19469836/21756031/297336a2-d61c-11e6-8954-26f822190935.png)

**Comment by huzaifaiftikhar** [comment]
I am working on this.
