### ISSUE TITLE
Unresolved reference: VITAMIN_B1

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4180]
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (5, 81): Unresolved reference: SILICA
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (6, 81): Unresolved reference: VITAMIN_A
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (7, 81): Unresolved reference: VITAMIN_B1
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (26, 13): Type mismatch: inferred type is String but Nutriment was expected
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (28, 13): Type mismatch: inferred type is String but Measurement was expected
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (29, 13): Type mismatch: inferred type is String but Measurement? was expected
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (31, 13): Type mismatch: inferred type is String but Modifier was expected
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (34, 44): The floating-point literal does not conform to the expected type Measurement
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (34, 48): Too many arguments for public final fun getForPortion(portion: Measurement): Measurement defined in openfoodfacts.github.scrachx.openfood.models.ProductNutriments.ProductNutriment
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (34, 110): Unresolved reference: convertFromGOrMl
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (35, 44): The floating-point literal does not conform to the expected type Measurement
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (35, 48): Too many arguments for public final fun getForPortion(portion: Measurement): Measurement defined in openfoodfacts.github.scrachx.openfood.models.ProductNutriments.ProductNutriment
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (35, 107): Unresolved reference: convertFromGOrMl
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (41, 31): Type mismatch: inferred type is String but Nutriment was expected
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (47, 31): Type mismatch: inferred type is String but Nutriment was expected
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (53, 31): Type mismatch: inferred type is String but Nutriment was expected
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (58, 31): Type mismatch: inferred type is String but Nutriment was expected
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (69, 36): Type mismatch: inferred type is String but Nutriment was expected
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (76, 42): Unresolved reference: SILICA
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (76, 50): Unresolved reference: SILICA
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (82, 42): Unresolved reference: VITAMIN_A
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (82, 53): Unresolved reference: VITAMIN_A
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (88, 42): Unresolved reference: VITAMIN_A
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (88, 53): Unresolved reference: VITAMIN_A
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (89, 20): Unresolved reference: VITAMIN_A
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/models/ProductNutrimentsTest.kt: (95, 20): Unresolved reference: VITAMIN_B1
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/utils/QuantityParserTest.kt: (27, 20): Comparison of incompatible enums 'Modifier' and '[ERROR : <ERROR PROPERTY TYPE>]' is always unsuccessful
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/utils/QuantityParserTest.kt: (27, 44): Unresolved reference: Modifier
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/utils/QuantityParserTest.kt: (30, 20): Comparison of incompatible enums 'Modifier' and '[ERROR : <ERROR PROPERTY TYPE>]' is always unsuccessful
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/utils/QuantityParserTest.kt: (30, 44): Unresolved reference: Modifier
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/utils/QuantityParserTest.kt: (33, 20): Comparison of incompatible enums 'Modifier' and '[ERROR : <ERROR PROPERTY TYPE>]' is always unsuccessful
e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/test/java/openfoodfacts/github/scrachx/openfood/utils/QuantityParserTest.kt: (33, 44): Unresolved reference: Modifier

**Comment by VaiTon** [comment]
Fixed by 81e58331f9352880396eee42c4bc61a3288607a5
