### ISSUE TITLE
F-Droid - AntiFeature Tracking

### ISSUE THREAD

**Issue by licaon-kter** [openfoodfacts/openfoodfacts-androidapp#4211]
Ref: https://gitlab.com/fdroid/fdroiddata/-/commit/f7d4c0beacd8bba1be0312a133ae9e4e714b2673

Since https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3258 Sentry is ON

We'd not need this AF if this would be an OPT-IN feature, but right now it's always ON (app tries to connect to `o241488.ingest.sentry.io`) and I don't even see any toggles to disable it.

The PR mentions something about flavors but right now it's universal:
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/3.6.8/app/build.gradle.kts#L149-L150

**Comment by licaon-kter** [comment]
@mimi89999 looking at https://gitlab.com/fdroid/fdroiddata/-/commit/279858e0b8f9403e5e4bd112ca2a7e79160c2bb3 you did try to remove Sentry but didn't help?

**Comment by mimi89999** [comment]
> @mimi89999 looking at https://gitlab.com/fdroid/fdroiddata/-/commit/279858e0b8f9403e5e4bd112ca2a7e79160c2bb3 you did try to remove Sentry but didn't help?

IIRC it did. 3.6.8 is in the repo.

**Comment by licaon-kter** [comment]
It is....and it's connecting to sentry servers :)

Sentry is FOSS...that's okay, but still needs an AF if not opt-in.

**Comment by licaon-kter** [comment]
Also for Pet: https://gitlab.com/fdroid/fdroiddata/-/commit/d53065f9d66d1c1afe3624ce4f3b51843128d1b9

Beauty didn't try to connect so far, odd :)

**Comment by teolemon** [comment]
hello @licaon-kter @mimi89999 :-)
- we have a F-Droid specific flavor to ensure we can disable at build time all potentially problematic things like Sentry.
- There's also an opt-in path of course.
- Help would be welcome to rectify what's not proper. Also be aware that we have a somewhat problematic regression in main (#4120 ) if you intend to refresh the F-Droid release

**Comment by licaon-kter** [comment]
> we have a F-Droid specific flavor to ensure we can disable at build time all potentially problematic things like Sentry.

And that's not used now, right?

> There's also an opt-in path of course.

Where?

**Comment by teolemon** [comment]
- That's possibly not yet in the build recipe. The flavor is `fdroid` and the other `playstore`
  - after upgrade, you see a modal (https://user-images.githubusercontent.com/920265/89418188-0590d000-d730-11ea-8715-12d13909528b.jpg)
  - on first use it's part of the onboarding screens (https://user-images.githubusercontent.com/1689815/131888148-9d760d69-2f11-490d-b2c2-47e5fdf7304a.png)

**Comment by licaon-kter** [comment]
Great, ping me when this new version is out so we can remove Tracking AF

**Comment by fireneat** [comment]
@licaon-kter [A new version has been released](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/HEAD/CHANGELOG.md#370-2021-12-26) on 2021-12-26, which seems to [fix this issue,](https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/94ae3390ba37bdb90152fcfa2308ceb3372f599e) [it hasn't been built by F-Droid though](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/openfoodfacts.github.scrachx.openfood.yml).

**Comment by licaon-kter** [comment]
Not build because it was not detected...

`AutoUpdateMode: Version %v` means `3.6.8` is detected, but `v3.6.8` is not

I'll see about updating the regex ( https://gitlab.com/fdroid/fdroiddata/-/commit/d7e8d31c9854b98434e3237eb76bf3959893af10 )

**Comment by licaon-kter** [comment]
@teolemon no new versionCode/Name either... https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/v3.7.0/app/build.gradle.kts#L213-L214

**Comment by licaon-kter** [comment]
Will need to update the recipes to Java11 too, ping me when you've fixed the version.

**Comment by licaon-kter** [comment]
Beauty (but all share the same codebase) builds from 3.7.0 but it brings a lot of non-FOSS deps: https://www.virustotal.com/gui/file/8d2df16ad6cc057af3f76174d86d5f65748a81cf1b70fbba78c9f58116ab5c76/details :(

**Comment by fireneat** [comment]
So a [new version has been released](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/HEAD/CHANGELOG.md#380-2022-02-09) on 2022-02-09, [but still the version code is still the same](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/v3.8.0/app/build.gradle.kts#L222-L223). Perhaps a new issue should be created? But it seems like current focus rather set on the "new" [smooth-app](https://github.com/openfoodfacts/smooth-app) for OpenFoodFacts. Perhaps consider changing the versionCode and versionNumber when a new version is released @teolemon and @VaiTon ?

**Comment by teolemon** [comment]
@licaon-kter @fireneat I've created a new release with a new version code. Much more stable thanks to @g123k :-) 
https://github.com/openfoodfacts/openfoodfacts-androidapp/releases/tag/v3.8.1

**Comment by teolemon** [comment]
Also, there's a dimension to ensure the absence of non-free blob (which are disabled by default on the Play Store release, by the way)
```
        create("fdroid") {
            dimension = "platform"

            buildConfigField("boolean", "USE_MLKIT", "false")
        }
    }
```

**Comment by teolemon** [comment]
I believe it's not taken into account: https://gitlab.com/fdroid/fdroiddata/-/commit/db16db2e2c8548ea11cb10fb25edab53b72fbc4c

**Comment by licaon-kter** [comment]
ref https://gitlab.com/fdroid/fdroiddata/-/commit/e019f676bfd18d8f313fe6c8de38282e03b70282

ref https://gitlab.com/fdroid/fdroiddata/-/commit/01cd9a54565e4f115e008160dfed8ac8a670c3b2

ref https://gitlab.com/fdroid/fdroiddata/-/commit/d34992a792cbc624e66920c1bec7b2614537810d

ref https://gitlab.com/fdroid/fdroiddata/-/commit/eb75939626b58e2962da0b098db78e60e67f7d5d

beauty is already released so I tested that. thanks
