### ISSUE TITLE
Display issues on the welcome slides

### ISSUE THREAD

**Issue by EasyVector** [openfoodfacts/openfoodfacts-androidapp#4212]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figures below, there are several display issues on those welcome slides:

**1. On the third slide, the description overlaps with the bar below.
2. On the last slide, the icon is blocked by its border and the texts below could not be seen fully as well.**

This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 3.6.8, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts without overlapping and the icon without being blocked.

**Steps to reproduce the behavior:**

1. use the largest font and display in the display setting
2. open this app for the very first time
3. this error could be seen when scrolling horizontally between those slides

**Screenshot**

(The issues are marked in red)

<img src="https://user-images.githubusercontent.com/25502419/131876601-f9392d38-24d4-4422-9fc4-b9846419ed3b.png" alt="copy" width="250"/> <img src="https://user-images.githubusercontent.com/25502419/131876605-b062ed25-8f7b-428b-9373-55edbffb5ac2.png" alt="copy" width="250"/>

**Environment**

1. Version of open food facts: 3.6.8
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by VaiTon** [comment]
Fixed in #4213
