### ISSUE TITLE
Refreshing the History in Open Products Facts causes layout issue

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4219]
Refreshing the History in Open Products Facts causes layout issue

https://user-images.githubusercontent.com/1689815/132094303-74023d99-97ca-4f90-9fec-69cee7eedb0a.mp4

**Comment by naivekook** [comment]
can it be because of Android 12? 
doesn't see this issue on latest develop on pixel 4a with android 11

**Comment by teolemon** [comment]
No idea, still happening on my device (Pixel 4, Android 12), latest develop. It's potentially a layout update that's hardcoded for OFF ?

**Comment by teolemon** [comment]
Can still reproduce with Open Pet Food Facts

**Comment by R4md4c** [comment]
That's weird, I've managed to reproduce it on Open Pet Food Facts, and fixed it there, sorry, I'll take a look later today.

**Comment by R4md4c** [comment]
@teolemon Can you please point me to the build that you've tried? I've tried building from develop, and I was still not able to reproduce the problem. Can you share your reproduction steps? 

https://user-images.githubusercontent.com/297007/152231386-267e0969-b7e2-428a-ab9c-73f7ac1f925f.mp4

**Comment by teolemon** [comment]
release/0.0.2 rebased from develop

**Comment by teolemon** [comment]
![Screenshot_20220202-214052.png](https://user-images.githubusercontent.com/1689815/152233916-47dfb064-832a-49a3-aefe-d89bae8057b5.png)

**Comment by teolemon** [comment]
Ok my bad @R4md4c 
It works on other flavors. The internal build for OPFF has been rejected, but OPF works fine. 
Closing, and sorry for the headache. 😹
