### ISSUE TITLE
Add an option to show the barcode in product view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#422]
Add an option to show the barcode as an image in product view (for people who need for some reason to scan the barcode of a product)

**Comment by ManavPoddar** [comment]
@teolemon I would love to work on this

**Comment by PrajwalM2212** [comment]
Working  on this

**Comment by ManavPoddar** [comment]
@PrajwalM2212 I am already working on it :)

**Comment by PrajwalM2212** [comment]
@ManavPoddar  ok
