### ISSUE TITLE
We need to change the deep link to Hunger games

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4220]
We need to change the deep link to Hunger games

![Screenshot_20210904-204339](https://user-images.githubusercontent.com/1689815/132105182-dea36cdd-0fd0-47a6-8d0d-5dab49892ec1.png)
![Screenshot_20210904-204334](https://user-images.githubusercontent.com/1689815/132105183-1819b18d-237d-493e-8515-943c6b1da103.png)

**Comment by alexfauquette** [comment]
Should not be a problem any more. Urls are back to the normal
