### ISSUE TITLE
Error resolving plugin [id: 'org.jetbrains.dokka', version: '1.5.30']

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4241]
* Where:
Build file '/home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/build.gradle.kts' line: 16

* What went wrong:
Error resolving plugin [id: 'org.jetbrains.dokka', version: '1.5.30']
> Could not resolve all dependencies for configuration 'detachedConfiguration3'.
   > Could not determine artifacts for org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:1.5.30
      > Could not get resource 'https://plugins.gradle.org/m2/org/jetbrains/dokka/org.jetbrains.dokka.gradle.plugin/1.5.30/org.jetbrains.dokka.gradle.plugin-1.5.30.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/org/jetbrains/dokka/org.jetbrains.dokka.gradle.plugin/1.5.30/org.jetbrains.dokka.gradle.plugin-1.5.30.jar'. Received status code 502 from server: Bad Gateway

**Comment by VaiTon** [comment]
@teolemon in develop we're using dokka 1.5.0. Where are you encountering this?

**Comment by teolemon** [comment]
I reverted a commit I merged too quickly, made by Dependabot
