### ISSUE TITLE
Do we still need loadtoast (1 usage) ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4254]
Do we still need loadtoast (1 usage) ?
https://github.com/openfoodfacts/openfoodfacts-androidapp/search?q=loadtoast

**Comment by naivekook** [comment]
I'm working on refactoring allergen screen and already removed the loadtoast, let's wait for the PR :)

**Comment by naivekook** [comment]
see #4269
