### ISSUE TITLE
Do we still use material-dialogs ? (1 match in gradle)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4255]
https://github.com/openfoodfacts/openfoodfacts-androidapp/search?q=material-dialogs
Do we still use material-dialogs ? (1 match in gradle)

**Comment by naivekook** [comment]
<img width="544" alt="Screenshot 2021-09-28 at 17 57 22" src="https://user-images.githubusercontent.com/1501831/135112614-5ea15b0c-b51c-4bea-b972-477074a2a0c6.png">
