### ISSUE TITLE
Trying to add a non existing product to a comparison creates a confusing message

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4267]
**Description**
Trying to add a non existing product to a comparison creates a confusing message

**To Reproduce**
1. Start a comparison
2. Scan a book
3. Boom

**Expected behavior**
"This product can't be added to the comparison because it does not exist in Open Food Facts. Would you like to add it ?"

**Screenshots**
![image](https://user-images.githubusercontent.com/1689815/135141681-1ee45eab-a198-4d3e-92b8-467825bc4e5a.png)

**Comment by TomerPacific** [comment]
Hi @teolemon , I'd like to help out.

**Comment by naivekook** [comment]
just need to replace `txtDialogsContentPowerMode` with `txtDialogsContent` on line 190 in ProductCompareActivity
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/dd598272e6c32da7a816dabcaad2480ea1887591/app/src/main/java/openfoodfacts/github/scrachx/openfood/features/compare/ProductCompareActivity.kt#L190
