### ISSUE TITLE
Open web pages in a custom browser

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-androidapp#428]
Other apps open pages in IceCat, but OpenFood starts Chrome (which shows ToS).

**Comment by teolemon** [comment]
Does it switch apps or try to open a webview ?

**Comment by aleksejrs** [comment]
Switch (a new window appears).

**Comment by teolemon** [comment]
Ok. What is expected is an overlay with ChromeCustom tabs (for systems that have it) that falls back to a Webview (with the default system FOSS webview)

**Comment by teolemon** [comment]
Preparing for other browsers
Remember the user may have more than one browser installed that supports Custom Tabs. If there's more than one browser that supports Custom Tabs and none if them is the preferred browser, ask the user how she wants to open the link

    /**
     * Returns a list of packages that support Custom Tabs.
     */	
    public static ArrayList getCustomTabsPackages(Context context) {
        PackageManager pm = context.getPackageManager();
        // Get default VIEW intent handler.
        Intent activityIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("http://www.example.com"));

        // Get all apps that can handle VIEW intents.
        List resolvedActivityList = pm.queryIntentActivities(activityIntent, 0);
        ArrayList packagesSupportingCustomTabs = new ArrayList<>();
        for (ResolveInfo info : resolvedActivityList) {
            Intent serviceIntent = new Intent();
            serviceIntent.setAction(ACTION_CUSTOM_TABS_CONNECTION);
            serviceIntent.setPackage(info.activityInfo.packageName);
            // Check if this package also resolves the Custom Tabs service.
            if (pm.resolveService(serviceIntent, 0) != null) {
                packagesSupportingCustomTabs.add(info);
            }
        }
        return packagesSupportingCustomTabs;
    }

**Comment by teolemon** [comment]
Allow the user to opt out of Custom Tabs
Add an option into the application for the user to open links in the default browser instead of using a Custom Tab. This is specially important if the application opened the link using the browser before adding support for Custom Tabs.

**Comment by teolemon** [comment]
https://developer.chrome.com/multidevice/android/customtabs#bestpractices

**Comment by Karljoones** [comment]
This is implemented, no? Safe to close?
