### ISSUE TITLE
Transfer the allergen warning popup into the view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#429]
From this: 
![image](https://cloud.githubusercontent.com/assets/1689815/21844866/96797efc-d7f0-11e6-8d12-8dc5b2bfcf10.png)
To this
![image](https://cloud.githubusercontent.com/assets/1689815/21844851/86fc871c-d7f0-11e6-9fb4-8b9a92f5ad08.png)

**Comment by ManognaMutyala** [comment]
Could you please translate the info into english? I would like to work on this issue.

**Comment by teolemon** [comment]
<string name="warning_alert_data">Your allergies info will never be sent to the Open Food Facts server. Also, be careful that data may not be accurate, please double-check by yourself! </string>

**Comment by rahul-jha98** [comment]
Is the issue still open? I would like to work on it if it is.

**Comment by teolemon** [comment]
@rahul-jha98 You can work on it :)

**Comment by rahul-jha98** [comment]
@teolemon I see that the alert is made to pop only if the user opens the fragment the first time.
Now I have made the view in the background containing the text.

Do I have to show it only first time the fragment is opened or it should be there if the list of Allergens is empty and hide it if the user's list of allergens is not empty?

**Comment by vanshikaarora** [comment]
Hey @teolemon Is the Issue already solved? I cannot see a popup here, or could you please help me reproduce the issue
![Screenshot_20190525_151012](https://user-images.githubusercontent.com/34261945/58368089-a74e4780-7f05-11e9-95b5-976fd73b0801.png)

**Comment by teolemon** [comment]
closing, thanks @vanshikaarora :-)
