### ISSUE TITLE
Pressing home icon in product page after scan closes the app

### ISSUE THREAD

**Issue by friedger** [openfoodfacts/OpenFoodFacts-androidApp#43]
Scan a product, see the product details, then click on the home icon in the top left corner. See that the app closes.

The main activity should be shown instead.

**Comment by friedger** [comment]
I don't really understand why the main activity is not launched. I assume it is related to `activity.finish()` here https://github.com/openfoodfacts/OpenFoodFacts-androidApp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/HomeFragment.java#L47

**Comment by itchix** [comment]
You are right, I'll fix it on the next commit :)
