### ISSUE TITLE
More minimalistic loading screen

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#430]
From this: 
![image](https://cloud.githubusercontent.com/assets/1689815/21845628/a1b229ce-d7f3-11e6-9df4-3bc1db86d727.png)
To this: 
![image](https://cloud.githubusercontent.com/assets/1689815/21845612/97e58a6c-d7f3-11e6-9068-78d4d6311efb.png)

**Comment by asmoth360** [comment]
You should consider consulting your notifications :)

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21954263/339a88ae-da4c-11e6-9e97-6aedcbc439a0.png)

**Comment by herau** [comment]
also the loading of a product from scan or by search
