### ISSUE TITLE
Layout/Behaviour issue with ingredient extraction

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4335]
Layout/Behaviour issue with ingredient extraction
![image](https://user-images.githubusercontent.com/1689815/139398738-ef78c7b2-128e-4f03-aa95-6b615b8058ae.png)

![image](https://user-images.githubusercontent.com/1689815/139398711-389a6ecc-9646-4155-ba80-b3a4b2bd6a2a.png)

![image](https://user-images.githubusercontent.com/1689815/139398760-5468b70f-d6cf-464c-a70e-3914137b4080.png)

**Comment by VaiTon** [comment]
Should be fixed by latest develop. https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/389bf33a2894672e82ee6e3358da17042dfcdaa1 I think.
