### ISSUE TITLE
Photo selection is not attributed to logged-in users

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4338]
### What
Photo attribution is inconsistant based on the queries made by the app
### Screenshot
![image](https://user-images.githubusercontent.com/1689815/139523044-37df45b9-ffc7-42a7-9ae5-9e1c650b3305.png)
### Part of

**Comment by g123k** [comment]
I have checked this issue and I think the problem is not from the app itself.
Basically, a call to `/cgi/product_image_upload.pl` is made with valid `user_id` and `password` fields.

I will post an issue on the dedicated repo

**Comment by teolemon** [comment]
We should probably have a test for successful attribution on openfoodfacts-dart

**Comment by stephanegigandet** [comment]
So from the screenshot attached (is that from the app?) it's not image upload that is not attributed, it's the photo selection / cropping. It also needs the user_id + password fields to be sent.

**Comment by g123k** [comment]
This issue should be resolved in the latest release
