### ISSUE TITLE
Replace NutriScore raster assets with svg version

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#434]
https://github.com/openfoodfacts/openfoodfacts-server/blob/5b43a3584b7843716870e2c349c6dc136bcef37f/html/images/misc/nutriscore-e.svg
https://github.com/openfoodfacts/openfoodfacts-server/blob/5b43a3584b7843716870e2c349c6dc136bcef37f/html/images/misc/nutriscore-d.svg
https://github.com/openfoodfacts/openfoodfacts-server/blob/5b43a3584b7843716870e2c349c6dc136bcef37f/html/images/misc/nutriscore-c.svg
https://github.com/openfoodfacts/openfoodfacts-server/blob/5b43a3584b7843716870e2c349c6dc136bcef37f/html/images/misc/nutriscore-b.svg
https://github.com/openfoodfacts/openfoodfacts-server/blob/5b43a3584b7843716870e2c349c6dc136bcef37f/html/images/misc/nutriscore-a.svg

**Comment by teolemon** [comment]
Seems like we have a conversion problem on one the scores```nutriscore-b.svg ```

**Comment by teolemon** [comment]
@herau tells me it applies to all files. I had one of them through https://jakearchibald.github.io/svgomg/ and it reduced the # of errors

**Comment by teolemon** [comment]
http://stackoverflow.com/questions/36453520/inconsistence-between-svg-file-and-android-studio-vector-asset

**Comment by teolemon** [comment]
http://inloop.github.io/svg2android/

**Comment by teolemon** [comment]
@herau I added the vector files

**Comment by jaindiv26** [comment]
The images in the above link are not compatible as images have not been cropped or resized properly for the android studio. Even changing the size dose not affect anything. Check Screenshot.

![screen shot 2018-05-13 at 1 05 47 am](https://user-images.githubusercontent.com/32436867/39960965-2561ce34-564a-11e8-9235-17eae589f860.png)

![screenshot_1526154499](https://user-images.githubusercontent.com/32436867/39961035-8f75d3a0-564b-11e8-8b54-5279b82f172a.png)

**Comment by VaiTon** [comment]
Fixed with 8ad01edb43513c66929f2ac2bbe3a6102df73c5f.
