### ISSUE TITLE
History unavailable

### ISSUE THREAD

**Issue by KommX** [openfoodfacts/openfoodfacts-androidapp#4347]
### What
- The history of products doesn't load.
- Might be related to #4340.
### Steps to reproduce the behavior:
1. Open the app.
2. Go to "History" ("Verlauf" in the German version)
3. See the loading animation forever.

### Expected behavior
The history loads.

### Screenshots
![image](https://user-images.githubusercontent.com/7859245/140639661-286f143a-a087-486f-8fca-3151184563dc.png)

**Smartphone **
 - Device: Google Pixel 3a
 - OS: Android 12
 - Browser: it's in the app, not the browser
 - Version 3.6.6 (542)

**Comment by g123k** [comment]
Hi @KommX,

A fix has landed for #4340. Could you check if it has also resolved this issue please?

**Comment by KommX** [comment]
@g123k 
No, unfortunately the history still doesn't load for me in version 3.6.6 (566).

**Comment by g123k** [comment]
@KommX and if you uninstall, then reinstall the app, do you still have the issue?

**Comment by KommX** [comment]
No, after reinstallation the issue is gone.

**Comment by g123k** [comment]
On my side, with a history containing deleted products, everything works well.
I will thus close this ticket. Please reopen-it, if necessary
