### ISSUE TITLE
3.6.6 (542): App doesn't show some nutrition facts

### ISSUE THREAD

**Issue by KommX** [openfoodfacts/openfoodfacts-androidapp#4349]
**Describe the bug**
After the latest update to 3.6.6 (542) the app doesn't display values that are present via browser.

**To Reproduce**
1. Open [this product](https://world-de.openfoodfacts.org/produkt/4061458215855/fruchtjoghurt-pfirsich#) in a browser.
2. Confirm that values for fat, protein, salt are present.
3. Open [this product](https://world-de.openfoodfacts.org/produkt/4061458215855/fruchtjoghurt-pfirsich#) in the app.
4. Go to 'Nährwertangaben' (nutrition facts).
5. See '?' for fat, protein, salt.

**Expected behavior**
The app should display the values that are in the database.

**Screenshots**
Browser:
![image](https://user-images.githubusercontent.com/7859245/141001714-19ee5440-ed20-42eb-a595-6f86eaf19582.png)

App:
![image](https://user-images.githubusercontent.com/7859245/141001561-67117c91-f61f-420b-92e9-d00cf88f4fcc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 94.0.1

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android 12
 - Browser: it's in the app, not the browser
 - Version 3.6.6 (542)

**Comment by naivekook** [comment]
The problem exists with locales that have comma(`,`) decimal separator instead of dot(`.`).
Need to think of an elegant fix and how to prevent this in the future.

**Comment by teolemon** [comment]
@KommX Does the latest internal build fix it for you ? 
https://play.google.com/apps/internaltest/4699092342921529278

**Comment by KommX** [comment]
@teolemon
I can't say because:
`App not available for this account`
`Your account hasn't yet been invited to participate in this app's internal testing program.`

**Comment by g123k** [comment]
@KommX Any news on this issue?
So, we can fully reproduce your error, in which language is your phone set?

**Comment by KommX** [comment]
I can't reproduce this anymore in 3.6.6 (566).
Thank you for fixing this!
