### ISSUE TITLE
Disable the drowdown

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#439]
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/accountheader_single_profile_without_dropdown.md

**Comment by herau** [comment]
@teolemon 
I'm ok with this idea but we have an `Manage account` item in the multi-accounts view

![screenshot_1484217580](https://cloud.githubusercontent.com/assets/2950666/21886427/ff967c52-d8bb-11e6-8779-b6bccb9e7888.png)

Maybe we can add this item in the user preference panel 

![screenshot_1484217596](https://cloud.githubusercontent.com/assets/2950666/21886442/0a2f5ed6-d8bc-11e6-9b2f-fa1c52aa35f5.png)

**Comment by PrajwalM2212** [comment]
Working on this
