### ISSUE TITLE
History still has old topbar color

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#441]
![image](https://cloud.githubusercontent.com/assets/1689815/21857506/fe5ecefc-d825-11e6-8516-627fc1a3c15a.png)

**Comment by herau** [comment]
![screenshot_1484217272](https://cloud.githubusercontent.com/assets/2950666/21886241/364e2890-d8bb-11e6-8b6e-a0694c642cf9.png)
