### ISSUE TITLE
[Security] Workflow codeql-analysis.yml is using vulnerable action eskatos/gradle-command-action

### ISSUE THREAD

**Issue by Freakston** [openfoodfacts/openfoodfacts-androidapp#4412]
The workflow codeql-analysis.yml is referencing action eskatos/gradle-command-action using references v1.3.3. However this reference is missing the commit [6ff2065a1233a621be482a67cf97261047133d35](https://github.com/eskatos/gradle-command-action/commits/6ff2065a1233a621be482a67cf97261047133d35) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by VaiTon** [comment]
We don't have a codeql-analysis.yml no more. Removed on commit ac5e4d0e161cfe2e761421c4a5e66785678f9cea.

Thanks for the report though!
