### ISSUE TITLE
The photo manager does not open from an expanded scan card

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4439]
### What

- The photo manager does not open from an expanded scan card, by tapping on an ingredient image, as it should
- The ingredient tab seems the only one impacted. The others work fine

### Screen recording

https://user-images.githubusercontent.com/1689815/150645929-351b878b-8a84-4265-ac8b-a347ba2d9152.mp4

### Part of
- #4170

**Comment by g123k** [comment]
@teolemon Could you add the steps to reproduce this issue, please?

**Comment by teolemon** [comment]
I believe this is fixed. Thanks @g123k
