### ISSUE TITLE
[Bug]: Application does not take into account "per portion" switch when entering nutrition facts

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-androidapp#4470]
### Open Food Facts username

postmalight

### What happened?

I report it on behalf of the user:

> When I try to enter the nutritional value of foods per serving, the application automatically puts me by 100ml/100g, but keeping the values entered for a smaller portion.
> I did another test with another food, I immediately chose the portion option before entering the information. Once saved, when I go back to the nutrition tab the portion is 100g.

> I've attached screenshots to show what's going on.
> ![Bug 2](https://user-images.githubusercontent.com/144788/153185968-216d502b-9aa1-43f2-98e7-b80a8f202663.jpg)
> ![Bug 1](https://user-images.githubusercontent.com/144788/153185976-1a6c3ac2-36af-4863-b878-20778581ed7b.jpg)

> Also I think it may be due to some information already entered by some users before me, but who did not specify the portion and which therefore automatically goes to 100 g

### Steps to reproduce the behavior

1. Scan a product without nutrition info
2. Edit nutrition info
3. Add a portion size in g
4. select "per portion" instead of per 100g
5. add values and validate
6. the data for a portion is shown as "per 100g"

### What device were you using ?

I'm not sure of Android Version. I don't know the phone

### Android Version

Android 12

### Barcode(s) of the product(s)

[0057700215036](https://fr.openfoodfacts.org/produit/0057700215036/chargement-maynards)

### Language your app was in

French

### Version

3.6.5 (Default)

### Flavor

Open Food Facts

### Installation method

Google PlayStore

**Comment by alexgarel** [comment]
~~The bug is still to confirm, as on the shown product, serving size is of 100g !~~

~~And in fact I don't see the user modification.~~

[Edit]: I was on wrong product

**Comment by alexgarel** [comment]
I confirm the bug.

**Comment by g123k** [comment]
I will check this issue ASAP @alexgarel, but one question before: what data is sent to the API (100g? or per portion?)
