### ISSUE TITLE
Add a material touch to the history

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#449]
Use cards with square edges instead of rounded ones

![image](https://cloud.githubusercontent.com/assets/1689815/21926244/3c0f6336-d981-11e6-808f-a4e60670e62a.png)

**Comment by herau** [comment]
maybe also use recyclerView (like with the search result) instead of a cardview ?

**Comment by teolemon** [comment]
yes, actually more space efficient, and more consistent.

**Comment by teolemon** [comment]
Also, replacing "OpenFood" by "History" as title

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21975141/3200f624-dbcb-11e6-925c-2cdfe8efc010.png)

**Comment by samagra14** [comment]
I am working on this.
