### ISSUE TITLE
Bug: crash on product edit

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4490]
1. Scan 8435177060038
![image](https://user-images.githubusercontent.com/1689815/154556567-321fbd8c-2cab-4ad1-9718-63a1ae669647.png)

2. Edit
3. Boom

Sentry Issue: [OPENFOODFACTS-ANDROID-512](https://sentry.io/organizations/openfoodfacts/issues/2884853601/?referrer=github_integration)

`
IllegalStateException: Attempting to launch an unregistered ActivityResultLauncher with contract openfoodfacts.github.scrachx.openfood.features.product.edit.ProductEditActivity$EditProductContract@197a442 and input Product[code=3560070597772,productName=Cidre de Bretagne IGP,additional_properties={customer_service_fr=Interdis - TSA 91431 - 91343 MASSY Cedex - France, generic_name_fr=Cidre de Bretagne IGP - Doux, nutrition_grades_tags=[not-applicable], attribute_groups_fr=[{attributes=[{description=, description_short=Qualité nutritionnelle inconnue, grade=unknown, icon_url=https://static.openfoodfacts.org/images/attributes/nutriscore-unknown.svg, id=nutriscore, match=0, name=Nutri-Score, status=unknown, title=Nutri-Score non calculé}, {grade=unknown, icon_url=https://static.openfoodfacts.org/images/attributes/nutrient-level-salt-unknown.svg, id=low_salt, missing=Données nutritionnelles manquantes, name=Sel, status=unknown, title=Sel en quantité inconnue}, {grade=unknown, icon_url=https://static.openfoodfacts.org/images/attributes/nutrient-level-fat-unknown.svg, id=low_fat, missing=Données nutritionnelles manquantes, name=Matières grasses, status=unknown, title=Matières grasses en quantité inconnue}, {grade=unknown, icon_url=https://static.openfoodfacts.org/images/attributes/nutrient-level-sugars-unknown.svg, id=low_sugars, missing=Données nutritionnelles manquantes, name=Sucres, status=unknown, title=Sucres en quantité inconnue}, {grade=unknown, icon_url=https://static.openfoodfacts.org/images/attributes/nutrient-level-saturated-fat-unknown.svg, id=low_saturated_fat, missing=Données nutritionnelles manquantes, name=Acides gras saturés, status=unknown, title=Acides gras saturés en quantité inconnue}], id=nutritional_quality, name=Qualité nutritionnelle}, {attributes=[{debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-gluten.svg, id=allergens_no_gluten, match=100, name=Gluten, status=known, title=Ne contient pas : Gluten}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-milk.svg, id=allergens_no_milk, match=100, name=Lait, status=known, title=Ne contient pas : Lait}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-eggs.svg, id=allergens_no_eggs, match=100, name=Œufs, status=known, title=Ne contient pas : Œufs}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-nuts.svg, id=allergens_no_nuts, match=100, name=Fruits à coque, status=known, title=Ne contient pas : Fruits à coque}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-peanuts.svg, id=allergens_no_peanuts, match=100, name=Arachides, status=known, title=Ne contient pas : Arachides}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-sesame-seeds.svg, id=allergens_no_sesame_seeds, match=100, name=Graines de sésame, status=known, title=Ne contient pas : Graines de sésame}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-soybeans.svg, id=allergens_no_soybeans, match=100, name=Soja, status=known, title=Ne contient pas : Soja}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-celery.svg, id=allergens_no_celery, match=100, name=Céleri, status=known, title=Ne contient pas : Céleri}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-mustard.svg, id=allergens_no_mustard, match=100, name=Moutarde, status=known, title=Ne contient pas : Moutarde}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-lupin.svg, id=allergens_no_lupin, match=100, name=Lupin, status=known, title=Ne contient pas : Lupin}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-fish.svg, id=allergens_no_fish, match=100, name=Poisson, status=known, title=Ne contient pas : Poisson}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-crustaceans.svg, id=allergens_no_crustaceans, match=100, name=Crustacés, status=known, title=Ne contient pas : Crustacés}, {debug=0 ingredients (0 unknown), grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/no-molluscs.svg, id=allergens_no_molluscs, match=100, name=Mollusques, status=known, title=Ne contient pas : Mollusques}, {debug=en:sulphur-dioxide-and-sulphites in allergens, grade=e, icon_url=https://static.openfoodfacts.org/images/attributes/contains-sulphur-dioxide-and-sulphites.svg, id=allergens_no_sulphur_dioxide_and_sulphites, match=0, name=Anhydride sulfureux et sulfites, status=known, title=Contient : Anhydride sulfureux et sulfites}], id=allergens, name=Allergènes, warning=Il est toujours possible que les données sur les allergènes soient manquantes, incomplètes, incorrectes ou que la composition du produit ait changé. Si vous êtes allergique, vérifiez toujours les informations sur l'emballage réel du produit.}, {attributes=[{grade=unknown, icon_url=https://static.openfoodfacts.org/images/attributes/vegan-status-unknown.svg, id=vegan, name=Végétalien, status=unknown, title=Caractère végétalien inconnu}, {grade=unknown, icon_url=https://static.openfoodfacts.org/images/attributes/vegetarian-status-unknown.svg, id=vegetarian, name=Végétarien, status=unknown, title=Caractère végétarien inconnu}, {grade=unknown, icon_url=https://static.openfoodfacts.org/images/attributes/palm-oil-content-unknown.svg, id=palm_oil_free, name=Sans huile de palme, status=unknown, title=Présence d'huile de palme inconnue}], id=ingredients_analysis, name=Ingrédients}, {attributes=[{description=, description_short=Aliments transformés, grade=c, icon_url=https://static.openfoodfacts.org/images/attributes/nova-group-3.svg, id=nova, match=50, name=Groupe NOVA, status=known, title=NOVA 3}, {grade=a, icon_url=https://static.openfoodfacts.org/images/attributes/0-additives.svg, id=additives, match=100, name=Additifs, status=known, title=Sans additifs}], id=processing, name=Transformation des aliments}, {attributes=[{description=L'agriculture biologique vise à protéger l'environnement et à conserver la biodiversité en prohibant ou limitant l'utilisation d'engrais synthétiques, de pesticides et d'additifs alimentaires., description_short=Les produits bios encouragent la durabilité écologique et la biodiversité., grade=e, icon_url=https://static.openfoodfacts.org/images/attributes/not-organic.svg, id=labels_organic, match=0, name=Agriculture biologique, status=known, title=Pas un produit bio}, {description=Quand vous achetez des produits du commerce équitable, les producteurs dans les pays en développement sont payés un prix plus haut et plus équitable, ce qui les aide à atteindre des plus hauts standards sociaux et environnementaux et à les conserver., description_short=Les produits du commerce équitable aident les producteurs des pays en voie de développement., grade=e, icon_url=https://static.openfoodfacts.org/images/attributes/not-fair-trade.svg, id=labels_fair_trade, match=0, name=Commerce équitable, status=known, title=Ne provient pas du commerce équitable}], id=labels, name=Labels}], product_name_fr=Cidre de Bretagne IGP, ingredients_from_palm_oil_tags=[], selected_images={front={display={fr=https://images.openfoodfacts.org/images/products/356/007/059/7772/front_fr.23.400.jpg}, small={fr=https://images.openfoodfacts.org/images/products/356/007/059/7772/front_fr.23.200.jpg}, thumb={fr=https://images.openfoodfacts.org/images/products/356/007/059/7772/front_fr.23.100.jpg}}, ingredients={display={fr=https://images.openfoodfacts.org/images/products/356/007/059/7772/ingredients_fr.20.400.jpg}, small={fr=https://images.openfoodfacts.org/images/products/356/007/059/7772/ingredients_fr.20.200.jpg}, thumb={fr=https://images.openfoodfacts.org/images/products/356/007/059/7772/ingredients_fr.20.100.jpg}}}, languages_codes={fr=10, it=8, nl=8}, ingredients_text_fr=Contie...
    at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
    at androidx.fragment.app.Fragment$9.launch(Fragment.java:3507)
    at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
    at openfoodfacts.github.scrachx.openfood.features.product.view.summary.SummaryProductFragment.editProduct(SummaryProductFragment.kt:903)
    at openfoodfacts.github.scrachx.openfood.features.product.view.summary.SummaryProductFragment.onEditProductButtonClick(SummaryProductFragment.kt:848)
...
(15 additional frame(s) were not displayed)
`

**Comment by g123k** [comment]
It seems that this issue is a duplicate of https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4528 and is thus fixed

**Comment by teolemon** [comment]
Thanks @g123k closing
