### ISSUE TITLE
Screenshots tests are failing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4497]
### What
- Screenshots tests are failing
### Part of
- #4167 

### Logs/Stacktrace

- [ ] https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/androidTestScreenshots/java/openfoodfacts/github/scrachx/openfood/AbstractScreenshotTest.kt
- [ ] e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/build/generated/source/kapt/offPlaystoreScreenshotsAndroidTest/openfoodfacts/github/scrachx/openfood/AbstractScreenshotTest_MembersInjector.java:13: error: cannot find symbol
- [ ] @QualifierMetadata("dagger.hilt.android.qualifiers.ApplicationContext")
- [ ]  ^
- [ ]   symbol: class QualifierMetadata
- [ ] https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/androidTest/java/openfoodfacts/github/scrachx/openfood/repositories/TaxonomiesRepositoryTest.kt
- [ ] e: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/build/generated/source/kapt/offPlaystoreScreenshotsAndroidTest/openfoodfacts/github/scrachx/openfood/repositories/TaxonomiesRepositoryTest_MembersInjector.java:13: error: cannot find symbol
- [ ] @QualifierMetadata("dagger.hilt.android.qualifiers.ApplicationContext")
- [ ]  ^
- [ ]   symbol: class QualifierMetadata
- [ ] w: warning: The following options were not recognized by any processor: '[eventBusIndex, kapt.kotlin.generated]'
- [ ] 
- [ ] > Task :app:kaptOffPlaystoreScreenshotsAndroidTestKotlin FAILED

**Comment by g123k** [comment]
Fixed by #4584
