### ISSUE TITLE
6 tests still failing after yesterday's fixes

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4502]
### What
- [6 tests still failing](https://github.com/openfoodfacts/openfoodfacts-androidapp/runs/5346726445?check_suite_focus=true) after yesterday's fixes
- [ ] ProductCompareViewModelTest > addProductToCompare_shouldTrackRightAnalytics_whenProductsAddedToCompare() FAILED org.mockito.exceptions.verification.TooFewActualInvocations at ProductCompareViewModelTest.kt:109
- [ ] ProductCompareViewModelTest > addProductToCompare_shouldAddProducts_whenProductsAreDifferent() FAILED
    com.google.common.truth.ComparisonFailureWithFacts at ProductCompareViewModelTest.kt:72
- [ ] ProductPhotosViewModelTest > Given product api returns product images > When imageNames is called > it should return image names sorted by uploaded time() FAILED
    java.lang.NullPointerException at ProductPhotosViewModelTest.kt:66
- [ ] ProductPhotosViewModelTest > Given product api returns product images > When imageNames is called > it should return non empty list() FAILED
    java.lang.NullPointerException at ProductPhotosViewModelTest.kt:66
- [ ] SimpleScanViewModelTest > changeCameraFlash_shouldChangeFlash() FAILED
    com.google.common.truth.ComparisonFailureWithFacts at SimpleScanViewModelTest.kt:75
- [ ] SimpleScanViewModelTest > changeCameraAutoFocus_shouldChangeAutoFocus() FAILED
    com.google.common.truth.ComparisonFailureWithFacts at SimpleScanViewModelTest.kt:57

**Comment by teolemon** [comment]
ProductCompareViewModelTest > addProductToCompare_shouldEmitAlreadyExistEvent_whenTheSameProductAdded() PASSED

ProductCompareViewModelTest > addProductToCompare_shouldTrackRightAnalytics_whenProductsAddedToCompare() FAILED
    org.mockito.exceptions.verification.TooFewActualInvocations at ProductCompareViewModelTest.kt:109

ProductCompareViewModelTest > onInit_productsAreEmpty() PASSED

ProductCompareViewModelTest > addProductToCompare_shouldAddProducts_whenProductsAreDifferent() FAILED
    com.google.common.truth.ComparisonFailureWithFacts at ProductCompareViewModelTest.kt:72

ProductPhotosViewModelTest > Given product api returns product images > When imageNames is called > it should return image names sorted by uploaded time() FAILED
    java.lang.NullPointerException at ProductPhotosViewModelTest.kt:66

ProductPhotosViewModelTest > Given product api returns product images > When imageNames is called > it should return non empty list() FAILED
    java.lang.NullPointerException at ProductPhotosViewModelTest.kt:66

SimpleScanViewModelTest > changeCameraFlash_shouldChangeFlash() FAILED
    com.google.common.truth.ComparisonFailureWithFacts at SimpleScanViewModelTest.kt:75

SimpleScanViewModelTest > changeCameraAutoFocus_shouldChangeAutoFocus() FAILED
    com.google.common.truth.ComparisonFailureWithFacts at SimpleScanViewModelTest.kt:57

**Comment by g123k** [comment]
If I'm not wrong, all tests seems to be OK right now: https://github.com/openfoodfacts/openfoodfacts-androidapp/runs/5633257154?check_suite_focus=true

**Comment by teolemon** [comment]
Thank you, I'm closing it
