### ISSUE TITLE
Crash on barcode scan

### ISSUE THREAD

**Issue by coastgnu** [openfoodfacts/openfoodfacts-androidapp#4504]
Scanning a barcode leads to immediate crash

OFFDB for Android Version 3.6.8, via freedroid

**Comment by teolemon** [comment]
Would you have the exact barcode @coastgnu ?

**Comment by coastgnu** [comment]
App crashed on all barcodes.

I removed the freedroid based app and reinstalled the app from the googleplay repository.

+ I activated the google barcode scan. BTW. The google barcode scan lib is much faster. 

The app works as I would expect it to do. No crash so far.

**Comment by g123k** [comment]
Ok, I close this issue since it seems fixed.
