### ISSUE TITLE
Scan button not intuitive

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/openfoodfacts-androidapp#452]
On the new home screen, I find the new "red camera button" not very intuitive. Nothing says it's the button to scan a barcode, instead it now looks like it takes a picture, which is not exactly its function. 
In my opinion a button with "scan", a barcode logo or anything like this would be clearer, especially for a new user.

**Comment by herau** [comment]
it was the barcode icon for the first draft but we using already the camera icon for the left menu, so i switch to this one.

I agree with you opinion but i don't think the barcode will improve the understanding of the feature (maybe we have to create a tutorial which be displayed the first time the app is opened).

![screenshot_1484327510](https://cloud.githubusercontent.com/assets/2950666/21938474/c9492e96-d9bb-11e6-954f-b3ae172591b8.png)

**Comment by asmoth360** [comment]
I like the barcode better. Why not put it in the left menu too? 
Also a tutorial was not needed when there was a "scan" button before. I think if we need one now, it means it's less clear... 
Out of curiosity, why did the button change to this one, is it to match the "official" material buttons or something like that?

**Comment by herau** [comment]
indeed WE are trying to apply the material design guidelines. 

i can switch to the barcode if @teolomon is agree.

**Comment by teolemon** [comment]
@asmoth360 I can see your point how the paper fab might be less intuitive for some than the "Scan product" in full text.
However, we chose the camera because the icon was standard, way more and quicker recognized than the barcode, and gave an equivalent idea of what's going to happen.

Let's give it a little time to live, and we'll do some more user testing ?

**Comment by asmoth360** [comment]
No problem, it's just my opinion.

**Comment by teolemon** [comment]
Let's use the Scan icon instead. Bonus points if you add the button on the all views of the app (especially on the product view), for Quick anytime scan.

**Comment by ross-holloway94** [comment]
Fixed in #671
