### ISSUE TITLE
New proposed UX for allergen detector

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#453]
New UX to add an allergen, stolen from ConsoReglo

![screenshot_20161106-200504](https://cloud.githubusercontent.com/assets/1689815/21387414/d87681a8-c777-11e6-88d5-378b3b149705.png)

**Comment by asmoth360** [comment]
Seems way better. Also this way there would be only real allergens? Currently the list is huge.
