### ISSUE TITLE
The flash button toggle doesn't work when the Edittext is visible

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-androidapp#4534]
### What
In the barcode scanner, if the text input dialog is visible, the flash button is clickable but doesn't do anything

### Steps to reproduce the behavior
1. Open the barcode scanner
2. Enter in "text mode"
3. Click on the flash toggle

### Expected behavior
Two options here: hide the button or make it work 😋

**Comment by g123k** [comment]
I can work on a fix for this issue if you want.

But what would be the right way to fix it? Hide the button or make it work?
Cc @teolemon or @VaiTo

**Comment by VaiTon** [comment]
I would prefer if it was hidden while in "input barcode mode", as the user is now focusing on another part of the UI. Any opinion @teolemon ?

**Comment by g123k** [comment]
Thanks for your reviews @teolemon & @VaiTon 
It's now fixed
