### ISSUE TITLE
Try to send images as soon they are selected.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#455]
Try to send images as soon they are selected
Provide live feedback on whether it has been properly received
```Sending…```
```Upload successful…```

**Comment by teolemon** [comment]
- You get an ```Currently uploading``` message from the moment you select the message to the successful end of the upload
- You get a ```Success``` message as soon as the server replies success. 
![image](https://cloud.githubusercontent.com/assets/1689815/22173762/a460e918-dfcc-11e6-8955-3a8e988b1298.png)
- You get a ```Try again``` prompt that attempts sending the image again.
![image](https://cloud.githubusercontent.com/assets/1689815/22173767/b2921d86-dfcc-11e6-9452-e8d1841be8f6.png)

**Comment by teolemon** [comment]
Here's a common example of the use by power contributors: 1 image per side of a box.
![image](https://cloud.githubusercontent.com/assets/1689815/22182909/4752dd9a-e0b1-11e6-9e80-3ebe96ea701d.png)

**Comment by ManognaMutyala** [comment]
I am working on this!!

**Comment by ManognaMutyala** [comment]
@teolemon @ross-holloway94 I just wanted to know if it is ok to add progress bar to show the status of upload?

**Comment by teolemon** [comment]
Visual feedback, as soon as possible, is extremely important. It should be visible, yet it should not prevent the users from continuing product addition.
