### ISSUE TITLE
Enable native nutrition input

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#458]
![image](https://cloud.githubusercontent.com/assets/1689815/21975359/8d4a3634-dbcc-11e6-8bd8-f2553a80365d.png)
![image](https://cloud.githubusercontent.com/assets/1689815/21975441/fe111ce8-dbcc-11e6-914c-ace14835de7a.png)

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21975359/8d4a3634-dbcc-11e6-8bd8-f2553a80365d.png)

**Comment by PrajwalM2212** [comment]
Native nutrition input is enabled during GSoC. So closing this.
