### ISSUE TITLE
The "No Nutrition facts" toggle does not work correctly

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4582]
### What
- The "No Nutrition facts" toggle does not work correctly

### Part of
- #4166 

### Video
https://user-images.githubusercontent.com/1689815/159445100-18216220-e401-427e-bb03-4d3ffc579b03.mp4

**Comment by teolemon** [comment]
Still not working: https://world.openfoodfacts.org/product/3021891403241/chargement

**Comment by teolemon** [comment]
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/1689815/159684536-ea98c022-9a9e-4438-84de-eef3bd59370d.png">

**Comment by g123k** [comment]
What's wrong exactly?

Because I can see the banner on your product:
<img width="636" alt="Screen Shot 2022-03-23 at 12 10 50" src="https://user-images.githubusercontent.com/246838/159686549-5dea9aeb-ab72-441b-836e-88e657f56139.png">

**Comment by teolemon** [comment]
I'm trying to reenable them, and I can't

**Comment by g123k** [comment]
Ok, I understood, I have to force the value

**Comment by teolemon** [comment]
The edit is not honored when I try editing the alcohol level.
In fact, it does not honor other fields.

**Comment by g123k** [comment]
Are you sure @teolemon?

On your product (https://world.openfoodfacts.org/product/3021891403241/loading), my edits were perfectly saved, including the alcohol level

<img width="613" alt="Screen Shot 2022-03-23 at 14 37 44" src="https://user-images.githubusercontent.com/246838/159712387-d50a167a-f544-4814-a99f-f973c9d377b3.png">

**Comment by teolemon** [comment]
it seems to be working now

**Comment by g123k** [comment]
@teolemon Can we close this issue?

**Comment by teolemon** [comment]
Closed, thank you 👍
