### ISSUE TITLE
old proposal for label edition

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#459]
![image](https://cloud.githubusercontent.com/assets/1689815/21966197/2f9ea766-db6f-11e6-9469-a0e78c025de8.png)

Either a checkbox like bio, or more probably an editable field with autocomplete

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21966197/2f9ea766-db6f-11e6-9469-a0e78c025de8.png)

**Comment by asmoth360** [comment]
@teolemon Good idead, it looks good. And when you type in the input field, it filters the logos ?
