### ISSUE TITLE
Use `Auto Update Mode` in fdroid meta data

### ISSUE THREAD

**Issue by friedger** [openfoodfacts/OpenFoodFacts-androidApp#46]
The current meta data use `None` as the method but it should be 
`Version %v`

See
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/openfoodfacts.github.scrachx.openfood.txt

**Comment by teolemon** [comment]
It looks like it's fixed @friedger ?

**Comment by friedger** [comment]
Fixed
