### ISSUE TITLE
After the camera permission granted, the camera screen should be opened

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-androidapp#4607]
### What
- After the camera permission granted, nothing happens right now
- It should open the camera instead

### Steps to reproduce the behavior
1. Launch the app for the first time (no permission set)
2. Open a product -> environment tab
3. Click to take a picture
4. Grant the permission
5. …… and nothing

**Comment by teolemon** [comment]
People are likely to add photos from scan (thus permission already granted), but good catch.
The Environment tab was added after the initial implementation, so it might provoke weird behaviours in general
