### ISSUE TITLE
The low battery mode is inconsistent

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4610]
### What
- My low battery mode was disabled in the Open Food Facts settings (but present system wide)
- The low battery mode is inconsistent because #4598 happened

**Comment by g123k** [comment]
For the app, the low battery mode requires two criteria:
- User prefs: Disable photo loading set to ON
- Device battery level < 15

**Comment by VaiTon** [comment]
What about querying the OS for the system wide battery save mode and remove the app-specific logic? @teolemon @g123k

**Comment by teolemon** [comment]
I realize that it's actually more of an annoyance than a plus, because the app starts behaving differently without letting me in control. 
So honoring the system without letting users opt out feels weird.

**Comment by g123k** [comment]
So what about:
- Removing the current dark mode feature in the app
- Add a new preference allowing to follow (or not) the system feature

**Comment by VaiTon** [comment]
> Removing the current **dark mode** feature in the app

@g123k are you sure you don't mean "battery save mode"?

**Comment by g123k** [comment]
@VaiTon Hmmm 🤦‍♂️ yes, yes you're right
