### ISSUE TITLE
NullNull in Nutrition

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#462]
https://fr.openfoodfacts.org/produit/3660140003865/la-bio-pizza-3-fromages-mozzarella-emmental-gorgonzola-manosque
![image](https://cloud.githubusercontent.com/assets/1689815/21957050/c51a3d6e-da8e-11e6-9af9-a37e70012858.png)

**Comment by teolemon** [comment]
https://fr.openfoodfacts.org/produit/3660140003865/la-bio-pizza-3-fromages-mozzarella-emmental-gorgonzola-manosque

**Comment by herau** [comment]
Also use the same layout than the web site and the current official OFF app.

Example

```
1.3 g Matières grasses / Lipides en faible quantité
0.23 g Acides gras saturés en faible quantité
0.8 g Sucres en faible quantité
2.7 g Sel en quantité élevée
```

**Comment by teolemon** [comment]
can we add an hyphen ?
```16.9 g – Fat in moderate quantity```

**Comment by herau** [comment]
16.9 g – **Fat** in moderate quantity ?

**Comment by herau** [comment]
@teolemon does the nutrition facts units are always in grammes in this view ? because the API doesn't return the unit all the time and i have to put a default unit value (like `g`).

**Comment by teolemon** [comment]
a priori, yes. weird that we don't have units.

**Comment by herau** [comment]
![screenshot_20170118-135249](https://cloud.githubusercontent.com/assets/2950666/22067532/f4334162-dd91-11e6-902d-c6bdeece4b3f.png)

@teolemon what do you think about this version ?
