### ISSUE TITLE
Monitor barcode scanning performance

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-androidapp#4622]
### What
Once the "tap-to-focus" feature is implemented, we have to monitor if changes worth the implementation on Smoothie (Flutter app). For that, we have to collect data on this.

- [x] Find a solution
- [x] Monitor performances (#4651)

**Comment by g123k** [comment]
To achieve this feature, which tool should we use?

- The embedded analytics?
- Or a dedicated tool like Firebase Performance Monitoring? https://firebase.google.com/docs/perf-mon

**Comment by VaiTon** [comment]
> The embedded analytics

I'm for this one. We can create an event and send it to matomo.
