### ISSUE TITLE
How is that possible ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4624]
### What
- Device: OnePlus 6
Device language: Italian
App version code: 23
App version name: 2.4.7
Android version: Android 11 (SDK 30)

**Comment by VaiTon** [comment]
@teolemon what's the issue here?

**Comment by teolemon** [comment]
A device on Android 11, stuck on app version code 23 ?

**Comment by teolemon** [comment]
What is the story here ?

**Comment by VaiTon** [comment]
I think we can close this as not reproducible.
