### ISSUE TITLE
Add spaces after commas in Product View

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#468]
Add spaces after commas in Product View 
- Packaging
- Manufacturing Places
- Purchase place

Check that all fields have proper spaces after commas, so that we're consistant across fields.

**Comment by Shubham2320** [comment]
@teolemon can I work on it?

**Comment by ross-holloway94** [comment]
@Shubham2320 It doesn't seem to be assigned or claimed, so by all means :)
