### ISSUE TITLE
"Ingredients are listed in order of importance (quantity)."

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#469]
Add above ingredients (perhaps in light gray)
```Ingredients are listed in order of importance (quantity).```

**Comment by sowmya9029** [comment]
I can work on this.

**Comment by mythio** [comment]
Is this fixed?

**Comment by diskostu** [comment]
I think it is completely unclear what has to be done here. Perhaps any more information on this, @teolemon ?

**Comment by teolemon** [comment]
It's something we display on the website, but looking back it's not a lot of value added.

**Comment by teolemon** [comment]
I propose we close this bug.
