### ISSUE TITLE
Allow anonymous contribution

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#47]
The Open Food Facts server allows anonymous contributions. Some users don't want to create accounts.
Let users create new products anonymously

**Comment by itchix** [comment]
So we don't have to send user_id and password parameters on this link : "http://world.openfoodfacts.org/cgi/product_jqm2.pl" if they want to be anonymous?

**Comment by LuccoJ** [comment]
If it's possible server-side, then it should be available in the mobile apps... users are particularly sensitive to have to enter credentials on phones, as it's annoying and attention spans are short.

**Comment by stephanegigandet** [comment]
It's possible server side. The Cordova OFF app allows to upload pictures and add product name, quantity, brand without a login / pass. Should work for other fields too.
