### ISSUE TITLE
Notice regarding self-made photos is missing

### ISSUE THREAD

**Issue by nebulon42** [openfoodfacts/openfoodfacts-androidapp#471]
On the web the user is notified that s/he should only upload self-made photos and must not use photos from the web. For the Android app this notice is currently missing.

**Comment by herau** [comment]
can you please add the website link where this information is displayed ?

**Comment by teolemon** [comment]
```<span>Information and data must come from the product package and label (and not from other sites or the manufacturer's site), and you must have taken the pictures yourself.<br>
→ <a href="">Why it matters</a>
 <a href="#" class="close">×</a>
</span>```

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=3256220394079

**Comment by teolemon** [comment]
NB: This **should not** be a popup. This should not get in the way. We moved the licence message to the menu in the Camera finder. We perhaps can put it there as well ?

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/22183143/16dd7930-e0b7-11e6-8b81-838cc5be54a4.png)

**Comment by ManognaMutyala** [comment]
@teolemon ,Could you please be more specific where can I add this message?

**Comment by teolemon** [comment]
I was thinking of the Product Addition Form

Also, I've found this library (there might be others)
https://github.com/sjwall/MaterialTapTargetPrompt

**Comment by ManognaMutyala** [comment]
I will work on it!!

**Comment by teolemon** [comment]
We remove the pick from gallery button, so closing this issue, as it's not very important
