### ISSUE TITLE
Add a promo to add a product if there are no search results.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#477]
Add a promo to add a product if there are no search results (either by barcode or by scan)

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/22173858/dc94b434-dfce-11e6-8040-c6ce52c92bdc.png)

**Comment by huzaifaiftikhar** [comment]
@teolemon I would like to work on this issue. Please assign it me.
