### ISSUE TITLE
Better looking error message if no results found (or offline)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#479]
This is what search results currently look like in offline mode
![image](https://cloud.githubusercontent.com/assets/1689815/22060370/bf72590c-dd70-11e6-8d2a-4e56789f395b.png)

- The reason of no results 'offline' should be displayed along with no results, instead of being shown as a transient message. 
- A try again button should be proposed
- Everything should be centered.
- Cloud optional

 ![image](https://cloud.githubusercontent.com/assets/1689815/22060079/b7f9a85c-dd6f-11e6-83f6-64ceb3ed6390.png)

**Comment by teolemon** [comment]
https://material.io/guidelines/patterns/offline-states.html#offline-states-offline-interactions

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/35852602-a5b66cda-0b2b-11e8-85b0-876f4385fb31.png)

**Comment by alexaldev** [comment]
I would like to fix this. Currently, when no results found, no internet connection icon shows up.

**Comment by huzaifaiftikhar** [comment]
@alexaldev This has already been fixed in #1323.
