### ISSUE TITLE
Remove hardcoded links

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-androidapp#4816]
- [ ] Login activity
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/e35897fa5a124ea68f1950d386d8996c411dd159/app/src/main/java/openfoodfacts/github/scrachx/openfood/features/login/LoginActivity.kt#L69-L70

**Comment by pratyaksh1610** [comment]
@VaiTon I would like to work on this issue.
Please assign this issue to me.
Thanks.
