### ISSUE TITLE
Dokka doc generation is failing because it could not create domain object 'androidTestFdroid'

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4829]
### What
- Dokka doc generation is failing because it could not create domain object 'androidTestFdroid'

### Log

* What went wrong:
Execution failed for task ':app:dokkaHtml'.
> Error while evaluating property 'unsuppressedSourceSets' of task ':app:dokkaHtml'
   > Could not create domain object 'androidTestFdroid' (GradleDokkaSourceSetBuilder)

**Comment by VaiTon** [comment]
This should be fixed as everything is passing now
