### ISSUE TITLE
Nutrition chips behaving weirdly when product is empty

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#483]
![image](https://cloud.githubusercontent.com/assets/1689815/22155411/9a58d5a4-df2f-11e6-92d9-07987c74e8e0.png)

**Comment by teolemon** [comment]
@herau is working on a table replacement for the chips. This bug does not need to be solved.

**Comment by itchix** [comment]
No longer an issue
