### ISSUE TITLE
Harmonize color and size of the share icon in product page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#486]
Small details about sharing. See https://github.com/openfoodfacts/OpenFoodFacts-androidApp/issues/185 for details on how to implement native sharing.

![image](https://cloud.githubusercontent.com/assets/1689815/22174023/d7426f6c-dfd3-11e6-91a2-198557a775f3.png)

**Comment by SatyamBansal** [comment]
I want to work on this issue

**Comment by Karljoones** [comment]
Fixed #779
