### ISSUE TITLE
Missing F-Droid updates leading to an unusable database

### ISSUE THREAD

**Issue by natrius** [openfoodfacts/openfoodfacts-androidapp#4868]
### What
The current version in the f-droid repository still has 3.6.8 while the release in this repo is still 3.8.1 with **major** problems. Unfortunately its even not possible to download the .apk from https://github.com/openfoodfacts/openfoodfacts-androidapp/releases/tag/v3.8.1 as workaround. (I remembered right now its available on the website itself)
This error leads to https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/3982 so thats over one year. Looking at site 1 in my country i count at least 41 such items. On site 5 its 31 again. Since 29.09.2022 - looking at a monthly 35 items that would make 630 items that should frankly be deleted - just in my country alone. Its mentioned in that the error was resolved, but the app was never updated.

If sorting "Worldwide" with "Recently added products" its better but there are still way to much entries just containing the product code and nothing else - with luck there is a photo available.

### Expected behavior
Somewhat up to date app available on F-Droid. Its usally slower than google updates, thats fine imo, every f-droid user is aware of that.

### Why
To make it possible to get an usable database - the maingoal of this website, after all. 

### Open Food Facts username
natrius

### Barcode(s) of the product(s)
The one i added and corrected afterwards: https://at.openfoodfacts.org/produkt/9100000690629/lebkuchenmischung-spar-premium
Random empty one from the first site when sorted with recently added: https://at.openfoodfacts.org/produkt/7398818389251

### Project
Open Food Facts

### Installation method
F-Droid

**Comment by natrius** [comment]
I just discovered the .apk from the website is even older, its 3.6.2 - so currently there is no way for someone with android without google to get a recent version as there is no automatic apk build on github as well?

**Comment by natrius** [comment]
For now it would be good of the most recent classic version would be in f-droid. The old version thats online in fdroid currently for at least a year is causing massive problems. I talked about it in the matrix channel https://matrix.to/#/#openfoodfacts_general:matrix.org

**Comment by teolemon** [comment]
Looking at the history, it seems Sentry related, amirite @licaon-kter 
 ? 
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/openfoodfacts.github.scrachx.openfood.yml

**Comment by licaon-kter** [comment]
@teolemon no, as the disable line say, mlkit, fyi: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4803

**Comment by VaiTon** [comment]
@licaon-kter 3.9.0 is published with the fixing PR!

**Comment by licaon-kter** [comment]
Updated: https://gitlab.com/fdroid/fdroiddata/-/commit/88d116898253d7f9116cca09bc1cb5807b70c0be
& https://gitlab.com/fdroid/fdroiddata/-/commit/eeba06413601333b2920b8360defb05c72b8af3d
& https://gitlab.com/fdroid/fdroiddata/-/commit/66807440d6b31f42686621f414350bfef01ab374

Note that you've forgot to bump versionCode https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/v3.9.0/app/build.gradle.kts#L191 but that's ok as F-Droid did not build the old version because of mlkit.

Buuut, on you next tagged version pretty please bump version code too ;)

**Comment by natrius** [comment]
I would close this when the new version is in f-droid tbh

**Comment by VaiTon** [comment]
> Note that you've forgot to bump versionCode https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/v3.9.0/app/build.gradle.kts#L191 but that's ok as F-Droid did not build the old version because of mlkit.

Ohh yeah right, I'm used to fastlane updating it in the Play Store pipeline. Next time will do!

**Comment by natrius** [comment]
Funny enough, yesterday was the update and now it shows 3.9.0 with a date 01.04.2022 :D Funny enough. I updated and tried it, the upload looks fine. I will close this, as f-droid got updated :) Thanks a lot!

**Comment by teolemon** [comment]
Are you encountering ? @natrius 

- https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4889
- https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4888

**Comment by natrius** [comment]
1. No, i scanned various items before i could find one that was not existent before. I found about 10 items instantly. I tried right now one more with 3.9.0 from f-droid.
2. How do i get to that view? Never seen that before. I scanned something right now and edited it, it worked https://world.openfoodfacts.org/product/9028800127827/naturradler-zitronensaft-alkoholfrei-gosser

**Comment by licaon-kter** [comment]
@teolemon this happens only with F-Droid for you? 

Regarding the date, will take a look, iirc known issue (if we disabled an old build and republished it now since the verCode was not bumped :()

**Comment by teolemon** [comment]
Nope, it's the dev branch on the internal PlayStore build. I'm not yet sure of the faulty commits, and whether it made its way to F-Droid (it would seem it didn't)
