### ISSUE TITLE
ProductsAPITest > post product() FAILED     retrofit2.HttpException at KotlinExtensions.kt:53

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4883]
### What
- ProductsAPITest > post product() FAILED
    retrofit2.HttpException at KotlinExtensions.kt:53
- Latest release build failing

**Comment by PeterHe0226** [comment]
Hi! Could you elaborate more on how to recreate this bug? Thanks!
