### ISSUE TITLE
The products to be completed view is broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4888]
### What
The products to be completed view is broken
![image](https://user-images.githubusercontent.com/1689815/207419176-a2602a97-6245-4782-9f82-2885ba2f70bf.png)

**Comment by teolemon** [comment]
The search view is also broken

**Comment by lonewolf2208** [comment]
Hey @teolemon , is this still still open ?

**Comment by rishujam** [comment]
@teolemon can you give steps to reproduce? I think its working fine

**Comment by pratyaksh1610** [comment]
@VaiTon This can be closed as it works fine now after merging #4918 .





https://user-images.githubusercontent.com/76740999/220343806-5e944fac-b663-4099-8dac-72be864d1cc6.mp4
