### ISSUE TITLE
Add suitable icons in `Preferences`

### ISSUE THREAD

**Issue by pratyaksh1610** [openfoodfacts/openfoodfacts-androidapp#4902]
### What
Add suitable icons in `Preferences`.

### Why/User story
Add suitable icons in `Preferences` for better UI.

### Before

![off](https://user-images.githubusercontent.com/76740999/211533455-bb424f6e-c70b-4d5b-89d3-fe52e691fd3c.png)

**Comment by gaurisharma1122** [comment]
Hi @teolemon , I want to work on this.

**Comment by dmdbilal** [comment]
Can I work on this issue ?

**Comment by anshgovil** [comment]
I see the previous pull request for the issue was closed instead of merged. Is this issue still open to be worked on? If so, is there a requirement for icon choices (a drive with the SVG files per se)?

**Comment by its-me-abhishek** [comment]
@teolemon If possible, can you please assign this issue to me . I want to work on this.
- As I have noticed, another PR was closed as the OP had used png file format.
- I will be implementing the icons using the svg file format using either the free open-source Google Fonts icons / or any other icon pack as suggested.
- Another issue that I have observed from the above PRs is the inconsistency in the thickness of the icons. Will be looking forward for a set of equally formatted icons.

**Comment by its-me-abhishek** [comment]
> @teolemon If possible, can you please assign this issue to me . I want to work on this.
> 
> * As I have noticed, another PR was closed as the OP had used png file format.
> * I will be implementing the icons using the svg file format using either the free open-source Google Fonts icons / or any other icon pack as suggested.
> * Another issue that I have observed from the above PRs is the inconsistency in the thickness of the icons. Will be looking forward for a set of equally formatted icons.

Following are the samples of the icons that we will be implementing:
[Theme](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Apalette%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

[Preferred Energy Unit
](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Alocal_fire_department%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)

[Preferred Volume Unit
](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Ascience%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)

[Delete Local Search History
](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Adelete%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
