### ISSUE TITLE
Crunch PNG Files

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#491]
The aapt tool can optimize the image resources placed in res/drawable/ with lossless compression during the build process. For example, the aapt tool can convert a true-color PNG that does not require more than 256 colors to an 8-bit PNG with a color palette. Doing so results in an image of equal quality but a smaller memory footprint.

Keep in mind that the aapt has the following limitations:

The aapt tool does not shrink PNG files contained in the asset/ folder.
Image files need to use 256 or fewer colors for the aapt tool to optimize them.
The aapt tool may inflate PNG files that have already been compressed. To prevent this, you can use the cruncherEnabled flag in Gradle to disable this process for PNG files:
```
aaptOptions {
    cruncherEnabled = false
}
```
https://developer.android.com/topic/performance/reduce-apk-size.html

**Comment by raghavpuri31** [comment]
Is this issue solved @teolemon or anyone working on it?

**Comment by teolemon** [comment]
@iml-v has sent a pull request on this
