### ISSUE TITLE
ProductSearch recycler view do not show data

### ISSUE THREAD

**Issue by rishujam** [openfoodfacts/openfoodfacts-androidapp#4913]
### What
- The recycler view of ProductSearchActivity doesn't show data

### Why
- The value of recycler view adapter is assigned to itself instead of the adapter declared in the class 

### Screenshot of code
![image](https://user-images.githubusercontent.com/74773876/216790786-36916f5a-8444-4684-bae2-b4c0b6c7d2d6.png)

**Comment by rishujam** [comment]
@teolemon Hey can I raise a PR for this?

**Comment by rishujam** [comment]
@teolemon is this repo active?

**Comment by pratyaksh1610** [comment]
Seems to be an easy fix. Will try to fix it soon.
