### ISSUE TITLE
Indicate in Quickview whether photos are needed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#492]
![image](https://cloud.githubusercontent.com/assets/1689815/22336037/304a8b38-e3e1-11e6-8d14-b7e439daeb6a.png)

**Comment by teolemon** [comment]
UX doesn't have to be exactly like this

**Comment by PrajwalM2212** [comment]
Working on it .

**Comment by teolemon** [comment]
QuickView is going to be deprecated. Closing
