### ISSUE TITLE
Crash when scanning Barcode

### ISSUE THREAD

**Issue by davidak** [openfoodfacts/openfoodfacts-androidapp#497]
1. scan barcode
2. ???
3. App crashes

Could it be because it is out of focus? It that case it should still not crash.

![screenshot_2017-02-09-13-28-28](https://cloud.githubusercontent.com/assets/91113/22789479/55758716-eee3-11e6-95f9-2480fd316969.png)

---

Open Food 0.5 from F-Droid
Fairphone 2 with Open OS 16.12.0 (Android 5.1)

**Comment by teolemon** [comment]
Can you provide a trace ?

**Comment by davidak** [comment]
@teolemon no, but i would like to get it if you tell me how.

**Comment by teolemon** [comment]
You can install Android Studio, connect your device using a USB cable, and look at the log in Android Studio.

**Comment by davidak** [comment]
That would take some time... is that log a file on the device? I can give you any file on the device.

I have here another image that crashes the app on my device.

![img_20170219_213646](https://cloud.githubusercontent.com/assets/91113/23368086/ec873bb8-fd0c-11e6-974e-3616d8b86348.jpg)

Can you reproduce it? Then you can also check if a potential fix works.

**Comment by teolemon** [comment]
I tried it with the latest version from Trunk: the product doesn't exist, and it doesn't crash.

**Comment by davidak** [comment]
@teolemon does it crash when you try to add it?

**Comment by itchix** [comment]
Any update? Feel free to reopen it =)

**Comment by davidak** [comment]
I just updated to latest version (0.7) and successfully scanned a product and added it. I don't have the box i had trouble with anymore but i will create a new bugreport if i have any problems. Thanks!
