### ISSUE TITLE
scanning a bar code when no internet connection available 

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/OpenFoodFacts-androidApp#5]
One get the following error:
![screenshot_2015-05-10-21-13-00](https://cloud.githubusercontent.com/assets/43065/7556062/9e9423ae-f759-11e4-84f6-24f4612f311e.png)
The image of the scan product stays on until the user is triggering something.

I'm not sure what is the best way to go about it.
probably retrying (with a message letting the user know it is retrying)
or providing a way to retry (like a button),
or simply going forward with adding the product  are

**Comment by itchix** [comment]
I add the possibility to add the product in offline mode. But I don't know if it's better to add a view which is showing all barcode that fail because of internet connection and then try again when there is connection.. What do you think?

**Comment by kyzh** [comment]
This is likely a tricky question.

Do you plan to regulary take a list of the bar code exisiting in off?
Therefore you could degrade to the list of known barcode and allow people to continue to the form.
