### ISSUE TITLE
Camera capture fails

### ISSUE THREAD

**Issue by Peuc** [openfoodfacts/OpenFoodFacts-androidApp#50]
The Scanner feature is broken due to bad camera capture. The sight appears, but the image is scrambled. Screenshot: https://i.imgur.com/MkyfXST.jpg
Barcode scanner (which uses ZXing too) works as expected on the same device

OpenFood v0.1.7 - F-droid version
Device: Galaxy Player 4.0
CyanogenMod 11

**Comment by wvengen** [comment]
For me the capture image is always black. Other barcode scanning apps work.

OpenFood v0.1.7 - F-droid version
Device: FairPhone 1
Android 4.2.2

**Comment by itchix** [comment]
I have updated the camera view  : 30ec989a73430d5637ea120d90307f555abe007f
I have tested on two device and it works, tell me if there are any issues.
