### ISSUE TITLE
The contribution popup should also let you login

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#500]
Currently, when clicking on "My Contributions" while logged out, you can only create an account. There should also be a button to let you login.

![image](https://cloud.githubusercontent.com/assets/1689815/22929547/945c73c2-f2bc-11e6-8783-3187aacfe94d.png)

**Comment by huzaifaiftikhar** [comment]
@teolemon Please take a look at the PR.
