### ISSUE TITLE
Kill the offline popup, and replace it by an inline card

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#501]
![image](https://cloud.githubusercontent.com/assets/1689815/22929626/f2c35d18-f2bc-11e6-9150-dece2d5ce4eb.png)

Kill the offline popup, and replace it by an inline card that can be dismissed (and that facts is remembered and honoured using settings)

**Comment by teolemon** [comment]
https://material.io/guidelines/patterns/offline-states.html#offline-states-offline-interactions

**Comment by teolemon** [comment]
Don't pay attention to the design, it should be gray text, very much like the Empty History

**Comment by Shubham2320** [comment]
Can I work on it?

**Comment by teolemon** [comment]
Yup, basically center the message with dark grey text, like in the history. And Whenever you have an offline product, the message disappears.

**Comment by Shubham2320** [comment]
okay.

**Comment by sachincool** [comment]
@Shubham2320  you can Refer this https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/730 as well and close both in 1 PR.  Thanks
