### ISSUE TITLE
F-Droid version crashes upon loading

### ISSUE THREAD

**Issue by picsi** [openfoodfacts/openfoodfacts-androidapp#505]
I just installed Open Food from F-Droid (Version 0.5 - Added on 2017-01-14) on my Android 4.4.2 and I can't use it. I open the app, the splash image with the logo appears and then an Android system error message tells me the app has crashed.

Any ideas?

**Comment by teolemon** [comment]
Can you try building it from trunk. @itchix has replaced the ORM engine, and it might help. Otherwise, we'll release an updated version soon.

**Comment by teolemon** [comment]
0.6 just released. should arrive soon on F-Droid

**Comment by Hangman228** [comment]
Still Crash on Android 4.4...
Here is a logcat
[logcat.txt](https://github.com/openfoodfacts/openfoodfacts-androidapp/files/820709/logcat.txt)

**Comment by teolemon** [comment]
Thank you so much for the log. @itchix

**Comment by teolemon** [comment]
@Hangman228 @picsi Did you receive the latest version ?

**Comment by picsi** [comment]
@teolemon Yes, I installed 0.6.2 today from F-Droid and it still crashes upon loading. Minor difference now: it doesn't even get to the splash screen before crashing.

**Comment by itchix** [comment]
Mhhh I'm working on it...

**Comment by picsi** [comment]
Error persists as of 0.7.

**Comment by itchix** [comment]
Can you confirm that it's fixed with the last version 0.7.1?

**Comment by picsi** [comment]
@itchix will do as soon as it lands on F-Droid. It might be a good idea to remind the F-Droid folks of the new version.

**Comment by teolemon** [comment]
@picsi fixed ?

**Comment by picsi** [comment]
Nope. On 0.7.4 the bug persists.

**Comment by picsi** [comment]
Sorry, that was a mistake on my behalf. I just got the 0.7.4 update from F-Droid, and now it works!

The app loads successfully, although the splash image is very distorted, tries to fill the whole screen. Other than that, it works. I noticed that clicking on Sign-in crashes the app. I'll create an issue specifically for that.
