### ISSUE TITLE
Using Wikidata Toolkit Java Library to enrich facets in the app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#506]
Many facets of Open Food Facts (categories, labels…) are linked to Wikidata, which is linked to Wikipedia.

Thus, by getting the Wikidata ID from the API, we can get Wikidata info we can display, and links to Wikipedia, so that the users can get more knowledge: controversies about additives, more info about the wine they are drinking…

https://github.com/Wikidata/Wikidata-Toolkit

**Comment by teolemon** [comment]
See https://github.com/openfoodfacts/openfoodfacts-server/issues/391

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/23339381/542ddc14-fc21-11e6-8d2a-a948262b656d.png)

**Comment by teolemon** [comment]
https://world-el.openfoodfacts.org/additives.json
https://world-el.openfoodfacts.org/categories.json
https://world-el.openfoodfacts.org/labels.json

```,{"linkeddata":{"pnns_group_2:en":"Cheese","wikidata:en":"Q10943"},"url":"https://world-el.openfoodfacts.org/κατηγορια/%CF%84%CF%85%CF%81%CE%AF","name":"Τυρί","products":5575,"id":"en:cheeses"}```

We now have Wikidata ID in the additives JSON

**Comment by Shubham2320** [comment]
Cool. :smile_cat: I would like to work on it.

**Comment by Shubham2320** [comment]
@teolemon could you please guide me on what exactly has to be done on this.

**Comment by Shubham2320** [comment]
I've read some documentation on wiki data and I got to know that I can get JSON response from item's id it.
In the JSON response, there are following objects from the JSON response that can be used:

- Label (in all languages)

- Description (in all languages)

- Sitelinks which contains links to Wikipedia page (in all languages)

Now, I'm thinking to make ingredients, additives, categories, labels all clickable then in onClick a bottom sheet would appear which would be containing the following information:

- Label of item

- Description of item

- Wikipedia link which would open in a chrome custom tab

- An option to browse products in the selected category, label, etc(Which in most of the things is already implemented)

@teolemon, @Karljoones Can I start working on it?

**Comment by teolemon** [comment]
That makes sense. 
Note: On some Wikidata entities, you have additional links like properties for additives (antioxydant…) and many other things (for instance, for French wines, there's a link to the official certification agency on Wikidata).
But I guess we should start simple by linking to the Wikipedia page. 
I had thought of a header approach (display info and links, and products below), but the bottom sheet seems like a reasonable approach. 
An extendable bottom sheet you could drag up to show products could be cool as well.

**Comment by Shubham2320** [comment]
😃 Thanks for assurance, I'm working on this now.

**Comment by teolemon** [comment]
@Shubham2320 You can join #wikidata on the Slack

**Comment by Shubham2320** [comment]
Thanks, @teolemon I would surely join it.

**Comment by teolemon** [comment]
The Wikidata IDs are now in the local taxonomies (downloaded once, no need for additional network calls)

https://static.openfoodfacts.org/data/taxonomies/categories.json
https://static.openfoodfacts.org/data/taxonomies/labels.json

**Comment by huzaifaiftikhar** [comment]
I guess we can close this now :slightly_smiling_face:
