### ISSUE TITLE
Change app icons

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#508]
![openfoodfacts round](https://cloud.githubusercontent.com/assets/1689815/23542715/03994be0-ffef-11e6-9c8e-3969b2933001.png)
![openbeautyfacts round](https://cloud.githubusercontent.com/assets/1689815/23542718/086e95a8-ffef-11e6-9c9d-f04762bed735.png)

**Comment by itchix** [comment]
#65ff3c105003d64a49485d799e398f8fc72916da
