### ISSUE TITLE
the OFF and OBF logos are in the Wrong languages

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#518]
The Open Beauty Facts logo has the English tagline, regardless of the language
The Open Food Facts logo has the French tagline, regardless of the language

**Comment by teolemon** [comment]
The Open Beauty Facts logo has the English tagline, regardless of the language
The Open Food Facts logo has the French tagline, regardless of the language

**Comment by teolemon** [comment]
We need to:
- include the logo without tagline by default (both SVG and PNG)
- download the localized logo on first load (both SVG and PNG). 
- download the localized logo on locale change (both SVG and PNG).

**Comment by teolemon** [comment]
Here are the links to the base SVG
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/html/images/misc/openbeautyfacts-logo-en-without-tagline.svg
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/html/images/misc/openfoodfacts-logo-no-tagline.svg

Here are the taglines that should be translatable below the logo 
OFF "the free food products database" 
OBF "the free cosmetic products database" 
OPFF "the free pet food products database"

**Comment by Shubham2320** [comment]
Working on it.

**Comment by teolemon** [comment]
https://static.openfoodfacts.org/images/misc/openfoodfacts-logo-sq-178x150.png
https://static.openfoodfacts.org/images/misc/openfoodfacts-logo-fr-178x150.png
https://static.openfoodfacts.org/images/misc/openfoodfacts-logo-en-178x150.png
https://static.openfoodfacts.org/images/misc/openfoodfacts-logo-pl-178x150.png
…

**Comment by teolemon** [comment]
https://static.openfoodfacts.org/images/misc/openbeautyfacts-logo-en-178x150.png
https://static.openfoodfacts.org/images/misc/openbeautyfacts-logo-fr-178x150.png
https://static.openfoodfacts.org/images/misc/openbeautyfacts-logo-es-178x150.png

**Comment by huzaifaiftikhar** [comment]
@Shubham2320 Are you still working on this?

**Comment by Shubham2320** [comment]
You can take this.
