### ISSUE TITLE
Share icon is grey while edit icon is black

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#519]
On product view, the Share icon is grey while edit icon is black. They should both be black and the same size.

**Comment by ManognaMutyala** [comment]
Could I know if anyone is still working on it or can I work on it @teolemon ?

**Comment by ross-holloway94** [comment]
@Karljoones have you started on this?

**Comment by teolemon** [comment]
I guess it's fine to go ahead.

**Comment by ManognaMutyala** [comment]
Thanks!! will be submitting PR soon !!

**Comment by Karljoones** [comment]
Sorry, haven't had a chance, had great ambition to get a lot of bugs closed but life got in the way!

**Comment by ManavPoddar** [comment]
@teolemon  i would love working on this

**Comment by teolemon** [comment]
#486

**Comment by Karljoones** [comment]
Closed duplicate #486
