### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#5265]
### What
- ProductsAPITest > post product() FAILED
    java.net.ConnectException at CoroutineDebugging.kt:46
        Caused by: java.net.ConnectException at RealConnection.java:249
            Caused by: java.net.ConnectException at Net.java:-2

ProductsAPITest > products by city paris not found() FAILED
    retrofit2.HttpException at KotlinExtensions.kt:53

ProductsAPITest > product not found() FAILED
    com.google.common.truth.ComparisonFailureWithFacts at ProductsAPITest.kt:129

**Comment by teolemon** [comment]
fixed by @g123k , dexing still fails in the CI

**Comment by g123k** [comment]
Dexing is indeed KO for debug builds.
But the code, as is, is OK for releases builds.

The way to fix this is to migrate to Gradle 8, which requires a lot of work (GreenDAO is deprecated and we have to rewrite everything)
