### ISSUE TITLE
Switch to POST instead of GET for credentials in API requests

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#529]
Switch to POST instead of GET for credentials in API requests
Contact @teolemon for details

**Comment by itchix** [comment]
It's already in POST request : https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/OpenFoodAPIService.java#L42
