### ISSUE TITLE
Clicking on the scan button when you arrived from the history brings back to history

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#530]
Clicking on the scan button when you arrived from the history brings back to history.
It should open the scan window instead.

**Comment by itchix** [comment]
I can't reproduce the bug...

**Comment by teolemon** [comment]
1. Go to history
2. Click on a product
3. Click on the red button
4. Back to history

**Comment by Karljoones** [comment]
@teolemon can you confirm that this is fixed? Just tried to reproduce it at the moment and could not with the instructions that you outlined above.

**Comment by teolemon** [comment]
Indeed, fixed. Closing
