### ISSUE TITLE
Excessive capabilities for Amazon devices

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#534]
```
Your APK manifest requires capabilities not present on this device. Learn more
android.hardware.camera.autofocus
android:minSdkVersion = '16'; device requires '15'
```
Excessive capabilities for Amazon devices. Can we perhaps do a flavor for the Amazon app store where the minSdkVersion is lower, and the autofocus not required ?

**Comment by teolemon** [comment]
And perhaps disable some features where no camera is detected ?

**Comment by Karljoones** [comment]
@teolemon I ran into this problem before. In terms of manifest items that allow for use with Fire (Amazon), you will need to put this into the `<manifest>` file of the app. 

`<uses-feature android:name="android.hardware.camera" android:required="false"/>`

`<uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>`

`<uses-feature android:name="android.hardware.camera.flash" android:required="false"/>`

This tells the app that it does not need the features to be able to install the application. You will still need to disable the camera features though manually.

**Comment by Karljoones** [comment]
Yep!
