### ISSUE TITLE
Clicking on Sign-in crashes the app

### ISSUE THREAD

**Issue by picsi** [openfoodfacts/openfoodfacts-androidapp#548]
As mentioned on #505, clicking on Sign-in crashes the app.

Environment: Open Food from F-Droid (Version 0.7.4) on Android 4.4.2

**Comment by teolemon** [comment]
Opened another bug with a trace. Closing this one

**Comment by picsi** [comment]
Can you link to itw

**Comment by mikini** [comment]
I think @teolemon is referring to #578. Experiencing the same bug, my trace also says something about an invalid vector in a binary xml file, seems to orignate from file app/src/main/res/drawable/ic_person_grey_24dp.xml.
