### ISSUE TITLE
[ru] Nutritional values and ingredients are mixed in the Russian translation

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-androidapp#550]
![img_0002](https://cloud.githubusercontent.com/assets/1025861/24837491/92ca8f80-1d46-11e7-8391-eeddd23fc49b.jpg)
![img_0003](https://cloud.githubusercontent.com/assets/1025861/24837492/92f6c5aa-1d46-11e7-8e07-28d182ed78bb.jpg)

"Пищевая ценность" means nutritonal values, "Состав" means ingredients.

**Comment by teolemon** [comment]
@aleksejrs Assuming this is no longer an issue. Can I close ?
