### ISSUE TITLE
Energy value in the nutrition table does not fit if the translations are too long

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-androidapp#551]
The number after "Энергетическая ценность" does not fit.
![img_0003](https://cloud.githubusercontent.com/assets/1025861/24837500/c12a5dce-1d46-11e7-888d-23dc16a980fb.jpg)

**Comment by teolemon** [comment]
poke @herau

**Comment by huzaifaiftikhar** [comment]
This can be closed as it was fixed in #1254

**Comment by huzaifaiftikhar** [comment]
![screenshot_20180511-201228](https://user-images.githubusercontent.com/10832531/39930288-f033612a-5557-11e8-9c6c-1b461168cfe2.png)

Closing as it is fixed and the values are displayed properly.
