### ISSUE TITLE
[ru] Some lists have no space after commas.

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-androidapp#552]
![img_0004](https://cloud.githubusercontent.com/assets/1025861/24837507/e2b9887a-1d46-11e7-831d-ce0fe4909852.jpg)
https://ru.openfoodfacts.org/product/40084701/kinder-chocolate-ferrero

**Comment by Shubham2320** [comment]
This issue has been solved in PR #468.
