### ISSUE TITLE
Adding Moodstock image recognition as an option at build time

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#56]
The new app is going to be distributed on FDroid, which doesn't allow binary blobs.
At the same time, the Moodstock image recognition is a wow effect when showing off OFF :-)

Adding Moodstock image recognition as an option at build time would enable to have a version with the Moostock binary parts and behaviour, and another Free as in beer version for F-Droid.

**Comment by LuccoJ** [comment]
Why not seek to find a usable free and open source image recognition framework instead? This is all about openness, after all, and something proprietary running on a closed server may be "wow"... for those who don't care about openness.
I haven't tried it but from the description, http://pastec.io/ looks like it would be suited to OpenFoodFacts use.

**Comment by stephanegigandet** [comment]
Pastec looks very interesting, thanks for the link.

One thing that makes Moodstock so impressive is that it does image recognition on the client (the smartphone) in realtime (running the image detection on frames from the video camera). There's no picture taken and no picture sent to the server, the database of image fingerprints and associated data is synchronized on the phone. That's very useful for scanning in stores where there is no network. I read the Pastec docs and at this time it does not do that (but it certainly could in the future).

My personal opinion is that it is a good thing to give users the choice.

**Comment by LuccoJ** [comment]
@stephanegigandet well, sure, but only if the choice doesn't involve me being stuck with a proprietary OpenFoodFacts binary, because then, the only choice left to me would be to stop using it!

**Comment by teolemon** [comment]
Moodstocks is shutting down its API. Issue is not relevant anymore.
