### ISSUE TITLE
Let the user choose his/her preferred units

### ISSUE THREAD

**Issue by fuddl** [openfoodfacts/openfoodfacts-androidapp#564]
I propose a switch or a series of switches in the settings that adjust which units a user will see on nutrition tables etc.

Preferred units  | Options
----------------|---------- 
 Energy              | kcal ↔ kj 
 Weight              | lb ↔ kg
 Mass                 | oz ↔ L

I don't know which of these settings are actually necessary. I only need the first one.

**Comment by KarthikRIyer** [comment]
@teolemon I'd like to work on this
