### ISSUE TITLE
The serializable class Nutriments does not declare a static final serialVersionUID field of type long

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#569]
```
/Users/pierreslam/Desktop/cloneandroid/openfoodfacts-androidapp/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/Nutriments.java
Warning:(21, 14) The serializable class Nutriments does not declare a static final serialVersionUID field of type long
```

**Comment by sachincool** [comment]
i would love to work on this. :fire:

**Comment by policorn** [comment]
Hi @sachincool, I've found there're other Serializable Classes without serialVersionUID. Can you please check them too please?

<img width="494" alt="screen shot 2018-02-16 at 19 32 52" src="https://user-images.githubusercontent.com/18316436/36323212-6bdf29f2-1350-11e8-85a7-f26121106565.png">

**Comment by sachincool** [comment]
@policorn  on it!
