### ISSUE TITLE
Support Android M

### ISSUE THREAD

**Issue by jinqian** [openfoodfacts/OpenFoodFacts-androidApp#58]
In order to support Android M, we'll need to: 
- Update target SDK version & related lib version
- Using [Permission Dispatcher](https://github.com/hotchemi/PermissionsDispatcher) to deal with the run time permission grant
- Tweak feel & style if necessary

**Comment by itchix** [comment]
Are you working on it @jinqian ? =)

**Comment by jinqian** [comment]
@itchix not yet, go ahead if you want to! I haven't found time to get started ;) I have a Nexus 5x if tests are needed.
