### ISSUE TITLE
Make Quick Mode more minimalistic, à la Google Maps

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#580]
The app would keep scanning all the time.
We could display the info at the bottom of the screen, in a edge to edge card, that you could swipe up to get more info.
You could add some action in the blue button. You could swipe up to go to full product view. 
This would make quick mode feel more powerful, less intrusive, almost like AR.

![image](https://cloud.githubusercontent.com/assets/1689815/25306442/a64b3f86-278d-11e7-99c6-9cc8a2f8e563.png)
![image](https://cloud.githubusercontent.com/assets/1689815/25306446/abbc7fde-278d-11e7-87e9-46cb893db004.png)
![image](https://cloud.githubusercontent.com/assets/1689815/25306450/af02f9d4-278d-11e7-8264-f05c02118b2c.png)
![image](https://cloud.githubusercontent.com/assets/1689815/25306454/b46ebdd6-278d-11e7-9fb7-16be9ca7df95.png)

**Comment by teolemon** [comment]
http://stackoverflow.com/questions/34310530/sliding-bottomsheet-like-google-map
https://github.com/umano/AndroidSlidingUpPanel
http://stackoverflow.com/questions/21826892/replicate-google-maps-bottom-panel-swipe-up

**Comment by jaztriumph** [comment]
@teolemon I will work on this

**Comment by jaztriumph** [comment]
@teolemon I am working on this I will make a PR soon

**Comment by jaztriumph** [comment]
@teolemon does the background need to be white or transparent , I think transparent background would be more appealing like below and you said when we swipe up it need to display more info does that mean the whole info we used to display in view pager.
![quick_mode](https://user-images.githubusercontent.com/22943390/36804310-37755594-1ce0-11e8-8070-c6c9e7b48b43.gif)

**Comment by jaztriumph** [comment]
@teolemon can you also tell me what information and in which layout should we display information when user completely swipes up the pannel and I also put link to complete info when user clicks on that dialog_info icon.

**Comment by teolemon** [comment]
I think a white background is preferable, because otherwise, you'd swipe up invisibility :)
I guess swiping up should reveal the full product view

**Comment by teolemon** [comment]
Implemented, only the swipe up is missing. Closing
