### ISSUE TITLE
Add zh_TW, zh_CN and zh_HK as locales

### ISSUE THREAD

**Issue by Cypresslin** [openfoodfacts/openfoodfacts-androidapp#585]
For Chinese, it should be divided into:
 * Traditional Chinese (zh_TW)
 * Simplified Chinese (zh_CN)

But for now there is only one, which is Simplified Chinese.

In order to reduce confusion, I would suggest:
 1. Rename "Chinese" to "Simplified Chinese" in the language selection menu.
 2. Add a new entry for Traditional Chinese.

**Comment by teolemon** [comment]
I've added zh_CN and zh_HK. Should I add zh_TW as well ?

**Comment by Cypresslin** [comment]
Yes please, that would be great. Many terms are significantly different between these three.
(I'm already doing translation work for zh_TW on launchpad.)
Thanks.

**Comment by teolemon** [comment]
I've added a rule on Crowdin and imported your translations from Launchpad.
Although a long time Launchpad user, the platform timeouts too often to be usable.
https://crowdin.com/project/openfoodfacts/zh-TW#

**Comment by Cypresslin** [comment]
Thanks, so it's better to make translations on Crowdin or on github directly instead of working on launchpad? (If that's the case, issue #301 will need an update)

**Comment by teolemon** [comment]
corrected on #301 
Yes, Crowdin is the way to go now. I'll be syncing for a while, but eventually, I'll probably disable Launchpad.

**Comment by teolemon** [comment]
- https://crowdin.com/project/openfoodfacts/zh-HK
- https://crowdin.com/project/openfoodfacts/zh-CN
- https://crowdin.com/project/openfoodfacts/zh-TW

**Comment by policorn** [comment]
Hi @teolemon, this is fixed I guess

**Comment by teolemon** [comment]
Yes. Serbian still eludes me.

**Comment by policorn** [comment]
Serbian Cyrillic is a typo in the lang_array; Serbian Latin seems to be trickier
