### ISSUE TITLE
l10n: on openfoodfacts.org, only Simplified Chinese / English available

### ISSUE THREAD

**Issue by Cypresslin** [openfoodfacts/openfoodfacts-androidapp#586]
If you set your country to Taiwan, there should be a Traditional Chinese version available on the website.

For now, only Simplified Chinese and English are available.

**Comment by teolemon** [comment]
This should be filed against the server
https://github.com/openfoodfacts/openfoodfacts-server

**Comment by Cypresslin** [comment]
Oops, thanks for pointing that out.
