### ISSUE TITLE
Enable CI & add build status

### ISSUE THREAD

**Issue by jinqian** [openfoodfacts/OpenFoodFacts-androidApp#59]
Enable [Travis CI](https://travis-ci.org/) for project to make sure we didn't break the build :)

**Comment by Ekt0s** [comment]
I'm on it 😃 
I'll start on my fork at lunch today 🚀

**Comment by jinqian** [comment]
Cool. Seem done? @Ekt0s

**Comment by Ekt0s** [comment]
Yep @itchix has done the changes based on my fork.
Don't if it's gonna work for the pull request though

**Comment by jinqian** [comment]
It builds on `master`, should be okay! 

I'll close the ticket in that case. Thank you both @Ekt0s @itchix 👍
