### ISSUE TITLE
App not sending images properly

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#592]
https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=84182111
I had put a photo of the front and of the ingredients. 1/2 got through.
The product was created in English, and Norwegian and French
![image](https://cloud.githubusercontent.com/assets/1689815/25562756/b38da8ee-2d8e-11e7-8903-cdf89809727f.png)

**Comment by pandark** [comment]
Same here (but only created in French and English, I think).
