### ISSUE TITLE
Upload popup misplaced on Moto G

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#596]
When uploading several images in a row, the upload popup is misplaced on Moto G 

![image](https://cloud.githubusercontent.com/assets/1689815/25610092/285b8a58-2f22-11e7-9919-1d401ddf932e.png)

![image](https://cloud.githubusercontent.com/assets/1689815/25610116/3afc1bdc-2f22-11e7-9aa1-8499696d8552.png)

**Comment by Shubham2320** [comment]
@teolemon so what are your thoughts on this, where the upload popup should be placed on the screen. I'll propose to make it in **centre of the screen** and also **upload popup is misplaced while uploading a single product image**.

**Screenshot:**

<img src="https://user-images.githubusercontent.com/25099208/36340324-a53e9c68-1400-11e8-835b-6cf9b6f69160.png" height="560" />

I'm willing to work on this issue.

**Comment by teolemon** [comment]
This bug has been obsoleted as the view has been rewritten
