### ISSUE TITLE
Cannot swipe

### ISSUE THREAD

**Issue by loi219** [openfoodfacts/openfoodfacts-androidapp#597]
When I take a picture of a barcode, I see the basic information and when I swipe to the right, the camera shows up and I can't see the other information about the product.

I'm on Android 6.0.

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/571

**Comment by teolemon** [comment]
@loi219 Where did you install Open Food Facts from ? source ? Play Store ? F-Droid ?

**Comment by loi219** [comment]
F-Droid

**Comment by teolemon** [comment]
Thanks. I've added a comment on #571. Closing this duplicate
