### ISSUE TITLE
Apply branching strategy

### ISSUE THREAD

**Issue by jinqian** [openfoodfacts/openfoodfacts-androidapp#60]
As we are having more and more contributors, I think it would be nice to apply some sort of [branching strategy](http://nvie.com/posts/a-successful-git-branching-model/).

Let's start by:
- keeping the master branch the release branch
- keeping all the WIP in the dev branch or other feature branches

**Comment by Ekt0s** [comment]
I think this is a really good idea !
That's what we're using here, without the hotfix branches that should not happened in CI/CD setup, cause you'll always release something :D

**Comment by sachincool** [comment]
@samagra14  @policorn  @Karljoones  I think we can close this and start following this.  
make the master as Stable Version  I.e the release apk code. 
Make the Development Branch where all the PR's get merge/revert.

**Comment by samagra14** [comment]
@sachincool I think this is a good idea. One of the owners should checkout a branch from the last stable release and make that branch the release branch.

**Comment by sachincool** [comment]
@teolemon  How does this look?  I was thinking on Attaching this md in the `Readme.md/#installation`  of the app once you create a development branch. Also you need to set the main Branch for PR's to `development`

### Branch Policy
We have the following branches
 * **development**
	 All development goes on in this branch. If you're making a contribution,
	 you are supposed to make a pull request to _development_.
	 Make sure it passes a build check on Travis

	 It is advisable to clone only the development branch using the following command:

	`git clone -b <branch> <remote_repo>`

	Example:

	`git clone -b my-branch git@github.com:user/myproject.git`

	Alternative (no public key setup needed):

	`git clone -b my-branch https://git@github.com/username/myproject.git`

	With Git 1.7.10 and later, add --single-branch to prevent fetching of all branches. Example, with development branch:

	`git clone -b development --single-branch https://github.com/username/openfoodfacts-androidapp`

 * **master**
   This contains the stable code. After significant features/bugfixes are accumulated on development, we move it to master.

**Comment by policorn** [comment]
+1 It makes a lot of sense

**Comment by teolemon** [comment]
@jinqian @ghost @sachincool @samagra14 @Ekt0s We finally did it 🎉
