### ISSUE TITLE
Open Beauty Facts,  Open Food Facts and Open Pet Food Facts have the same name

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#600]
![image](https://cloud.githubusercontent.com/assets/1689815/25840185/1f837e30-349b-11e7-8fd3-2cde7b8fb260.png)

**Comment by teolemon** [comment]
Solutions: https://stackoverflow.com/questions/19830972/different-app-names-for-different-build-flavors

**Comment by policorn** [comment]
This is fixed, right?

**Comment by teolemon** [comment]
It seems so:
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/build.gradle
