### ISSUE TITLE
The Rounded icon for Nougat doesn't work

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#601]
![image](https://cloud.githubusercontent.com/assets/1689815/25840220/4c1ea988-349b-11e7-8413-07fd52c80d5c.png)
It should fill up the circle

**Comment by teolemon** [comment]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by sachincool** [comment]
@teolemon Is this still the case?  In my nougat the icon fills the circle.

**Comment by teolemon** [comment]
fixed, closing, thanks @sachincool
