### ISSUE TITLE
compare/use data from national government databases

### ISSUE THREAD

**Issue by nutpantz** [openfoodfacts/openfoodfacts-androidapp#61]
Most of the info on the nutrition label is also available free (to use both online or in a local database) from various National (usda,health Canada,etc) run nutritional databases.(which are far more complete)
It would be useful to beable to see the view and or compare that data to the collected from users.

An option to load data from those sources would be very useful.

**Comment by teolemon** [comment]
@nutpantz Usually, they don't include barcodes. They are thus quite difficult to track reliably. Moreover, this is more a @openfoodfacts/openfoodfacts-server  bug than a mobile bug

**Comment by teolemon** [comment]
@nutpantz I've started an effort on Wikidata to link those ids to Wikidata. We, in turn, are linked to Wikidata. Does that sound a good approach to you ?
https://www.wikidata.org/wiki/Wikidata:WikiProject_Food

**Comment by nutpantz** [comment]
It's sounds like a possible start. I am just concerned about so much duplicate effort to gather nutritional info from products when so many products have their info in databases already.tracking the barcodes is helpful but not as much as getting proper nutritional information easily into the populations hands, then getting them to use proper portions on top of that.
But any start is better than the way most things are now
I can't think of a better way at the moment.

**Comment by teolemon** [comment]
@nutpantz Great news, the USDA has released a database with barcodes that we'll be importing shortly. As for other countries, and generic products without barcodes, I invite you to file a bug server side at https://github.com/openfoodfacts/openfoodfacts-server
