### ISSUE TITLE
Ask questions when users scans an uncomplete product

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#63]
At the bottom of an uncomplete product we could ask

> Answer questions about this product, help others and complete missions

![prompt](https://cloud.githubusercontent.com/assets/1689815/14763214/327d215e-098f-11e6-8dea-e9f53c4468a8.png)

> Either open questions ("type weight") or YES/NO questions
> ![maxresdefault](https://cloud.githubusercontent.com/assets/1689815/14763208/0f8122b8-098f-11e6-8111-53e5cea2d033.jpg)

(Google Maps for inspiration)

**Comment by teolemon** [comment]
![prompt](https://cloud.githubusercontent.com/assets/1689815/14763214/327d215e-098f-11e6-8dea-e9f53c4468a8.png)

**Comment by aleene** [comment]
drip-editing : for each new view/access, ask a question to check a product value

**Comment by teolemon** [comment]
https://github.com/Jimeux/Yezna-Android

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21745978/b8c773e4-d537-11e6-9169-0ca22549d55b.png)

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21746005/4c13609a-d538-11e6-8742-83c9cc8d5cb4.png)

**Comment by Phyks** [comment]
:+1: for something like the last image. I would tend to think users will be more encline to answer a simple yes/no question (is this product complete / accurate) when they scan, rather than actually completing the product infos directly on their mobile. This would not provide additional data, but some quality metrics which are always nice to have :)

**Comment by Karljoones** [comment]
Found a nice library for this: https://github.com/shivasurya/FeedbackDialog?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=6693

**Comment by PrajwalM2212** [comment]
That is a very nice library .

**Comment by teolemon** [comment]
nice one

**Comment by teolemon** [comment]
I filed a bug to ask for image support:
https://github.com/shivasurya/FeedbackDialog/issues/5

**Comment by teolemon** [comment]
I was thinking about:
- [ ] checking the product state (state=categories-to-be-completed)
- [ ]  looking up the product names (name, common_name)
- [ ]  comparing that to the taxonomy JSON for categories that we have stored locally
- [ ]  If there is a match, display inline infotip
- [ ] if click on the infotip, display the popup
- [ ] if answer is yes, write the category back to the server with an API call

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/47089512-4947dc00-d221-11e8-8fb9-d927e3e87823.png)
![image](https://user-images.githubusercontent.com/1689815/47089542-5ebd0600-d221-11e8-8edb-7091c1e3b8d4.png)

**Comment by teolemon** [comment]
closing, since fixed
