### ISSUE TITLE
Send an anonymized hash with each contribution non-logged in device

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#634]
Send an anonymized hash for each non-logged in device so that we can block any spammer or bad-meaning person server side.
It has to remain the same across contributions, but shouldn't contain any information that could let anyone trace back to the user.
Strongly hashing a uuid might be an option. We need to add a secret string to further protect against any rainbow tables of hashed uuids that might exist on the internet.
Perhaps Android has a native mechanism for that.

**Comment by teolemon** [comment]
https://android-developers.googleblog.com/2011/03/identifying-app-installations.html

**Comment by prashantkh19** [comment]
Interested, working on this issue.

**Comment by prashantkh19** [comment]
@teolemon Review this commit. The hashed code needs to be parsed at the server side. I have sent it with the key 'identity_code'. Also, the code will be same for a single Installation.

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/product/99999971/test
Can you send it in the comment field instead ?
