### ISSUE TITLE
The Jack toolchain is deprecated and will not run

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#641]
Warning:The Jack toolchain is deprecated and will not run. To enable support for Java 8 language features built into the plugin, remove 'jackOptions { ... }' from your build.gradle file, and add

android.compileOptions.sourceCompatibility 1.8
android.compileOptions.targetCompatibility 1.8

Future versions of the plugin will not support usage of 'jackOptions' in build.gradle.
To learn more, go to https://d.android.com/r/tools/java-8-support-message.html

**Comment by policorn** [comment]
This was fixed by commit#86fc1016d641c83b39463862414705a44706dedb
