### ISSUE TITLE
All flavors must now belong to a named flavor dimension. 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#642]
Error:All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

**Comment by AbsolutelySaurabh** [comment]
@teolemon , Is this issue has been solved now?

**Comment by teolemon** [comment]
thanks @AbsolutelySaurabh for spotting this. @VaiTon can you confirm ? If so, we may close it.
