### ISSUE TITLE
The specified Android SDK Build Tools version (25.0.1) is ignored, as it is below the minimum supported version (26.0.2) for Android Gradle Plugin 3.0.0.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#643]
Error:The specified Android SDK Build Tools version (25.0.1) is ignored, as it is below the minimum supported version (26.0.2) for Android Gradle Plugin 3.0.0.
Android SDK Build Tools 26.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
<a href="fix.build.tools.version">Update Build Tools version and sync project</a><br><a href="openFile:/Users/pierreslam/Desktop/fix/openfoodfacts-androidapp/app/build.gradle">Open File</a>

**Comment by netoliguz91** [comment]
Thanks man, I just had to updated my grandle and that made the trick.  My regards dude...

**Comment by samagra14** [comment]
@teolemon Please close this issue as it has been taken care of.

**Comment by teolemon** [comment]
thanks @samagra14
