### ISSUE TITLE
Category browser

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#650]
Enable users to delve into the Open Food Facts category system, and see products in those categories
https://world.openfoodfacts.org/categories.json

This should be modular, so that we can reuse the code to browse other stuff (packaging types, country of origin…)

![image](https://user-images.githubusercontent.com/1689815/32414283-bbbe9e2c-c223-11e7-984b-5cf37002f093.png)

**Comment by alikyo** [comment]
Hello,

I will work on that ticket.

Br

**Comment by teolemon** [comment]
Ok, Assigning it to you :-)
