### ISSUE TITLE
The Storage Permission is asked at the wrong time

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#656]
The Storage Permission is asked at the wrong time, and thus scary. It is asked when you land on an existing product page.

**Why would I possibly need the storage permission to view a product ?**

- We only need it when **adding a new product from images already on the device**. 
- Otherwise, **if adding a new product from the camera, we only need the camera**.
- **If adding additional photos to an existing product**, we can show the permission request **when the users clicks on the "Add more photos" button**

**Comment by ross-holloway94** [comment]
Fixed in #664
