### ISSUE TITLE
SaveProductOfflineActivty: incorrect titles & resources

### ISSUE THREAD

**Issue by Karljoones** [openfoodfacts/openfoodfacts-androidapp#688]
Noticed this issue when working on the activity. Please ignore the lack of camera button as this is relevant to PR #686. There appears to be two titles for the nutrition images, with the "Take nutrition image" should not be there. This may be confusing to some users.

These titles are also hardcoded in `activity_save_product_offline.xml`.

![screenshot_20180130-173211](https://user-images.githubusercontent.com/5596450/35581548-04d1c658-05e4-11e8-8fda-0fcef00d1d59.png)

**Comment by ross-holloway94** [comment]
This is addressed in #684 .
