### ISSUE TITLE
Create deeplinks for product pages

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#690]
Create deeplinks for product pages so that we can make it easier to open them from search results.

https://developer.android.com/training/app-links/deep-linking.html

**Comment by Ekt0s** [comment]
What are the link that needs to be supported ? 

• Search link ?
• Direct link to an item ?

**Comment by teolemon** [comment]
Direct link to an item would be a good first step. The facet system is the next good candidate

**Comment by abdulwd** [comment]
@teolemon I would like to work on this issue.

**Comment by teolemon** [comment]
@abdulwd are you still working on this ?

**Comment by abdulwd** [comment]
@teolemon No.

**Comment by prajurock** [comment]
Can i take this issue?

**Comment by teolemon** [comment]
@prajurock as a result, yes :-)

**Comment by prajurock** [comment]
Ok.

**Comment by teolemon** [comment]
Duplicate of #273
