### ISSUE TITLE
Categories crash when the network is low or unexistant

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#692]
![image](https://user-images.githubusercontent.com/1689815/35852268-baf9a41e-0b2a-11e8-9519-3d61745b42fb.png)

**Comment by policorn** [comment]
Hi @teolemon, can it be related with #677 ?

**Comment by PrajwalM2212** [comment]
@teolemon  One of the typical way to solve this is to display another layout which asks the user to try again after network becomes available(like browsers) . 
Would you like have such a iimplementation?
