### ISSUE TITLE
Put the nutriscore in the Summary tab, below product name

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#697]
Put the nutriscore in the Summary tab, below product name
Most people want it first, as a nutrition summary, and it's the killer feature of V1

The code is in the Nutrition tab. Duplicate it. Don't remove it from the nutrition tab. We can live with the nutriscore being displayed twice :-)

**Comment by policorn** [comment]
Going to work on it

**Comment by policorn** [comment]
![screenshot_1518291465](https://user-images.githubusercontent.com/18316436/36065982-60b827c0-0ea2-11e8-8553-87bcc0e82c8c.png)

**Comment by Shubham2320** [comment]
@teolemon hey, is any more work left on this issue or otherwise, it should be closed now.
