### ISSUE TITLE
[BUG] Language codes appear as translatable

### ISSUE THREAD

**Issue by yarons** [openfoodfacts/openfoodfacts-androidapp#698]
This could break numerous applications, can I just remove these from the values/strings.xml file or is there any further step I should take in order to prevent breaking the build?

We're talking about this list:
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/src/main/res/values/strings.xml#L32

Kind regards,
Yaron (Hebrew translation)

**Comment by teolemon** [comment]
cc @policorn

**Comment by policorn** [comment]
Ok, going to try to understand the issue and work on it

**Comment by policorn** [comment]
I've reused a big part of @mac-adder's #324 code (https://github.com/mac-adder/openfoodfacts-androidapp/commit/e6339c9715354602623a6163664d34431dab405b)

**Comment by policorn** [comment]
![screenshot_1518387676](https://user-images.githubusercontent.com/18316436/36080188-9903fe48-0f8c-11e8-8b62-f76a419923a3.png)
![screenshot_1518387727](https://user-images.githubusercontent.com/18316436/36080189-99206a42-0f8c-11e8-8d09-d1dfcf725f86.png)
![screenshot_1518387744](https://user-images.githubusercontent.com/18316436/36080190-993cb7ec-0f8c-11e8-89f1-0d649c2f17be.png)

**Comment by policorn** [comment]
I've added the locale at the end of each language to make it more easy to pick the desired language (i.e.: you select Chinese by mistake and you don't remember 英语 means "English" by heart).

**Comment by yarons** [comment]
You can use CLDR instead of asking translators to do this manually, this will require less strings to translate and maintain.

**Comment by teolemon** [comment]
Android has https://developer.android.com/reference/java/util/Locale.html

**Comment by teolemon** [comment]
fixed. Thank @policorn . High impact one.
