### ISSUE TITLE
Picture don't display within the form as soon as they are taken

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/OpenFoodFacts-androidApp#7]
I hit the take picture button
take a picture, like so
![screenshot_2015-05-10-21-28-31](https://cloud.githubusercontent.com/assets/43065/7556099/b2ffe51a-f75b-11e4-945b-70b5c0b6db0e.png)

I hit the tick mark for OK.
The image is not displayed like so

![screenshot_2015-05-10-21-28-38](https://cloud.githubusercontent.com/assets/43065/7556114/10b84724-f75c-11e4-99e0-117dac3f1479.png)

I cannot save the product as the image i just took is not there

**Comment by kyzh** [comment]
Ok, so one need both an image and at least the "name" property to be filled.

There should be a way to let user know how many picture have been taken and that they have been successfully transmitted.

**Comment by kyzh** [comment]
While I was not able to find it with the original app.
On second scan the picture displayed ok.

![screenshot_2015-05-10-21-41-00](https://cloud.githubusercontent.com/assets/43065/7556160/80fc7b4e-f75d-11e4-95dd-774da644dfde.png)
![screenshot_2015-05-10-21-41-49](https://cloud.githubusercontent.com/assets/43065/7556163/953cdc7a-f75d-11e4-819a-d50270f290c5.png)

**Comment by itchix** [comment]
Can you see it from your panel user? if the product is added?
![screen shot 2015-05-10 at 21 56 33](https://cloud.githubusercontent.com/assets/2846894/7556211/8644ca5a-f75f-11e4-84c2-b1187b7acb5c.png)

**Comment by kyzh** [comment]
So since the 'save' only save locally see #8 and that the actuall way to send it to the database is not working for me #10 , the data is not showing up [here](http://world.openfoodfacts.org/contributor/kyzh).

I think the issue only occurs on first scan.

**Comment by itchix** [comment]
Fixed now
