### ISSUE TITLE
Add a bottom navigation

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#704]
![image](https://user-images.githubusercontent.com/1689815/36087196-6597a448-0fd1-11e8-8141-86f1521ce290.png)

- Language switching of the product
- Share button
- Jump to sections of the product
- Save product to a list

**Comment by abhinavbajpai2012** [comment]
hey ,can I work on this?

**Comment by samagra14** [comment]
Yeah, sure @abhinavbajpai2012. Noone has claimed this issue. So I guess it is open to contributions.

**Comment by abhinavbajpai2012** [comment]
thank you @samagra14 👍

**Comment by abhinavbajpai2012** [comment]
@teolemon I don't think overlap of FAB or any other view is allowed over bottom bar, although I have implemented it. Shall I send you a PR?

**Comment by AbsolutelySaurabh** [comment]
We can add a ScrollView effect, in which the bottom bar will be visible once the user taps on the screen, otherwise it'll disappear. Moreover, we'll "bottombar + FAB" in a coordinator layout to make them interact smoothly, that must even eliminate the overlapping problem.

**Comment by Karljoones** [comment]
FYI: this issue is available for anyone who wants to work on it :)

**Comment by iml-v** [comment]
@Karljoones  i will take it forward from here

**Comment by iml-v** [comment]
@Karljoones i will take it forward from here

**Comment by iml-v** [comment]
@teolemon @Karljoones what about this 
![video2gif_20180317_182652 1](https://user-images.githubusercontent.com/30701209/37555653-e644e61a-2a10-11e8-9999-b7020780f0b8.gif)

**Comment by iml-v** [comment]
@teolemon  @Karljoones i have Sent PR for first GIF's implementation ,Pls review it
