### ISSUE TITLE
Add a product of the day card on homefeed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#706]
![image](https://user-images.githubusercontent.com/1689815/36087332-2dba0a56-0fd2-11e8-995b-02fb325a6aea.png)

**Comment by Shubham2320** [comment]
Can I work on it?

**Comment by Shubham2320** [comment]
Is there any API call we can make to get the  required product?

**Comment by Kartikkman** [comment]
Hey @teolemon , I want to work on this !! I am beginner , Can you provide me some inputs ?? 
Thanks
