### ISSUE TITLE
3D product history / switching

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#707]
![image](https://user-images.githubusercontent.com/1689815/36087347-4ade8e5e-0fd2-11e8-8d85-5a52ce00e646.png)

**Comment by jaztriumph** [comment]
@teolemon I wish to work on this.

**Comment by ManavPoddar** [comment]
I would love to work on this if still available

**Comment by jaztriumph** [comment]
@ManavPoddar you can go on with this.

**Comment by Karljoones** [comment]
@ManavPoddar Did you ever manage to look into this?
