### ISSUE TITLE
Add a donation button "Support Open Food Facts"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#708]
![image](https://user-images.githubusercontent.com/1689815/36087400-877978c4-0fd2-11e8-9b68-9baa0a088b46.png)
![image](https://user-images.githubusercontent.com/1689815/36087374-6f753c54-0fd2-11e8-94ea-4664421b8932.png)
![image](https://user-images.githubusercontent.com/1689815/36087381-7974c92c-0fd2-11e8-902e-1669c83df7c1.png)

**Comment by teolemon** [comment]
https://wikimediafoundation.org/wiki/Keep_Wikipedia_Free
https://www.helloasso.com/associations/open-food-facts/formulaires/1/widget/en

**Comment by batbrain7** [comment]
@teolemon may I work on this?

**Comment by teolemon** [comment]
That's a good and useful introduction to the code, I guess. :-)
We work using branches and pull-requests.

**Comment by Karljoones** [comment]
@batbrain7 @teolemon Please be aware of this: 

From: https://play.google.com/about/developer-content-policy.html

- App purchases: Developers charging for apps and downloads from Google Play must do so by using Google Play's payment system.

- In-app purchases:
            Developers offering virtual goods or currencies within a game downloaded from Google Play must use Google Play's in-app billing service as the method of payment.
            Developers offering additional content, services or functionality within another category of app downloaded from Google Play must use Google Play's in-app billing service as the method of payment

Make sure that this feature conforms to the terms of service or it could put OFF at risk :) i think if donations are done in the app but in a webview handled by an external source it's okay though

**Comment by teolemon** [comment]
@batbrain7 as long as we use the Chrome custom tab it will be ok

**Comment by teolemon** [comment]
https://www.helloasso.com/associations/open-food-facts/formulaires/1/widget/en

**Comment by ManognaMutyala** [comment]
![screenshot_20180228-085913](https://user-images.githubusercontent.com/22299553/36769300-7caf7c10-1c69-11e8-863a-a075550a68bf.png)
![screenshot_20180228-085920](https://user-images.githubusercontent.com/22299553/36769335-b16ef958-1c69-11e8-8112-07c2f0a1aac7.png)

It would look something like this!!!
