### ISSUE TITLE
Add Installation Script install.sh

### ISSUE THREAD

**Issue by ujjwalagrawal17** [openfoodfacts/openfoodfacts-androidapp#713]
**Issues Faced**
1.Installation failed due to insufficient permission on running easy_install android2po
2. a2po COMMAND --android myproject/res --gettext myproject/locale gives 

**Log**
1.error: can't create or remove files in install directory
The following error occurred while trying to add or remove files in the
installation directory:
    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-26480.write-test'
The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:
    /usr/local/lib/python2.7/dist-packages/

2.ImportError: No module named termcolor
**Steps to Reproduce**
3. After installing from sudo pip install termcolor it gives this error
a2po: error: argument command: invalid choice: 'COMMAND' (choose from u'import', u'init', u'export')
Add installation script install.sh and update the readme

**Comment by teolemon** [comment]
We don't use android2po anymore

**Comment by teolemon** [comment]
Just removed it from instructions
