### ISSUE TITLE
Adding PULL_REQUEST_TEMPLATE.md file for new contributors 

### ISSUE THREAD

**Issue by iml-v** [openfoodfacts/openfoodfacts-androidapp#714]
There should be PULL_REQUEST_TEMPLATE.md file which tell new contributors how to get started  .

**Comment by iml-v** [comment]
working on it

**Comment by samagra14** [comment]
@iml-v Please don't close issues until your PR is merged. Open issues are a great place for discussions.

**Comment by iml-v** [comment]
@samagra14 i agree but there was some problem so did that and reopened same new issue.
