### ISSUE TITLE
Create ISSUE_TEMPLATE.md file 

### ISSUE THREAD

**Issue by iml-v** [openfoodfacts/openfoodfacts-androidapp#715]
There should be proper Issue Template for creating new issues so that others can know about that issue means how he/she created and all .

**Comment by ujjwalagrawal17** [comment]
can I work on this?

**Comment by ujjwalagrawal17** [comment]
I will send a PR you review it.

**Comment by iml-v** [comment]
@ujjwalagrawal17  i am working on this
