### ISSUE TITLE
there should be wiki page for Introduction to Git and Github for new contributors .

### ISSUE THREAD

**Issue by iml-v** [openfoodfacts/openfoodfacts-androidapp#720]
A wiki page for Introduction  to Git and Github should be there to get started to contributing in project .
something like this -
![giithub](https://user-images.githubusercontent.com/30701209/36137834-f571f046-10bc-11e8-8db3-e29fe20d08e2.PNG)

**Comment by iml-v** [comment]
would like to work on this ?

**Comment by iml-v** [comment]
@teolemon what is your point on this ?

**Comment by samagra14** [comment]
I guess this is completely unnecessary as people are expected to know git and Github if they are willing to dive into OSS. Besides, there will be no point in adding Introduction to git and Github on every project.

**Comment by iml-v** [comment]
@samagra14 yeah, but most of time in starting people are not version control familiar ,also there is no guideline how to start working on any Openfoodfacts project .
