### ISSUE TITLE
Show Nutriscore in search results and scan history as a color dot

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#721]

**Comment by teolemon** [comment]
assigning to @Nymerea

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/36647566-dbb4a3d6-1a87-11e8-94e5-c4993c54a8f4.png)

**Comment by Shubham2320** [comment]
I think this can be closed now.

**Comment by teolemon** [comment]
thanks @Shubham2320
