### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by ManognaMutyala** [openfoodfacts/openfoodfacts-androidapp#726]
App is crashing on clicking information related to products such as ingredients,nutrition,nutrition table

![screenshot_20180213-233214](https://user-images.githubusercontent.com/22299553/36165850-dbed6538-1116-11e8-83f2-940a0c0865e1.png)

**Comment by huzaifaiftikhar** [comment]
Not able to reproduce this bug. Works fine on my device.
Android 7.1.1

**Comment by ross-holloway94** [comment]
I believe this is a duplicate of #621

**Comment by policorn** [comment]
Hi @ManognaMutyala, PR #783 should have fixed it, can you update your repo and try to reproduce it? If it's already fixed please close this issue ticket. Thanks!

**Comment by policorn** [comment]
Thanks @ManognaMutyala!
