### ISSUE TITLE
Progress Bar not properly placed

### ISSUE THREAD

**Issue by abhinavbajpai2012** [openfoodfacts/openfoodfacts-androidapp#729]
![screenshot_2018-02-14-00-51-20-873_openfoodfacts github scrachx openfood](https://user-images.githubusercontent.com/24355881/36169440-41f91ab0-1122-11e8-9db7-4b97a87a2118.png)

Progress bar is getting trimmed at the top in some of the devices.
I want to work on this.

**Comment by teolemon** [comment]
thanks :) go ahead

**Comment by teolemon** [comment]
Can we use a bottom snackbar instead. I'm uneasy with using an offset when screen size and orientation can change (tablets, phablets…), and make it move over the logo or elsewhere

**Comment by sachincool** [comment]
@teolemon I can do the changes. @abhinavbajpai2012  can i take this or are you already working on this?

**Comment by ManognaMutyala** [comment]
@sachincool  I have already submitted PR for this and it is under review!!
