### ISSUE TITLE
Add an alert window when no internet access detected.

### ISSUE THREAD

**Issue by abhinavbajpai2012** [openfoodfacts/openfoodfacts-androidapp#730]
The app notifies the user for no internet connection when he has entered all the details for sign up/search. There should be a alert box to notify the user before searching or accessing the feature regarding no internet connection.
I am willing to work on this and would implement a similar alert box a shown in the below screenshot.
![screenshot_2018-02-14-01-25-35-411_openfoodfacts github scrachx openfood](https://user-images.githubusercontent.com/24355881/36171128-724c1ee2-1127-11e8-91d2-68c08d458423.png)
![screenshot_2018-02-14-01-25-48-003_openfoodfacts github scrachx openfood](https://user-images.githubusercontent.com/24355881/36171133-72c71cc8-1127-11e8-8070-b332378889a4.png)
![screenshot_2018-02-14-01-33-10-777_startup ab nightfoodler](https://user-images.githubusercontent.com/24355881/36171134-73447b0a-1127-11e8-99f4-a448f3afc004.png)

**Comment by samagra14** [comment]
@abhinavbajpai2012  Notifying beforehand is perfect. Nice idea. But I guess a toast message will be a better alternative. Besides, it would cause some unnecessary check network calls.

**Comment by abhinavbajpai2012** [comment]
yup any of the options would work, toast will be better though.

**Comment by teolemon** [comment]
For the login system, if we push it further: it might store the identifier locally, so that login is easier when back online (or even attempt to auto-login when back online)

**Comment by teolemon** [comment]
For the categories, it could queue the download, and attempt again when network is detected.

**Comment by abhinavbajpai2012** [comment]
Ok @teolemon , I will surely implement as you suggested.

**Comment by Karljoones** [comment]
@abhinavbajpai2012 What is happening with this? Did you manage to implement this?
