### ISSUE TITLE
Bug on getting back from findProductFragment to homeFragment.

### ISSUE THREAD

**Issue by Shubham2320** [openfoodfacts/openfoodfacts-androidapp#731]
On pressing back button from **find product fragment** we switch back to **home fragment** and in this process overlap of two fragments occur which should be fixed.

<img src="https://user-images.githubusercontent.com/25099208/36171010-195441de-1127-11e8-81c6-fbb8d9e81a90.png" height="440px" />

I will work on this issue.

**Comment by samagra14** [comment]
@Shubham2320  Is this the right flavor you have built? It says Open Beauty Facts.

**Comment by teolemon** [comment]
It closes the app for me. Weird.

**Comment by Shubham2320** [comment]
@samagra14  I've built Flavour `obf`. I assume its the right flavour. Correct me if I'm wrong.

**Comment by Shubham2320** [comment]
> Is this the right flavor you have built? It says Open Beauty Facts
 thanks @samagra14 you're right I was in a different flavour, but still, the bug should be fixed.

**Comment by Shubham2320** [comment]
@teolemon yes you're right it closes the app mostly, but I've found the way to reproduce the bug.

**Ways to reproduce:**

1) Open homepage.
2) Search for any product.
3) After getting search results press back.
4) Now the app is back on the homepage.
    
     Open any of the below fragment.

-     Find product fragment (Search by barcode)
-     Allergen alert
-     Preferences

    
<img src="https://user-images.githubusercontent.com/25099208/36191380-dc274cdc-1182-11e8-94fa-ec8497fd6e1c.png" height="560"> </img>

<img src="https://user-images.githubusercontent.com/25099208/36191383-df1604b0-1182-11e8-9d9d-fd2f08b93222.png" height="560"> </img>

<img src="https://user-images.githubusercontent.com/25099208/36191386-e4176da0-1182-11e8-841d-f7c2cda338bd.png" height="560"> </img>
