### ISSUE TITLE
No warning on pressing back in home activity and app closes 

### ISSUE THREAD

**Issue by iml-v** [openfoodfacts/openfoodfacts-androidapp#735]
**Summary:** 

when user press back button in app it takes out from app but there is no warning message "Please press back again to exit" .

**Steps to reproduce:** 

Start the app ---> press back button on home screen .

**Add System logs:**

**Expected behavior:** 

It should show warn message to user like "Please press back again to exit " to come out from app.

**Observed behavior:** 

on pressing back it takes out from app .

**Device and Android version:** 

Android 7.0 ,API 24

**Screen-shots:** 

![video2gif_20180214_031555 1](https://user-images.githubusercontent.com/30701209/36175462-872473d8-1135-11e8-9600-c744be8c898e.gif)

**Comment by iml-v** [comment]
@teolemon  i am working on the issue.

**Comment by ross-holloway94** [comment]
@iml-v Before you go too far, I would like to hear more opinions on this. Personally, I would find it annoying.

**Comment by iml-v** [comment]
@ross-holloway94  sometimes we incidentally presses back and comes out of app and whatever we were doing before become useless so i think it should warn user before going out of app ,also i would like to hear from others opinion on this .

**Comment by samagra14** [comment]
@ross-holloway94 I share your opinion. I guess that those "Are you sure you want to exit ?" are annoying.

**Comment by Karljoones** [comment]
@ross-holloway94 @teolemon I agree, they can be annoying and interrupt the users flow through their device, might be off-putting for some users, myself included. Exiting out of the app won't remove any data that the user has input, the onResume() should handle this anyway if this is the case.

**Comment by AbsolutelySaurabh** [comment]
I would like to work on this issue.

**Comment by iml-v** [comment]
@AbsolutelySaurabh thanks you are interested but changes i have done on my local machine i am waiting for @teolemon viewpoint on this issue   .
