### ISSUE TITLE
Adding a side scroll in the categories tab for easier navigation

### ISSUE THREAD

**Issue by ManavPoddar** [openfoodfacts/openfoodfacts-androidapp#754]
**Summary:** 

There should be a scroll on side of the categories tab for easier navigation of users to their desired category. 

![scroll](https://user-images.githubusercontent.com/18038492/36239762-33b7f8de-1232-11e8-85ee-4f543e59eddc.png)
![screenshot_20180215-092320](https://user-images.githubusercontent.com/18038492/36239785-6808eb52-1232-11e8-9cf6-dd7e17220673.png)

**Comment by ManavPoddar** [comment]
@teolemon i'm working on it

**Comment by samagra14** [comment]
@ManavPoddar Please wait till there is an official nod for the related feature. Don't just start working on issues that are not accepted officially. It might not be agreed upon and you might have wasted your time.

**Comment by ManavPoddar** [comment]
@samagra14  yeah i agree, thanks :)

**Comment by teolemon** [comment]
Yup, it's ok.
Also, it would be cool to be able to actually click the categories ;-)
