### ISSUE TITLE
Option for deleting a particular item in History

### ISSUE THREAD

**Issue by ManavPoddar** [openfoodfacts/openfoodfacts-androidapp#755]
**Summary:** 

There is an option  for deleting all the scan history, but there may be some users who might want to delete only a particular product from their history.

**Steps to reproduce:** 

Menu -> History

**Expected behavior:** 

We can improvise the feature by selecting the product we want to delete by long pressing it and then pressing the delete button.

**Screen-shots:** 

A small example of what i'm trying to say.
![select-contacts-for-deleting-android](https://user-images.githubusercontent.com/18038492/36240303-c9f9c864-1236-11e8-82b8-dcdd03247cdc.png)

**Comment by PrajwalM2212** [comment]
@toelmon Nowadays apps come with option to delete by a swipe action . So as an enhancement we may allow a user a delete by swiping a item across the screen . It may lead to a better User Experience as the user need not have to long press a item and delete it .

**Comment by ManavPoddar** [comment]
@PrajwalM2212  that's a really nice idea, it is much more convenient :)

**Comment by AbsolutelySaurabh** [comment]
May I work on this issue?

**Comment by ManavPoddar** [comment]
Hi @AbsolutelySaurabh, I am working on it :)
