### ISSUE TITLE
The username does not change in the menu when you sign out

### ISSUE THREAD

**Issue by ManavPoddar** [openfoodfacts/openfoodfacts-androidapp#763]
**Summary:** 

When you sign-out or sign-in, the username does not change in the menu, it changes only when we restart the app.

**Steps to reproduce**
open app (username in menu is anonymous) -> sign-in (after signing in, username is anonymous)->restart the app (now username changed to that of yours)  

**Expected behavior:** 

The username should change immediately after we signed in or signed out, not after restarting the app

**Screen-shots:** 

![videotogif_2018 02 15_21 31 22](https://user-images.githubusercontent.com/18038492/36266700-1fd72f18-1298-11e8-8a06-b38bed10b7f8.gif)

**Comment by ManavPoddar** [comment]
@teolemon i would love to work on this issue

**Comment by jaztriumph** [comment]
@ManavPoddar Already discussed in #756 and resolved in #760
