### ISSUE TITLE
There is an empty list item in the start of the categories tab.

### ISSUE THREAD

**Issue by ManavPoddar** [openfoodfacts/openfoodfacts-androidapp#764]
**Summary**
The list item in the start of categories is empty

**Steps to reproduce:** 
menu->categories

**Screen-shots:** 

![screenshot_20180215-214337](https://user-images.githubusercontent.com/18038492/36267517-143793c6-129a-11e8-93d0-7919bf3a2707.png)

**Comment by Shubham2320** [comment]
I would love to work on this issue if available.

**Comment by ManavPoddar** [comment]
I am already working on it
