### ISSUE TITLE
Show notifications when network status of device changes.

### ISSUE THREAD

**Issue by Siddharth-Singhs** [openfoodfacts/openfoodfacts-androidapp#766]
**Summary:** 

Whenever the user goes offline or online,a snackBar should give notification to the User.

**Screen-shots:** 
![whatsapp image 2018-02-16 at 00 06 57-2](https://user-images.githubusercontent.com/31280485/36274434-c4320906-12ad-11e8-858b-70451a34e51d.jpeg)
![whatsapp image 2018-02-16 at 00 06 57](https://user-images.githubusercontent.com/31280485/36274436-c65d02da-12ad-11e8-8dbd-f5987f05e08e.jpeg)

**Comment by gerry101** [comment]
I would like to work on this feature if possible

**Comment by sidknight** [comment]
I am working on it.

**Comment by Siddharth-Singhs** [comment]
I am working on it @gerry101

**Comment by gerry101** [comment]
Okay.

**Comment by Siddharth-Singhs** [comment]
@Karljoones please check the commit
