### ISSUE TITLE
App is crashing(sometimes) while scanning the bar code on Home screen.

### ISSUE THREAD

**Issue by AbsolutelySaurabh** [openfoodfacts/openfoodfacts-androidapp#769]
**Summary:** 

The app is crashing(sometimes) while scanning the bar code on home screen. It did worked once, and the item got added in the "history", but clicking on the added item in the "history" is crashing afterthen. .

**Steps to reproduce:** 

Just press the FAB on the home screen and scan the bar code on the food packet, it's crashing with a message "Unfortunately open food facts has stopped".

**Add System logs:**

Url to Log message: https://gist.github.com/AbsolutelySaurabh/f79ed0af23cd990e831d76c1d7210685

**Device and Android version:** 
The app crashed on Samsung Galaxy J5 with Android 6.0.1 Marshmallow.

**Screen-shots:** 
![screenshot_20180216-030035](https://user-images.githubusercontent.com/17049336/36282058-dc8d0f92-12c5-11e8-8588-ac01b050a8e4.png)

**Comment by jaztriumph** [comment]
@AbsolutelySaurabh Its already discussed in #761 and resolved in #765.

**Comment by AbsolutelySaurabh** [comment]
@jaztriumph , should I close this issue?

**Comment by jaztriumph** [comment]
@AbsolutelySaurabh yes.
