### ISSUE TITLE
Implement Product List item as card view

### ISSUE THREAD

**Issue by PrajwalM2212** [openfoodfacts/openfoodfacts-androidapp#770]
![screenshot_1518796308](https://user-images.githubusercontent.com/30733262/36316238-c82c5964-135f-11e8-9a93-c8f0d82d1948.png)

The product list items can be card views . The text sizes and colours can be changed to match material design guidelines.

**Comment by PrajwalM2212** [comment]
@teolemon @ross-holloway94  I would like to work on this.

**Comment by teolemon** [comment]
Yup, totally agree :-)
Also, as a side note, it takes ages to load if the network is poor. We should cache the products from the history

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/36316965-16ac2e1c-133c-11e8-8283-9b56fe705e8d.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/36316999-26d779e0-133c-11e8-939f-5a0d6c28cce3.png)

**Comment by PrajwalM2212** [comment]
@teolemon  Let me solve the design aspect of the problem first . 
The loading time is large because it is displaying the items after parsing the all the available items .
So we can decrease the load time if can somehow send batches of parsed items (say 10 each time).This way the screen gets populated fast . Or we may add a next button at the bottom and parse only limited number of items each time to increase load speeds. 
The plan is to only parse a limited number of items instead of all the items ( for example in the image I uploaded it is displaying after parsing 1498 items ) . By adding a next button or a listening to the scrolling at bottom of the screen we may again parse the number of items to fill the screen.
What do you have to say about this?

**Comment by teolemon** [comment]
Yes, let's focus on  one issue at the time :)

**Comment by teolemon** [comment]
I thought you were going to apply the material style (see my last screenshot) to the History, not apply the Bubble history style to Search :-S

**Comment by PrajwalM2212** [comment]
@teolemon  The fork that i have already has card view implemented to the history .

**Comment by PrajwalM2212** [comment]
![history](https://user-images.githubusercontent.com/30733262/36343313-aae6052c-1430-11e8-825a-3aacc2f664f9.png)
@teolemon  The history already looks like this .

**Comment by PrajwalM2212** [comment]
@teolemon  Do you want any changes in the appearance of the history above?

**Comment by Karljoones** [comment]
@PrajwalM2212 I think there may have been a bit of confusion on my behalf, just had a chat with @teolemon regarding this issue. What we wanted to do was to make the history look like the search results. The lists for history, and for search results should be the same, aka: how the search results look at the moment, without card views.

**Comment by PrajwalM2212** [comment]
@Karljoones  The history already has card views implemented before itself(see the image above). So it would be fine to make search also as card views right?

**Comment by teolemon** [comment]
The Material Design list spec uses lines, like in the history
https://material.io/guidelines/components/lists.html#lists-usage

**Comment by PrajwalM2212** [comment]
@teolemon  That is the list implementation. Below they have listed cards as an alternative.  
I have used card views. The history (in the above image ) already has implemented card views. All search results of google are card views if you see. So it would be better to use card views. 
Or do you prefer list views itself.

**Comment by PrajwalM2212** [comment]
@Karljoones @teolemon  What is the update on this issue? 
Should we go with cards or lists?

**Comment by Karljoones** [comment]
@PrajwalM2212 the history list should not have cards. You can find more information on the implementation of the search lists [here](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/ProductsListAdapter.java). The history list adapter is [here](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java).

**Comment by PrajwalM2212** [comment]
@Karljoones  Then we will have to convert card views in history back to lists .I will convert the history into lists .

**Comment by PrajwalM2212** [comment]
@Karljoones  Since the history list should not have cards . We will have to change https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/src/main/res/layout/history_list_item.xml code to remove card views.
I will do that.

**Comment by Karljoones** [comment]
Yep! You can use product_list_item.xml for reference! Thanks! Let me know when it is done and I can have another look

**Comment by PrajwalM2212** [comment]
@Karljoones  Since this issue was opened for making search as card views , i will create a new issue to remove card views from history.

**Comment by Karljoones** [comment]
Sure, we can close this pull request for now, and then when you have made the changes, just reopen a new one and we can take it from there. Just so I see it, request a review from me or ping me on Slack.
