### ISSUE TITLE
Replace hardcoded strings with string resource in the project 

### ISSUE THREAD

**Issue by AdityaGupta030697** [openfoodfacts/openfoodfacts-androidapp#771]
Hardcoded strings are used at some places in the project. It would be great if we replace the strings with string resource.

I would like to work on the issue.

**Comment by teolemon** [comment]
Perfect :)
Feel free to be more specific when opening bugs

**Comment by Karljoones** [comment]
@AdityaGupta030697 can you put a bit more detail into this issue so others know what it is about? Also, can you confirm if you are working on this?

**Comment by AdityaGupta030697** [comment]
Yes
