### ISSUE TITLE
Camera Scan button  making it difficult to view the  nutrition facts  for some products

### ISSUE THREAD

**Issue by ManavPoddar** [openfoodfacts/openfoodfacts-androidapp#773]
**Summary:** 

It is nearly impossible to view the bottom most  details of some products under  the Nutrition Facts tab. This is because of the camera  scan button coming in between. For some products, even the scrolling doesn't help.

**Steps to reproduce:** 
Open any product -> swipe right to nutrition facts.

**Expected behavior:** 

The camera scan button can fade a little or become invisible until we touch the screen again. This would help us see the details easily.

**Screen-shots:** 

![screenshot_20180217-012257](https://user-images.githubusercontent.com/18038492/36326853-961e265a-1382-11e8-93cb-e32ef88ba183.png)
![screenshot_20180217-012406](https://user-images.githubusercontent.com/18038492/36326856-98056636-1382-11e8-8350-66aece835dea.png)
![screenshot_20180217-012310](https://user-images.githubusercontent.com/18038492/36326857-99398fdc-1382-11e8-91d0-cd924696728d.png)

**Comment by teolemon** [comment]
Or perhaps add enough space after the table so you can scroll.

**Comment by ManavPoddar** [comment]
@teolemon I would love working on this issue

**Comment by teolemon** [comment]
go ahread :)
