### ISSUE TITLE
Improvement needed for adding a Allergen

### ISSUE THREAD

**Issue by ManavPoddar** [openfoodfacts/openfoodfacts-androidapp#775]
**Summary:** 

It is very difficult to search for a specific allergen, as the list is not sorted and neither there is any option to search. 

**Steps to reproduce:** 

Menu -> allergen alert -> click on the add button.

**Expected behavior:** 

Either the list of allergens can be sorted alphabetically or we can add an option for searching our preferred allergen.
 

**Screen-shots:** 

![screenshot_20180217-015853](https://user-images.githubusercontent.com/18038492/36327961-5094a5c4-1386-11e8-8ae6-80d813d7102d.png)

**Comment by teolemon** [comment]
I guess both (sorting, and filtering) are interesting

**Comment by AbsolutelySaurabh** [comment]
I am working on this issue.

**Comment by ManavPoddar** [comment]
I would love to work on this issue if still available :)
