### ISSUE TITLE
0.8 was published on GPS, but no tag and no changelog here

### ISSUE THREAD

**Issue by ArchangeGabriel** [openfoodfacts/openfoodfacts-androidapp#776]
**Summary:** 

See title.

**Steps to reproduce:** 

Go to the Play Store (or your favourite PlayStore app), maybe you will see the new version (0.8.0)…

**Expected behavior:** 

The new version would be tagged here, a changelog would be available here as written in the Play Store changelog (“Voir GitHub”).

**Observed behavior:** 

No tag, no changelog for this version.

**Comment by teolemon** [comment]
@itchix

**Comment by ArchangeGabriel** [comment]
0.8.1 has now been published on GPS, still nothing here, except an addition in CHANGELOG.md without any information: https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/a91778b62067e6b1ebccf732d2b9135249c2691e#diff-4ac32a78649ca5bdd8e0ba38b7006a1e.

**Comment by ArchangeGabriel** [comment]
You should maybe add a line on top of `CHANGELOG.md` saying that now changes are listed in the release section. ;)

**Comment by ArchangeGabriel** [comment]
Well honestly I don’t care about the changelog on GPS. My issue was more that no new version was tagged here, so that F-Droid couldn’t build it. ;)
