### ISSUE TITLE
LoginActivity landscape mode UI issues

### ISSUE THREAD

**Issue by doomers** [openfoodfacts/openfoodfacts-androidapp#778]
**Summary:** 

currently, almost whole of the app is built in portrait mode, but LoginActivity can go in landscape mode also, and this is causing UI issues hiding the sign-up button(as seen in the screenshot), so the orientation of activity should be portrait mode not in landscape mode.

**Steps to reproduce:** 

open the LoginActivity and tilt your phone to landscape mode.

**Expected behavior:** 

so the orientation of activity should be portrait mode not in landscape mode.

**Screen-shots:** 

![openfood-1](https://user-images.githubusercontent.com/11586392/36334950-add723f8-13a2-11e8-8ae6-2ef72734cdac.jpeg)

**Comment by doomers** [comment]
should i send a PR for this?

**Comment by Karljoones** [comment]
Fixed in #782
