### ISSUE TITLE
"Send all" button in offline edition does nothing, images and data not sent

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/OpenFoodFacts-androidApp#78]
Related to bug #69:

I have a few images and some data for one product that I saved and that I'm not trying to upload to the server.

When I tap on "Tout envoyer", absolutely nothing happens. The product stays there, the button does not change (e.g. it doesn't change color to show that it has been pressed).

**Comment by teolemon** [comment]
Has been solved.
