### ISSUE TITLE
Implement static shortcuts for Open Food Facts

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#788]
**Summary:** 

Add feature for displaying static shortcuts to specific actions. Shortcuts let users quickly start common or recommended tasks within the app. Works on API 25 or above.

**Expected behavior:** 

We can add shortcuts for specific actions like 'Scan Barcode' , 'History' and 'Search by barcode' to  let users quickly search the products and also quickly view their history.

**Observed behavior:** 

No shortcuts as of now.

**Screen-shots:** 
![pinned-shortcuts](https://user-images.githubusercontent.com/10832531/36343404-ea87fb30-1431-11e8-93af-588475e1f8b8.png)

**Comment by teolemon** [comment]
We already have a bug for App Shortcuts at https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/171
Pinned Shortcuts would be cool as well :-)

**Comment by huzaifaiftikhar** [comment]
Ohh I am sorry I didn't look up for that :( 
Can I work on that issue?

**Comment by Karljoones** [comment]
@huzaifaiftikhar of course you can, I am going to close this issue as a duplicate :) Please continue your work on #171
