### ISSUE TITLE
Shortcut icons are Bitmaps instead of VectorDrawables

### ISSUE THREAD

**Issue by policorn** [openfoodfacts/openfoodfacts-androidapp#801]
Please replace the shortcuts bitmaps icons introduced in PR #792 by VectorDrawables. 

As an example, you can use layer-list to combine the required elements (grayed circle in the back and a referenced drawable on top of it):

```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <!-- drawable/circle_card_icon.xml -->
        <shape xmlns:android="http://schemas.android.com/apk/res/android"
            android:shape="oval">
            <solid android:color="#eee"/>
            <size
                android:width="24dp"
                android:height="24dp"
                />
        </shape>
    </item>
    <item android:drawable="@drawable/ic_search_black" />
</layer-list>
```
Change the sizes, colors as required to replicate the ones used currently. 

**Note**: Not an issue, but a suggested improvement

**Comment by huzaifaiftikhar** [comment]
@policorn I would like to work on this. Please assign it to me.

**Comment by policorn** [comment]
HI @huzaifaiftikhar, consider it assigned to you 👍

**Comment by huzaifaiftikhar** [comment]
@policorn @teolemon Please review.
