### ISSUE TITLE
The red cross for missing image is pixelated in History

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#802]
**Summary:** 

The red cross for missing image is blurry and pixelated in History. We should have something crisper.

**Device and Android version:** 

Android Oreo on a Google Pixel

**Screen-shots:** 

![image](https://user-images.githubusercontent.com/1689815/36354142-06311954-14d0-11e8-95e5-9782e8b5ca55.png)

**Comment by SatyamBansal** [comment]
@teolemon, I suggest that instead of red cross we could use place holder image like this 
![placeholder](https://user-images.githubusercontent.com/19202937/36354355-036d7eb4-14f9-11e8-9578-8595dbecfbf0.jpg)

**Comment by teolemon** [comment]
We use the Open Food Facts pacman on the website
https://static.openfoodfacts.org/images/misc/pacman.svg

**Comment by teolemon** [comment]
we should use vectors, and a raster fallback

**Comment by huzaifaiftikhar** [comment]
@SatyamBansal are you working on this issue?

**Comment by SatyamBansal** [comment]
no i m not right now , u can have it

**Comment by huzaifaiftikhar** [comment]
Okay @SatyamBansal .
I am working on this issue.

**Comment by huzaifaiftikhar** [comment]
@teolemon I have fixed this issue. Please merge.
