### ISSUE TITLE
Persistent dismissal of image upload message

### ISSUE THREAD

**Issue by Karljoones** [openfoodfacts/openfoodfacts-androidapp#805]
**Summary:** 

The message that informs the user that only one image is necessary for an upload should not be displayed once the user dismisses this. You can check out the message that was added in #789. The message should always appear, but once dismissed by the user, this should be stored in prefs and never shown again.

**Expected behavior:** 

This should always display unless dismissed by the user. Once dismissed by the user, it should never show again.

**Comment by Shubham2320** [comment]
I am working on it.
