### ISSUE TITLE
Share app feature in the app

### ISSUE THREAD

**Issue by doomers** [openfoodfacts/openfoodfacts-androidapp#807]
**Summary:** 

currently if user want to share the app with other users, there is no feature available, but we can that feature in navigation bar as shown in the screenshot.

this will ease users to share the app with other users on whatsapp, facebook, text, etc with just one click.

![openfood-2](https://user-images.githubusercontent.com/11586392/36378194-de2527f4-159f-11e8-8fc2-b2bdcc7c8ec1.jpeg)

**Comment by doomers** [comment]
should i send PR for this?

**Comment by teolemon** [comment]
An interesting idea. A couple of remarks though:
- it needs to take into account the fact that it is distributed both on the Play Store, F-Droid, and it will be distributed on Chinese App store (and some people as a result don't have the Play Store)
- Some people will be annoyed by the button, so it should be dismissable.

Perhaps we could put it in the settings section ?

**Comment by doomers** [comment]
thanks for the useful remarks,
- firstly,  i don't people will be annoyed by this because of the fact it is the in the last of navigation drawer, only users who want to share the app will navigate that far.

- also putting it in settings will almost hide it, instead what i think is on clicking the share app button in the navigation drawer we will open a menu consisting playstore, F-droid and also the chinese store user can share whatever the link he/she wants to share

in my opinion this is better alternative, what say?

**Comment by doomers** [comment]
should i do it @teolemon?

**Comment by Karljoones** [comment]
I think based on what @teolemon is saying, the only way to effectively doing this would be to lead the user to a webpage where they would be able to choose from a list where they would like to download the app from as there are so many different channels that they can download from.

**Comment by huzaifaiftikhar** [comment]
We could have an option in settings to hide the share option from the navgation drawer. As pointed out by @teolemon that it might annoy some users. In this way users who don't like it would hide the share option from setting.

**Comment by Karljoones** [comment]
I think he means just hide the whole lot in the settings and not have anything in the navigation drawer for this feature. It's not a feature that a lot of people will use so it does not need to be seen at all times. But hopefully people will see it in settings and be like "OH! Let me share this"

**Comment by Karljoones** [comment]
You might want to check out this link [here](https://stackoverflow.com/questions/3178043/is-there-a-way-to-detect-if-app-was-installed-with-market-or-not) as it gives a bit of information regarding detecting where the user has installed the app from.

**Comment by doomers** [comment]
from what i have understood @teolemon @Karljoones , we want to add share button but it should be disabled from the settings, upon settings user can enable that if they need, in this case users who don;t want to use the button willn't get annoyed by the share button, am i right?

**Comment by Karljoones** [comment]
@doomers No, I think there might be some confusion. If this feature is to be implemented, no item will be going into the navigation drawer. There would only be a share option in the settings. There would be no reason to allow users to enable and disable this feature.

**Comment by doomers** [comment]
@Karljoones  thanks for making this clear.

**Comment by samagra14** [comment]
@Karljoones @doomers What's the progress on this? Are you still working on this?

**Comment by doomers** [comment]
there is still no confirmation that this should be implemented as of now or later

**Comment by teolemon** [comment]
We now have a magic link that works cross platform:
https://fr.openfoodfacts.org/application-mobile-open-food-facts

**Comment by KarthikRIyer** [comment]
@teolemon can this be added now?

**Comment by teolemon** [comment]
Yes, it could.
