### ISSUE TITLE
Project is not getting build due to Invalid resource directory name.

### ISSUE THREAD

**Issue by Shubham2320** [openfoodfacts/openfoodfacts-androidapp#809]
**Summary:** 

The project contains invalid resource directory name due to which project is not getting build.

Path : _openfoodfacts-androidapp\app\src\main\res\values-sr-rME__
 and _openfoodfacts-androidapp\app\src\main\res\values-sr-r__

**Comment by teolemon** [comment]
oh thanks. I broke the build, sorry. I'm going to fix that

**Comment by Shubham2320** [comment]
Welcome :)

**Comment by Shubham2320** [comment]
If it is resolved can I close this issue?

**Comment by teolemon** [comment]
yup
