### ISSUE TITLE
Remove "Store" from input fields, add "Brands"

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/OpenFoodFacts-androidApp#81]
The "Store" field is not very important, we should prioritize which input field we display:
- Product name
- Brands
- Quantity
- ...

**Comment by teolemon** [comment]
@herau @itchix Brand is more important than the store (for the web version) so we need it more than the Store

**Comment by herau** [comment]
Ideally the user should be able to fill any fields of a product... without any limitations regarding the web version. Maybe we have to find a UI to expose all the possibilities

**Comment by teolemon** [comment]
The pencil button plays a temporary solution. If it could load in a Chrome View instead of Chrome, that would improve usability until a better native solution is ready.

**Comment by herau** [comment]
d0650ddb3b2a772d6a4075749b37e5d7ce5e102b
