### ISSUE TITLE
Add Intro Screens 

### ISSUE THREAD

**Issue by Arshilgenius** [openfoodfacts/openfoodfacts-androidapp#813]
**Summary:** 

Currently when a user opens the app for the first time their is no intro screens about what are the main features of the app or how should the user proceed in the app.

**Steps to reproduce:** 

Open the App for the first time.

**Observed behavior:** 

Adding intro screens in the android app will make it more appealing to new users.

**Screen-shots:** 

<img src=https://user-images.githubusercontent.com/21264401/36390956-8a7bf116-15ca-11e8-9afb-345d4cf73a26.jpeg width="300" height="500">

This is the intro screen of one of the apps made by me and adding screens like this will make the app more appealing to new users.

I would like to work on this feature.

**Comment by teolemon** [comment]
We need to design carefully what messages we want to send, and what pictures we use.
We need to design it for Open Food Facts, Open Beauty Facts, and Open Pet Food Facts.
== Open Food Facts ==

Scan icon (xlarge)
"Contribute to Food transparency"
"Scan products, take them in picture, make food transparency happen"

Image of the Nutriscore from A to E, if possibly animated(xlarge)
"Get the Nutriscore"
"A synthetic view of the nutritional properties of your favorite food products"

Lightbulb icon(xlarge)
"Get the facts"
"Extensive information about the product you've scanned, deciphered for you."

Airplane icon (as seen in the Offline edit menu)(xlarge)
"Works offline"
"You can add new products, even if you don't have an Internet connexion right now"

== Open Beauty Facts ==

Scan icon (xlarge)
"Contribute to Cosmetic transparency"
"Scan products, take them in picture, make cosmetic transparency happen"

Lightbulb icon(xlarge)
"Get the facts"
"Extensive information about the product you've scanned, deciphered for you"

History icon (xlarge)
"Keep track of the product you use"
"All the cosmetic you use, in one handy list you can export"

Airplane icon (as seen in the Offline edit menu)(xlarge)
"Works offline"
"You can add new products, even if you don't have an Internet connexion right now"


== Open Pet Food Facts ==

Scan icon (xlarge)
"Contribute to Cosmetic transparency"
"Scan products, take them in picture, make pet food transparency happen"

Lightbulb icon(xlarge)
"Get the facts"
"Extensive information about the product you've scanned, decyphered for you"

History icon (xlarge)
"Keep track of the product you use"
"All the cosmetic you use, in one handy list you can export"

Airplane icon (as seen in the Offline edit menu)(xlarge)
"Works offline"
"You can add new products, even if you don't have an Internet connexion right now"

**Comment by teolemon** [comment]
We use the Android flavor system 
https://developer.android.com/studio/build/build-variants.html

As a result, you can have different strings based on the flavor. See for instance the text on the home screen.

**Comment by huzaifaiftikhar** [comment]
@Arshilgenius Those are just the flavors of the same app. You can change the build variant from studio to get the other versions. There is no seperate repo for that. I hope this helps :smile:
