### ISSUE TITLE
show notification upon downloading history

### ISSUE THREAD

**Issue by doomers** [openfoodfacts/openfoodfacts-androidapp#814]
**Summary:** 

as of now upon downloading history, the app is not notifying user where we are storing the .csv file,
so we should follow the standard and best approach which almost all apps are following, we should create a notification after downloading of csv file, and the user can open the file directly by clicking that notification.

**Comment by teolemon** [comment]
Yup, +1
And also add the option to share it, within the notification

**Comment by doomers** [comment]
sure, i am working on it.

**Comment by policorn** [comment]
Hi @doomers, I saw you deleted the PR; are you going to continue working on it?

**Comment by doomers** [comment]
i am working on it, actually, i messed up something accidentally,  i will send the PR tomorrow.
