### ISSUE TITLE
show/hide the password in edittext field.

### ISSUE THREAD

**Issue by Arshilgenius** [openfoodfacts/openfoodfacts-androidapp#816]
**Summary:** 

Currently in login activity there is no option to unhide/unmask the password if the user want's to check whether he has typed the password correctly or not. This feature although very basic is very useful to the users.

**Steps to reproduce:** 

Go to the sign in section of the app.

**Expected behavior:** 

This is small but useful feature for the users.

<img src=https://user-images.githubusercontent.com/21264401/36392453-39b9663a-15d1-11e8-878e-e9ad9c675bce.jpeg width="400" height="80">

**Observed behavior:** 

No option for the user to see the password behind the asterix.

<img src=https://user-images.githubusercontent.com/21264401/36392472-58336070-15d1-11e8-9949-4edad3e584c9.jpeg width="300" height="500">

I would like to work on this issue.

**Comment by teolemon** [comment]
go ahead, useful one
