### ISSUE TITLE
Loading toast in login screen is not properly placed. 

### ISSUE THREAD

**Issue by Arshilgenius** [openfoodfacts/openfoodfacts-androidapp#817]
**Summary:** 

When a user sign's in the app, the Loading toast appears to be half outside the screen rather it should be below in the bottom middle of the screen.

**Steps to reproduce:** 

Login in the app

**Expected behavior:** 

The Loading toast should not be half outside the screen and rather it should be in the bottom middle of the screen

**Observed behavior:** 

<img src=https://user-images.githubusercontent.com/21264401/36393011-d07f15c2-15d3-11e8-88ea-dc8e97476626.jpeg width="300" height="500">

I Would like to work on this issue

**Comment by huzaifaiftikhar** [comment]
You can also take a look at #430

**Comment by Arshilgenius** [comment]
@huzaifaiftikhar  is someone working on that ?

**Comment by Karljoones** [comment]
Thanks for logging this but this is already being worked on in #739 :) I am going to close this issue for the time being!

**Comment by huzaifaiftikhar** [comment]
@Arshilgenius You can post a comment there and ask if anyone is working on it or not.
