### ISSUE TITLE
Missing photo and barcode for Products in the Offline edit view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#827]
![image](https://user-images.githubusercontent.com/1689815/36430195-db4c5254-1654-11e8-8041-3e0f91e9aa59.png)
When clicking on it: 
![image](https://user-images.githubusercontent.com/1689815/36430213-e46fc136-1654-11e8-904b-16751863755c.png)

We should see the barcode, and the picture I took. Both are missing.

**Comment by AbsolutelySaurabh** [comment]
I am working on this issue.

**Comment by l-o-b-s-t-e-r** [comment]
#892

**Comment by policorn** [comment]
Hi @AbsolutelySaurabh; this has been fixed by #892
