### ISSUE TITLE
Upload toast is hiding the "Upload All" button

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#830]
![image](https://user-images.githubusercontent.com/1689815/36430543-ab5d79aa-1655-11e8-8a7f-c5047ecbb4e8.png)

**Comment by Siddharth-Singhs** [comment]
I want to work on it

**Comment by Siddharth-Singhs** [comment]
@teolemon can I work on it

**Comment by teolemon** [comment]
you can go ahead :)

**Comment by Karljoones** [comment]
@Siddharth-Singhs I noticed that you closed the PR for this, how is this issue coming along? Are you still working on it?

**Comment by Siddharth-Singhs** [comment]
@Karljoones working on it.
Today I will send new PR

**Comment by Karljoones** [comment]
Perfect, thanks @Siddharth-Singhs :)

**Comment by shivanshsoni** [comment]
@Siddharth-Singhs Are you still working on this issue??

**Comment by sachincool** [comment]
@Siddharth-Singhs this was an Easy Task.  how's the progress?

**Comment by shivanshsoni** [comment]
@Siddharth-Singhs If you are not working on this then, I already had done changes and I will be happy to reopen my closed PR for this :-) Please reply.
