### ISSUE TITLE
Invisible camera icon in the Product addition form

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#832]
Invisible camera icon in the Product addition form
I've tweaked the colors so it is visible. It probably shouldn't be here ?
![image](https://user-images.githubusercontent.com/1689815/36435286-8e589162-1661-11e8-8a3e-37c699abee41.png)

**Comment by AbsolutelySaurabh** [comment]
@teolemon , I would like to work on this issue please.

**Comment by teolemon** [comment]
you can go ahead :)

**Comment by huzaifaiftikhar** [comment]
@teolemon I have fixed this. Please merge.

**Comment by teolemon** [comment]
Merged, thanks @huzaifaiftikhar
