### ISSUE TITLE
Wrong title in various Activities

### ISSUE THREAD

**Issue by Arshilgenius** [openfoodfacts/openfoodfacts-androidapp#839]
**Summary:** 

Currently in various screens like History,Sign in etc the name  of the app in the title instead of 
the name of that particular activity is shown.

**Steps to reproduce:** 

Go to history,sign in activity

**Expected behavior:** 

Name of that particular Activity should be shown.

**Screen-shots:** 

<img src=https://user-images.githubusercontent.com/21264401/36438472-0d739ce8-1690-11e8-9d80-f7c548428c2f.jpeg width="300" height="500">

Yes i would like to work on this issue.

**Comment by teolemon** [comment]
Go ahead.
