### ISSUE TITLE
Replace the share icon by the Nutriscore on the History view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#840]
Replace the share icon by the Nutriscore on the History view. People will be still able to share the product from the detailed product view.
Quick Mockup
![image](https://user-images.githubusercontent.com/1689815/36439030-ebaca88a-166b-11e8-8ff3-2330eb02f5db.png)

**Comment by Siddharth-Singhs** [comment]
@teolemon can I work on it

**Comment by teolemon** [comment]
Yes. The Nutriscore is shown on the summary page (if you need to see how to fetch it)
