### ISSUE TITLE
Dialog box buttons are not appropriately placed.

### ISSUE THREAD

**Issue by Arshilgenius** [openfoodfacts/openfoodfacts-androidapp#845]
**Summary:** 

The dialog box buttons like Create Account, Cancel,Login etc are not appropriately arranged. They should be horizontal not vertical.
 
**Steps to reproduce:** 

Go to the contribution activity in the app.

**Expected behavior:** 

The buttons should be horizontly placed instead they are arranged in vertical order.

**Observed behavior:** 

Vertical placement of buttons.

**Screen-shots:** 

<img src=https://user-images.githubusercontent.com/21264401/36463481-3c7b1e0c-16f0-11e8-94bb-6fd5f2e5b568.jpeg width="300" height="500">

Yes i would like to contribute to this issue.

**Comment by sowmya9029** [comment]
I think this issue is fixed. I can see the dialog with buttons aligned horizontally.

**Comment by Karljoones** [comment]
There seems to be too many buttons on the dialog with too long strings. This would occur on some devices, this is the expected behaviour of the dialog. Maybe we can remove the cancel button? Tapping outside of this dialog should allow for dismissal anyway is `isCancelleable()` is set.

**Comment by Arshilgenius** [comment]
@Karljoones okay i'll remove the cancel button as it is not needed.

**Comment by Karljoones** [comment]
That is just my opinion, might be best to let someone else voice their opinion on this first :)

**Comment by Arshilgenius** [comment]
Sure. :)

**Comment by Karljoones** [comment]
@teolemon can we get your opinion on removing the cancel button? I agree that it looks messy when the buttons are too long and bunch up like the image.

**Comment by teolemon** [comment]
mmh, okay for removing cancel I guess.
Hopefully, less experienced user won't be confused.
