### ISSUE TITLE
App name texts are incorrect

### ISSUE THREAD

**Issue by ArmenApresyan8** [openfoodfacts/openfoodfacts-androidapp#848]
**Summary:** 

App name and splash screen image are incorrect

**Expected behavior:**

Shouldn't the app name be Open Food Facts?

**Screen-shots:** 

![screenshot_20180221-165509](https://user-images.githubusercontent.com/18738136/36481126-449e2628-1728-11e8-9fde-539349b80008.png)

**Comment by teolemon** [comment]
We use the Android flavor system to create Open Food Facts, Open Beauty Facts and Open Pet Food Facts out of the same code base. Just select offdebug to get the right version.

**Comment by ArmenApresyan8** [comment]
What do I select?

**Comment by ArmenApresyan8** [comment]
Ok, I got it thanks!
