### ISSUE TITLE
Getting rid of this dirty hack (tag.replaceAll("(en:|fr:)", "")) for language management

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#852]
Getting rid of this dirty hack

```  String tagWithoutLocale = tag.replaceAll("(en:|fr:)", "").toUpperCase(Locale.getDefault());```
We have many more locales, beyond en: and fr:

**Comment by iml-v** [comment]
@teolemon  i will correct  this ,should i go ahead ?

**Comment by samagra14** [comment]
I was just gonna open an issue for that :sweat_smile: . Thanks.

**Comment by teolemon** [comment]
How would you both go about solving it ? That's a very good opportunity to delve into the language subtleties of the API :)

**Comment by iml-v** [comment]
@samagra14  wanted to work on this issue before me ,so i will go with other issues at the same time @teolemon  :)

**Comment by iml-v** [comment]
@samagra14 confirm if you will work on this  or should i work ?

**Comment by samagra14** [comment]
I am working on this.

**Comment by Karljoones** [comment]
@samagra14 are you still working on this?

**Comment by VaiTon** [comment]
I think we can close this @teolemon.
