### ISSUE TITLE
Infinite loading in splash screen

### ISSUE THREAD

**Issue by ArmenApresyan8** [openfoodfacts/openfoodfacts-androidapp#853]
**Summary:** 

The app doesn't open when the Wi-Fi is on, but when I open the app without the Wi-Fi on, and then turning it on, it doesn't work either.

**Steps to reproduce:** 

Just open the app

**Device and Android version:** 

Samsung Galaxy S6 edge
Android 7.0 (touchwiz)

**Screen-shots:** 

![screenshot_20180221-204758](https://user-images.githubusercontent.com/18738136/36493315-b80de60a-1748-11e8-8504-397c72330a8a.png)

![screenshot_20180221-205430](https://user-images.githubusercontent.com/18738136/36493650-884fe20a-1749-11e8-8cea-06a7c0c7b6f0.png)

**Comment by sachincool** [comment]
Duplicate Issue #793  @teolemon

**Comment by ArmenApresyan8** [comment]
Is there a working solution for this?

**Comment by sachincool** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/858 Here's an ongoing PR for this issue

**Comment by Karljoones** [comment]
Before closing this issue, I would like clarification that this is the same issue. Leave this open for now, but I would like this issue tested again once #858 is merged, to see if this resolves the issue.

**Comment by sachincool** [comment]
@Karljoones https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/858 Merged You can confirm and close this one now.
