### ISSUE TITLE
Invalide Resource Directory Name

### ISSUE THREAD

**Issue by Siddharth-Singhs** [openfoodfacts/openfoodfacts-androidapp#857]
**Summary:** 

After Updating the Fork there is error while building the gradle.
Thats why travis CI is not passing.

**Screen-shots:** 

<img width="271" alt="screen shot 2018-02-21 at 11 21 13 pm" src="https://user-images.githubusercontent.com/31280485/36496432-3dcb28ec-175e-11e8-99af-e95bb423d6e8.png">
<img width="962" alt="screen shot 2018-02-21 at 11 20 57 pm" src="https://user-images.githubusercontent.com/31280485/36496437-40630584-175e-11e8-981e-432b29b0981b.png">

**Comment by Siddharth-Singhs** [comment]
@teolemon Please Resolve this

**Comment by huzaifaiftikhar** [comment]
@Siddharth-Singhs This is resolved. Just update again. 
@teolemon This can be closed.

**Comment by Siddharth-Singhs** [comment]
Okay Thanks
