### ISSUE TITLE
Remove "no data" toast from offline edit fragment

### ISSUE THREAD

**Issue by Karljoones** [openfoodfacts/openfoodfacts-androidapp#864]
**Avoid reporting a duplicate**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issue tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating reporting a issue.
   - Also before reporting please ensure that you have tested it with the latest (dev) version of the software.

**Summary:** 

When opening the offline edit fragment in the app, if there is no entries there, then there is a toast displayed with "no data". This should be removed in replace of a view being added into the center of the page. This view should tell the user that there are no offline products.

**Steps to reproduce:** 

Open the "offline edit" fragment.

**Expected behavior:** 

The app should inform the user that there are no products to display. However, there should be a view there instead of a toast, this view should always be visible when the user is in the fragment and there is no information to display.

**Observed behavior:** 

A toast is displayed.

**Device and Android version:** 

OnePlus 5T Android 8

**Comment by ArmenApresyan8** [comment]
I would like to work on it

**Comment by Karljoones** [comment]
You're more than welcome to! Thanks for picking it up!

**Comment by shushilkumarr** [comment]
![image](https://user-images.githubusercontent.com/22811731/36582270-d445d13a-1896-11e8-8596-538aa933c464.png)

Are you expecting something like this? @Karljoones

**Comment by ArmenApresyan8** [comment]
I still have yo wait for #858 to be merged to work on this, as I can't debug the app with by phone. If anyone else wants to work on this, please go ahead.

**Comment by shushilkumarr** [comment]
can i work on it?

**Comment by shushilkumarr** [comment]
Is this good enough?
![offline frag](https://user-images.githubusercontent.com/22811731/36593368-696a7d2e-18bf-11e8-9a1e-80efbf41760a.jpeg | width=100)

**Comment by Karljoones** [comment]
@shushilkumarr something similar but more "open food fact-y" if that makes sense! Try recreate the same view that should be displayed if there are no products returned in a result to ensure that all is consistent. 

This should be a good thing, so include a positive message along the lines of "All done!" or similar. 

Does that make sense?

**Comment by teolemon** [comment]
Also, it should not be sad. There are no products potentially because the user was able to send it with the online mode.
So it should convey something like: "The products you add to Open Food Facts while offline will appear here."

**Comment by shushilkumarr** [comment]
![pr pic](https://user-images.githubusercontent.com/22811731/36628825-d0f13294-1973-11e8-87b0-3f65b229285d.jpeg)

How about this layout?

**Comment by Karljoones** [comment]
@shushilkumarr Right idea, wrong implementation. The icon is too large and pixelated. This of the unread thread in Slack, a postive message and a small icon. 

![image](https://user-images.githubusercontent.com/5596450/36629554-05aa7baa-194f-11e8-8b13-4e3249cde2e8.png)

Think along the lines of material design, check out this [icon](https://material.io/icons/#ic_done_all) for inspiration.

**Comment by shushilkumarr** [comment]
Just to be clear, Do you want me to change the icon or can I use it after resizing?

**Comment by huzaifaiftikhar** [comment]
Use vectors wherever possible they are scalable and won't get pixelated :)

**Comment by Karljoones** [comment]
@shushilkumarr in my opinion, it should be something simpler, the icon that you used just seems to have a lot going on in it and does not suit material design :)

**Comment by shushilkumarr** [comment]
![updated_layout](https://user-images.githubusercontent.com/22811731/36631485-b6781b32-199e-11e8-926c-60860d754b6d.jpeg)

How about this one?

**Comment by teolemon** [comment]
- When designing user interfaces, avoid exclamation marks. 
- "All your contributions have been sent." would be a nice wording.
- Keep everything the same color (gray), like in your first mockup. In material design, gray is used for empty screens.

**Comment by shushilkumarr** [comment]
![updated_layout](https://user-images.githubusercontent.com/22811731/36632089-dffe9f36-19a7-11e8-997d-1764c1113b5a.jpeg)

Is this ok?

**Comment by teolemon** [comment]
Yes :-)
The icon is not 100% material, but it's looking good anyway :)

**Comment by teolemon** [comment]
You need to take into account two cases:
- When your contributions have been sent ("All your contributions have been sent.")
- Before first use of the feature ("Your offline contributions will appear here.")
So you need to store the fact that the user has used the feature once

**Comment by shushilkumarr** [comment]
Do you want me to keep the same image for "first use" too or different images are fine?

**Comment by sachincool** [comment]
@shushilkumarr I think different images 
I found this awsome image ![](https://image.freepik.com/free-icon/food-donation_318-114267.jpg)

[Here](https://www.freepik.com/free-icon/food-donation_871841.htm#term=gestures&page=5&position=9)

You can put an ImageView there and we can Swap Src in java based on first use or "upload done"  :+1:

**Comment by shushilkumarr** [comment]
![screenshot_20180301-201337](https://user-images.githubusercontent.com/22811731/36936648-044472cc-1f2e-11e8-8986-aa5fb2889096.jpg)
I have used "ic_cloud_off" image for the "first use" fragment. The Boolean value is stored in sharedpreferences file with key "firstupload" and is updated to true when "upload all" button is clicked for the first time. Is this logic and layout ok?
