### ISSUE TITLE
Let people share images with barcodes to Open Food Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#868]
Sometimes people don't have the time to open the app and properly scan a product. Instead, they take  2 or 3 photos of the product, including one with the barcode. Let the people add those pictures to Open Food Facts, and then open a wizard to help them add those pictures to an existing product or create  a new product, based on the case.

If the user only selects one image, it should ensure he has no more additional pictures he can share

![image](https://user-images.githubusercontent.com/1689815/36557401-6f75311c-1808-11e8-9e75-21c2894c7fb7.png)

**Comment by sowmya9029** [comment]
Can you please explain it more about what is the exact expectation ?I have added the OFF application in the sharing option. I'm not sure how the flow of the application should be. 
Which screen should be launched after selecting open food facts app  from the option? 
 
![1](https://user-images.githubusercontent.com/11407233/36617845-e7184b88-189d-11e8-95cc-62e38e0863ee.png)

**Comment by teolemon** [comment]
![](https://i.imgur.com/rH80zMX.jpg)

**Comment by sowmya9029** [comment]
I am working on this implementation. This is what I have done till now. Please let me know if this looks ok  
![device-2018-03-04-143646](https://user-images.githubusercontent.com/11407233/36951764-0cf1f578-1fbc-11e8-9aa5-15be94dc8df9.png)
![device-2018-03-04-143812](https://user-images.githubusercontent.com/11407233/36951765-0d0985d0-1fbc-11e8-9754-b51071896816.png)

**Comment by sowmya9029** [comment]
I have finished adding this feature  but not sure if i am totally correct.I am still confused on some parts.
I have few question here
1)if the user selects multiple images with bar code then which one should we consider? - currently I'm assuming the images will have only one with barcode.
2)should we consider those images as "OTHER" images for the product ? - currently I'm uploading the images to product image OTHER instead for front,ingredent,nutrition(as we cannot find out which are those respective images ).
3)In case of offline I am navigating to SaveProductOfflineActivity .Am I correct ? Is this as per expectation?

**Comment by teolemon** [comment]
- Add the picture above "Please type the barcode below:" (for people who shared an illegible barcode picture the human eye can decipher)
- Correcting from "please type bar code below" to: "Please type the barcode below:"

1) Try to find a barcode in all of them, starting from the first one, and assign the first found barcode to the product. Ideally create a separate product if a second barcode is found, or drop all following pictures (as they probably belong to a second product)
2) OTHER is a very good option. We could add a visual interface to assign either to "Front, ingredient, nutrition, or other", but we risk unselecting existing images, so you can leave it as OTHER for the first iteration of the feature.
3) Perfect :)

**Comment by sowmya9029** [comment]
@teolemon  Thankyou your response. I have completed the changes and trying to do PR but unable to because  when I checkout the master, I'm getting missing file error.
"import openfoodfacts.github.scrachx.openfood.models.ToUploadProductDao" .Can you please help in resolving this.
