### ISSUE TITLE
automatic update for FDroid

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#87]
@krt16s @LuccoJ Is it possible to set an automatic update for FDroid ?

**Comment by krt16s** [comment]
Actually its already set up. The tag is just 23hrs old, so let's just wait a day for fdroid to pick it up. It did so on my local box.

**Comment by teolemon** [comment]
Ok. closing then.

**Comment by LuccoJ** [comment]
I received an update a couple of days ago, so it looks like it's working.
