### ISSUE TITLE
Keep the products in the history in cache

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#875]
The products in the history are reloaded each time. They should be cached on the phone.

**Comment by PrajwalM2212** [comment]
I will work on this .

**Comment by teolemon** [comment]
It's part of the GSOC proposals >> https://en.wiki.openfoodfacts.org/Student_projects/GSOC/Proposals#Offline_mode

**Comment by PrajwalM2212** [comment]
Shall this issue be left for GSoC or should I work on it ?

**Comment by teolemon** [comment]
Let's focus on other more urgent issues right now, like using the lite API, or correcting the bugs filed yesterday
