### ISSUE TITLE
Add optional label images in Product View

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#876]
Enable the user to optionally display label images in Product View:
https://static.openfoodfacts.org/data/taxonomies/labels.json
```
en:assured-food-standards":{"image":{"en":"assured-food-standards.82x90.svg"},"wikidata":{"en":"Q4810404"},"name":{"ca":"Assured Food Standards","en":"Assured Food Standards","fi":"Assured food standards","ru":"Гарантированный пищевой стандарт"}}
```
https://static.openfoodfacts.org/images/lang/en/labels/assured-food-standards.82x90.svg

**Comment by sashank27** [comment]
@teolemon I would like to work on this. Could you please elaborate more on the issue?

**Comment by PrajwalM2212** [comment]
Working on it .

**Comment by PrajwalM2212** [comment]
@teolemon How do you want this to be implemented ?
Should it be like the EMB codes , which opens in a chrome custom tab ?

**Comment by PrajwalM2212** [comment]
Can i implement a new tab for this ?

**Comment by PrajwalM2212** [comment]
@teolemon  How should this be implemented ? Should label images be displayed in recycler view ?
What should be done when there are no label images ?
