### ISSUE TITLE
Additives are always displayed in English while we have translations

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#877]
https://world.openfoodfacts.org/api/v0/product/737628064502.json

https://world-fr.openfoodfacts.org/additives.json
https://world-ru.openfoodfacts.org/additives.json
https://world.openfoodfacts.org/additives.json

![image](https://user-images.githubusercontent.com/1689815/36606150-1d6db662-18c3-11e8-8447-8b92dfd3c13d.png)

**Comment by Shubham2320** [comment]
Can I work on it?

**Comment by Karljoones** [comment]
Of course @Shubham2320, all yours :)

**Comment by Shubham2320** [comment]
Thank you :)

**Comment by teolemon** [comment]
We have actually dozens of translations, so it might be more scalable to concatenate the locale ?
