### ISSUE TITLE
Replacing anonymous classes with lambdas.

### ISSUE THREAD

**Issue by samagra14** [openfoodfacts/openfoodfacts-androidapp#881]
With the addition of JAVA 8, it is advised to use lambdas over anonymous classes for implementation of functional interfaces.

**Steps to reproduce:** 

NA

**Add system logs:**

NA

**Expected behaviour:** 

It is better if lambdas are more frequently used. Major benefit being runtime invocation of lambdas leading to smaller APk (avoids compile-time creation of anonymous .class files).

**Observed behaviour:** 

Instead of using anonymous classes it is better to switch to lambdas for implementing functional interfaces.

**Device and Android version:** 
NA
**Screenshots:** 

NA

###### Are you interested to work on this issue?
Yes

**Comment by Karljoones** [comment]
@samagra14 do you have any examples of where you would use this?

**Comment by samagra14** [comment]
@Karljoones the best example is the implementation of various Callbacks. Currently, we are doing this
````java
someObject.onPositive(new MaterialDialog.SingleButtonCallback() {
            @Override
            public void onClick(MaterialDialog dialog, DialogAction which) {
                logout();
            }
        })
        .onNegative(new MaterialDialog.SingleButtonCallback() {
            @Override
            public void onClick(MaterialDialog dialog, DialogAction which) {
                Toast.makeText(getApplicationContext(),"Cancelled",
                        Toast.LENGTH_SHORT).show();
            }
        }).show();
````
However this can be replaced by the code below
````java
someObject.onPositive((dialog, which) -> logout())
        .onNegative((dialog, which) -> Toast.makeText(getApplicationContext(),"Cancelled",
                Toast.LENGTH_SHORT).show()).show();
                            break;
                        default:
                            break;}
````
**Short + Simple + Lower size **

**Comment by Karljoones** [comment]
I think that we should wait a little before jumping the gun on this, I would like to wait to see other peoples opinions. We are trying to close off older issues at the moment rather than starting to refactor the app.

**Comment by samagra14** [comment]
Yeah sure :sweat_smile:

**Comment by Arshilgenius** [comment]
@Karljoones  I think we should focus on adding new features and solving existing bugs and after that we can move to refractoring. That's my opinion let hear from other people.

**Comment by sbeitzel** [comment]
IntelliJ IDEA offers a code intention to suggest replacing anonymous classes with lambdas. I'd be willing to bet that your development environment can handle most of this work.
