### ISSUE TITLE
Image Upload Fails on nougat 

### ISSUE THREAD

**Issue by sachincool** [openfoodfacts/openfoodfacts-androidapp#888]
**Summary:** 
Image upload  fails on nougat

**Steps to reproduce:** 
* scan a product 
* Put details 
* the content you put is sent succesfully and uploaded on server, but image  upload  fails and a Toast message appears 
* try uploading again by going through history.

**Expected behavior:** 
Image upload is  successful 

**Device and Android version:** 
 Nougat 7.0

**Comment by sachincool** [comment]
#858

**Comment by waadalkatheri** [comment]
Can I work on this?

**Comment by sachincool** [comment]
Yes, Go Ahead @waadalkatheri

**Comment by sachincool** [comment]
@waadalkatheri any updates?

**Comment by Karljoones** [comment]
@sachincool @waadalkatheri does this issue still occur? If so, are either of you working on it?

**Comment by sachincool** [comment]
@Karljoones I haven't tested it recently. you can take it.

**Comment by Karljoones** [comment]
I'm going to close this for now, to be reopened if someone else comes across the issue
