### ISSUE TITLE
Product not found toast in search should be removed

### ISSUE THREAD

**Issue by Karljoones** [openfoodfacts/openfoodfacts-androidapp#890]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting a issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 

The toast should be removed from the search fragment when there are no search results found, there is already a view to inform the user of this. Just a little step for clearing up old features.

**Steps to reproduce:** 

Search a product not in the database

**Expected behavior:** 

Just show the view on the fragment rather than the toast

**Observed behavior:** 

Toast and view are observed.

**Device and Android version:** 

OP5T - Android 8 

**Screenshots:** 

![screenshot_20180224-111139](https://user-images.githubusercontent.com/5596450/36629832-daa7f93c-1953-11e8-8f26-4648e6d3d0cc.jpg)

**Comment by waadalkatheri** [comment]
Can I work on this?
