### ISSUE TITLE
cancel button in camera selection mode of Scanning with barcode pausing the camera

### ISSUE THREAD

**Issue by shivanshsoni** [openfoodfacts/openfoodfacts-androidapp#898]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting a issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 

ON pressing cancel button in camera selection mode (i.e rear of front) in scanning with barcode option pauses the camera instead of taking back to it's previous state as no change is selected.
**Steps to reproduce:** 

By clicking cancel option in camera selection mode of scanning with barcode in slide bar menu.

**Expected behavior:** 

Going back to same state of camera as no change is selected.

**Observed behavior:** 

It pauses the camera

**Device and Android version:** 

Redmi Note 4 having android 7.0 (nougat)

**Comment by l-o-b-s-t-e-r** [comment]
already fixed #883

**Comment by shivanshsoni** [comment]
OK
