### ISSUE TITLE
Crash when entering offline edition mode

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/OpenFoodFacts-androidApp#90]
Hi, first of all, this is the first time I participate in reporting issues in this project, so thank you for this app :)

There is the issue : the app instantly crashes when I enter the offline edition mode. Since a few weeks I have the app, each time I tried, I encountered this problem, but it doesn't seem reported yet. 

It only says (in french) "Open Food s'est arrêté" (Open Food stopped working) with a button to send a report, what I did a few times. For information I have Android 5.0.2 on a HTC One (M7).

Thanks.

**Comment by itchix** [comment]
I saw your report, I'm on it =)

**Comment by asmoth360** [comment]
Thanks for your quick answer. Indeed, I cleared the cache, I even reinstalled the app just to be sure, and after a very long loading screen, I was able to enter the offline edit mode :) 
Do you know why this was not working because of the data? I'm curious.

**Comment by itchix** [comment]
I think it's because I changed the "model" and the new version need data that the old version didn't need, that's why a Null Pointer Exception was thrown.

**Comment by asmoth360** [comment]
Ok, thanks for the info adn for fixing that.
