### ISSUE TITLE
Add a secret mode to use the .net server

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#900]
Add a secret mode to use the .net server instead or the .org server, so that we can easily test new features.

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
What do you mean by "secret mode"? Just add one more build varian with new HOST?

**Comment by teolemon** [comment]
Nope, because that would mean 6 flavors (3 current flavors *2). I was thinking of a hidden setting.
It is not a priority bug, anyway.

**Comment by policorn** [comment]
Hi @teolemon; what about using a local proxy (for development?)? Would it be feasible or we prefer an automated configuration integrated with Android Studio?
