### ISSUE TITLE
Use the new lite API in the Quick Scan mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#901]
https://world.openfoodfacts.org/api/v0/product/3700278400881.json?fields=product_name,categories_tags,ingredients_text,image_front_small_url,nutrition_grades_tags

Beware: ensure you pass all the fields necessary to the URL

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
How can I find this "Quick Scan mode"?

**Comment by teolemon** [comment]
You can activate it from the settings

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
We don't use such API to find product by barcode. We use api/v0/produit/{barcode}.json.

**Comment by teolemon** [comment]
Updated, thanks :)
