### ISSUE TITLE
Use the new lite API to delve into categories in the category browser

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#903]
https://world.openfoodfacts.org/category/pizzas.json?fields=product_name,categories_tags,ingredients_text,image_front_small_url,nutrition_grades_tags

Beware: ensure you pass all the fields necessary to the URL

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
If I'm not mistaken, there is no implementation to display products which are related to category, because category list is not even clickable. Also, API call for loading products by category isn't using.

Do we have to start implementing this?

**Comment by samagra14** [comment]
@l-o-b-s-t-e-r Yes I guess, there is an option to expand the list but it is not clickable. @teolemon please clarify what is expected to be done.

**Comment by teolemon** [comment]
I expect the app to open the category page when a category is clicked. Bonus points if you show the category natively.

**Comment by Shubham2320** [comment]
I would like to work on it.
