### ISSUE TITLE
Let the user choose the resolution of images he/she sends

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#904]
Newer cameras can produce images up to 20MB large.
Let the user choose the resolution of images he/she sends on mobile networks, with a minimum, to ensure the image is legible.

**Comment by shivanshsoni** [comment]
@teolemon I would like to work on this issue

**Comment by shivanshsoni** [comment]
Ya, I think it's a good idea. I would love to work on this.

**Comment by vaishali51** [comment]
I will like to work on it.
