### ISSUE TITLE
(Meta bug) Improve the allergen list

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/openfoodfacts-androidapp#91]
Currently, the allergens list used to set an alert is huge, and seems like a random list of almost all ingredients. It's not practical at all and suffers from a few issues, I have a few ideas that could be useful :
- sort the items alphabetically
- add a search field : the user enters a few letters, and the corresponding items appear in a list
- language : the list uses french items (at least for me), and once added, the allergens use english terms. Moreover the connexion between french and english terms is wrong : "Mozarella" is not "gluten", "Vin" isn't "mustard" etc...
- maybe only keep useful items, I'm not sure the hole list is relevant as it is huge
- performance improvements : currently on my phone the list takes 3-4 seconds to appear (may be related to previous point), even if displayed more than once in a row. The data is apparently stored locally, so I find this very slow.

Thanks for reading me and have a good day :)

**Comment by teolemon** [comment]
#158 (Alphabetical order)

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/OpenFoodFacts-androidApp/issues/333

**Comment by teolemon** [comment]
![screenshot_20161106-200504](https://cloud.githubusercontent.com/assets/1689815/21387414/d87681a8-c777-11e6-88d5-378b3b149705.png)

**Comment by Karljoones** [comment]
I'm going to close this as we now have the new system of handling allergens :)

**Comment by ross-holloway94** [comment]
@Karljoones I thought the new system was temporary whilst it wasn't working?

**Comment by ross-holloway94** [comment]
@teolemon What's going on regarding the above comments?
