### ISSUE TITLE
Large logo Size on home screen

### ISSUE THREAD

**Issue by shivanshsoni** [openfoodfacts/openfoodfacts-androidapp#912]
logo size on home screen is looking too big. So, it's size must be fixed.

Device Name: Redmi Note 4 (Android version 7.0(nougat))

Screnshot attached:
before
![whatsapp image 2018-02-25 at 18 03 00](https://user-images.githubusercontent.com/24546371/36641569-94529d70-1a57-11e8-88ef-daf875dcec52.jpeg)

after
![whatsapp image 2018-02-25 at 18 38 34 1](https://user-images.githubusercontent.com/24546371/36641779-9cba91d0-1a5b-11e8-9f99-465bf8d2fc14.jpeg)

**Comment by Karljoones** [comment]
Hi @shivanshsoni, please ensure that you upload screenshots with issue logging to make sure that people know exactly what you are referring to. If possible, please also include device information as the size of this icon may change depending on the device.

**Comment by shivanshsoni** [comment]
OK Sir, I updated the issue and Small logo os looking more good on big screen as redmi note 4 has 5.5 " screen

**Comment by Karljoones** [comment]
Thank you for updating it!
