### ISSUE TITLE
Search doesn't work when invoked from settings

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#920]
Search doesn't work when invoked from settings

**Comment by Arshilgenius** [comment]
@teolemon can you please elaborate? from where?

**Comment by teolemon** [comment]
![](https://i.imgur.com/6lUyLVd.png)

**Comment by Karljoones** [comment]
IMO: there should be no search button in the preferences anyway, people would assume that it is for searching the preferences

**Comment by Arshilgenius** [comment]
@teolemon it's working for me

**Comment by Arshilgenius** [comment]
@teolemon  @Karljoones shall i remove it?

**Comment by Karljoones** [comment]
This also apples for Allergen Alert where it should not be there as people may think that they are searching allergens and possibly offline edits where they may think that they are searching their own offline edits :)

**Comment by Arshilgenius** [comment]
@Karljoones True. :)
@teolemon Views?

**Comment by l-o-b-s-t-e-r** [comment]
@Karljoones more over, it also appears in "Offline edit" screen :)

**Comment by shivanshsoni** [comment]
@Karljoones @teolemon I would like to solve this issue

**Comment by Karljoones** [comment]
This has been removed, no? @teolemon can you confirm?

**Comment by huzaifaiftikhar** [comment]
Search has been removed from preferences (settings)
