### ISSUE TITLE
Offline product "save" button should be disabled while it saves 

### ISSUE THREAD

**Issue by Karljoones** [openfoodfacts/openfoodfacts-androidapp#924]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting a issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

Save button should be disabled to prevent duplicate savings

**Steps to reproduce:** 

Save a product and click save again

**Expected behavior:** 

Button should be disabled to prevent double clicking

**Observed behavior:** 

Saves duplicates because it is possible to press it twice.

**Comment by teolemon** [comment]
It still takes a while before there is any feedback that the product is being saved
