### ISSUE TITLE
Make the history layout more consistant with the search layout

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#925]
Current search: https://user-images.githubusercontent.com/1689815/36647480-913da272-1a86-11e8-8cdd-49973013ec46.png

Proposed history:
![image](https://user-images.githubusercontent.com/1689815/36647494-c90f9926-1a86-11e8-9485-c1e815020f63.png)

**Comment by Karljoones** [comment]
Related: #840

**Comment by Shubham2320** [comment]
Seems good. Can I work on it?

**Comment by l-o-b-s-t-e-r** [comment]
Looks like there is no progress here, so I've taken this issue.
