### ISSUE TITLE
Improve UI of History list item 

### ISSUE THREAD

**Issue by shivanshsoni** [openfoodfacts/openfoodfacts-androidapp#934]
Mobile phone Vivo Y28(screen size 4.7")

**How it is looking right now:**

![screenshot_2018-02-26-16-12-45](https://user-images.githubusercontent.com/24546371/36666552-0aa1594e-1b11-11e8-94b7-fa893835811b.png)

**Expected:**

![screenshot_2018-02-26-16-01-41](https://user-images.githubusercontent.com/24546371/36666609-30b377c0-1b11-11e8-8532-2f3182e984f6.png)

**Comment by shivanshsoni** [comment]
I think this is looking much better now.

**Comment by l-o-b-s-t-e-r** [comment]
@shivanshsoni This task is already in work #925

**Comment by shivanshsoni** [comment]
But it was already discussed[ here](https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/915)  It was solved already [here](https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/f13cba009ad4a1f6955d151a03f061b2feb0b2a15)

**Comment by shivanshsoni** [comment]
@l-o-b-s-t-e-r @teolemon It is looking more approachable as comapred to [this](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/925)

**Comment by Karljoones** [comment]
@l-o-b-s-t-e-r @shivanshsoni @Shubham2320 is working on creating the new history item layout, it looks messy at the moment but it might be best just to wait for him to complete that issue and make a pull request about it
