### ISSUE TITLE
Issues with timestamp formatting in the history

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#939]
![image](https://user-images.githubusercontent.com/1689815/36670258-0b6bd002-1af8-11e8-9fab-df1837337908.png)

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/36670292-238e516e-1af8-11e8-8988-222cd17b6628.png)

**Comment by PrajwalM2212** [comment]
I will correct it .

**Comment by PrajwalM2212** [comment]
@teolemon  I have used a function from https://developer.android.com/reference/android/text/format/DateUtils.html.  
Do you want me to use any particular function from the above page ?

**Comment by PrajwalM2212** [comment]
@teolemon  Seems to work well on my phone .
But I have changed the function in my pull request.
