### ISSUE TITLE
Bad translation 

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/OpenFoodFacts-androidApp#94]

**Comment by asmoth360** [comment]
Oops, l validated by mistake without entering a description. 
I wanted to report a small correction, in the french version, the brands label is called "magasins", it should be "marques".

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/OpenFoodFacts-androidApp/blob/master/app/src/main/res/values-fr/strings.xml

**Comment by asmoth360** [comment]
Thanks
