### ISSUE TITLE
Error on uploading additional image

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#940]
![image](https://user-images.githubusercontent.com/1689815/36670317-3bf65ee0-1af8-11e8-9ac1-1e353628fa13.png)

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=00369220

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
Could you describe steps, because it works fine on my device. 
Does it happen for all products? 
Most likely app asked you to grant some permissions before taking the photo, am I right? This is the only one reason which I can see for now.

**Comment by teolemon** [comment]
The bug is old and most likely fixed by refactoring. Closing. Thanks @l-o-b-s-t-e-r for investigating.
