### ISSUE TITLE
In AlertUserFragment all the allergens need to be shown in every language.

### ISSUE THREAD

**Issue by Shubham2320** [openfoodfacts/openfoodfacts-androidapp#943]
We should look for all translations of an allergen, in all available languages on the product. This might yield false positives but will be safer than the current implementation.

Please ask for more clarification if needed.

**Comment by Shubham2320** [comment]
From where I can get the translations, is there any API call I can make?
At present, the app gets Allergen from https://ssl-api.openfoodfacts.org/allergens.json.

**Comment by teolemon** [comment]
for reference: https://static.openfoodfacts.org/data/taxonomies/allergens.json
