### ISSUE TITLE
Add an activity for FAQ (Frequently Asked Questions)

### ISSUE THREAD

**Issue by Arshilgenius** [openfoodfacts/openfoodfacts-androidapp#944]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting a issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

Currently there is nothing as FAQ in the app for the new users, so i thought why not include that in the app? 

I would like to work on it.

**Comment by teolemon** [comment]
You can add it as an entry in the settings. The left menu is already overloaded
https://world.openfoodfacts.org/faq

**Comment by shivanshsoni** [comment]
May I add this feature?
