### ISSUE TITLE
Labels are always displayed in French, although we have translations for them.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#946]
Labels are always displayed in French, although we have translations for them.

1.Display Labels in user language if available
2.Otherwise display Labels in English if available
3.Otherwise display Labels in the product main's language

https://world.openfoodfacts.org/labels.json
https://world-fr.openfoodfacts.org/labels.json

**Comment by l-o-b-s-t-e-r** [comment]
I've taken this one and related issues with translations #945

**Comment by teolemon** [comment]
Please look at 
Use the new labels.json file to translate labels
#1022 opened 2 minutes ago by teolemon
