### ISSUE TITLE
Back button closes the activity in fragments

### ISSUE THREAD

**Issue by policorn** [openfoodfacts/openfoodfacts-androidapp#948]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting a issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 

Back button closes the activity instead of going back to Home. Examples:

- Search by barcode
- Allergen alert
- Preferences
- Offline edit

**Steps to reproduce:** 

Go to the section. Press back button. 

**Expected behavior:** 

Go to home

**Observed behavior:** 

Activity closes

**Comment by PrajwalM2212** [comment]
I will fix this issue .
