### ISSUE TITLE
No runtime permissions for camera.

### ISSUE THREAD

**Issue by samagra14** [openfoodfacts/openfoodfacts-androidapp#950]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting a issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

The app doesn't ask for runtime permissions for the camera while scanning. It just displays the alert that permissions are not granted.

**Steps to reproduce:** 

Go to App settings and deny Camera Permissions to OpenFood Facts. Then open the app and click on the Scan Barcode nav drawer item.
**Add system logs:**
NA

Add logcat files here (if you are able to add).
NA

**Expected behavior:** 

App should ask for runtime permissions.

**Observed behavior:** 

No runtime permissions are requested.

**Screenshots:** 
![test](https://user-images.githubusercontent.com/25154317/36715329-ce841d60-1bbb-11e8-95c5-41e5f1702c9d.png)

**Comment by samagra14** [comment]
I would love to work on it.

**Comment by teolemon** [comment]
We should ask for permissions when they are required not before

**Comment by teolemon** [comment]
That is to say the first time people scan a product
