### ISSUE TITLE
Add a warning about allergen detector when a product is not complete

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#951]
When the user has set at least an allergen to detect, add a warning about allergen detector when a product is not complete.

"This product is not complete. As a result, we couldn't do the allergen check."

**Comment by Shubham2320** [comment]
I would like to work on it :).

**Comment by teolemon** [comment]
Go ahead :)

**Comment by teolemon** [comment]
Please don't use pop-ups, just a dismissible message in the summary tab

**Comment by Shubham2320** [comment]
Sure, thanks :).

**Comment by Shubham2320** [comment]
Hey, how could I know that the product is incomplete?

**Comment by teolemon** [comment]
```"states_tags":["en:to-be-checked","en:complete","en:nutrition-facts-completed","en:ingredients-completed","en:expiration-date-to-be-completed","en:packaging-code-to-be-completed","en:characteristics-completed","en:categories-completed","en:brands-completed","en:packaging-completed","en:quantity-completed","en:product-name-completed","en:photos-validated","en:photos-uploaded"]```

**Comment by teolemon** [comment]
Uncomplete:
```"states_tags":["en:to-be-completed","en:nutrition-facts-completed","en:ingredients-to-be-completed","en:expiration-date-to-be-completed","en:packaging-code-to-be-completed","en:characteristics-to-be-completed","en:categories-to-be-completed","en:brands-completed","en:packaging-to-be-completed","en:quantity-to-be-completed","en:product-name-completed","en:photos-to-be-validated","en:photos-uploaded"]```

**Comment by Shubham2320** [comment]
Thanks :).

**Comment by Shubham2320** [comment]
I've analyzed the code and in that, I came to know that we're getting `states_tags` array from the server but we're not storing it anywhere so I'm thinking to store these values in `Product` class shall I do this?
