### ISSUE TITLE
Keep a local cache of the categories.json

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#952]
Keep a local cache of the categories.json
Loading it each time takes time, and overloads the server.

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon Actually, app keeps categories...

`public Single<List<Category>> retrieveAll() {
        if (memoryCache.get() != null) {
            return Single.just(memoryCache.get());
        }
        return networkService.getCategories()
                .map(categoryResponse -> mapper.fromNetwork(categoryResponse.getTags()))
                .doOnSuccess(memoryCache::set)
                .subscribeOn(Schedulers.io());
    }`

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/39083883-6c25bca2-456c-11e8-8cc7-e419db0a6bf4.png)
Here's the current behaviour in offline mode

**Comment by l-o-b-s-t-e-r** [comment]
ah, you mean Offline mode. Okay, I will take a look at this.
