### ISSUE TITLE
Brand and Weight are not displayed in the Offline product list

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#953]
Brand and Weight are not displayed in the Offline product list
![image](https://user-images.githubusercontent.com/1689815/36721272-b55cf2fa-1baa-11e8-95e6-5a70bdc6fcb6.png)

**Comment by shivanshsoni** [comment]
I am working on it...

**Comment by PrajwalM2212** [comment]
This issue can be closed
