### ISSUE TITLE
The Upload All icon has a visual glitch

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#954]
The Upload All icon has a visual glitch
![image](https://user-images.githubusercontent.com/1689815/36721264-acb4d8b6-1baa-11e8-83b7-2e24d551fe24.png)

**Comment by ManognaMutyala** [comment]
So do you want to change the position of toast or upload button @teolemon ?

**Comment by teolemon** [comment]
Not at all it is just the asset that seems to have a tiny issue

**Comment by shivanshsoni** [comment]
@teolemon SO May I know what you want to change??

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/36724461-8ede6e48-1bb3-11e8-8b3f-c54793eedde1.png)
![image](https://user-images.githubusercontent.com/1689815/36724477-9ba46416-1bb3-11e8-93ae-1f6634c23ee6.png)

**Comment by shivanshsoni** [comment]
Ok Cool I will solve it...
