### ISSUE TITLE
Hide empty fields

### ISSUE THREAD

**Issue by asmoth360** [openfoodfacts/openfoodfacts-androidapp#98]
Empty fields shouldn't be visible : packaging, categories, traces, additives etc often display "null" or an empty field, they should be hidden instead. 
In the nutrition page, an indication should be present saying a given nutritional info is not indicated, or if they aren't available for the product (when "Nutrition facts are not specified on the product") instead of "nullnull" everywhere.

**Comment by herau** [comment]
is it a duplicate of #86 ? 
Do you have an exemple of a product that can be used for to test the empty fields ?
