### ISSUE TITLE
 Crashing when open Offline Edit Menu

### ISSUE THREAD

**Issue by pprathameshmore** [openfoodfacts/openfoodfacts-androidapp#987]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting a issue.
- [ ] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.

**Summary:** 

Crashing app when Open Offline Edit Menu

**Steps to reproduce:** 

How can we reproduce the issue?

**Expected behavior:** 

What did you expect the app to do?

App must me open Offline Edit

**Observed behavior:** 

![capture](https://user-images.githubusercontent.com/17108186/36784611-0abc5b68-1ca6-11e8-803d-6768f06ac5d9.JPG)

**Device and Android version:** 

Android Emulator API 26

**Screenshots:** 
![capture](https://user-images.githubusercontent.com/17108186/36785030-77902764-1ca7-11e8-9056-b211b5ee6a61.JPG)

Please review issue @nicolasleger

**Comment by teolemon** [comment]
@nicolasleger is not working on the Android app

**Comment by Shubham2320** [comment]
Could you give more details about it like stack trace? And are you able to reproduce it?
