### ISSUE TITLE
Multiple Toast showing on Search Barcode

### ISSUE THREAD

**Issue by sachincool** [openfoodfacts/openfoodfacts-androidapp#999]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting a issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 
If the user Clicks on Search Barcode Multiple times. the Toast instance is displayed multiple times Even if you close the app
**Steps to reproduce:** 
* Open app
* Click on search barcode multiple times.
* close the app and you can see the multiple Toasts
**Expected behavior:** 

The Toast is shown only once.

**Device and Android version:** 
7.0
**Screenshots:** 
![](https://cdn.discordapp.com/attachments/397972978933170178/418514232137482250/20180301_023136.gif)

**Comment by sachincool** [comment]
i would like to work on this issue.

**Comment by danzzen** [comment]
i also work on this issue.

**Comment by danzzen** [comment]
What you want is that toast should be displayed only once for first time, rest of the time there should not be any toast messages.But there should be some thing to tell user that your `Barcode required` or `Barcode Invalid` ,if he/she keep clicking the button. So what we can do is keep a text view hidden and  show it with highlighted text when one of these conditions `Barcode required`or`Barcode Invalid` occur.

**What you think about it please let me know.**

**Comment by samagra14** [comment]
@danzzen As @sachincool has already claimed the issue, please find some other issue to work on.

**Comment by Karljoones** [comment]
This is the expected operation of a toast in Android, this is not considered an issue. The chances of people repeatedly clicking it like that is slim

**Comment by sachincool** [comment]
@Karljoones No, that is not expected behaviour in good apps.  For Eg.  
* Try clicking on the button 2-3 times and close the app. you'll still be stuck seeing the Toast messages even outside the app. Normally a Service bound should unregister on onPause or onDestroy, right?  Also If 1 Toast instance is executing other instance should not execute till the first one cancels.
you'll understand what i mean after looking at my code. then, it's upto you
